### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by zhou1012** [iikira/BaiduPCS-Go#1]
linux_arm64
./baidupcs_go: 1: ./baidupcs_go: Syntax error: "(" unexpected

**Comment by iikira** [comment]
linux_arm64 我这边测试没问题啊,
可能你的运行方式有问题...
我猜你是这么运行的
```
sh ./baidupcs_go
```
如果不是, 请检查下是否匹配 CPU 架构..

**Comment by zhou1012** [comment]
我的锅，忘记服务器跟电脑的构架不一样了，
