### ISSUE TITLE
当没有离线下载任务时od l出错

### ISSUE THREAD

**Issue by WeidiDeng** [iikira/BaiduPCS-Go#100]
如题，会输出“精确查询离线下载任务, no input any task_ids”，感觉应该是od q的错误信息，od q反而不会出错。
![default](https://user-images.githubusercontent.com/28780594/38007065-3635487e-327a-11e8-8aff-65aa3daa8747.JPG)

另外作者能不能考虑添加对回收站里的文件进行操作。

**Comment by iikira** [comment]
有时间的话就加上回收站操作吧
