### ISSUE TITLE
编译的话，需要使用go 1.10版本

### ISSUE THREAD

**Issue by SongShawn** [iikira/BaiduPCS-Go#101]
我本地go 1.9.2版本，没有strings.Builder

**Comment by iikira** [comment]
参见 [编译/交叉编译帮助](https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9), 有提到的...
