### ISSUE TITLE
下载卡住了怎么办呀，死等？

### ISSUE THREAD

**Issue by SongShawn** [iikira/BaiduPCS-Go#102]
![image](https://user-images.githubusercontent.com/12530965/38073982-c9512d22-335f-11e8-86e0-c506ab328cf8.png)

**Comment by SongShawn** [comment]
敲了一下回车，过去了。
找时间撸一边大婶的代码

**Comment by iikira** [comment]
好多人反馈这个问题，不过我从来没遇到过啊
