### ISSUE TITLE
3.22-windows-64位，下载一整个目录文件时，网速很慢。

### ISSUE THREAD

**Issue by caizijiao** [iikira/BaiduPCS-Go#103]
下载一整个目录的文件时，速度很慢，常见的速度变化是：0k/s—256k/s—0k/s—256k/s

**Comment by iikira** [comment]
下载单个文件，速度怎么样呀

**Comment by caizijiao** [comment]
下载单个文件，速度还可以的，但是依然有瓶颈，感觉就是到了一定速度，就归零，然后开始爬坡，然后到一定速度后又归零。





--


Best Regards.


Cai Zi Jiao
Shu Lun Pan CPA CO.,LTD
NO.61,East NanJing Road
Huangpu District
Shanghai 200002
P.R.China
Phone:0086-021-23280260

Fax:0086-021-63214325
Mobile:0086-13818303746
E-mail:caizijiaoqd@163.com





在 2018-03-29 23:13:39，"iikira" <notifications@github.com> 写道：


下载单个文件，速度怎么样呀

**Comment by caizijiao** [comment]
我目前的版本是64位win系统的3.3.2版本。网速不能一直保持高速，下载整个文件夹这样的方法，网速甚至不到非付费会员百度云exe下载的速度。




--


Best Regards.


Cai Zi Jiao
Shu Lun Pan CPA CO.,LTD
NO.61,East NanJing Road
Huangpu District
Shanghai 200002
P.R.China
Phone:0086-021-23280260

Fax:0086-021-63214325
Mobile:0086-13818303746
E-mail:caizijiaoqd@163.com





在 2018-03-29 23:13:39，"iikira" <notifications@github.com> 写道：


下载单个文件，速度怎么样呀

**Comment by iikira** [comment]
更新版本吧，目前最新版是3.3.2。也可以试试编译安装

**Comment by caizijiao** [comment]
我用的就是3.3.2啊，什么叫编译安装我也不知道。


--


Best Regards.


Cai Zi Jiao
Shu Lun Pan CPA CO.,LTD
NO.61,East NanJing Road
Huangpu District
Shanghai 200002
P.R.China
Phone:0086-021-23280260

Fax:0086-021-63214325
Mobile:0086-13818303746
E-mail:caizijiaoqd@163.com





在 2018-03-30 09:52:26，"iikira" <notifications@github.com> 写道：


更新版本吧，目前最新版是3.3.2。也可以试试编译安装

**Comment by iikira** [comment]
哦，我看到了你的标题……有时间的话我就测试测试吧

**Comment by caizijiao** [comment]
好，辛苦





--


Best Regards.


Cai Zi Jiao
Shu Lun Pan CPA CO.,LTD
NO.61,East NanJing Road
Huangpu District
Shanghai 200002
P.R.China
Phone:0086-021-23280260

Fax:0086-021-63214325
Mobile:0086-13818303746
E-mail:caizijiaoqd@163.com





在 2018-03-30 10:04:48，"iikira" <notifications@github.com> 写道：


哦，我看到了你的标题……有时间的话我就测试测试吧

**Comment by iikira** [comment]
测试了一圈, 没发现有什么问题. 以前的版本确实存在下载目录速度很慢的问题, 不过应该已经修复了.
运行命令加上前缀`-verbose`, 下载文件时可以看到调试信息, 例如
```
BaiduPCS-Go -verbose download file3.txt
-verbose download file3.txt
```

**Comment by teslaliu** [comment]
刚刚测试目录下载，速度达网路最高速，而且跟之前版本比较，稳定很多，这是目前测试最好的版本！谢谢开发者的努力！

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
