### ISSUE TITLE
使用internal包编译报错

### ISSUE THREAD

**Issue by opteronx** [iikira/BaiduPCS-Go#105]
main.go:6:2: use of internal package not allowed
main.go:7:2: use of internal package not allowed
main.go:8:2: use of internal package not allowed
似乎直接将internal放入import中不妥？

**Comment by iikira** [comment]
奇怪, 我这里可以通过编译, 你是怎么编译的..

**Comment by opteronx** [comment]
go clean
go get
此时就如上报错
go build 同样报错

**Comment by iikira** [comment]
试一试吧。
1. 删除
 $GOPATH/pkg/$GOOS_$GOARCH/github.com/iikira/BaiduPCS-Go
2. 尝试升级go版本
3. 检查一下项目路径...

**Comment by opteronx** [comment]
目前是go1.9，并且GOPATH肯定没问题
那个目录完全是空的，我尝试删掉src下的BaiduPCS-Go也没有用

**Comment by iikira** [comment]
先升级go1.10或go1.10.1看看吧，程序用到了go1.10的新特性，go1.9是不会通过编译的，即使消掉了internal错误......

**Comment by opteronx** [comment]
才发现早晨已经更新到1.10了
所以刚才的所有内容都是在1.10下完成的

**Comment by iikira** [comment]
那...gopath和本项目的目录结构是否正确呢...还不行的话，设置新的gopath，go get -u -v github.com/iikira/BaiduPCS-Go，看看行不行。

**Comment by opteronx** [comment]
我大概知道是什么问题了，在gopath下的src里直接build是可以的，但是我日常的git目录不在gopath下

**Comment by iikira** [comment]
我就知道...编译go程序，gopath是逃不掉滴。

**Comment by kiinoo** [comment]
没看懂应该怎么设置哦。。我这儿一样提示错误。

````
GOROOT=/usr/local/go
GOPATH=/Users/kiia/go

cd /Users/kiia/Downloads/code/fork/BaiduPCS-Go
````

在目录/Users/kiia/Downloads/code/fork/BaiduPCS-Go运行go get的时候，包都下载到这个目录了
/Users/kiia/go/src/github.com

但是依然报错，不管是go get还是go build

求助啊

**Comment by iikira** [comment]
```
cd /Users/kiia/go/src/github.com/iikira/BaiduPCS-Go
```

在这里编译试一试

**Comment by kiinoo** [comment]
啊，这个地方可以编译，谢谢！

**Comment by weaming** [comment]
@iikira 没有别的办法吗，比如某些项目就是不在 GOPATH 底下
