### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by SeAL80s** [iikira/BaiduPCS-Go#106]
系统Arch Linux x86_64
BaiduPCS-Go 版本3.3.2
文件大小是2.2G。是不是文件过大啊？以前不是官方客户端有个4G限制，现在改2G了？从状态来看，2G以下可以正常上传的。求解！

**Comment by iikira** [comment]
是的，大于2g的文件需要分片上传，程序还没有加入这个功能

**Comment by SeAL80s** [comment]
@iikira 说点题外话。哥(姐姐?)们，你太棒了！！！

**Comment by iikira** [comment]
已支持, 2ba6ac7327adeb6f53ae2981933d917702450fd9
