### ISSUE TITLE
最新commit会导致下载目录文件多时出错退出

### ISSUE THREAD

**Issue by WeidiDeng** [iikira/BaiduPCS-Go#108]
如题，由于直接打开会直接跳出，使用的是powshell
![default](https://user-images.githubusercontent.com/28780594/38249556-9fa8d8e4-377e-11e8-8d92-7307d41df150.JPG)

**Comment by iikira** [comment]
知道了，最近事有点多...

**Comment by iikira** [comment]
应该修复了
