### ISSUE TITLE
HDD硬盘慢的要死。。

### ISSUE THREAD

**Issue by redapple0204** [iikira/BaiduPCS-Go#110]
在HDD硬盘下载的时候，电脑硬盘灯常亮，卡的要死不说，而且速度只有400k/s，线程为300。

**Comment by iikira** [comment]
建议调高下载缓存
```
BaiduPCS-Go config set -cache_size 163840
```

如果你使用的是旧版的程序, 请[更新](https://github.com/iikira/BaiduPCS-Go/releases)

**Comment by redapple0204** [comment]
@iikira 好的谢谢
