### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by yi1873** [iikira/BaiduPCS-Go#111]
BaiduPCS-Go rapidupload -length=129612844 -md5=6f3303a50e6f860e0c4a69b80f52049 -slicemd5=96c13715f362420f16630d5d41784ca -crc32=149456998 目录
秒传失败, 消息: 秒传文件 遇到错误, 保存路径不可以覆盖目录
问题出在哪里？

**Comment by iikira** [comment]
已提交修复, f5d512b49e9aee2833d83c8c0a7f305b65b09fe3
编译安装程序可修复该错误, 或者等待下一版本的发布...

**Comment by iikira** [comment]
测试正常，也行你应该提供完整的示例命令……?

**Comment by iikira** [comment]
看你的命令: 
```
BaiduPCS-Go rapidupload <...> 目录
```
猜测你只是传入文件要保存的目录, 没有指明具体的文件名. 由于秒传文件, 服务器无法推导出文件名, 所以要指定文件名, 例如
```
BaiduPCS-Go rapidupload <...> 目录/1.mp4
```
