### ISSUE TITLE
下载文件是后面的时间可以标注一下剩余时间

### ISSUE THREAD

**Issue by charming7201** [iikira/BaiduPCS-Go#120]
![k6pp fpw6q p 72 t2 p5 d](https://user-images.githubusercontent.com/24864636/38857769-9f65a676-425c-11e8-8324-bada978f2108.png)

**Comment by iikira** [comment]
可以啊

**Comment by iikira** [comment]
已加上, c4e4df669883a58d288048755c7f17c2d4d90b48
