### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by oditian** [iikira/BaiduPCS-Go#121]
mkdir /data/data/com.termux/files/home/BaiduPCS-Go-v3.3.3-android-21-arm64/download/1000349699_没有想好二代: permission denied, 重试 2/3
手机上不知道哪里出错了

**Comment by iikira** [comment]
权限没有设置好吧
建议你保存到外部储存
```
BaiduPCS-Go config set -savedir /sdcard/Download
```
前提是给了termux外部储存权限……

**Comment by oditian** [comment]
如何给termux增加外部权限

**Comment by oditian** [comment]
已经好了，多谢啦
