### ISSUE TITLE
部分文件下载到结尾时就没速度了

### ISSUE THREAD

**Issue by comvir** [iikira/BaiduPCS-Go#125]
[![CnwYOx.png](https://s1.ax1x.com/2018/04/18/CnwYOx.png)](https://imgchr.com/i/CnwYOx)
持续十几分钟后文件依然没下载成功。
经过多个不同类型的文件下载测试后，发现视频类文件都不能下载成功。

**Comment by iikira** [comment]
我测试一下...

**Comment by JohnYQW** [comment]
Same problem here.

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
