### ISSUE TITLE
请教个问题？

### ISSUE THREAD

**Issue by SongShawn** [iikira/BaiduPCS-Go#126]
1. pcs的api文档能共享一份吗？
2. 用当前的下载方式能够实现百度分享内容的下载吗？
   -- 主线现在碰到一个情况，转存分享内容对文件个数有上限要求。

有时间看到，麻烦答复一下我。谢谢~~

**Comment by iikira** [comment]
api文档在本项目的docs目录下, 另外, 有时间的话就加上直接下载分享页的内容吧.

**Comment by SongShawn** [comment]
嗯，看到了，我先研究一下。
