### ISSUE TITLE
下载无速度

### ISSUE THREAD

**Issue by zxh95320** [iikira/BaiduPCS-Go#128]
有时候下载没有速度，但是重新打开就又恢复正常了。用的win-3.3.3，最近已经发生过好多次这种情况了。

**Comment by iikira** [comment]
1. 尝试调整下载线程；

2. c4e4df669883a58d288048755c7f17c2d4d90b48, 重构并优化了下载器，建议你编译安装试试效果，或者到[这里](https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts)下载。

**Comment by csrgxtu** [comment]
![image](https://user-images.githubusercontent.com/5053620/39285957-6a3e3d38-4945-11e8-981f-5b8837ccd20d.png)

**Comment by iikira** [comment]
@csrgxtu 建议你看一下[这里](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E), 反馈结果以供我判断.

**Comment by csrgxtu** [comment]
@iikira 
![image](https://user-images.githubusercontent.com/5053620/39287352-82a66f1e-494d-11e8-80f7-c41a33e2ba50.png)

**Comment by iikira** [comment]
@csrgxtu download加上status选项看看，

**Comment by iikira** [comment]
@csrgxtu No response from reporter.

@zxh95320 
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
