### ISSUE TITLE
打开直接闪退，命令行输入报错

### ISSUE THREAD

**Issue by misasky** [iikira/BaiduPCS-Go#13]
命令行输入报错：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x6d4c70]

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/command.ReloadInfo()
        D:/gopath/src/github.com/iikira/BaiduPCS-Go/command/command.go:20 +0x30
github.com/iikira/BaiduPCS-Go/command.init.1()
        D:/gopath/src/github.com/iikira/BaiduPCS-Go/command/command.go:14 +0x27
github.com/iikira/BaiduPCS-Go/command.init()
        D:/gopath/src/github.com/iikira/BaiduPCS-Go/command/util.go:101 +0xd9
main.init()
        D:/gopath/src/BaiduPCS-Go/main.go:525 +0x59

**Comment by iikira** [comment]
行数对不上……尝试更新一下版本吧……

**Comment by misasky** [comment]
emmmm,解决了
