### ISSUE TITLE
下载的时候卡住

### ISSUE THREAD

**Issue by charming7201** [iikira/BaiduPCS-Go#130]
下载的时候时间不动了，速度是0 ，然后按ctrl+c就可以恢复，可以看到下载了多少，时间也正常，速度也正常

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
