### ISSUE TITLE
下载路径包含空格怎么处理

### ISSUE THREAD

**Issue by wenhao13947** [iikira/BaiduPCS-Go#133]
如题，该怎么替换空格呢，谢谢！

**Comment by iikira** [comment]
[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98), 有提到的

**Comment by wenhao13947** [comment]
已看到，软件制作辛苦了，谢谢！
