### ISSUE TITLE
# 安卓 建立软链接, 指向 /sdcard/Download 目录 出错

### ISSUE THREAD

**Issue by zdzliqian** [iikira/BaiduPCS-Go#135]
安卓 建立软链接, 指向 /sdcard/Download 目录 出错
已经给了储存权限了 下载时  显示permission denied

**Comment by iikira** [comment]
permission denied属于系统权限的问题，于程序无关，你可以提供更多的信息以供我判断。

**Comment by zdzliqian** [comment]
@iikira ![screenshot_neoterm_20180424-175017](https://user-images.githubusercontent.com/10721790/39234643-6d4ae7aa-48a6-11e8-9e97-9bd56f692c07.png)
系统是安卓8.1 出错如上图

**Comment by zdzliqian** [comment]
@iikira 还需要什么别的信息吗？

**Comment by iikira** [comment]
@zdzliqian 版本有点低啊，建议你先更新一下程序，

**Comment by iikira** [comment]
在[这里](https://github.com/iikira/BaiduPCS-Go/releases)更新

**Comment by zdzliqian** [comment]
@iikira 好的 多谢了

**Comment by ChinaYGL** [comment]
我也遇到这个问题，求解决方法

**Comment by ChinaYGL** [comment]
运行./BaiduPCS-Go前，运行sudo su，切换root账号就能下载了

**Comment by iikira** [comment]
@ChinaYGL 这就是说明权限没有设置好咯.
不清楚你的情况, 自行解决吧
