### ISSUE TITLE
强烈建议增加自动补全功能

### ISSUE THREAD

**Issue by naivecao** [iikira/BaiduPCS-Go#136]
不知道别的版本有没有这个功能，我在win10 cmd 下没有这个功能，强烈建议加入，要不使用起来有点费劲

**Comment by iikira** [comment]
暂时用通配符代替吧

**Comment by BruceChen2017** [comment]
能添加文件夹及文件名自动补全功能吗 @iikira

**Comment by iikira** [comment]
@BruceChen2017 有时间会加上的
