### ISSUE TITLE
“下载完成后自动执行”功能

### ISSUE THREAD

**Issue by xzc0001** [iikira/BaiduPCS-Go#138]
相关：[aria2下载完后自动上传至谷歌云盘](https://www.nozarc.com/2018/01/15/aria2-auto-upload/)

想通过这种操作以实现百度盘转存googe drive 或者 onedrive 的功能。
不知道是不是可以添加一下这个feature？（云PM233）

或者不知道有没有其他的思路去实现这种功能呢？

**Comment by iikira** [comment]
这并不是程序的主要功能, 时间充足才会考虑.
可以写一个脚本吧, 等下载完成了, 程序退出, 然后执行后续的操作.

**Comment by zhanglianbo35** [comment]
自己写shell命令同步就行了。简单的很

发自我的 iPhone 

**Comment by xzc0001** [comment]
@iikira 好的试试~谢谢~

@zhanglianbo35 我比较菜……去试试，，谢谢解答~

**Comment by zzzop** [comment]
同问该怎么写命令呢

**Comment by xzc0001** [comment]
@zzzop 我目前是用bash，比较笨，先tree下来，然后编辑脚本，一个一个文件下载，然后再执行后续步骤
