### ISSUE TITLE
有些时候下载完zip文件解压会出错

### ISSUE THREAD

**Issue by shiftwinting** [iikira/BaiduPCS-Go#14]
有些时候下载完zip文件解压的话
有些文件解压不出来，发生校验错误。

**Comment by peiying16** [comment]
出现了同样问题 特别是大文件的时候

**Comment by peiying16** [comment]
系统ubuntu 16
下载大文件 3G
下载完成后使用 md5sum命令查看 跟文件不一样
用的是release里面的 `BaiduPCS-Go-v3.3.Beta4-linux-amd64.zip`
希望可以修复一下
小文件没有问题

**Comment by iikira** [comment]
@peiying16 正在测试了...

**Comment by peiying16** [comment]
@iikira 请问测试结果如何？只是想知道是不是只有我出现这个问题。很喜欢这个project的，下载速度很快。

**Comment by iikira** [comment]
@peiying16 测试不出来，可能跟网络有关...

**Comment by peiying16** [comment]
@iikira 测试不出来是指你的文件完好？MD5值一样？我是aws上的服务器运行的。

**Comment by iikira** [comment]
@peiying16 对呀, 每次md5值都一样, 无论文件有多大😄

**Comment by peiying16** [comment]
@iikira 好吧可能国外网有问题

**Comment by peiying16** [comment]
@iikira 可能找到原因了http://blog.sina.com.cn/s/blog_610787990102xcnv.html  如果对大文件可以自动的修复一下就最好了。

**Comment by Cologler** [comment]
这个问题是随机发生的，和文件大小无关。我下载一个包含 143 个 zip 文件的目录，下载完后测试压缩文件，有一个 200KB 的压缩包解压出错。

重新下载就好了，说明不是服务器上的文件的问题，是下载过程的问题……

能不能下载文件以后自动进行文件校验（校验失败则重新下载或者下载失败）？

**Comment by Cologler** [comment]
![snipaste_2018-06-02_15-03-34](https://user-images.githubusercontent.com/10906962/40871843-377d2550-6676-11e8-94fb-fe689f55f1b5.png)

同一文件每次下载的 MD5 都不一样，而且目前我没下载过和 pcs 中显示的一样的 MD5 ……
而且是视频文件，缺乏类似压缩包的校验机制。

**Comment by iikira** [comment]
已支持下载完成后校验文件, df82928b832bac26321236ebeb4d6db9a918d48f
