### ISSUE TITLE
使用appveyor中编译好的mipsle架构文件 可以运行，但下载出错

### ISSUE THREAD

**Issue by yurimoe** [iikira/BaiduPCS-Go#140]
github最新的releases使用正常，下载超大文件没速度。
想试试appveyor中的最新编译，然后下载报错
goroutine 59 [running]:
runtime/internal/atomic.lockAndCheck(0x91280d4)
        C:/go/src/runtime/internal/atomic/atomic_mipsx.go:33 +0x20
runtime/internal/atomic.Store64(0x91280d4, 0xffffffff, 0x7fffffff)
        C:/go/src/runtime/internal/atomic/atomic_mipsx.go:96 +0x18
github.com/iikira/BaiduPCS-Go/requester/rio/speeds.(*Speeds).GetSpeedsPerSecond(0x91280c8, 0x9114280, 0x0)
        C:/gopath/src/github.com/iikira/BaiduPCS-Go/requester/rio/speeds/speeds.go:52 +0x98
github.com/iikira/BaiduPCS-Go/requester/downloader.(*Worker).updateSpeeds.func1(0x619620, 0x9010a00, 0x91280b0)
        C:/gopath/src/github.com/iikira/BaiduPCS-Go/requester/downloader/worker.go:208 +0x4c
created by github.com/iikira/BaiduPCS-Go/requester/downloader.(*Worker).updateSpeeds
        C:/gopath/src/github.com/iikira/BaiduPCS-Go/requester/downloader/worker.go:201 +0x60

**Comment by yurimoe** [comment]
@iikira 好的，辛苦您了。
换回github中的编译，下载压缩文件（7G）我等了3分钟之后 开始有速度了

**Comment by iikira** [comment]
[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

```
BaiduPCS-Go -verbose download -status SomeFunkyFilePathHere
```

可以看到详细的下载状态
