### ISSUE TITLE
3.5版本下载速度好像没有3.3版本的下载速度快了,只有我一个人有这种情况吗？

### ISSUE THREAD

**Issue by xieyixiao** [iikira/BaiduPCS-Go#146]
3.3的下载速度可以到2.7M/s而3.5版本只有1.1M/s。

**Comment by iikira** [comment]
[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)
自己调整一下吧

**Comment by zdzliqian** [comment]
调整了速度有
也明显感觉到了 试了下下同一个文件 同样的网络

**Comment by iikira** [comment]
多尝试几次，不行就用回旧版吧

**Comment by xieyixiao** [comment]
可以的
