### ISSUE TITLE
百度开始限制了

### ISSUE THREAD

**Issue by redapple0204** [iikira/BaiduPCS-Go#15]
>redapple@redapple-PC ~> gopcs download "SimplePlanes 1.7.0.6.rar"
could not locate box "static"
获取单个文件/目录的元信息遇到错误, 路径: /apps/SimplePlanes 1.7.0.6.rar, 错误代码: 31045, 消息: 操作失败, 可能BDUSS已过期, 请尝试重新登录, 消息: user not exists
redapple@redapple-PC ~> 

重新登录无效

**Comment by redapple0204** [comment]
不对，只有一个文件无法下载，但是其实是在的

**Comment by iikira** [comment]
这文件有毒(黑人问号脸……)

**Comment by redapple0204** [comment]
@iikira 链接: https://pan.baidu.com/s/1c4hfkDM 密码: zrth
这个文件，我觉得挺奇怪，没啥问题啊

**Comment by iikira** [comment]
我下载没问题啊……噗…

**Comment by orrzz** [comment]
Win平台还是命令行，门槛有点高啊 老铁

**Comment by iikira** [comment]
@orrzz 我不会ui啊……

**Comment by redapple0204** [comment]
@iikira emmm目前只遇到这个文件没法下载，那就算了吧，我用别的办法搞下好了...
PS：你是我遇到最负责的一个项目负责人了，希望这个项目能够越做越好= =

**Comment by swituo** [comment]
@orrzz Win下要图形界面的, 可以用SpeedPan.

不开源, 但.net写的, 可以反编译看有没有脏东西~ = =
