### ISSUE TITLE
登录百度账号之后光标显示错误

### ISSUE THREAD

**Issue by roachsinai** [iikira/BaiduPCS-Go#150]
感谢提供这么棒的工具，但是第一次使用中发现登录之后光标显示位置左移了**两格**！

```
BaiduPCS-Go:/ 百度账号$ ls
```

就是比如输入`ls`命令，光标应该在`s`后面闪烁，结果在字母`l`上闪烁。

+ 终端：guake
+ 发行版：Manjaro
+ **BaiduPCS-Go**版本：BaiduPCS-Go-v3.5-linux-amd64.zip

**Comment by iikira** [comment]
看起来你应该去这里反馈，https://github.com/peterh/liner

或者换一个终端，或者不使用本程序提供的交互界面

**Comment by iikira** [comment]
你的百度用户名是否包含有中文？

**Comment by roachsinai** [comment]
是。。。

**Comment by iikira** [comment]
那就是中文的问题了，猜测你的终端对中文的支持不是很好，把中文的宽度当英文的算了……

**Comment by roachsinai** [comment]
嗯，这样么。不使用PCS的话进入有中文的目录是正常的。

**Comment by iikira** [comment]
用到的是这个组件：https://github.com/peterh/liner

一般的终端不会出现这个问题，应该是liner不能很好支持你的终端，去那里提交issue吧，

**Comment by roachsinai** [comment]
好，谢谢。

**Comment by roachsinai** [comment]
liner的问题应该已经解决了，如果可以的话麻烦发布一个新的版本。

**Comment by roachsinai** [comment]
额，issue不是关于汉字，是其他特殊字符。百度ID比较奇特。。

**Comment by iikira** [comment]
我知道了
