### ISSUE TITLE
是否有限速下载功能？

### ISSUE THREAD

**Issue by reaCodes** [iikira/BaiduPCS-Go#151]
这个软件确实很快，很多情况下会占满我的带宽，但是同时浏览网页速度很慢。有没有设置速度上限的功能，若没有以后的版本是否考虑添加？

**Comment by iikira** [comment]
限速还不简单吗，调低下载线程就可以哈哈，
嗯，考虑加上!

**Comment by PaPerseller** [comment]
> 限速还不简单吗，调低下载线程就可以哈哈，
> 嗯，考虑加上!

调至最低线程数50仍然满速下载，请求考虑加入限速功能

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已增加上传、下载设置限速
