### ISSUE TITLE
[require] 请求添加指定配置文件所在路径功能

### ISSUE THREAD

**Issue by axionl** [iikira/BaiduPCS-Go#153]
https://github.com/iikira/BaiduPCS-Go/blob/91dc667cd22fafdd0acfc3f600ee5606b2b24d40/pcsutil/file.go#L62

建议添加指定配置文件目录功能，而非直接获取可执行文件所在目录，便于打包到 Linux。

**Comment by iikira** [comment]
这样每次运行都要引入配置文件路径, 这样好吗?

**Comment by iikira** [comment]
可不可以考虑使用软链接, 就是程序单独存放在一个目录, 然后链接到 bin 目录,  或者是将目录加入 PATH...

**Comment by axionl** [comment]
然而这并不符合包管理器的目录规范，普通用户不应该能写 /usr/bin 等 PATH 目录，包管理器也不应该动 $HOME 目录。同时软连接会产生一个问题，同机其他用户不能正常生成配置文件

**Comment by farseerfc** [comment]
建議用 https://github.com/shibukawa/configdir 尋找配置文件路徑

**Comment by axionl** [comment]
> 这样每次运行都要引入配置文件路径, 这样好吗?

另外如果图省事的话可以直接指定 Path 缺省为家目录，如有修改需求的话再加参数。

**Comment by iikira** [comment]
我是说将目录加入 PATH 环境变量...

**Comment by farseerfc** [comment]
要是每個軟件都要加 PATH 的話 255 字節的限制很快就不夠用了…

**Comment by zhanglianbo35** [comment]
非root用户一般都用 $HOME/.local/bin，所以把执行文件设link 到这个文件夹即可

发自我的 iPhone 

**Comment by farseerfc** [comment]
包管理器不能寫入 $HOME ，.local/bin 是用戶自己手動安裝的時候用的，也不應該讓包管理器寫入。

**Comment by iikira** [comment]
好吧，我打算将配置文件放到HOME下，由程序写入，不由包管理器，有什么意见吗？

**Comment by iikira** [comment]
看了一下那个，并未兼容ios，所以我会自己实现一个……

**Comment by reaCodes** [comment]
3.5.1版本在Windows上， 如何自定义配置文件路径？

**Comment by iikira** [comment]
@reaCodes 设置环境变量指定 BAIDUPCS_GO_CONFIG_DIR

**Comment by reaCodes** [comment]
@iikira 请问具体怎么修改，不太明白在哪里修改
![image](https://user-images.githubusercontent.com/13817254/39912553-ae88f152-5531-11e8-9c05-eeadc53b9aaf.png)

**Comment by iikira** [comment]
@reaCodes http://www.ujiaoshou.com/upanjc/diannao/1289.html

**Comment by reaCodes** [comment]
@iikira 不如在config里设置直接
