### ISSUE TITLE
貌似pcs模式被限制，开再多线程速度也上不去

### ISSUE THREAD

**Issue by dongshige** [iikira/BaiduPCS-Go#155]
max_parallel 从 500 慢慢下降，到 10 速度也没太多变化

![](https://user-images.githubusercontent.com/20633751/39630828-2093ec24-4fe3-11e8-8803-012a4ab70126.png)

同样文件，网页用idm下载 10m 左右

上传速度也不行，网页上传可以 2m 左右
![](https://user-images.githubusercontent.com/20633751/39631072-cf6568f4-4fe3-11e8-8f0f-44e14d2ec31c.png)

能否改用网页 api 上传下载

**Comment by iikira** [comment]
[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

也就是说并不保证速度.

另外你说下载并发量, 500和10是没什么区别吗, 建议打开-status 选项查看下载详情.
