### ISSUE TITLE
能否加个cls清屏命令

### ISSUE THREAD

**Issue by Nice2MetU** [iikira/BaiduPCS-Go#157]
有时候文本行数太多，眼花缭乱，能否考虑加个类似于 CMD 的 cls 清屏命令，清空屏幕上的文本，另外能否用 cd 进入一个目录之后，自动 ls 列出当前文件夹下的所有目录和文件，不然每次进入一个文件夹后还要 ls 一下，挺麻烦的

**Comment by iikira** [comment]
1. Ctrl + L
2. BaiduPCS-Go cd -l
