### ISSUE TITLE
为什么下载到最后就没速度了？

### ISSUE THREAD

**Issue by dxvgef** [iikira/BaiduPCS-Go#16]
<img width="421" alt="2018-01-21 19 48 13" src="https://user-images.githubusercontent.com/5192264/35193856-1ed2950c-fee4-11e7-90f6-b44bb7fc1b37.png">

**Comment by iikira** [comment]
多线程下载的通病。。。一般都能下载完的，实在不行还可以重启程序，支持断点续传的。。

**Comment by 674273563** [comment]
@iikira 下载速度断断续续呢

**Comment by iikira** [comment]
@674273563 可能是百度的限制，尝试调高下载线程

**Comment by fentensoft** [comment]
我也常遇见，到最后降到0速，而且会停住不动，重开也是0速保持不动，我一般把下载的两个临时文件删掉再重新下载，要人工一直看着。。所以不知道有没有什么临时解决方案，比如0速度多久就删掉重来这样。。

**Comment by iikira** [comment]
@fentensoft 马上测试……

**Comment by iikira** [comment]
尝试修复长时间卡死不动的bug... [#af2f9d0](https://github.com/iikira/BaiduPCS-Go/commit/af2f9d07dae13d5ee5c9232bbe2f7091d15d28c4)
你们可以试着编译运行程序, 看一下效果怎么样...

**Comment by fentensoft** [comment]
测试了几天下来，没再出现问题，感谢

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
