### ISSUE TITLE
关于UI的建议

### ISSUE THREAD

**Issue by reaCodes** [iikira/BaiduPCS-Go#161]
目录可不可用制表的方式输出，类似MySQL的输出方式，文件名输出固定数量，不然文件名稍微长一点，就会造成换行，布局就会改变，很不美观（虽然命令行界面注定与美观无缘）

---
## 窗口最大化的时候
![2](https://user-images.githubusercontent.com/13817254/39671349-2ac3bf3c-5149-11e8-9678-99103ba92ac8.png)
## 正常大小的窗口
![1](https://user-images.githubusercontent.com/13817254/39671350-2eedbad6-5149-11e8-810c-0e3db40f5a7f.png)
## MySQL制表形式的输出
![qq 20180506150004](https://user-images.githubusercontent.com/13817254/39671336-edc474dc-5148-11e8-9959-42f23c69a8fe.png)
![qq 20180506161637](https://user-images.githubusercontent.com/13817254/39671337-ee12f210-5148-11e8-9438-94a93d9b428b.png)

**Comment by reaCodes** [comment]
确实影响复制，不过有大段复制的使用场景吗，最多复制个目录名文件名，而且现在使用频率更低了，因为有了很赞的Tab补全功能。

不限制显示名字的长度，会造成不美观，写死了输出长度也不一定能解决，不过如果做成感知窗口大小，自适应文件名长度，应该挺困难那的吧

**Comment by iikira** [comment]
嗯, 而且感觉没必要啊

**Comment by zhanglianbo35** [comment]
没有必要啊

发自我的 iPhone 
