### ISSUE TITLE
如果已有实例正在下载，此时云里有了新的文件夹，则download命令无法自动tab补齐该新文件夹名

### ISSUE THREAD

**Issue by justyre** [iikira/BaiduPCS-Go#164]
如果已有实例正在下载，此时云里有了新的文件夹，则download命令无法自动tab补齐该新文件夹名。只能新开一个pcs-go的实例，才能自动tab补齐新文件夹名……

**Comment by justyre** [comment]
PPS 发现一个新问题。。如果一个文件因故未能下载成功 本地会生成一个0KB的该文件 当pcs-go尝试重新下载时会直接跳过之。。应该用MD5校验一下再跳过比较合理吧。。

问题举例：

[76] ----
  类型              文件
  文件路径          /新入Boxcar/BC 1-138/BC 077.rar
  文件名称          BC 077.rar
  文件大小          64802386, 61.800371MB
  md5 (截图请打码)  blablabla
  fs_id             948651855589280
  创建日期          2017-05-09 09:17:32
  修改日期          2018-05-07 09:32:32

[76] 准备下载: /新入Boxcar/BC 1-138/BC 077.rar
[76] 文件已经存在: C:\INVC160\3490081141_justyre02\新入Boxcar\BC 1-138\BC 077.rar, 跳过..

**Comment by iikira** [comment]
6ab5bc429675f5cffe38eda2ec059ef9fc90a119
应该不会再出现空文件的情况了，并且支持输出下载失败的文件列表

**Comment by iikira** [comment]
已支持目录排序功能，支持按大小、日期等排序
已支持下载完成后校验文件, df82928b832bac26321236ebeb4d6db9a918d48f
