### ISSUE TITLE
golang编译的时候,提示use of internal package not allowed

### ISSUE THREAD

**Issue by unreal0** [iikira/BaiduPCS-Go#166]
main.go:6:2: use of internal package not allowed
main.go:7:2: use of internal package not allowed
main.go:8:2: use of internal package not allowed

需要怎么设置

**Comment by iikira** [comment]
参见:
[编译/交叉编译帮助](https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9)
#105

编译 go 程序, GOPATH 是逃不掉的~
