### ISSUE TITLE
建议添加下载相应序号文件的功能

### ISSUE THREAD

**Issue by leitwolf** [iikira/BaiduPCS-Go#167]
如 ls 出来一个列表，可下载相应序号的文件或文件夹，这样就不用复制文件名了，比较方便，而且这样也不用注意文件名里那里小括号，中括号，空格之类的问题了。

**Comment by iikira** [comment]
使用tab 补齐路径(输入 ls 以后 , 按一下键盘上的tab键), 或者使用通配符

**Comment by leitwolf** [comment]
不太理解怎么操作，按tab之后要怎么弄？

**Comment by iikira** [comment]
tab会自动补齐文件路径，v3.5以上可支持
