### ISSUE TITLE
本地开发 代码如何启动呀 ？

### ISSUE THREAD

**Issue by bobiscool** [iikira/BaiduPCS-Go#168]
go 才开始接触 ，请教一下，使用go run  main.go 会显示  
![image](https://user-images.githubusercontent.com/9073321/39689898-e57c1420-520a-11e8-9965-2bcfad90e17e.png)

**Comment by iikira** [comment]
将整个项目移动到$GOPATH/src/github.com/iikira/BaiduPCS-Go

在这里默认的GOPATH是/Users/wuyiping/go

总而言之，go语言是逃不掉gopath的……如果你是用go get获取代码，会自动处理好这些
