### ISSUE TITLE
Download speed is unstable.

### ISSUE THREAD

**Issue by f8zhao** [iikira/BaiduPCS-Go#169]

**Comment by reaCodes** [comment]
On my computer, the speed is unstable, too.

**Comment by ccshare** [comment]
下载速度太霸道了, 下载时网页都浏览不了了 ..............

**Comment by reaCodes** [comment]
@ccshare 这个现象我已经发起过issue了，#151，作者已经在考虑添加。这个issue不适合反馈你的问题，请到 #151 下。
