### ISSUE TITLE
建议增加 batch rename 命令

### ISSUE THREAD

**Issue by offwalk** [iikira/BaiduPCS-Go#17]
rename会很实用；
还有could not locate box "static"修复一下。
希望项目会越来越好。谢谢

**Comment by iikira** [comment]
could not locate box "static" 应该已经修复了 [#0a646e83](https://github.com/iikira/BaiduPCS-Go/commit/0a646e83deeca855359fa012094f3f5d24db63df)

还有批量重命名……命令实现起来估计很蛋疼……我……

**Comment by offwalk** [comment]
好的，继续加油。
