### ISSUE TITLE
update 和 export 命令取消了吗

### ISSUE THREAD

**Issue by maonx** [iikira/BaiduPCS-Go#170]
下载了是新版本3.5 ，这2个命令是取消了吗，使用`help`命令的时候没有看到，但网页说明里面有。

**Comment by iikira** [comment]
这是下一个版本的功能，编译安装程序即可看到

**Comment by maonx** [comment]
下一个版本 不需要编译也可以用吗

2018年5月8日 下午12:27，"iikira" <notifications@github.com>写道：

这是下一个版本的功能，编译安装程序即可看到

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iikira/BaiduPCS-Go/issues/170#issuecomment-387280726>,
or mute the thread

**Comment by iikira** [comment]
这里也可以获取到！https://ci.appveyor.com/project/iikira/baidupcs-go

**Comment by maonx** [comment]
好的，非常感谢

iikira <notifications@github.com> 于 2018年5月8日周二 下午12:34写道：
