### ISSUE TITLE
为什么下载速度不稳定？

### ISSUE THREAD

**Issue by reaCodes** [iikira/BaiduPCS-Go#171]
最新版，我的并发量设为300，下载速度来回跳，一会四五兆，一会几十K，非常不稳定。

网络应该没问题，是不是我哪里设置不对？

**Comment by iikira** [comment]
正在解决中……
duplicate of #169

**Comment by shaopy** [comment]
@iikira  many thanks you make the tool free,  have you fixed  the download rate quitely not stable issue?
