### ISSUE TITLE
这个软件还没有暂停和断点续传功能么，请问？

### ISSUE THREAD

**Issue by mysq1isworst** [iikira/BaiduPCS-Go#176]
RT,有时候会需要暂停一下，尤其是下载的东西比较大的时候

**Comment by lengyanyu258** [comment]
直接退出即可；重新登陆再下载，会断点续传。

**Comment by iikira** [comment]
下载暂停功能已经记录: #25, 目前正在找实现方法

支持断点续传了啊, 触发的条件是, 下载文件未完成程序退出, 下一次下载到该文件时自动继续...

**Comment by FinalThorn** [comment]
@iikira  “下一次下载到该文件时自动继续...”是指 下次你手动download 上次未完成的下载的文件或文件夹吗？还是说程序启动启动之后自动检查是否存在未下载完成的文件然后自动下载呢？

**Comment by lengyanyu258** [comment]
@FinalThorn 前者。
