### ISSUE TITLE
能否把web功能用前端实现？

### ISSUE THREAD

**Issue by kangyu1230** [iikira/BaiduPCS-Go#177]
大佬你的BaiduPCS-Go真的很好很强大，赞一个。目测web功能正在测试中，有个小小的建议，大佬能否考虑一下把web前端单独拿出来，这样可以独立地部署到 Nginx / Caddy 等web服务器中，类似于 AriaNG [https://github.com/mayswind/AriaNg](url) ，通过端口和token连接BaiduPCS-Go 。这样BaiduPCS-Go运行压力估计能小些，而且Nginx / Caddy 跑着web要更稳定一点。
ps: 我是用x86软路由跑的BaiduPCS-Go ，所以远程操作的需求比较大~~

**Comment by iikira** [comment]
应该不会拿出来的，go 语言本身就可以做代替 nginx 等功能，例如监听端口等，拿出来多此一举. 至于你说的压力和稳定性更优，不见得...
