### ISSUE TITLE
下载的存储路径是不是可以短一点？

### ISSUE THREAD

**Issue by reaCodes** [iikira/BaiduPCS-Go#179]
我设置的自定义下载路径是`C:\Users\zhong\Downloads`，本意是把需要下载的单个文件/文件夹直接放到这个文件夹里。可程序总是在路径里加上百度网盘里的完整路径，这样两层三层文件夹还好，如果文件夹层数多，找到这个文件就有点麻烦了。是不是可以考虑不加上百度网盘里的那部分路径？😊

---
![image](https://user-images.githubusercontent.com/13817254/39963462-108ef316-569e-11e8-8450-7fa0ced0716c.png)

**Comment by iikira** [comment]
建议使用save和saveto参数

**Comment by iikira** [comment]
参见 [下载可选参数](https://github.com/iikira/BaiduPCS-Go#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0-1)
