### ISSUE TITLE
下载大小超出实际文件大小，导致下载失败

### ISSUE THREAD

**Issue by nihaoa97** [iikira/BaiduPCS-Go#182]
5] ↓ 685.54MB/685.16MB 0B/s in 13m21.96s, left - .......................

linux_armv7_3.5.1
整个文件夹下载时出现这个问题

**Comment by iikira** [comment]
正在解决
Duplicate of #174.

**Comment by nihaoa97** [comment]
哈哈，想不到你这么快回复 @iikira
