### ISSUE TITLE
你好，我用bduss登陆出现了错误

### ISSUE THREAD

**Issue by bboy-xp** [iikira/BaiduPCS-Go#183]
我按照readme里面的bduss方法获取到了bduss
用login -bduss=<BDUSS>
报错：检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试

**Comment by iikira** [comment]
bduss无效，检查一下格式或者重新登录……

**Comment by bboy-xp** [comment]
好嘞
