### ISSUE TITLE
CentOS下使用？

### ISSUE THREAD

**Issue by 321zhangli123** [iikira/BaiduPCS-Go#185]
请问是否可以在CentOS下使用？运行BaiduPCS-Go-v3.5.1-linux-arm64版本，提示：
./BaiduPCS-Go: ./BaiduPCS-Go: cannot execute binary file
谢谢！

**Comment by 321zhangli123** [comment]
抱歉，打扰了，应该下载amd64版本就可以了。

**Comment by hujy23** [comment]
根据1楼，你下的不就是arm64吗？我再Ubuntu18.04上也遇到了同样的报错
