### ISSUE TITLE
下载完成时，无法自动结束，0速度保持很久

### ISSUE THREAD

**Issue by reaCodes** [iikira/BaiduPCS-Go#186]
遇到了几次这样的情况，似乎下载已经完成，速度为0，但是就是不结束，只能手动强制结束，但是重新下载还是记忆这个断点，还是继续0速度状态

版本v3.5.2
v3.5.1不知是否存在这个情况，但是我没遇到，我是新版本才遇到

---
![image](https://user-images.githubusercontent.com/13817254/40162821-a6d9e6b8-59e7-11e8-94ad-2d9e95e4a2c3.png)

**Comment by iikira** [comment]
Duplicate of #186.
