### ISSUE TITLE
BaiduPCS-Go-v3.5.1-windows-x64下载目录的时候，某些文件下载完毕字节为0

### ISSUE THREAD

**Issue by simonliu009** [iikira/BaiduPCS-Go#189]
我在下载备份的照片目录的时候，发现了这个问题。RAW文件和XMP文件都出现了这种情况，猜测其他文件类型也有可能。
幸好在清空回收站之前检查了一下。
建议：
1. 自动生成一个log文件，提示下载后字节数为0的文件有哪些。
2. 如果下载完毕字节数为0，建议重新自动下载若干次。

**Comment by iikira** [comment]
空文件应该是下载失败了，并且超过了下载失败重试次数，
现在可以输出下载失败的文件列表了，如有需要可以重定向标准输出流和标准错误流

**Comment by simonliu009** [comment]
原先的重下机制可能有问题？如果0字节的文件我不删除直接用d命令重下，直接会跳过的。
所以自动重试的时候应该先自动删除那些0字节文件。

**Comment by iikira** [comment]
建议先更新版本，对空文件有处理的

**Comment by simonliu009** [comment]
直接用 go get -u -v github.com/iikira/BaiduPCS-Go 编译就是最新了的吧？

**Comment by iikira** [comment]
是的

**Comment by simonliu009** [comment]
目前下载了2000多个文件，没再出现0字节问题了。Closed这个issue了。
