### ISSUE TITLE
版本3.5.2 只识别一层文件夹

### ISSUE THREAD

**Issue by ghzgqx** [iikira/BaiduPCS-Go#190]
/下有文件夹a 
文件夹a里面有文件夹b和文件c.txt
文件夹b里面有文件d.txt
使用download /时只能读取一层
下载后a文件夹里面只有一个c.txt和空的文件夹b
二级文件夹b里面的内容没有被下载

**Comment by iikira** [comment]
测试并无问题，提供更多信息可好
