### ISSUE TITLE
undefined: strings.Builder

### ISSUE THREAD

**Issue by a631069724** [iikira/BaiduPCS-Go#193]
编译时报错undefined: strings.Builder 是我用的版本有问题吗？还是strings包有问题？

**Comment by iikira** [comment]
更新go版本go1.10
[编译/交叉编译帮助](https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9)
