### ISSUE TITLE
screen 下文字显示不正确

### ISSUE THREAD

**Issue by Radonodar** [iikira/BaiduPCS-Go#194]
你好，我在使用 BaiduPCS-Go 的时候发现文字显示在 screen 下行为有异常。

# 环境：

环境|版本/平台/值
-----|----
BaiduPCS-Go | 3.5.2(linux-armv7)
Raspbian | 9
screen | 4.05.00(GNU)
$LANG | zh_CN.UTF-8
$LC_CTYPE | zh_CN.UTF-8

# 重现步骤：
1. SSH 登陆该机器。（其实我用的是树莓派 😂）
2. 运行 BaiduPCS-Go，观察输出。（此时显示行为正常）
3. 运行 screen（命令 `screen -dmS bdpcs ./BaiduPCS-Go`），观察输出。（此时显示行为*不正常*）

# 期望结果：
第 2 步和第 3 步中的中文可以正常显示并显示一致

# 实际结果：
第 2 步显示正常、第 3 步显示不正常。
问题（第 3 步）截图见附图[1]

# 其他信息：
我尝试在本地 docker 中搭建了一个 debian，并设置好了 LOCALE，观察到了相同的现象。
也尝试了在目标环境下用 C 输出相同的中文（用的 printf() 按行输出），输出正常。
Go 语言不熟悉，不知道如何处理。

请麻烦看下，谢谢！

# 附图
## 
[1]
![Screenshot-1](https://user-images.githubusercontent.com/39480825/40297686-370deff8-5d13-11e8-9bcc-7178e8627340.PNG)

**Comment by iikira** [comment]
测试正常
试试`screen -dmSU bdpcs ./BaiduPCS-Go`

**Comment by Radonodar** [comment]
多谢。。。确实加上 -U 选项就好了。。。UTF-8。。。没有仔细看 screen 的帮助
