### ISSUE TITLE
zsh: exec format error: ./BaiduPCS-Go

### ISSUE THREAD

**Issue by yejunyu** [iikira/BaiduPCS-Go#195]
zsh: exec format error: ./BaiduPCS-Go

**Comment by iikira** [comment]
应该是你下载错版本了，检查一下系统或者cpu架构吧

**Comment by iikira** [comment]
See also #199.

**Comment by yejunyu** [comment]
谢谢,我是用的mac编译的源码,之前linux没事的,直接下你的执行文件就没事了
