### ISSUE TITLE
请问树莓派3b应该下载哪个版本？  cpu 是 arm v8

### ISSUE THREAD

**Issue by lssb** [iikira/BaiduPCS-Go#199]

**Comment by iikira** [comment]
arm64

**Comment by lssb** [comment]
感谢老铁的及时回复， 可是我下载了arm64之后没办法执行二进制文件啊？
提醒
`
root@raspberrypi:~/BaiduPCS-Go-v3.5.2-linux-arm64 # ./BaiduPCS-Go

-bash: ./BaiduPCS-Go: cannot execute binary file: Exec format error

root@raspberrypi:~/BaiduPCS-Go-v3.5.2-linux-arm64 #
`

**Comment by iikira** [comment]
那就armv5，armv7都试一试吧

**Comment by lssb** [comment]
....ok吧，， 实在不行我就上源码 

辛苦了，
我会及时反馈

**Comment by lssb** [comment]
v5 和 v7 都可以。。。

**Comment by iikira** [comment]
可能你的操作系统是32位的，所以不能运行64位程序

**Comment by lssb** [comment]
天呐，，我忘记这茬了。，。刚刚从64位换回到官方系统 我， 忘记了

**Comment by lssb** [comment]
在screen中启动不了?

**Comment by linux0ne** [comment]
顺便问一下，android版本的程序，有个“16”和“21”是什么意思 ？
手机用arm64的，还是用armv7 or v5 的？
我的手机是麒麟960  华为的    cat cpuinfo 没发现是哪个呀

**Comment by iikira** [comment]
@linux0ne 16和21代表android api级别
可以选择arm64
