### ISSUE TITLE
【bug反馈】下载目录或者文件的时候，无法输入文件完整路径，名字输入不进去。

### ISSUE THREAD

**Issue by ugvf2009** [iikira/BaiduPCS-Go#20]
![2](https://user-images.githubusercontent.com/2819436/35253942-fb83bcda-0022-11e8-83aa-990888cdadb3.png)
有的时候还会出现31066错误。
![3](https://user-images.githubusercontent.com/2819436/35253963-1ed28dc4-0023-11e8-863e-b21eac6af317.png)

**Comment by ugvf2009** [comment]
windows10 64bit OS

**Comment by iikira** [comment]
文件名含有空格时，请使用通配符，或者双引号包含起来……或者空格前加一个反斜杠 \

至于第一张图片，不太懂你的意思……

**Comment by ugvf2009** [comment]
第1张图片意思是：
根目录下面有一个  /自媒体赚钱实操手册.pdf    
复制粘贴时会少字。只显示“媒体实操手册.pdf”” 导致下载失败。如上图所示，
手动输入的时候，“自” 也输入不上去。

**Comment by iikira** [comment]
这.....我。。。这应该是cmd的问题吧，我解决不了。。

**Comment by redapple0204** [comment]
@ugvf2009 用powershell

**Comment by hzc54188** [comment]
@iikira 汉字无法输入：联想的联 剪辑的辑
![3333](https://user-images.githubusercontent.com/24639554/35453381-f9814238-0304-11e8-8856-ef1f97f4f816.png)

**Comment by iikira** [comment]
@hzc54188 这应该不是程序的问题……尝试更换输入法或powershell等……

**Comment by chncpla** [comment]
cmd和powershell都有相同问题，粘贴不全，且手动输入不了

**Comment by iikira** [comment]
@chncpla 有机会我测试一下……身边没windows系统……你可以先用通配符代替一下吧，不用重命名的……

**Comment by dusthan** [comment]
发现很多不能输入中文的问题，我查了下，主要原因为：当输入的中文文字的Unicode编码大于等于u8000（耀）时出现，输入u7FFF（翿）不会出现。
经过追踪，发现问题github.com\peterh\liner\input_windows.go  ——line 106，将Char            int16 改为Char            uint16 问题解决。
看了下代码，当输入的汉字编码大于等于u8000时，溢出了，循环会跳过处理该输入。

**Comment by iikira** [comment]
@dusthan 这非常棒, 可以给 github.com/peterh/liner 发pull request了

**Comment by iikira** [comment]
已修复, 下载新版试试效果
