### ISSUE TITLE
[Enhancement Request] Download path customization

### ISSUE THREAD

**Issue by CaesarW** [iikira/BaiduPCS-Go#204]
First, thank you very much for your effort in making downloading files from Baidu Cloud on all platforms possible! It's really convenient and rapid!

But since I am running it on a server and enabled _nginx autoindex_ function for Baidu download path. (pictures below).  

![screenshot from 2018-05-26 15-30-45](https://user-images.githubusercontent.com/11749340/40573817-001db894-60fa-11e8-9304-3b5dd865ff69.jpg)

Therefore, it's possible to customize __the path of 747******_[username]  folder__, but I would be quite annoying to see one more layer of user folder on the download page. Why not just set an option to allow users to fully customize the download path? I know the current design is for multiple user accounts. But if there's an option to switch between user-divided download folders and fully customize download path, that would really helpful!

Thanks again!

**Comment by iikira** [comment]
```
BaiduPCS-Go download -save /path
BaiduPCS-Go download -saveto=/root /path
```

See also #179.

**Comment by CaesarW** [comment]
Sorry for that. I didn't read the instruction carefully... :-)

**Comment by CaesarW** [comment]
Wait...

Does this means I have to add options and parameters every time I start a download? Is it possible to make -saveto as an config setting?

**Comment by iikira** [comment]
no, may cause confusion (saveto and savedir).
