### ISSUE TITLE
建议把第七条打码

### ISSUE THREAD

**Issue by redapple0204** [iikira/BaiduPCS-Go#21]
emmm据我所知，得到了BDUSS可以直接登录百度账号，这样子有风险
所以建议把第七条打码
![deepinscreenshot_select-area_20180124210704](https://user-images.githubusercontent.com/16254644/35333713-b70f5298-014a-11e8-87b4-70d76f1e19c5.png)

**Comment by iikira** [comment]
哈哈哈哈哈哈哈哈，这个是前年做的教程，做完以后好像退出掉了……所以…应该已经失效了吧.

**Comment by redapple0204** [comment]
@iikira 那应该就没啥问题了
