### ISSUE TITLE
文件名中有空格无法识别

### ISSUE THREAD

**Issue by A1pha2er0** [iikira/BaiduPCS-Go#211]
如果文件名有空格，下载时会得到如下错误信息：
获取路径信息错误, 获取文件/目录的元信息, 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: file does not exist

**Comment by iikira** [comment]
参见[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98), 有提到的
