### ISSUE TITLE
ls 能加个grep功能吗？或者增加一下搜索的功能？

### ISSUE THREAD

**Issue by MoneZhao** [iikira/BaiduPCS-Go#214]
RT

**Comment by iikira** [comment]
在外部使用grep吧

**Comment by MoneZhao** [comment]
@iikira 一直用的cli交互模式，忘了还有外部命令

**Comment by iikira** [comment]
已增加搜索功能, https://github.com/iikira/BaiduPCS-Go/commit/eb5f66a5fb110201f98f192063040c73b78153f0
