### ISSUE TITLE
[编译请求] 优化mips编译参数

### ISSUE THREAD

**Issue by hpeng526** [iikira/BaiduPCS-Go#221]
On 32-bit MIPS systems, the new environment variable settings GOMIPS=hardfloat (the default) and GOMIPS=softfloat select whether to use hardware instructions or software emulation for floating-point computations.

官方版openwrt一般没有开启fpu emulator， 希望编译mips时候增加参数。

https://golang.org/doc/go1.10

**Comment by iikira** [comment]
已加上这个参数, e403a71a8e1f1ca147f8a70e4b9073678c730367
