### ISSUE TITLE
在iOS上运行时报错

### ISSUE THREAD

**Issue by lz233** [iikira/BaiduPCS-Go#224]
rt
iOS 7.1.2;iPhone 4(3,1)
提示 runtime/cgo:no Info.plist URL
![ea s 06v5cfa956bu efh5](https://user-images.githubusercontent.com/32504382/41409909-6a693c68-700a-11e8-9c1e-4622d676a4b2.jpg)

**Comment by iikira** [comment]
只是一个警告消息，可以忽略，将源码的Info.plist文件，复制到程序同级目录即可消除该消息
