### ISSUE TITLE
未匹配到当前系统的程序更新文件, GOOS: linux, GOARCH: amd64

### ISSUE THREAD

**Issue by roachsinai** [iikira/BaiduPCS-Go#225]
使用`sudo BaiduPCS-Go update`时显示`未匹配到当前系统的程序更新文件, GOOS: linux, GOARCH: amd64`。

是Arch不支持么？

**Comment by iikira** [comment]
3.5.1自动更新功能异常，所以手动更新吧

**Comment by roachsinai** [comment]
好的，谢谢！
