### ISSUE TITLE
直接执行编译命令报错

### ISSUE THREAD

**Issue by Rhenium187** [iikira/BaiduPCS-Go#226]
系统环境：Manjaro linux 4.14.48; 64位
go version go1.9.2 linux/amd64
下载无问题
编译过程中出现如下报错

> go get -u -v github.com/iikira/BaiduPCS-Go

`# github.com/iikira/BaiduPCS-Go/pcspath
/home/maple/golang-work/src/github.com/iikira/BaiduPCS-Go/pcspath/util.go:14:14: undefined: strings.Builder
/home/maple/golang-work/src/github.com/iikira/BaiduPCS-Go/pcspath/util.go:37:14: undefined: strings.Builder
/home/maple/golang-work/src/github.com/iikira/BaiduPCS-Go/pcspath/util.go:78:14: undefined: strings.Builder
# github.com/iikira/BaiduPCS-Go/requester/multipartreader
/home/maple/golang-work/src/github.com/iikira/BaiduPCS-Go/requester/multipartreader/multipartreader.go:46:14: undefined: strings.Builder
# github.com/iikira/BaiduPCS-Go/requester/downloader
/home/maple/golang-work/src/github.com/iikira/BaiduPCS-Go/requester/downloader/monitor.go:448:14: undefined: strings.Builder
`

**Comment by iikira** [comment]
[编译/交叉编译帮助](https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9)

不看readme么？

**Comment by iikira** [comment]
升级go1.10以上即可
