### ISSUE TITLE
关于pcs_config.json文件的位置问题

### ISSUE THREAD

**Issue by LuomingXu** [iikira/BaiduPCS-Go#227]
在3.3.3的时候, 这个文件是在exe文件的目录下的, 然后我今天更新到了3.5.3, 不明白为什么到了appdata/roaming里面..., 
毕竟用命令改配置有点烦, 直接改json文件方便, 这配置文件"藏"的有点深...

**Comment by iikira** [comment]
v3.5调整了配置路径 #153,
你可以将pcs_config.json移到程序所在目的录下，会自动识别的

**Comment by LuomingXu** [comment]
nice
