### ISSUE TITLE
请问如何查看linux系统应该下载哪个版本

### ISSUE THREAD

**Issue by waltli** [iikira/BaiduPCS-Go#229]
linux版本较多，arm64，amd64，mips等，如何知道自己的linux系统适用哪个版本呢？谢谢！

**Comment by iikira** [comment]
这些是cpu架构类型，你不清楚的话，可一个个尝试

**Comment by waltli** [comment]
额，我想LINUX应该有相应的口令可以直接查询到CPU架构类型的，自己在百度上查了下，没找到准确的口令，如果你能提示下那就实在是太好了啊。

**Comment by waltli** [comment]
model name      : Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
Architecture:          x86_64

谢谢哦，我用口令看了下，我是intel的CPU   64位的架构，应该选用哪个啊？貌似没有Intel的？

**Comment by iikira** [comment]
amd64

**Comment by waltli** [comment]
好的，谢谢
