### ISSUE TITLE
下载的时候进度条前后抖动

### ISSUE THREAD

**Issue by JosephRowing** [iikira/BaiduPCS-Go#230]

**Comment by iikira** [comment]
麻烦详细描述

**Comment by iikira** [comment]
No response from reporter.

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)
