### ISSUE TITLE
上传到一半速度变为0,如何断点续传？

### ISSUE THREAD

**Issue by litingfeng** [iikira/BaiduPCS-Go#235]
同时上传很多文件时，突然速度变为0,卡住1个小时了，又不敢关掉。怎么解决呢？

**Comment by iikira** [comment]
目前上传无法断点续传哦，建议重试

**Comment by litingfeng** [comment]
好的，非常感谢！

**Comment by iikira** [comment]
支持断点续传了, 2ba6ac7327adeb6f53ae2981933d917702450fd9

另外，上传很多文件的过程中断，下一次上传会检测重复的
