### ISSUE TITLE
建议加入多文件同时下载的选项（同时下载的文件数可设置）

### ISSUE THREAD

**Issue by justyre** [iikira/BaiduPCS-Go#236]
如题，最近几天工作原因，每天需要下载上千个小文件（单个大小<5M），线程和缓存数都调到接近上限了，还是明显比下载单个正常文件（几十M或更大的）要慢很多。

感觉单单调高线程不能解决多个小文件依次下载、不能用满带宽的问题。建议加一个多文件同时下载的参数，文件数可以用户设置。

**Comment by iikira** [comment]
已经支持了哦, 0dfdbacfff5509098b5885c3d34c51bb52c8c1e4
编译安装吧.
