### ISSUE TITLE
账号密码怎么登录

### ISSUE THREAD

**Issue by weargle** [iikira/BaiduPCS-Go#24]
你账号密码登录例子看不懂

**Comment by iikira** [comment]
login命令就行了啊
readme忘记更新了，待会儿补上……

**Comment by weargle** [comment]
登录出现错误，怎么重新登录
![20180127154450](https://user-images.githubusercontent.com/26951765/35469865-5fd03520-0379-11e8-9b56-ad850e4508f8.png)

**Comment by iikira** [comment]
@weargle 是网络错误，重新运行命令即可……我得完善一下……

**Comment by iikira** [comment]
emmmmm...... 应该不会报这个错误了 [#51f76cb](https://github.com/iikira/Baidu-Login/commit/51f76cb19e0821e6a407b1266d1708f538dfc2e8)

**Comment by weargle** [comment]
下载最新的登录成功了，暂时没啥问题，谢谢

**Comment by iikira** [comment]
@weargle windows下的中文输入确实是有些问题

**Comment by weargle** [comment]
cmd有中文问题，powershell没有这个问题，你打包生成的EXE文件默认cmd运行

**Comment by iikira** [comment]
貌似powershell也有中文的问题……
你可以试试双击程序之后输入一些中文看看，应该会有一些中文无法输进去的……

**Comment by weargle** [comment]
web运行报报错，没有自动退出
![20180128103815](https://user-images.githubusercontent.com/26951765/35478404-a0ab6850-0417-11e8-9152-0d7b386a1685.png)

**Comment by iikira** [comment]
要把源码下载到本地才行的

**Comment by weargle** [comment]
确实没办法输进去

**Comment by iikira** [comment]
噗…

**Comment by weargle** [comment]
我觉得最好设置报错重新输入，而不是卡在显示报错的地方

**Comment by iikira** [comment]
登录报错吗？

**Comment by iikira** [comment]
应该不会报这种错误了 [#a8534e0](https://github.com/iikira/BaiduPCS-Go/blob/a8534e03c8e86644dbe58cac43d8495a6699d92a/pcsweb/pcsweb.go)
不过要把源码下载到本地才行才能看到效果

**Comment by iikira** [comment]
关闭这条issue了，关于部分中文没办法输入的问题，与 [#20](https://github.com/iikira/BaiduPCS-Go/issues/20) 一样，等待修复，目前可以暂时使用通配符代替不能输入的中文。
web一般的报错支持重新输入了，不过web需要的静态和模板文件都在源码里面，没打包进程序里，所以要把源码下载到本地才可以看到web......(其实也没什么好看的哈哈哈)
