### ISSUE TITLE
[功能请求]对于文件名和路径的操作希望加入通配符支持

### ISSUE THREAD

**Issue by SeAL80s** [iikira/BaiduPCS-Go#242]
在Windows环境下，文件名有空格是合法的，但是上传到网盘的过程中。程序不能自动对空格加转义，而且对于子目录貌似不能自动加\转义。如果想上传一个目录层次较多，或者文件多含有空格的情况，无法上传，会提示路径不存在。例如E:\目 录1\子 目录2\文 件3.mp4 

还有希望mv命令，也能支持通配符，比如mv *.mp4 指定目录。

**Comment by iikira** [comment]
空格是识别多个文件的分隔符，需手动转义
mv 命令已支持这种操作，v3.5.3的 mv 命令异常，最新的 commit 已修复
