### ISSUE TITLE
下载大文件时速度为零

### ISSUE THREAD

**Issue by shiyue2002** [iikira/BaiduPCS-Go#244]
使用本工具下载100M以下的文件时，速度理想。但下载几个G的文件时，往往几秒后速度就降为零。调整了线程数和缓存后也没有改变
系统：Windows 7
版本：3.5.3

**Comment by iikira** [comment]
[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

建议打开调试查看情况

**Comment by iikira** [comment]
没有回应，先关闭了，如果有问题再打开
