### ISSUE TITLE
[Feature Request] 加密分享与自定义分享密码

### ISSUE THREAD

**Issue by lewisxy** [iikira/BaiduPCS-Go#248]
如题，share set好像没有加密分享的功能，不加密的分享有时候会被封的比较快。另外我在一个[网站](https://greasyfork.org/en/scripts/367750-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98-%E7%99%BE%E5%BA%A6%E4%BA%91%E5%88%86%E4%BA%AB%E5%AF%86%E7%A0%81)上看到用Javascript实现网页版自定义分享密码，不知作者有没有计划添加此功能。

**Comment by iikira** [comment]
已经记录, #243
