### ISSUE TITLE
下载断点续传，文件损坏

### ISSUE THREAD

**Issue by xodidox** [iikira/BaiduPCS-Go#249]
系统突然断电，重启后下载这个文件直接断点续传，但最终下载的文件MD5不对。比较了一下错误的文件和正确的文件（又重新从头下载了一次），好像是在断电的时候，文件数据丢失了一部分。断点续传能不能加一个分块校验的机制，对于检验失败的块直接丢弃重新下载？否则下载完成的部分已经出错了，再继续下载已经没有意义了，如果不行的话，最好直接从头开始下载。

**Comment by Songxuewen** [comment]
嗯，新版本我也发现这个问题

**Comment by iikira** [comment]
已支持下载完成后校验文件, df82928b832bac26321236ebeb4d6db9a918d48f, 可以提示校验失败的文件了
