### ISSUE TITLE
并发和缓存都调最大了为什么不能满速

### ISSUE THREAD

**Issue by Mortalit** [iikira/BaiduPCS-Go#250]
正常下载速度应该有10M/s
可是并发和缓存调到一半数值或是调满都只能达到2M/s

**Comment by iikira** [comment]
不保证速度!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

**Comment by Mortalit** [comment]
还有win版为啥 max_download_load设置不了,不是增加了这个功能吗?

**Comment by iikira** [comment]
该功能测试中，编译安装即可看到
