### ISSUE TITLE
登陆失败 代码错误-1

### ISSUE THREAD

**Issue by 2465068058** [iikira/BaiduPCS-Go#251]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com: getaddrinfow: A non-recoverable error occurred during a database lookup.

**Comment by iikira** [comment]
测试正常

查了一下，此错误消息说明是你的网络出了问题，
> 指示在数据库查找时发生了某种不可恢复错误。它可能是因为数据库文件（如HOSTS、SERVICES或PROTOCOLS文件）找不到，或DNS请求应服务器有严重错误而返回。

自行排查以上可能的异常

**Comment by 2465068058** [comment]
好的，谢谢
