### ISSUE TITLE
获取离线下载列表时候出错了

### ISSUE THREAD

**Issue by YinMengStudio** [iikira/BaiduPCS-Go#257]
查询离线下载任务列表, json 数据解析失败, struct { TaskInfo map[string]*baidupcs.cloudDlTaskInfo "json:\"task_info\""; *baidupcs.ErrInfo }.TaskInfo: baidupcs.cloudDlTaskInfo.FileList: []*struct { FileName string "json:\"file_name\""; FileSize string "json:\"file_size\"" }: struct { FileName string "json:\"file_name\""; FileSize string "json:\"file_size\"" }.FileSize: ReadString: expects " or n, but found 1, error found in #10 byte of ...|le_size":1143178900}|..., bigger context ...|\u4e2d\u82f1\u53cc\u5b57\u5e55.rmvb","file_size":1143178900}],"result":0},"2191993243":{"status":"0"|...

**Comment by iikira** [comment]
提供一下版本号

**Comment by YinMengStudio** [comment]
----
  BaiduPCS-Go - 百度网盘客户端 for windows/amd64

USAGE:
  BaiduPCS-Go.exe [global options] command [command options] [arguments...]

VERSION:
  v3.5.3-devel

**Comment by iikira** [comment]
是服务器返回的数据无法解析，原因未知

**Comment by iikira** [comment]
现在来看，这个功能是正常的，请更新新版本试一试
