### ISSUE TITLE
您好，老铁iPhone7 ios11.3.1  越狱了安装了你源内的插件。不能运行

### ISSUE THREAD

**Issue by HuangGajim** [iikira/BaiduPCS-Go#258]
在终端中运行BaiduPCS-go 显示   
sh ：/usr/bin/BaiduPCS-go Cannot execute  binary
file：operation Not permitted

**Comment by iikira** [comment]
有没有切换root用户执行

**Comment by HuangGajim** [comment]
已经su root 执行了    然后也试过chmod777 给过权限也不行

**Comment by iikira** [comment]
将文件移到另外一个目录试试能不能执行

**Comment by HuangGajim** [comment]
不行

**Comment by HuangGajim** [comment]
移到根目录也不行

**Comment by iikira** [comment]
软件源内的只有32位的软件，建议到发布页下载64位的试一试呢
[BaiduPCS-Go-v3.5.3-darwin-ios-5.0-arm64.zip](https://github.com/iikira/BaiduPCS-Go/releases/download/v3.5.3/BaiduPCS-Go-v3.5.3-darwin-ios-5.0-arm64.zip)

**Comment by HuangGajim** [comment]
老铁 还是同样提示。。。

**Comment by iikira** [comment]
没设备，没有办法测试呢

**Comment by iikira** [comment]
v3.6已发布, 应该修复这个问题了, 目前软件源未更新，到发布页手动下载运行吧
