### ISSUE TITLE
shell 脚本调用 offlinedl 返回值的逻辑判定问题

### ISSUE THREAD

**Issue by Ancientwood** [iikira/BaiduPCS-Go#259]
由于惯于用 **renren zimuzu** 看美剧，于是写了 `shell` 脚本通过 `rss` 获取 `ed2k` ，利用您的 `BaiduPCS-Go` 自动定时进行 `offlinedl`  ，脚本可以正常使用，测试过多后出现：

`[1] 添加离线下载任务, 遇到错误, 远端服务器返回错误, 代码: 36022, 消息: user is vip and exceed concurrency ...`

为避免 **实际未成功** 执行 `offlinedl` ，需要修改语句：

```
    ~/BaiduPCS-Go/BaiduPCS-Go offlinedl add -path /movie/$1 ${ed2ks[$i]}

    if [ $? -eq 0 ]
    then
        echo ${ed2ks[$i]} >> $2.ed2k
    fi

```

`shell` 语句的确正常执行了，返回的 `$? -eq 0`  没有问题，执行了您的 `BaiduPCS-Go offlinedl` 输出 `36022` ，这时该如何通过 `BaiduPCS-Go` 获得错误代码，进行逻辑判定？

通过标准输出来判断亦或是 `BaiduPCS-Go` 有接口输出？ _《shell 编程从入门到没摸到门槛》_

附：

```
#!/bin/bash

function autoD(){

if [ -f $2 ]
then
    rm $2
fi

wget -q  "http://diaodiaode.me/rss/feed/$2"

ed2ks=($(grep -oP '(?<=ed2k>)[^<]+' "$2"))

for i in ${!ed2ks[*]}
do

    if [ ! -f $2.ed2k ]
    then
        echo "mkdir $1 in movie ..."
        ~/BaiduPCS-Go/BaiduPCS-Go mkdir /movie/$1
        touch $2.ed2k
    fi

    COUNT=$(wc -l < $2.ed2k)

    if [ $COUNT -le $i ]
    then

    echo "downloading $1-$i ..."

    ~/BaiduPCS-Go/BaiduPCS-Go offlinedl add -path /movie/$1 ${ed2ks[$i]}

    if [ $? -eq 0 ]
    then
        echo ${ed2ks[$i]} >> $2.ed2k
    fi

    sleep 2s
    fi

done
}

autoD "shinv" 35039
autoD "yinziBishou" 36385
```

**Comment by iikira** [comment]
暂无shell 的逻辑判定方法
不过，可通过这个 go 的库自行编程：
[github.com/iikira/BaiduPCS-Go/baidupcs](https://github.com/iikira/BaiduPCS-Go/tree/master/baidupcs)
