### ISSUE TITLE
linux版本的一些建议

### ISSUE THREAD

**Issue by alexchanchan** [iikira/BaiduPCS-Go#26]
1、web功能，希望能自定义端口。
2、希望能加入后台下载

**Comment by iikira** [comment]
1，会的；2，虽然golang的daemon不太好首先，不过总有办法吧……

**Comment by redapple0204** [comment]
@iikira 后台下载直接用&不行？

**Comment by iikira** [comment]
@redapple0204 可以啊，加个nohup不错

**Comment by ghostry** [comment]
后台我喜欢用screen

**Comment by fvstar** [comment]
linux 版下载后还是不会用，"光标所在行的前缀应为 BaiduPCS-Go >"这个前缀怎么调出来？

**Comment by iikira** [comment]
@fvstar 给BaiduPCS-Go加执行权限，然后直接执行即可，在终端执行……

**Comment by iikira** [comment]
后台下载，感觉没有加入的必要。必要的话可以使用nohup等实现。
