### ISSUE TITLE
无法设置带空格的下载目录

### ISSUE THREAD

**Issue by TGSAN** [iikira/BaiduPCS-Go#260]
使用`config set -savedir=<DOWNLOAD_DIR>`不能设置带空格的目录，\s和引号内带空格都试过了，但是均不能设置带空格的下载目录，如`config set -savedir="D:\\Baidu Download"`

**Comment by iikira** [comment]
去掉等号即可
```
config set -savedir "D:\\Baidu Download"
```
可能是这个库的bug:
https://github.com/urfave/cli

**Comment by swqmaven** [comment]
@iikira 问下啥时候支持大文件上传？

**Comment by iikira** [comment]
@swqmaven 已支持, 2ba6ac7327adeb6f53ae2981933d917702450fd9
