### ISSUE TITLE
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: proxyconnect tcp: EOF

### ISSUE THREAD

**Issue by summerwiki** [iikira/BaiduPCS-Go#261]
![image](https://user-images.githubusercontent.com/38489611/42564211-c8706024-8532-11e8-9e36-26b3072d608f.png)
我是deepin的Linux系统，64位，我下载的BaiduPCS-Go-v3.5.3-linux-amd64.zip安装包，登录的时候提示EOF，然后我用朋友的Ubuntu上的3.5版本登录，可以登录成功

**Comment by iikira** [comment]
看你的关键字"proxyconnect", 先排除一下代理的问题

**Comment by ShixiangWang** [comment]
和题主一样的系统和问题，有解决吗？

**Comment by ShixiangWang** [comment]
> 和题主一样的系统和问题，有解决吗？
我去掉代理就解决了。
