### ISSUE TITLE
获取和下载都出错

### ISSUE THREAD

**Issue by heixiake** [iikira/BaiduPCS-Go#263]
获取目录下的文件列表, 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: lookup pcs.baidu.com on 223.113.97.99:53: read udp 10.1.5.62:64264->223.113.97.99:53: i/o timeout

**Comment by iikira** [comment]
这属于网络问题，目前你的dns是223.113.97.99，无法连接，更换个能用的dns即可

**Comment by heixiake** [comment]
获取目录下的文件列表, 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: lookup pcs.baidu.com on 1.1.1.1:53: read udp 10.1.5.62:50380->1.1.1.1:53: i/o timeout

**Comment by heixiake** [comment]
@iikira  换成1.1.1.1也不行
获取目录下的文件列表, 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: lookup pcs.baidu.com on 1.1.1.1:53: read udp 10.1.5.62:50380->1.1.1.1:53: i/o timeout

**Comment by iikira** [comment]
8.8.8.8
119.29.29.29
都试一试
