### ISSUE TITLE
下载时速度为0

### ISSUE THREAD

**Issue by Meier2011** [iikira/BaiduPCS-Go#265]
![_20180712140441](https://user-images.githubusercontent.com/37300119/42615545-409d9bca-85dd-11e8-8379-ee761642b9e7.png)
最开始的几秒有速度，但很快，在几秒内就会跌到0
此时时间计数也会停止，一直卡在35秒左右
已经设置环境变量，在程序运行时加上全局option: -verbose显示
DEBUG: monitor: resetAllFailedAndNetErrorWorkers start

**Comment by iikira** [comment]
与#238 一样，关闭了，等待修复
