### ISSUE TITLE
还是上次反映的

### ISSUE THREAD

**Issue by xzzbz** [iikira/BaiduPCS-Go#269]
echo "deb [arch=arm] http://termux.iikira.com stable main" >> /data/data/com.termux/files/usr/etc/apt/sources.list

apt update

apt list

并没有baidupcs-go

apt install baidupcs-go自然未找到软件包

**Comment by iikira** [comment]
无视即可，不影响使用

**Comment by iikira** [comment]
cpu类型是否正确？

查看cpu类型:
```
uname -m
```

另外试一试
```
vi /data/data/com.termux/files/usr/etc/apt/sources.list
```
将多余的内容去掉.

**Comment by xzzbz** [comment]
去掉试过的，cup是armv7l。类型正确！

麻烦你测试一下，我fq，apt update的。不存在被墙，应该是源出现问题。

我另一个arm64位也显示为签署啥的东东，麻烦你了

**Comment by 978634482** [comment]
$ apt install baidupcs-go
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package baidupcs-go
$

**Comment by 978634482** [comment]
Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by iikira** [comment]
```
apt --allow-unauthenticated update
apt install baidupcs-go
```

试一试, 改天看一看这个是怎么签名的

**Comment by iikira** [comment]
应该没有这个问题了，请查看最新的文档
