### ISSUE TITLE
车字复制不了，也不能输入欸

### ISSUE THREAD

**Issue by sayviness** [iikira/BaiduPCS-Go#27]
不知道怎么上图，反正就是我下载欧洲卡车2的时候，发现，车字，不能输入..
最后只好去网盘把车删了。麻烦修复下呗，谢谢

**Comment by sayviness** [comment]
![snipaste_20180129_152004](https://user-images.githubusercontent.com/22439347/35498208-4e609934-0508-11e8-8da5-22faa90a42b1.png)

**Comment by sayviness** [comment]
试用了下，速度快的时候可以满速，慢的时候是几百kb，基本稳定在中游，还是很厉害的。感谢感谢

**Comment by iikira** [comment]
我关闭这条issue了，因为与 [#20](https://github.com/iikira/BaiduPCS-Go/issues/20) 一样，等待修复，目前可以暂时使用通配符代替不能输入的中文。
