### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by MAX-Man-1** [iikira/BaiduPCS-Go#271]
下载失败

**Comment by iikira** [comment]
麻烦详细描述

**Comment by cuijianzhuang** [comment]
提示: 当前下载最大并发量为: 100, 下载缓存为: 1024
[1] 加入下载队列: /1
[1] 获取路径信息错误, 获取文件/目录的元信息, 遇到错误, 远端服务器返回错 误, 代码: 31066, 消息: file does not exist
任务结束, 数据总量: 0B
BaiduPCS-Go:/ CJZQWER$
BaiduPCS-Go:/ CJZQWER$

**Comment by iikira** [comment]
@cuijianzhuang 文件不存在，检查输入

@MAX-Man-1 未回应，先关闭了
