### ISSUE TITLE
SVIP 文件20GB的分卷ZIP包上传失败

### ISSUE THREAD

**Issue by codeshif** [iikira/BaiduPCS-Go#272]
我是百度SVIP，上传20GB的zip包分卷时，显示失败。
> 显示信息：
[1] 上传文件失败, 上传单个文件, 网络错误, http 响应错误, 413 Request Entity Too Large, 重试 0/3

文件体积太大了吗？

**Comment by iikira** [comment]
上传暂不支持2g以上的文件
和#106 一样，关闭了

**Comment by codeshif** [comment]
好的谢谢领导
