### ISSUE TITLE
根目录执行ls命令报错

### ISSUE THREAD

**Issue by deng55** [iikira/BaiduPCS-Go#273]
获取目录下的文件列表, 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2F: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  

执行下载命令也会报这个错！

**Comment by deng55** [comment]
digitalOcean 的vps debian64位系统

**Comment by iikira** [comment]
网络超时
