### ISSUE TITLE
秒传 是否可以用于上传文件夹？

### ISSUE THREAD

**Issue by codeshif** [iikira/BaiduPCS-Go#275]
大佬您好，秒传文件我知道怎么使用，请问秒传文件夹的问题，现在我的问题是：

我有很多**20GB**文件的**分卷**，但是百度服务器现**没有MD5**，通过BaiduPCS-GO上传失败需要分片操作(**因不支持2GB以上**)，
我预估分卷解压后，直接上传解压后的文件数据，**百度服务器肯定有那些文件的MD5**，但是需要**上传目录**，

**请问上传目录，是否会对目录中的文件进行秒传判定？**

**Comment by iikira** [comment]
你的目录指的是压缩包内的目录？

**Comment by codeshif** [comment]
将压缩包解压后的目录哦大佬

**Comment by codeshif** [comment]
压缩包解压之后，**直接上传该文件夹**，是否可以将文件夹的文件秒传呢？（在百度服务器有该文件MD5的情况下） @iikira

**Comment by iikira** [comment]
可以的

**Comment by codeshif** [comment]
好的非常感谢
