### ISSUE TITLE
文件下载失败 illegal seek

### ISSUE THREAD

**Issue by deng55** [iikira/BaiduPCS-Go#276]
![image](https://user-images.githubusercontent.com/9801268/42854999-1a8849b0-8a71-11e8-9018-588d9ff9340c.png)

**Comment by deng55** [comment]
![image](https://user-images.githubusercontent.com/9801268/42856257-fe411f4c-8a76-11e8-9ed7-ba839ba7213c.png)
权限应该没问题，下载目录也是挂载的google drive 的目录

**Comment by iikira** [comment]
这个不是本地的目录吗

**Comment by deng55** [comment]
googledrive是本地的目录，用rclone挂载了google drive在googledrive这个目录下，然后我把BaiduPCS-Go的下载目录也设置成googledrive，不管下载什么文件都是illegal seek 错误

**Comment by deng55** [comment]
试了一下，把保存目录设置到/home可以成功下载，不过googledrive这个文件夹权限没问题，不知道啥原因

**Comment by iikira** [comment]
猜测rclone或googledrive没提供完整的文件操作指令，例如truncate和seek等

**Comment by iikira** [comment]
rclone挂载googledrive，模拟的文件系统，没有办法提供完整的文件操作指令，建议先下载到本地储存再手动复制到googledrive.
