### ISSUE TITLE
不支持有空格的文件和目录

### ISSUE THREAD

**Issue by Rakau** [iikira/BaiduPCS-Go#278]
目录不带空格,目录里文件带空格可以下
但是文件和目录带空格就不能下

**Comment by iikira** [comment]
参见[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98), 有提到的

**Comment by Rakau** [comment]
谢谢
