### ISSUE TITLE
web 无法访问

### ISSUE THREAD

**Issue by shanaiardor** [iikira/BaiduPCS-Go#28]
BaiduPCS-Go > web
web 客户端功能为实验性功能, 测试中, 打开 http://localhost:8080 查看效果
could not locate box "static"

访问 http://localhost:8080/ 后 cmd 输出

2018/01/29 17:41:35 http: panic serving [::1]:3181: open index.html: The system cannot find the file specified.
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc04220e140)
        /usr/local/go/src/net/http/server.go:1697 +0xd7
panic(0x84c260, 0xc042186fc0)
        /usr/local/go/src/runtime/panic.go:491 +0x291
github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go%2erice.(*Box).MustString(0xc042158090, 0x8d636e, 0xa, 0x7, 0xc0421fc748)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go.rice/box.go:329 +0x8a
github.com/iikira/BaiduPCS-Go/web.indexPage(0xb4e980, 0xc0423ae000, 0xc042130800)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/web/httpserver.go:72 +0x4bf
net/http.HandlerFunc.ServeHTTP(0x93a628, 0xb4e980, 0xc0423ae000, 0xc042130800)
        /usr/local/go/src/net/http/server.go:1918 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb8bbe0, 0xb4e980, 0xc0423ae000, 0xc042130800)
        /usr/local/go/src/net/http/server.go:2254 +0x137
net/http.serverHandler.ServeHTTP(0xc04221c270, 0xb4e980, 0xc0423ae000, 0xc042130800)
        /usr/local/go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc04220e140, 0xb4f280, 0xc042171280)
        /usr/local/go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x28f
2018/01/29 17:41:35 http: panic serving [::1]:3182: open index.html: The system cannot find the file specified.
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc042043b80)
        /usr/local/go/src/net/http/server.go:1697 +0xd7
panic(0x84c260, 0xc042187320)
        /usr/local/go/src/runtime/panic.go:491 +0x291
github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go%2erice.(*Box).MustString(0xc042158090, 0x8d636e, 0xa, 0x7, 0xc0421fc988)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go.rice/box.go:329 +0x8a
github.com/iikira/BaiduPCS-Go/web.indexPage(0xb4e980, 0xc0423ae0e0, 0xc042130900)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/web/httpserver.go:72 +0x4bf
net/http.HandlerFunc.ServeHTTP(0x93a628, 0xb4e980, 0xc0423ae0e0, 0xc042130900)
        /usr/local/go/src/net/http/server.go:1918 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb8bbe0, 0xb4e980, 0xc0423ae0e0, 0xc042130900)
        /usr/local/go/src/net/http/server.go:2254 +0x137
net/http.serverHandler.ServeHTTP(0xc04221c270, 0xb4e980, 0xc0423ae0e0, 0xc042130900)
        /usr/local/go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc042043b80, 0xb4f280, 0xc042171380)
        /usr/local/go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x28f
2018/01/29 17:41:35 http: panic serving [::1]:3183: open index.html: The system cannot find the file specified.
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc042043c20)
        /usr/local/go/src/net/http/server.go:1697 +0xd7
panic(0x84c260, 0xc042191230)
        /usr/local/go/src/runtime/panic.go:491 +0x291
github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go%2erice.(*Box).MustString(0xc042158090, 0x8d636e, 0xa, 0x7, 0xc042075b88)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/GeertJohan/go.rice/box.go:329 +0x8a
github.com/iikira/BaiduPCS-Go/web.indexPage(0xb4e980, 0xc04212e1c0, 0xc042130a00)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/web/httpserver.go:72 +0x4bf
net/http.HandlerFunc.ServeHTTP(0x93a628, 0xb4e980, 0xc04212e1c0, 0xc042130a00)
        /usr/local/go/src/net/http/server.go:1918 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb8bbe0, 0xb4e980, 0xc04212e1c0, 0xc042130a00)
        /usr/local/go/src/net/http/server.go:2254 +0x137
net/http.serverHandler.ServeHTTP(0xc04221c270, 0xb4e980, 0xc04212e1c0, 0xc042130a00)
        /usr/local/go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc042043c20, 0xb4f280, 0xc042171440)
        /usr/local/go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x28f

**Comment by iikira** [comment]
要把源码下载到本地才行的。
建议你更新一下程序，应该不会报这种错误了

**Comment by iikira** [comment]
不会报这种错误了，[#d27f335](https://github.com/iikira/BaiduPCS-Go/commit/d27f335daef741a0805b6018d0cb78a1f5bc922c)
另外，web需要的静态和模板文件都在源码里面，没打包进程序里，所以要把源码下载到本地才可以看到web......(其实也没什么好看的哈哈哈)

**Comment by shanaiardor** [comment]
😬  web界面还是比较方便的  (⁄ ⁄•⁄ω⁄•⁄ ⁄)

**Comment by iikira** [comment]
@shanaiardor 不过我会的不多……
