### ISSUE TITLE
run命令不能自动补全

### ISSUE THREAD

**Issue by Dimerbone** [iikira/BaiduPCS-Go#281]
rt，不能tab补全真的超烦的，命令稍微长一点就特别麻烦，比如 run cat /media/root//My\ HardDisk/**/**/**/***.txt 必须挨个打字，有时候还得分清大小写，建议改一下

**Comment by iikira** [comment]
只是提供个功能，运行简单的系统命令，至于tab补全不打算加了

运行 run bash
然后执行你的命令
