### ISSUE TITLE
代理设置？

### ISSUE THREAD

**Issue by jiangjiangflies** [iikira/BaiduPCS-Go#285]
您好，
请问可以增加代理设置参数吗？国外服务器连接度盘速度太慢，想通过设置代理解决。希望增加代理设置参数~~~

**Comment by iikira** [comment]
试试
```
export HTTP_PROXY=http://代理地址
```
好像也支持socks5的代理

**Comment by jiangjiangflies** [comment]
感谢回复，这样设置的话就是系统代理了吧，也会影响其它网络连接的。能不能在BaiduPCS-Go上进行设置？

**Comment by iikira** [comment]
不是系统代理，只在当前终端会话有效

**Comment by jiangjiangflies** [comment]
试了一下 顶呱呱~！谢谢老板~ 
不过还是希望以后老板有机会可以考虑加入这个比较实用的代理功能~

**Comment by iikira** [comment]
已经记录了, #70 , 关闭了
