### ISSUE TITLE
下载只有4k

### ISSUE THREAD

**Issue by redapple0204** [iikira/BaiduPCS-Go#29]

**Comment by iikira** [comment]
请提供更多的信息，如下载进度，文件信息，截图，等等……

**Comment by redapple0204** [comment]
@iikira 
![qq 20180130134445](https://user-images.githubusercontent.com/16254644/35550103-e8983c44-05c3-11e8-94a6-5d5b527359cd.png)
如图

**Comment by iikira** [comment]
有没有改过什么配置，还有，最好分享一下，下载速度慢的文件……

**Comment by redapple0204** [comment]
@iikira 没有欸...另外、链接: https://pan.baidu.com/s/1snhvi4t 密码: ix3c

**Comment by iikira** [comment]
<img width="518" alt="2018-01-30 2 59 10" src="https://user-images.githubusercontent.com/19154488/35552379-a96c9d3e-05ce-11e8-9260-435a6682ba6f.png">

我这里没问题啊...(笑)
还有，就这个文件有问题是吗

**Comment by redapple0204** [comment]
@iikira 是的，挺奇怪啊。不过还好别的资源不影响，那就不管他好了
