### ISSUE TITLE
bug：自动补全有bug

### ISSUE THREAD

**Issue by widon1104** [iikira/BaiduPCS-Go#291]
BaiduPCS-Go:05.Hadoop2.X大数据... widon1104$ ls

当前目录: /大数据/大数据开发之Hadoop工程师全套课程/01.大数据开发之Hadoop工程师基础/05.Hadoop2.X大数据平台视频教程 14课
----
  #   文件大小       修改日期                             文件(目录)                        
   0         -  2018-07-24 18:14:38  第10讲 Hadoop数据入库系统Flume与Sqoop/                 
   1         -  2018-07-24 18:14:38  第11讲 数据分析系统Hive与Pig应用与比较/                
   2         -  2018-07-24 18:14:38  第12讲 数据挖掘工具包Mahout/                           
   3         -  2018-07-24 18:14:38  第13讲 工作流引擎Oozie与Azkaban应用/                   
   4         -  2018-07-24 18:14:38  第14讲 两个综合案例：日志分析系统与机器学习平台/       
   5         -  2018-07-24 18:14:38  第1讲 ：　Hadoop生态系统以及版本演化/                  
   6         -  2018-07-24 18:14:38  第2讲 ：　HDFS 2.0应用场景、原理、基本架构及使用方法/  
   7         -  2018-07-24 18:14:38  第3讲 ：　YARN应用场景、基本架构与资源调度/            
   8         -  2018-07-24 18:14:38  第4讲  MapReduce 2.0基本原理与架构/                    
   9         -  2018-07-24 18:14:38  第5讲  MapReduce 2.0编程实践（涉及多语言编程）/        
  10         -  2018-07-24 18:14:38  第6讲 HBase应用场景、原理与基本架构/                   
  11         -  2018-07-24 18:14:38  第7讲 HBase编程实践（涉及多语言编程）/                 
  12         -  2018-07-24 18:14:38  第8讲 HBase案例分析/                                   
  13         -  2018-07-24 18:14:38  第9讲 Zookeeper部署及典型应用/                         
        总: 0B                       文件总数: 0, 目录总数: 14 

两个问题
1）第一个问题，输入“ls 第1”，然后按tab键自动补全，会补全出“ls 第10讲\ Hadoop数据入库系统Flume与Sqoop/”，这是不对的，应该让我选“第1讲 ：　Hadoop生态系统以及版本演化/ ”还是“第10讲 Hadoop数据入库系统Flume与Sqoop/”
2）第二个问题，输入“download 第1讲”，然后按tab键补全，补全结果是“download 第1讲\ ：　Hadoop生态系统以及版本演化/”，冒号后面是一个空格，前面应该加上转意符'\'，不然会找不到这个目录

**Comment by iikira** [comment]
自动补全是按照服务器返回的数据来排序的，即文件名前面的序号。第二个问题修复了,  217defb44e93fb25ebf356c4c160cda3d6d677fb
