### ISSUE TITLE
存在多层目录的情况下不能下载全部文件

### ISSUE THREAD

**Issue by 12101519** [iikira/BaiduPCS-Go#297]
如A目录下存在AA 子目录（内有bb文件）和aa文件
采用d A方式下载A目录，则只能下载AA空子目录（其中的bb文件不会下载）和aa文件
win7旗舰版  BaiduPCS-Go-v3.5.3-windows-x64版

**Comment by iikira** [comment]
测试正常

**Comment by 12101519** [comment]
我测试文件目录内文件超过1000个，不知道是否这个原因

**Comment by iikira** [comment]
应该和文件的数量没关系的，你可以提供一下输出的日志或截图

**Comment by iikira** [comment]
没有回应。先关闭了，有问题再打开
