### ISSUE TITLE
登录提示：网络请求失败

### ISSUE THREAD

**Issue by jyuan15** [iikira/BaiduPCS-Go#298]
BaiduPCS-Go > login
请输入百度用户名(手机号/邮箱/用户名), 回车键提交 > *****15
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com on [::1]:53: read udp [::1]:54261->[::1]:53: read: connection refused

请问如何解决？

**Comment by iikira** [comment]
你是在安卓上用的嘛？

**Comment by iikira** [comment]
不要使用linux版的程序，网络访问会出问题的

**Comment by jyuan15** [comment]
@iikira 官方介绍中不是明确说明可以在termux上使用吗？我就是按这个说明来操作的

**Comment by iikira** [comment]
是可以运行，下载程序的时候请选择下载android的，不要下载到linux的了，你检查一下

**Comment by jyuan15** [comment]
@iikira 难怪我把文件夹移到arch中就可以登录了。

很久没安装过都忘了这个区别了。。。
