### ISSUE TITLE
不能设置下载到的目录吗？家目录/C盘都有限，虽然可以绕过，但是有些不方便。

### ISSUE THREAD

**Issue by biluohc** [iikira/BaiduPCS-Go#3]

**Comment by iikira** [comment]
queued

**Comment by iikira** [comment]
增加了: [#54c31d9](https://github.com/iikira/BaiduPCS-Go/commit/9e951604b4ec060e56962d0313917bb8e41f7ef0)

**Comment by biluohc** [comment]
感谢， 编译运行成功。
