### ISSUE TITLE
有没有考虑引入同步的概念

### ISSUE THREAD

**Issue by ghostry** [iikira/BaiduPCS-Go#30]
我看现在上传目录。文件存在且一样的时候，还是走一遍。而不是直接跳过。

**Comment by iikira** [comment]
有了秒传，这样就相当于检测了文件是否一样了...

**Comment by ghostry** [comment]
还是差点事。
可能你没有传很多文件。我在上传的是近5万小文件。
每个文件大概几字节到二百多kb。秒传和普通传看不出什么区别。
一个文件一秒是5万秒。就是13小时。
而且现在的不跳过的情况下，网盘里的文件日期会变成最新的日期，即使它好久没改过。

**Comment by iikira** [comment]
好吧，考虑先引入缓存.....

**Comment by iikira** [comment]
应该会跳过一样的文件了, [#c63cbbd](https://github.com/iikira/BaiduPCS-Go/commit/c63cbbd1f7d144601b5dde23a2252110f835d267)
你可以试着编译安装程序，看一下效果怎么样吧......

**Comment by ghostry** [comment]
这非常棒，上传4w文件使用了19分钟。
现在可以很明显的看到文字在向上跳。
