### ISSUE TITLE
建议增加传输完成关闭。

### ISSUE THREAD

**Issue by xqzr** [iikira/BaiduPCS-Go#303]

**Comment by iikira** [comment]
什么意思

**Comment by xqzr** [comment]
说错了，是：传输完成关机。

**Comment by derekhe** [comment]
感觉这个传输完成关机功能可以自己写脚本实现啊
#/usr/bin/bash
Baidupcs-go upload xxxx
shutdown -t 0

**Comment by CoolLby** [comment]
@derekhe 您已经实现了传输完成关机了吗？？？

**Comment by iikira** [comment]
不考虑加入这个功能了，相关功能可以自己写脚本实现
