### ISSUE TITLE
如何编译自己的branch

### ISSUE THREAD

**Issue by Zxilly** [iikira/BaiduPCS-Go#305]
想用这个项目和onedrivecmd配合着做一个网盘转发的工具，然而fork之后修改了无法编译。
所有我能找到的依赖包我都fork了换成自己的链接，然而编译还是报错 
![错误信息](https://imgurl.learningman.top/temp/1808/1e0d15e232b23666.png)

**Comment by iikira** [comment]
建议你直接clone本仓库直接进行修改，比较省事，否则就需把所有源码的import相关的关键字，修改成你仓库的关键字

**Comment by Zxilly** [comment]
@iikira clone了直接修改的话就是要本地编译啊。。。然后那些在线的库都不能导入

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/43813459-5e395ba8-9af8-11e8-8f71-82413007cf88.png)
报错。。

**Comment by Zxilly** [comment]
原来要开Go Vender

**Comment by Zxilly** [comment]
设置了Path...vender可以正确的找到了，然而项目本身的代码也到vender里去找了。。。
```
main.go:10:2: cannot find package "github.com/iikira/BaiduPCS-Go/internal/pcsupdate" in any of:
        C:\Users\12009\Desktop\transfer\src\baidupcsgo\src\BaiduPCS-Go\vendor\github.com\iikira\BaiduPCS-Go\internal\pcsupdate (vendor tree)
        C:\Go\src\github.com\iikira\BaiduPCS-Go\internal\pcsupdate (from $GOROOT)
        C:\Users\12009\go\src\github.com\iikira\BaiduPCS-Go\internal\pcsupdate (from $GOPATH)
        C:\Users\12009\Desktop\transfer\src\baidupcsgo\src\github.com\iikira\BaiduPCS-Go\internal\pcsupdate
```

**Comment by Zxilly** [comment]
看目录结构像是dep，用GoLand设置还是满屏飘红，还要设置GoPath
![image](https://user-images.githubusercontent.com/31370133/43816245-4aff6b78-9b06-11e8-8add-6b00279578a8.png)

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/43816657-660200d2-9b08-11e8-998d-9e2f2e2211e4.png)

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/43817413-f2ea41dc-9b0b-11e8-9828-966f0dcfe2af.png)
![image](https://user-images.githubusercontent.com/31370133/43817423-01405654-9b0c-11e8-9948-d515f8913547.png)

**Comment by iikira** [comment]
弄好了没

**Comment by Zxilly** [comment]
弄好了，用系统自带的GoPath就好了。。。
