### ISSUE TITLE
misple架构下运行后无法登陆，出现以下代码

### ISSUE THREAD

**Issue by 1095893390** [iikira/BaiduPCS-Go#309]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: lookup wappass.baidu.com on 127.0.0.1:53: dial udp 127.0.0.1:53: errno -9

**Comment by iikira** [comment]
貌似这是golang的问题，等golang的下一个版本看看吧
……

https://github.com/golang/go/issues/23446

**Comment by 1095893390** [comment]
好的

**Comment by iikira** [comment]
实际上错误已经发生了，应该为errno 9, EABDF, 原因可能是系统的内核版本太低了，检查一下的的内核版本

根据 https://github.com/golang/go/wiki/MinimumRequirements ，Linux支持golang的最低内核为2.6.23

**Comment by 1095893390** [comment]
嗯，这个原因是对的，内核版本太低导致的错误，谢谢
