### ISSUE TITLE
按照步骤输入账号显示账号不存在

### ISSUE THREAD

**Issue by huyong007** [iikira/BaiduPCS-Go#31]
错误代码：400010，消息：您输入的账号不存在，请重新输入。反复几次都是如此

**Comment by huyong007** [comment]
我的是windows10系统，64位，正常输入login之后让我填写账户名，之后输入密码回车之后就报错了

**Comment by iikira** [comment]
尝试邮箱或手机号登录，目前程序在windows的中文输入有点问题

**Comment by iikira** [comment]
我测试不出错误……你能提供一下截图吗

**Comment by icepie** [comment]
哦对了，我有两个账号，一个使用手机号登录会提示账号不存在，而使用用户名登录没有什么问题，另外一个账号都正常

**Comment by iikira** [comment]
@icepie 尝试去 https://wappass.baidu.com 用手机号登录一下……

**Comment by icepie** [comment]
@iikira 这个页面登录没问题，但是在项目里面显示账号不存在:pensive:

**Comment by iikira** [comment]
@icepie 噗……我猜，程序没判断出你的手机号，因为这个登录接口需要指明是否手机号登录……
程序要求手机号前三位只能是130~139, 145~147, 150~153, 155~159, 180, 185~189
是不是有点严格了……

**Comment by iikira** [comment]
修复了手机号不能登录的问题, 0f7e913f90f25d5f59654c32d6985c843da408eb
可编译运行程序, 试试用手机号登录, 看看效果怎么样...

**Comment by iikira** [comment]
已修复, 下载新版试试效果

**Comment by huyong007** [comment]
真棒，我之前应该是手机号是182的不支持，现在好了，你们真棒，我也要学着做个东西，对了我现在在写一个博客系统，有没有在github上写博客系统同时不断用新技术进行迭代的大牛啊，有的话推荐给我下呗
