### ISSUE TITLE
这些接口是怎么获取的？

### ISSUE THREAD

**Issue by banjiaojuhao** [iikira/BaiduPCS-Go#310]
是web抓包还是调试PC客户端还是逆向安卓端？

**Comment by iikira** [comment]
大部分是用百度开放的api：https://github.com/iikira/BaiduPCS-Go/tree/master/docs

还有少部分未开放的或失效的api，例如离线下载、分享，只能web抓包了

**Comment by banjiaojuhao** [comment]
这个不是早就封了吗？用这个api加个高并发下载，就没限速了
