### ISSUE TITLE
检测BDUSS有效性json解析出错: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by yfcube** [iikira/BaiduPCS-Go#311]
使用v3.5.3，unbuntu16.04
登录时输入手机验证之后，显示：

$ 检测BDUSS有效性json解析出错: invalid character '<' looking for beginning of value

**Comment by iikira** [comment]
应该是网络问题，更换网络环境试一试

**Comment by wj401625836** [comment]
v3.2.2能够正常登陆v3.5.3不行，你看看原因@iikira

**Comment by iikira** [comment]
测试正常, 建议更换网络环境

**Comment by zhanglianbo35** [comment]
看看这个是否和下面的例子是一个原因？
https://github.com/stripe/stripe-go/issues/642
