### ISSUE TITLE
 BaiduPCS-Go-v3.5.3-windows-x86.zip 被检测为病毒文件

### ISSUE THREAD

**Issue by zhou515271606** [iikira/BaiduPCS-Go#317]
文件名称 :	BaiduPCS-Go.exe 
文件大小 :9429734 byte
文件类型 :application/x-dosexec
MD5:efd7982dcbf6d4ba69dd6c2a6fb0fdf9
SHA1:3aae7b4c08ba1c5dbcf701be4d63f675394ffced

检测结果：http://r.virscan.org/language/zh-cn/report/e76166b18d8f6ad9a4a8fc5a6ec168d2

**Comment by iikira** [comment]
是误报了，本程序所有组件均为开源的，作者可以保证程序无毒，并且不会获取并上报用户的一切信息.

**Comment by zhou515271606** [comment]
我相信开源软件，只是想反馈一下情况。
