### ISSUE TITLE
多文件下载，个别之前下载失败的文件因为文件名存在直接跳过了怎么办

### ISSUE THREAD

**Issue by Brannua** [iikira/BaiduPCS-Go#318]
因为指定文件保存路径里有下载失败的文件，再次下载整个文件夹的文件时，因为那个下载失败的文件是存在的，就提示文件已经存在，跳过下载。。该怎么解决呢？求帮助！谢谢。

**Comment by iikira** [comment]
目前只能手动删除下载失败的文件

**Comment by Brannua** [comment]
嗯嗯好的，谢谢啦

**Comment by iikira** [comment]
已支持下载完成后校验文件, df82928b832bac26321236ebeb4d6db9a918d48f, 对于校验失败的文件默认重试下载3次, 超过重试次数的文件还是得手动删除.
