### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by CyshallChan** [iikira/BaiduPCS-Go#32]
![image](https://user-images.githubusercontent.com/22564041/35604815-40094688-067f-11e8-9787-29b799f5316d.png)

识别不了“资”这个字，手动输入和粘贴都没用。
补充：PowerShell，cmd，cmder都是这样。

**Comment by CyshallChan** [comment]
补充：PowerShell，cmd，cmder都是这样。

**Comment by iikira** [comment]
关闭这条issue了，因为与  [#20](https://github.com/iikira/BaiduPCS-Go/issues/20) 一样，等待修复，目前可以暂时使用通配符代替不能输入的中文。
