### ISSUE TITLE
请问如何打开fpu功能？

### ISSUE THREAD

**Issue by qcnhy** [iikira/BaiduPCS-Go#321]
我在路由器上使用您的软件确实提示非法指令，尝试安装shine无法解决。请问如何能开启fpu功能？

**Comment by qcnhy** [comment]
对于已编译的固件需要重新编译来启用这个功能吗？
现在我使用的是最新原版的lede官方固件

**Comment by qcnhy** [comment]
如果可以通过安装某个lib来启用该功能当然最好了

**Comment by iikira** [comment]
先试一试新版3.5.4能不能运行

**Comment by qcnhy** [comment]
提示非法指令，

**Comment by suikatomoki** [comment]
@iikira @qcnhy 
不建议开启 FPU 
新版我这里可以用 BaiduPCS-Go-v3.5.4-linux-mips.zip

![qq 20180818172248](https://user-images.githubusercontent.com/10336224/44297877-8a983a00-a30b-11e8-80a2-43eb5771c960.png)

**Comment by qcnhy** [comment]
我刚才尝试下载使用新版，已经正常。
给您一个建议，我刚才尝试下载文件的时候出现几个问题
1.下载文件目录不是该程序放置的目录，而是在/root下新建一个download目录，建议修改为程序放置目录下的download目录
2.下载文件速度逐渐趋于0 这点似乎是百度云单文件下载的通病问题。我的解决方法是利用批量下载让百度云将所有文件打包为zip 然后下载到本地后解压，您可以尝试这个方式下载文件，我的测试可以达到2m/s的速度，相对现在有很大的提升。

**Comment by iikira** [comment]
1 下载目录是可以自定义的，另外默认的下载目录设定在家目录, 是出于多用户的考量.
2 建议你参考 [关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E), 有多种下载方式
