### ISSUE TITLE
我想写一个Mac下的安装指南好么

### ISSUE THREAD

**Issue by VDeamoV** [iikira/BaiduPCS-Go#323]
我在下载安装的时候，觉得安装指南不够直接，希望能让我来写一个建议的安装指南。

**Comment by iikira** [comment]
可以的
我准备支持通过homebrew安装，先等一等吧

**Comment by niyoh120** [comment]
可以暂时先用我的brew tap
brew install niyoh120/homebrew-niyoh/baidupcs-go

**Comment by iikira** [comment]
已添加homebrew, https://github.com/iikira/homebrew-baidupcs

另外, https://github.com/iikira/BaiduPCS-Go/invitations, 邀请你为合作者, 可以在Wiki那里添加和修改页面

**Comment by VDeamoV** [comment]
Okay！ 我开始写啦～主要是针对Mac下的安装

**Comment by VDeamoV** [comment]
@iikira 
`brew search baidu`结果中没有baidupcs

 不知名原因不能通过`brew install iikira/homebrew-baidupcs`安装。

 可以使用`brew install niyoh120/homebrew-niyoh/baidupcs-go`安装。

 `brew search baidu`结果中没有baidupcs～

总结：除了homebrew使用的是niyoh120的安装意外，教程已写好

**Comment by iikira** [comment]
```
brew install iikira/homebrew-baidupcs/baidupcs-go
```

**Comment by VDeamoV** [comment]
Okay ！ 已经改好了



开 2018年8月20日 在 13:01:36, iikira (notifications@github.com<mailto:notifications@github.com>) 写到:

brew install iikira/homebrew-baidupcs/baidupcs-go
