### ISSUE TITLE
内存占用530%cpu负载逐渐提升

### ISSUE THREAD

**Issue by qcnhy** [iikira/BaiduPCS-Go#325]
由于这个问题会使设备强制重启，请问如何降低内存和cpu占用？

**Comment by iikira** [comment]
不下载或使用其他功能的时候，占用怎么样

**Comment by qcnhy** [comment]
正常情况下负载在0.5左右不超过1 话说这个内存占用真的假的，600多M 530% 我这机器128的内存+512的虚拟内存，

**Comment by qcnhy** [comment]
10线程以下负载稳定1.5左右，下载速度500k/s左右不论线程多少缓存大小
联系您可以采纳我之前批量下载的建议，可以稳定2M/s

**Comment by qcnhy** [comment]
10线程以下负载稳定1.5左右，下载速度500k/s左右不论线程多少缓存大小
建议您可以采纳我之前批量下载的建议，可以稳定2M/s
