### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by widon1104** [iikira/BaiduPCS-Go#327]
widon@widon-X555YI:~$ baidupcs-go.sh 
提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
BaiduPCS-Go:大数据精英实战... widon1104$ ls
获取目录下的文件列表, 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2F%E5%A4%A7%E6%95%B0%E6%8D%AE%2F%E5%A4%A7%E6%95%B0%E6%8D%AE%E7%B2%BE%E8%8B%B1%E5%AE%9E%E6%88%98%E9%A1%B9%E7%9B%AE%E7%8F%AD: proxyconnect tcp: dial tcp 127.0.0.1:54361: connect: connection refused
BaiduPCS-Go:大数据精英实战... widon1104$ cd /
获取文件/目录的元信息, 网络错误, Post http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=meta: proxyconnect tcp: dial tcp 127.0.0.1:54361: connect: connection refused

项目的git也不能用了。。
widon@widon-X555YI:~/go/src/github.com/iikira/BaiduPCS-Go$ git pull
fatal: unable to access 'https://github.com/iikira/BaiduPCS-Go/': Failed to connect to 127.0.0.1 port 54361: 拒绝连接

网络是好的：
widon@widon-X555YI:~$ ping pan.baidu.com
PING yiyun.n.shifen.com (180.149.145.241) 56(84) bytes of data.
64 bytes from 180.149.145.241 (180.149.145.241): icmp_seq=1 ttl=53 time=53.7 ms
64 bytes from 180.149.145.241 (180.149.145.241): icmp_seq=2 ttl=53 time=54.1 ms
为什么会这样呢？

**Comment by Shadowalker1995** [comment]
+1

**Comment by iikira** [comment]
这是你代理的问题

**Comment by ucker** [comment]
已经取消了代理，但还是会使用代理连接
<img width="949" alt="2018-08-30 2" src="https://user-images.githubusercontent.com/19532347/44857071-95ef4c00-aca1-11e8-9931-708d8701da0a.png">
<img width="948" alt="2018-08-30 3" src="https://user-images.githubusercontent.com/19532347/44857292-07c79580-aca2-11e8-8e1f-5ae980c5cbbb.png">
