### ISSUE TITLE
断点续传连接失败以及可靠性疑问

### ISSUE THREAD

**Issue by yo1995** [iikira/BaiduPCS-Go#33]
下载到最后速度停滞，尝试重启程序提示：
Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=meta&path=%2F: dial tcp 117.185.16.59:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
似乎连不上服务器，不知为何？当然多等一会似乎就好了……不知道是不是百度在限制？

~~另，这个工具会不会导致账号被百度方面恶意限速？看之前有案例用别的工具后账号被限制在10Kb/s……~~
多谢:smile:

**Comment by iikira** [comment]
1. 是网络的问题吧，这条错误是获取文件信息时产生的；
2. 有这个可能，不过我刚测试了下，正常下载的速度有一百多kb每秒呢……最好小心一点吧。

**Comment by yo1995** [comment]
补充一下…前几天下一个文件夹大概14G，下到10G左右的时候开始没有速度，重启无果。
登陆官方客户端后发现被限10K… :cry: 
准备等几天再试试，可能撸的太狠被ban了
FYI

**Comment by iikira** [comment]
没遇过这种情况……建议你更新下程序，优化了下载……
