### ISSUE TITLE
上传一直出错，且上传速度很慢 可否支持多线程上传

### ISSUE THREAD

**Issue by zby1234** [iikira/BaiduPCS-Go#336]
V3.5.4(旧版也出错)，错误如下：

[1] 秒传失败, 开始上传文件...

[1] ↑ 1.20GB/17.76GB 5.61MB/s in 3m29.039s ............panic: runtime error: invalid memory address or nilpointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82fa25]

goroutine 55 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1.1(0xc4203a85a0, 0xc4203e8550, 0x4f, 0xc4200f9cc0, 0xc42000c388, 0xc420373290, 0xc42002af00, 0xc42000c380)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:57 +0xe5
created by github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:52 +0x1db

**Comment by zby1234** [comment]
因为经常用到上传的功能，恳请解决一下

**Comment by effzmt** [comment]
上传还是在网页里面最快，几M每秒，这个倒不是痛点需求，百度自己做的上传就是最快速度了

**Comment by zby1234** [comment]
@effzmt 但是上传一直出错没办法用，baidupcs分片多线程上传开多线程可以到100MB/s，但是作者不维护了
需求可能不太一样 因为我只用上传功能

**Comment by effzmt** [comment]
额。。只用上传的话，倒不如用百度自己的客户端了，基本没限速的
