### ISSUE TITLE
关掉终端下载也中断

### ISSUE THREAD

**Issue by shimmer520** [iikira/BaiduPCS-Go#338]
你好，非常感谢此工具！本人linux小白，有2个问题：
1、因为用的VPS装的baidupcs，在我关掉Xshell会话窗口后，发现后台下载也中断了，有什么方法可以解决吗？不然就只能保持一直开着电脑？
2、问题列表里有一个人问在下载中能不能新建另外一个下载，我也在好奇下载中如果要执行其他vps命令需如何处理，必须新建一个ssh会话窗口嘛

**Comment by iikira** [comment]
使用nohup或screem等工具可以解决你的问题
