### ISSUE TITLE
下载的文件当中有几段错误

### ISSUE THREAD

**Issue by lte2000** [iikira/BaiduPCS-Go#34]
今天下载的APE里有几段是这样的：
{"error_code":31245, "error_msg":"query exceed cloudui circuit breaker mechanism threshold, maybe hot file"}{"error_code":31245, "error_msg":"query exceed cloudui circuit breaker mechanism threshold, maybe hot file"}{"error_code":31245, "error_msg":"query exceed cloudui circuit breaker mechanism threshold, maybe hot file"}
下载的时候没有报错，手工检查MD5发现的。

**Comment by iikira** [comment]
尝试调低下载线程……

**Comment by iikira** [comment]
增加了下载出错处理: [#4e1e920](https://github.com/iikira/BaiduPCS-Go/commit/4e1e920ba6da94981f16ae3c97c7031abdbc0f8a)
你可以尝试编译安装程序, 看看效果怎么样.

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
