### ISSUE TITLE
BaiduPCS-Go能否做一个小米路由器插件

### ISSUE THREAD

**Issue by Hylocereus0011** [iikira/BaiduPCS-Go#342]
经本人测试BaiduPCS-Go的mipsle版本在小米路由器3开启ssh以后可以使用，但是有一个弊端就是退出ssh界面后会停止下载，所以请问作者能否做一个BaiduPCS-Go的小米路由器插件？

**Comment by Hylocereus0011** [comment]
如果挂载在路由器上下载大文件也是挺不错的

**Comment by database64128** [comment]
没人写 2333

**Comment by Hylocereus0011** [comment]
emmmm



发自我的小米手机
在 database64128 <notifications@github.com>，2018年8月25日 下午12:04写道：

没人写 2333

**Comment by iikira** [comment]
使用nohup或screem等工具可以解决你的问题
