### ISSUE TITLE
 添加离线下载任务遇到错误

### ISSUE THREAD

**Issue by 674273563** [iikira/BaiduPCS-Go#343]
[21] 添加离线下载任务遇到错误, 远端服务器返回错误, 代码: 36022, 消息: user is vi
p and exceed concurrency, 
批量添加时出现
输入码为
offlinedl add -path=2 ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S01E12.CN.HR-HDTV.AC3.1024x576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mkv|597789584|DE65B56D131154BDF39A2D2ABCC073EC|h=EDN4XCWGGMTFDENH7AH5UIBWFTTPFVI3|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S01E13.CN.HR-HDTV.AC3.1024x576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mkv|587715842|52E8FAFA2E7C8C99ACB2D2DFA84FDB26|h=N76JHJO4Y5HHYW7R4ZTULGFOAQMERS27|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E01.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|445933568|58EEA9BCE2A35779A66B7AA568571EA5|h=QZVGJFTVM6CMBPXKEM42LXGRGUGE3BMA|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E02.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|445872128|429DA2FEFEE2C8DA91944755304F6C6F|h=R2S2K5SP4KBRODUCQOHPQ2JWGU7AEEGC|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E03.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|442181632|BC0F347DA84AA48CA85152F68FEB15A7|h=HWWWAAEGAX3DPNFAQJGYEDPV62VTHBKJ|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E04.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|471142400|3E9B67ABB759E1F6A47154122C27B19D|h=UZVZUX4FCFCC4ZLJBEWWIOJOWAM7SAK7|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E05.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|474492928|B717DADA5F79B0F454E658588FDE3257|h=T7BAETKEHA4QF7GZD3TJSVKATZ7RNGFX|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E06.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|476043264|2A72D25FE77F664D7F1A7655B9AC66F9|h=7AUH6ABFAY4TBRT2643PFKIXPLB7FTDL|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E07.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|463343616|78C4C18326B7712CE6B9BDDD54853393|h=UBCIZSO3ZAQPQ3OO4VZ225LRK6YIENIF|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E08.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|472686592|E51BBC28FACC313E3D20AF1C360CB20D|h=ESA3EGTH6Q6BHHRSAUJPDEAD5JMBYZH2|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E09.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|470525952|E8C3CB507B65E04E902BBF1FEB489641|h=HFDEK2BTN5GXLFGBQFQFI44O4RHEPKY3|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E10.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|476264448|2729922A811E1421F5D9DAA9390DAF6A|h=AL2WF6F5IJC6TRKJHCOGYNI3RF4FC7NY|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E11.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|473227264|0A4683B589A7FC025D0B098DF024D669|h=AJGU33CUUIB2WLLKFGZ7V7D7BPKAI3QK|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E12.Chi_Eng.BD-HR.AAC.1024X576.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.mkv|459363541|8367F2DA89525FB5F591A100044397EC|h=AALIKKXBD4ZVFL3WPCKLVQIV6MFWMYZG|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E13.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|470480896|8F8D269DB96C985BECD6D04F52B50AB0|h=R4PC7AW6FBIENNNGCGELH67UUH65KASS|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E14.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|473026560|2617225D781B9EAA5C39AEB720DC2DC8|h=JS7NGH4Z2L6JVOGFN5A4DCTE5PP6ETUV|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E15.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|470315008|26DC1EF71AE5416D0BAC942524F0CC1D|h=SQEKHVUYIYRPUVIVSTQHBG6LMFLEZUWM|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E16.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|471097344|5619D95295D60E601105F0B09F0F04D7|h=N6JRDYUMPM4HQMS6UOHXXK6P2M4BTWW2|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E17.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|474386432|1CEC4E103E7B03AF6CB001B20B8506B8|h=K64ZCSJZX6NPUPMOLJ6U7QQMVP63IKY2|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E18.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|473714688|1164A6100984D7DDB5E5267B14E8C5C1|h=ZNOKI3ZDIXKNRQHQSPRNW5VCUKZMN4YO|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E19.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|470607872|12B8950BFB33C0ED72DAB6B896A38168|h=5OGZ66TN4B3JA5KICFFQQWOQTW3MCKQY|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E20.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|471175168|F04D28484FC9193A81DB61561D409A58|h=YEYSYMKENF2PLVJ2FLLVBPXWFMOHVO7W|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E21.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|471406592|24D100376C20FDA39B1F6C28934D9360|h=7AQAL5YQRJRYHU6Z4C6QDEPJJPJY2FSS|/ ed2k://|file|%E8%B6%85%E5%B8%82%E7%89%B9%E5%B7%A5.Chuck.S02E22end.Chi_Eng.HR-HDTV.AC3.960X528.x264-YYeTs%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.avi|471545856|26E854703592D3ACD50F08E51BB02ABB|h=GLLCCPR

**Comment by iikira** [comment]
离线下载同时进行的任务数量有限, 超出限制的部分将无法添加. 已添加说明, 8340bb7
