### ISSUE TITLE
上传错误：panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by jiangjiangflies** [iikira/BaiduPCS-Go#346]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).deleteIndex(...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:111
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).clearModTimeChange(0xc420319d40)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:173 +0x5d5
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadingDatabase).Search(0xc420319d40, 0xc4200ddd80, 0xc420064230)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_database.go:140 +0x49
github.com/iikira/BaiduPCS-Go/internal/pcscommand.RunUpload.func2(0xc4202eee80, 0xc420319d40, 0xc42000ca60, 0xc420316740, 0xc420396368, 0xc420319380, 0xc420394a30)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcscommand/upload.go:246 +0x1b6
github.com/iikira/BaiduPCS-Go/internal/pcscommand.RunUpload(0xc42001c0a0, 0x1, 0x2, 0x7ffeb3bc1e14, 0x40, 0xc4200214f8)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcscommand/upload.go:401 +0x912
main.main.func24(0xc42010cc60, 0x0, 0xc42010cc60)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:1133 +0x15a
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x8ef600, 0x9dcce0, 0xc42010cc60, 0xc420066e00, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x9b5137, 0x6, 0x0, 0x0, 0xc4202e9960, 0x1, 0x1, 0x9bec42, 0x13, 0xc4200640e0, ...)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc420093a00, 0xc42001c080, 0x4, 0x4, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:1776 +0x5186

**Comment by iikira** [comment]
应该修复了, 8340bb7

**Comment by fz19870823** [comment]
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/iikira/BaiduPCS-Go/requester/uploader.(*fileBlock).Read(0x19088240, 0x19094000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/requester/uploader/block.go:109 +0x1b4
bufio.(*Reader).Read(0x19088270, 0x190a727e, 0xd82, 0xd82, 0x18ff2120, 0x84, 0x84)
        /usr/local/go1.10.8/src/bufio/bufio.go:216 +0x22b
github.com/iikira/BaiduPCS-Go/requester/uploader.(*bufioFileBlock).Read(0x1907f500, 0x190a727e, 0xd82, 0xd82, 0x0, 0x8537590, 0x18e0c038)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/requester/uploader/block.go:96 +0x3c
io.(*multiReader).Read(0x1908e4c0, 0x190a727e, 0xd82, 0xd82, 0x84, 0x0, 0x0)
        /usr/local/go1.10.8/src/io/multi.go:26 +0x9d
github.com/iikira/BaiduPCS-Go/requester/multipartreader.(*MultipartReader).Read(0x18e7b980, 0x190a727e, 0xd82, 0xd82, 0x84, 0x0, 0x0)
        /Users/syy/go/src/github.com/iikira/BaiduPCS-Go/requester/multipartreader/multipartreader.go:122 +0xac
net/http.transferBodyReader.Read(0x18e60d20, 0x190a727e, 0xd82, 0xd82, 0x84, 0x0, 0x0)
        /usr/local/go1.10.8/src/net/http/transfer.go:60 +0x43
io.(*LimitedReader).Read(0x1908e510, 0x190a727e, 0xd82, 0xd82, 0x84, 0x0, 0x0)
        /usr/local/go1.10.8/src/io/io.go:446 +0x9d
bufio.(*Writer).ReadFrom(0x190a41c0, 0x8537dd0, 0x1908e510, 0xb7687468, 0x190a41c0, 0x1, 0x4ca)
        /usr/local/go1.10.8/src/bufio/bufio.go:703 +0x9c
io.copyBuffer(0x8537190, 0x190a41c0, 0x8537dd0, 0x1908e510, 0x0, 0x0, 0x0, 0x10, 0x8474400, 0x1, ...)
        /usr/local/go1.10.8/src/io/io.go:386 +0x2be
io.Copy(0x8537190, 0x190a41c0, 0x8537dd0, 0x1908e510, 0xf, 0x1907f628, 0x1, 0x1)
        /usr/local/go1.10.8/src/io/io.go:362 +0x51
net/http.(*transferWriter).WriteBody(0x18e60d20, 0x8537190, 0x190a41c0, 0x2, 0x2)
        /usr/local/go1.10.8/src/net/http/transfer.go:337 +0x538
net/http.(*Request).write(0x18e88800, 0x8537190, 0x190a41c0, 0x0, 0x190a41e0, 0x0, 0x0, 0x0)
        /usr/local/go1.10.8/src/net/http/request.go:622 +0x5b4
net/http.(*persistConn).writeLoop(0x18e14b40)
        /usr/local/go1.10.8/src/net/http/transport.go:1825 +0x17c
created by net/http.(*Transport).dialConn
        /usr/local/go1.10.8/src/net/http/transport.go:1238 +0x815
