### ISSUE TITLE
下载文件名如果包含空格会提示:获取单个文件/目录的元信息遇到错误

### ISSUE THREAD

**Issue by JustYummy** [iikira/BaiduPCS-Go#35]
例如：
BaiduPCS-Go > d /down load.dmg
获取单个文件/目录的元信息遇到错误, 路径: /down, 错误代码: 31066, 消息: file does not exist

应该是把下载的文件当作目录下载了。
系统：macOS

**Comment by iikira** [comment]
使用通配符，或者双引号包含起来文件……或者空格前加一个反斜杠 \
