### ISSUE TITLE
可以增加“打开当前所在文件夹路径”功能吗？

### ISSUE THREAD

**Issue by willxiang** [iikira/BaiduPCS-Go#351]
个人觉得这个功能还挺实用的。
查看了一下帮助说明，好像没有这个功能。
有时候东西下载完毕后，由于下载目录是按照网盘内的路径生成的，目录稍微深一点可能要打开好多层文件夹，
如果有一个打开当前文件夹的命令就更方便了。

**Comment by iikira** [comment]
已记录, #296
