### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by EricDuy** [iikira/BaiduPCS-Go#354]
下载大文件时，刚开始能达到8，9兆。一段时间后就维持在1~2兆之间，有时还不到1兆。
请问正常下载速度大约是多少？(100兆带宽，只有一台电脑使用）
有什么提升速度的办法吗？
谢谢！

**Comment by gyz147** [comment]
好像我也有这个问题，一开始很快，很快速度就降下来了

**Comment by huguoliang** [comment]
都一样，忽快忽慢的，落差很大，显示的下载速度不稳定。

**Comment by zlq4863947** [comment]
建议显示速度以短时间内的平均值为准

**Comment by DTSSR** [comment]
+1 百兆网，开始满速，过一段时间就慢下来，稳定在一半的网速

**Comment by GitHubyoyo** [comment]
Project作者有說過，這個不是"暴力下載"，只是讓你"穩定下載"，至少不是擺渡原本的龜速

**Comment by mengyyy** [comment]
下载速度只要超过56K /S 我就能接受了

**Comment by gyz147** [comment]
不不不，我记得早几个版本还能达到最高速度，我记得我当时50M宽带，下载速度都是稳定在50/8=6M/S这样子，但现在用不行了，用最新版本也不行，估计是百度云官方做了什么动作或者限制

**Comment by GitHubyoyo** [comment]
@gyz147 現在也很快阿，估計你是被拉黑的帳號吧.....也許換一個就有解

**Comment by CRO2017** [comment]
@GitHubyoyo 同意这位朋友的说法ing

**Comment by terrantsh** [comment]
这么说网络上的百度网盘破解版的速度是如何达到的呢

**Comment by iikira** [comment]
并不保证速度的!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)
