### ISSUE TITLE
希望增加下载后校验 MD5 的功能

### ISSUE THREAD

**Issue by iChenyao** [iikira/BaiduPCS-Go#36]
下载的文件，常有损坏的现象，检查后发现是 MD5 变动了，手动逐一检查过于费时，可能的话，下载完成后自动检查 MD5，并且，报告下载后的 MD5 与网盘上不一致的文件，让用户决定是要重新下载或者忽略。

**Comment by iikira** [comment]
好的

**Comment by iChenyao** [comment]
好的，谢谢！
