### ISSUE TITLE
取消分享文档失效

### ISSUE THREAD

**Issue by liuzhuoling2011** [iikira/BaiduPCS-Go#360]
![image](https://user-images.githubusercontent.com/8407297/44986082-1f11c600-afb5-11e8-83f9-e996a010651f.png)
显示取消分享成功, 实际没有成功

**Comment by iikira** [comment]
取消分享的接口没办法得知操作是否成功的，如果取消失败，建议再试一次或到官方的网页端取消分享

**Comment by iikira** [comment]
已修复, 7fc9912281cead2d0fd73ac8f1b657d5228f25d0
