### ISSUE TITLE
分享的时候不是创建私有链接, 并且正常的分享也很容易被官方删掉

### ISSUE THREAD

**Issue by liuzhuoling2011** [iikira/BaiduPCS-Go#361]
![image](https://user-images.githubusercontent.com/8407297/44988302-c9411c00-afbc-11e8-86b6-96447d343b2c.png)

**Comment by liuzhuoling2011** [comment]
![image](https://user-images.githubusercontent.com/8407297/44988525-8a5f9600-afbd-11e8-86d7-7537377b1aff.png)
分享的时候先是成功的, 不过有些奇怪, 如图所示, 之后就被百度删了

**Comment by iikira** [comment]
是私有链接的，虽然没有密码，但外人是搜索不到的，并且不会出现在分享人的主页
至于分享被删，试试先创建一个空文件夹的分享，再将文件移动进去
