### ISSUE TITLE
下载的文件名如果有空格，会识别为两个文件导致下载失败

### ISSUE THREAD

**Issue by luojianxhlxt** [iikira/BaiduPCS-Go#362]
当前目录: /软件/装机
----
  #    文件大小         修改日期                     文件(目录)
  0       46.79MB  2018-09-03 22:09:15  aida64business LCG.zip
  1       23.00MB  2017-11-27 10:04:38  Dism++10.1.4.5 Release2.zip
  2        2.73MB  2016-11-01 09:45:30  npp.7.1.Installer.x64.exe
  3        1.56MB  2016-10-21 14:06:37  UltraISO v9.6.5.3237.exe
  4       14.11MB  2018-08-30 23:45:36  V2Ray.zip
  5      197.64MB  2018-08-30 21:14:26  WePE_64_V1.2.exe
  6      207.39MB  2017-12-26 10:49:43  WePE_64_V2.0.exe
  7       46.02MB  2016-09-28 23:50:09  WPS Office Personal（5745）（V3）.7z
  8       28.69MB  2017-04-24 14:40:12  软件解包.zip
  9       24.02MB  2016-09-28 23:50:09  搜狗拼音传统版8.0H(8083)去广告版.exe
     总: 591.95MB                       文件总数: 10, 目录总数: 0
----
BaiduPCS-Go:装机 XXXXXXX$ d /软件/装机/aida64business LCG.zip

[0] 提示: 当前下载最大并发量为: 100, 下载缓存为: 30000
[1] 加入下载队列: /软件/装机/aida64business
[2] 加入下载队列: /软件/装机/LCG.zip
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在
[2] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

**Comment by Zxilly** [comment]
标准的命名方式应该是用.而不是空格。。。

**Comment by iikira** [comment]
[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
