### ISSUE TITLE
通配符操作文件好像有bug

### ISSUE THREAD

**Issue by xtay573269555** [iikira/BaiduPCS-Go#364]
BaiduPCS-Go:/ myname$ mkdir 茶马古道
创建目录成功: 茶马古道
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.*.mkv 茶马古道/
解析路径出错, 文件路径匹配失败, 请检查通配符
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse*.mkv /茶马古道
解析路径出错, 文件路径匹配失败, 请检查通配符
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E0*.720p.HDTV.x264-NGB.mkv  /茶马古道
解析路径出错, 文件路径匹配失败, 请检查通配符
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E0?.720p.HDTV.x264-NGB.mkv  /茶马古道
解析路径出错, 文件路径匹配失败, 请检查通配符
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E01.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E01.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E01.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E02.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E02.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E02.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E0*.720p.HDTV.x264-NGB.mkv 茶马古道/
解析路径出错, 文件路径匹配失败, 请检查通配符
BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E03.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E03.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E03.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E04.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E04.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E04.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E05.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E05.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E05.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$ mv \[茶马古道\].Ancient.Road.for.Tea.and.Horse.E06.720p.HDTV.x264-NGB.mkv 茶马古道/
操作成功, 以下文件/目录移动成功:
  \#                                 原路径                                                                     目标路径

  0  /[茶马古道].Ancient.Road.for.Tea.and.Horse.E06.720p.HDTV.x264-NGB.mkv  /茶马古道/[茶马古道].Ancient.Road.for.Tea.and.Horse.E06.720p.HDTV.x264-NGB.mkv

BaiduPCS-Go:/ myname$
BaiduPCS-Go:/ myname$ --version
BaiduPCS-Go version v3.5.4
BaiduPCS-Go:/ myname$

**Comment by iikira** [comment]
文件名含义中括号, 需要转义或加上双引号

**Comment by xtay573269555** [comment]
[mv_log.txt](https://github.com/iikira/BaiduPCS-Go/files/2358350/mv_log.txt)

直接贴文字，markdown会自动转义。其实真实的操作记录是我是加了转义符在中括号之前的，而且这个问题是可以重现的。刚才我又试了下，操作记录保存到 mv_log.txt 中了，请参考附件。

我操作的文件分享：链接: https://pan.baidu.com/s/1EU5YmIZbqErts09c-dfkRA 密码: 7r67
