### ISSUE TITLE
非中文语言Windows CMD乱码，建议和暂时解决方法

### ISSUE THREAD

**Issue by jackhuny** [iikira/BaiduPCS-Go#367]
这不是程序本身的问题， 非中文系统的Windows CMD运行程序时会现实乱码， 我暂时的解决方法是写一个bat先转码再运行

```
@ECHO OFF
CHCP 936
CLS
.\BaiduPCS-Go.exe
```

建议作者能把这个加入到程序里吧

**Comment by iikira** [comment]
可自行设置cmd的编码方式为utf8，这个就不加上去了
