### ISSUE TITLE
2018/2/3 测试无法下载

### ISSUE THREAD

**Issue by TooFlow** [iikira/BaiduPCS-Go#37]
2018/2/3 测试无法下载。

- 通道被封了，还是本人网络有问题？

**Comment by iikira** [comment]
麻烦你提供更多信息，例如截图...

**Comment by Aurami** [comment]
Login 时显示：Get https://wappass.baidu.com/: dial tcp: lookup wappass.baidu.com on [::1]:53: read udp [::1]:50592->[::1]:53: read: connection refused，这是网络问题么

**Comment by iikira** [comment]
dns问题，更换dns地址试试……

**Comment by TooFlow** [comment]
@iikira  
![snipaste_2018-02-03_13-54-22](https://user-images.githubusercontent.com/30330442/35765434-7f3584e4-08fe-11e8-86b6-484bf230d8df.jpg)

**Comment by iikira** [comment]
不清楚，没遇过这样的问题……下载其他的文件也是这样吗?

**Comment by TooFlow** [comment]
@iikira 
谢谢解答。
应该是网络原因，重新用BDUSS登陆帐号，更换网络测试可以正常使用！
