### ISSUE TITLE
上传上万个文件途中报错 v3.5.4

### ISSUE THREAD

**Issue by imadeit** [iikira/BaiduPCS-Go#373]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14380e5]

goroutine 2625 [running]:
github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1.1(0xc42038a550, 0xc420b5bf90, 0x4f, 0xc420709540, 0xc420568648, 0xc42070b2b0, 0xc4205c5140, 0xc420568640)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:57 +0xe5
created by github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*PCSUpload).TmpFile.func1
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload.go:52 +0x1db

**Comment by iikira** [comment]
已经修复, ba09943cb6b24dac3e6fd93ce3707da26b7db02e
