### ISSUE TITLE
offlinedl list 有bug。

### ISSUE THREAD

**Issue by dupeliuhao** [iikira/BaiduPCS-Go#374]
我现在无法用offlinedl list来查看信息。。。然后也无法添加新的task。错误：
[1] 添加离线下载任务: 遇到错误, 远端服务器返回错误, 代码: 36022, 消息: user is vip and exceed concurrency,

我怀疑是因为我有很多在下载。。。但是我无法查到task ID。。从而删除它们。。。所以我现在卡在这里了。。。

有没有比如offlinedl del 0 或者offlinedl cancel 0。。。类似于shell里面kill 0 这种可以一次性删除取消所有tasks的

**Comment by iikira** [comment]
已修复此问题, 8340bb779ccb7c8723959f290b011fee18d351a2
已增加清空离线下载任务记录, 12628f1f2668971e36335ce329978074a52191c5

**Comment by dupeliuhao** [comment]
非常感谢！
