### ISSUE TITLE
上传时无法正常显示上传了多少

### ISSUE THREAD

**Issue by wiznan** [iikira/BaiduPCS-Go#376]
如题，校园网上传时上传量忽高忽低，似乎是下载速度。而下载速度非常低，希望大佬解决，谢谢

**Comment by iikira** [comment]
提供一下版本号

**Comment by DiegoSan1895** [comment]
BaiduPCS-Go version v3.5.5-devel   我用的这个版本 centos 7.4 的系统，上传的时候无法正常显示上传了多少，而且上传不成功 @iikira

**Comment by iikira** [comment]
新增设置上传最大并发量, 0007020252c3d84f2227cad0f65a88e98c4b7e3a
出现这个问题，可能是因为以前的上传最大并发量，使用了下载最大并发量的配置，并发量太高就导致上传异常。先关闭了，如果有问题再打开
