### ISSUE TITLE
Win7 64位 SP1 登录问题

### ISSUE THREAD

**Issue by gitLinan** [iikira/BaiduPCS-Go#378]
我的系统是win7 64位的Sp1  下载使用的BaiduPCS-go的版本是v3.5.5，在登录的时候报“invalid character '<' looking for beginning of value”的错误，我尝试过Cookie登录和账号密码登录，报错信息是一致的。

**Comment by iikira** [comment]
应该是网络问题，更换网络环境试一试。另外 v3.5.5登录功能失效，请更新
