### ISSUE TITLE
linux下默认下载目录可以修改吗？

### ISSUE THREAD

**Issue by widon1104** [iikira/BaiduPCS-Go#379]
默认下载目录是/home/widon/Downloads，我想把下载目录设置成其他目录，可以吗？

**Comment by gitLinan** [comment]
可以，这是Windows下的命令 “BaiduPCS-Go config set -savedir D:/Downloads”     我认为命令是一致的而且沿用Linux的“/”

**Comment by iikira** [comment]
可以修改的
