### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by ygowill** [iikira/BaiduPCS-Go#38]
<img width="697" alt="2018-02-05 11 07 50" src="https://user-images.githubusercontent.com/29591009/35786834-f86a2dc6-0a64-11e8-9738-5aa85f0d8380.png">

**Comment by iikira** [comment]
网络问题，重试或重启网络服务即可……

**Comment by fvstar** [comment]
![_2018-02-05_12-35-59](https://user-images.githubusercontent.com/22077176/35788639-7b38e2b8-0a71-11e8-85fc-b205ecc5978f.png)
还是不知道怎么进去。怎么把前缀调出来。   ：==

**Comment by iikira** [comment]
@fvstar 这么执行: ./BaiduPCS-Go 
或者将该目录加入 PATH

**Comment by ygowill** [comment]
尝试了重启网络服务以及重试，得到了完全一样的结果

**Comment by iikira** [comment]
看你报错的关键字"proxyconnect"……是不是挂什么代理了……
如果不是，尝试浏览器能不能打开报错的那个网址

**Comment by iikira** [comment]
好吧, 你是挂了代理的, 不然不会出现关键字"proxyconnect", 尝试更换或者取消代理.
设置代理示例: 
```
export HTTP_PROXY=socks5://localhost:1086
```
