### ISSUE TITLE
OpenWrt X86_64 下载出错

### ISSUE THREAD

**Issue by cxyzzz** [iikira/BaiduPCS-Go#381]
OpenWrt X86_64，软路由上运行。下载的是 linux amd64 版的，使用 d xx 下载时报错，错误提示：x509: failed to load system roots and no roots provided, 重试 3/3 下载目录为usb挂载的U盘（ext4格式）/mnt/sdb1

**Comment by cxyzzz** [comment]
关闭https后无问题

**Comment by iikira** [comment]
原因可能是交叉编译造成的，修复这个问题要用到目标平台的交叉编译工具链，并启用cgo重新编译
```
CC=/path/to/gcc CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build
```
