### ISSUE TITLE
上传大于4G的文件报错

### ISSUE THREAD

**Issue by LondyGhost** [iikira/BaiduPCS-Go#385]
版本3.5.4~3.5.5

比如说某个文件，上传到3.28G的时候，已上传大小会卡住3.28G/10G。但是上传速度确实有的。过了5分钟，已上传大小会变成2.89G/10。取消传输从头开始，也是会出现这种情况。但是已上传大小卡住是随机大小，并不是固定值。有时候会4G多卡住，有时候会3G多卡住。今天出现了两个报错，不知道有没有关系。大家帮忙看下。

**Comment by LondyGhost** [comment]
[https://s1.ax1x.com/2018/09/17/iZMii6.png](url)

**Comment by iikira** [comment]
具体的版本号是多少呢

**Comment by LondyGhost** [comment]
版本号是3.5.4和3.5.5都会

**Comment by LondyGhost** [comment]
@iikira 这位的情况也是一样[https://github.com/iikira/BaiduPCS-Go/issues/369](url)

**Comment by iikira** [comment]
新增设置上传最大并发量, 0007020252c3d84f2227cad0f65a88e98c4b7e3a
出现这个问题，可能是因为以前的上传最大并发量，使用了下载最大并发量的配置，并发量太高就导致上传异常。先关闭了，如果有问题再打开
