### ISSUE TITLE
windows64位系统，无法用d /xxx 命令下载文件夹内的文件

### ISSUE THREAD

**Issue by bombeater** [iikira/BaiduPCS-Go#386]
windows 64 系统

获取路径信息错误，获取文件/目录的元信息：遇到错误远程服务器返回错误，代码：4，消息：No permission to do this operation

今天突然这样了，不能下载文件夹内的文件。好像被度盘那边夺了权限？希望大大尽快看看，谢谢！

**Comment by woodongwong** [comment]
Duplicate of #387

**Comment by iikira** [comment]
与#387 一样, 关闭了
