### ISSUE TITLE
路径太深不行？

### ISSUE THREAD

**Issue by lonee8** [iikira/BaiduPCS-Go#39]
开始还以为是有.的不行，后来测试了一下，不是.的问题。
![qq 20180205215604](https://user-images.githubusercontent.com/19191933/35808097-baef2d56-0abf-11e8-9dc6-bf8e04869b55.jpg)

**Comment by iikira** [comment]
啥意思……

**Comment by iikira** [comment]
好吧，我试一试……

**Comment by iikira** [comment]
是中括号的问题......等修复..........

**Comment by iikira** [comment]
已修复, [#d868756](https://github.com/iikira/BaiduPCS-Go/commit/d8687562b76bbf1e801e159c212d252d0c47a627)

你可以试着编译安装程序，看一下效果怎么样吧......

**Comment by lonee8** [comment]
可以了。
![0](https://user-images.githubusercontent.com/19191933/35860824-6d8ab0c8-0b80-11e8-959f-2a9bef082a3c.jpg)
