### ISSUE TITLE
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

### ISSUE THREAD

**Issue by zisee** [iikira/BaiduPCS-Go#391]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by woodongwong** [comment]
Duplicate of #387

**Comment by CoolLby** [comment]
别人都提过问题...就没必要重复添加了吧，很显然是大面积出现的问题，等作者修复就好了。。

**Comment by iikira** [comment]
与#387 一样, 关闭了
