### ISSUE TITLE
ubuntu为什么没法运行软件

### ISSUE THREAD

**Issue by zeal-github** [iikira/BaiduPCS-Go#392]
系统：ubuntu 16
cpu：intel i7
按照发布页下载了压缩包然后解压之后有一个可运行程序，但是双击之后没有反应，在终端里直接输入【BaiduPCS-Go】也无法找到命令？是那里出错了吗？翻了半天README没有找到linux下的特殊操作。
试过发布页的几个版本：arm64，amd64, 386都不行

**Comment by Lurito** [comment]
终端里应该输入 ./BaiduPCS-Go ，只有放在bin里的程序才能不加路径直接运行。

如果还是不行的话，ls -l 看看有没有给 x 权限。

**Comment by yzddahaoren** [comment]
mv BaiduPCS-Go /usr/local/bin

**Comment by yxmline** [comment]
chmod +x BaiduPCS-Go
sudo mkdir -p /opt/BaiduPCS-Go/bin
sudo cp BaiduPCS-Go /opt/BaiduPCS-Go/bin
sudo update-alternatives --install /usr/bin/baidupcs-go baidupcs-go /opt/BaiduPCS-Go/bin/BaiduPCS-Go 100
这样就可以用了

**Comment by iikira** [comment]
非程序的问题

**Comment by callmexss** [comment]
我也是这个问题，按照上面的方法试了不行啊

**Comment by Lurito** [comment]
> 我也是这个问题，按照上面的方法试了不行啊

报错信息是什么

**Comment by callmexss** [comment]
> > 我也是这个问题，按照上面的方法试了不行啊
> 
> 报错信息是什么

no such file or directory: ./BaiduPCS-Go

我在同级目录下试过，添加PATH后试过都是这个错。最后用go语言编译了一下可以用了，我也不知道是为什么，release版那个压缩包解压下来就是提示文件或路径不存在

**Comment by yxmline** [comment]
release版那个压缩包解压下来就是提示文件或路径不存在
需要先用chmod+x给执行权限，必要时需要chown设置用户
