### ISSUE TITLE
已经无法使用了，是否是百度封号了？

### ISSUE THREAD

**Issue by houalibaba** [iikira/BaiduPCS-Go#393]
版本3.5.3/5正确登陆，但提示以下信息：
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by ColeHou** [comment]
config set -appid= 266719

**Comment by iikira** [comment]
与#387 一样, 关闭了

**Comment by zinwalin** [comment]
@ColeHou thanks heaps.
