### ISSUE TITLE
homebrew版本没有跟随更新进行更新

### ISSUE THREAD

**Issue by VDeamoV** [iikira/BaiduPCS-Go#395]
之前出现了apple-id的问题，问题修复后没有homebrew的版本还是没有更新

OS：MacOS 10.14

**Comment by iikira** [comment]
未发布

**Comment by VDeamoV** [comment]
好


开 2018年9月20日 在 15:54:09, iikira (notifications@github.com) 写到:

未发布

**Comment by iikira** [comment]
已更新
