### ISSUE TITLE
获取目录是报错！！！error  code 4 

### ISSUE THREAD

**Issue by 1104049235** [iikira/BaiduPCS-Go#396]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by gyz147** [comment]
我也是这种情况

**Comment by 1104049235** [comment]
不好意思没看见有人提问过了，等待作者解决吧

**Comment by smarterning** [comment]
这个问题已经有人解决了，请看前面 #387 最下面的解决方案

**Comment by 1104049235** [comment]
谢谢！387 已经给我解决方式了  谢谢了· appid 被封了！！ 改下appid就好了

**Comment by 1104049235** [comment]
> 我也是这种情况
#387 里边 执行 config set -appid id号
