### ISSUE TITLE
31045

### ISSUE THREAD

**Issue by stre1654** [iikira/BaiduPCS-Go#399]
早上下的時候都好好的

結果剛剛無論是調取目錄，或是下載，都會出現
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

已經試過bduss更換，甚至土法煉鋼打帳號密碼驗證碼都是如此。

一直顯示已經登入成功，無論要獲取全部目錄或是切換，都會遇到上面這則訊息

**Comment by stre1654** [comment]
這是目前的設置
![default](https://user-images.githubusercontent.com/43469974/45880059-4ea83700-bdd9-11e8-9690-a9eb6a8b5e94.png)


這是錯誤訊息
![31045](https://user-images.githubusercontent.com/43469974/45880083-5c5dbc80-bdd9-11e8-88b5-9709cdfb546d.png)

**Comment by zkkandrew** [comment]
我也是同样的问题。

**Comment by stre1654** [comment]
我也嘗試清空設置在c碟的數據，重新安裝下載、重開機、換appId、換user_agent後，都沒有用，還是一樣的狀況

**Comment by derekhe** [comment]
看来是已经凉了……
洗洗睡吧

**Comment by greymanking** [comment]
我也是一样的问题。就是这两天出现的。不是被百度封了吧？

**Comment by iikira** [comment]
在发生错误之前，是否有登录帐号的行为？各位

**Comment by harekazewin** [comment]
> 在发生错误之前，是否有登录帐号的行为？各位

没有。突然今天不能用的

**Comment by hhuysqt** [comment]
的确今天突然不能用了

**Comment by wi24rd** [comment]
按照(7c1ca7802fca1945ccf4ca8224251e158875fc85)更改了设置

```
config set -appid=266719
config set -user_agent="netdisk;8.3.1;android-android"
```

还是出现

```
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期,
请尝试重新登录, 消息: user not exists
```


On Fri, Sep 21, 2018 at 11:50 PM hhuysqt <notifications@github.com> wrote:
>
> 的确今天突然不能用了
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
GNU powered it...
GPL protect it...
God blessing it...

Regards,
Wi24rd

**Comment by iBug** [comment]
刚测了我这边没问题，AppID是266719，BDUSS没过期也没更新，能 `ls` 也能下载东西

**Comment by EatMedicine** [comment]
我这边也出现这个问题了。。BDUSS是刚刚获取的 账号密码登录也是31045

**Comment by stre1654** [comment]
我是下午6:12有登入百度雲後就不能用了

**Comment by zhaoloving** [comment]
FYI，我在两台电脑上登录了。

其中一台重新login后修改appid和user_agent无效，提示“请尝试重新登录, 消息: user not exists”，重新登录无效。

另一台没有重新login直接修改appid和user_agent能work。

**Comment by greymanking** [comment]
我在这之前启动过官方已经停止更新的那个百度云。

**Comment by coderfox** [comment]
```
[0] 提示: 当前下载最大并发量为: 100, 下载缓存为: 30000
[1] 加入下载队列: /我的资源
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
```

```
$ bdy config               
----
运行 BaiduPCS-Go config set 可进行设置配置

当前配置:
        名称                    值                 建议值                              描述                          
  appid              266719                                    百度 PCS 应用ID                                       
  enable_https       true                           true       启用 https                                            
  user_agent                                                   浏览器标识                                            
  cache_size         30000                      1024 ~ 262144  下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值  
  max_parallel       100                          50 ~ 500     下载最大并发量                                        
  max_download_load  1                              1 ~ 5      同时进行下载文件的最大数量                            
  savedir            /Users/*********/Downloads                 下载文件的储存目录
```

**Comment by iikira** [comment]
应该修复了, 82a39798a360f1ee7280187db496c6f11ebddcfc
可到这里下载使用, 并重新登录, https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

或者编译安装后重新登录

**Comment by xxxman2008** [comment]
当前配置:
       名称                                   值                               建议值                              描述

 appid              260149                                                                 百度 PCS 应用ID

 enable_https       true                                                        true       启用 https

 user_agent         netdisk;1.0                                                            浏览器标识

 cache_size         262144                                                  1024 ~ 262144  下载缓存, 如果硬盘占用高或下
载速度慢, 请尝试调大此值
 max_parallel       5                                                         50 ~ 500     下载最大并发量

 max_download_load  5                                                           1 ~ 5      同时进行下载文件的最大数量

 savedir            D:\LinuxTools\BaiduPCS-Go-v3.5.4-windows-x64\Downloads                 下载文件的储存目录

BaiduPCS-Go > login -bduss=***************************
百度帐号登录成功: 星际**高手3
BaiduPCS-Go:/ 星际**高手3$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation
BaiduPCS-Go:/ 星际**高手3$ logout
确认退出百度帐号: 星际**高手3 ? (y/n) > y
退出用户成功, 星际**高手3
BaiduPCS-Go:/ 星际**高手3$ login
请输入百度用户名(手机号/邮箱/用户名), 回车键提交 > 星际**高手3
请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) >

需要验证手机或邮箱才能登录
选择一种验证方式
1: 手机: 132******04
2: 邮箱: xx...7@gmail.com

请输入验证方式 (1 或 2) > 2
消息: 验证码已发送至你的邮箱 xx...7@gmail.com

请输入接收到的验证码 > *****
百度帐号登录成功: 星际**高手3
BaiduPCS-Go:/ 星际**高手3$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

BaiduPCS-Go version v3.5.5-devel -------------------  最新 
 https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载的，浙江电信线路。

总的来说，没有修复，请继续努力。顺便说一下，Go 的编译真的完全没有逻辑性，反人类设计。。。。

**Comment by xxxman2008** [comment]
追加：

config set -appid=266719
config set -user_agent="netdisk;8.3.1;android-android"

修改后，可以使用了

**Comment by fatinghenji** [comment]
我这里依旧没有办法解决
        名称                             值                          建议值                              描述           
  appid              266719                                                      百度 PCS 应用ID                        
  enable_https       true                                             true       启用 https                             
  user_agent         "netdisk;8.3.1;android-android"                             浏览器标识                             
  cache_size         30000                                        1024 ~ 262144  下载缓存, 如果硬盘占用高或下载速度慢,  请尝试调大此值
  max_parallel       100                                            50 ~ 500     下载最大并发量                         
  max_download_load  1                                                1 ~ 5      同时进行下载文件的最大数量             
  savedir            D:\BaiduPCS-Go-v3.5.3-windows-x64\Downloads                 下载文件的储存目录                     

保存配置成功!

BaiduPCS-Go:/ fthji111$ l
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登 录, 消息: user not exists

**Comment by jysw980** [comment]
> 应该修复了, [82a3979](https://github.com/iikira/BaiduPCS-Go/commit/82a39798a360f1ee7280187db496c6f11ebddcfc)
> 可到这里下载使用, 并重新登录, https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> 
> 或者编译安装后重新登录

亲测有效

**Comment by UQJRlex** [comment]
wget -O http://xxxx 1.zip
困在了这一步。

中间的网址不是这个
https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts/BaiduPCS-Go-android-arm64

不知道正确网址……

**Comment by xxxman2008** [comment]
我是 第一次 使用  这个 脚本。。。
但是。。令我很诧异的是。。。它，居然居然。。居然 。。会下载不完全 。我用 这个工具，批量下载电影，中途 有几次 “ctrl+C”  。。
但是。。居然。。居然 。。电影放到 末尾会 无法播放。。就是说 “有一部分数据，没有下载下来”

话说，http 的断点续传是一个 基础功能，你确定你 的 脚本里面  对下载结果验证过了么？？你确定你开启断点续传了么？？你确定每隔一段时间写入下载的数据了么（我的 机器上 ，你的程序的磁盘操作比较奇怪。很长一段时间都无法看到 文件的真实大小。）？？

下载不完整这个bug ，非常非常的奇怪。。。奇怪。

**Comment by zangqiyue** [comment]
+11111

**Comment by LuomingXu** [comment]
> 追加：
> 
> config set -appid=266719
> config set -user_agent="netdisk;8.3.1;android-android"
> 
> 修改后，可以使用了
> 
> BTW: 如果 appid 是必须重新设置的。。为啥在 master 代码里面，不干脆更新过来呢？？？我之前就是以为最新代码已经更新这个 id 了。。

works
=

**Comment by UQJRlex** [comment]
卡在这一步
wget -O 1.zip https://xxx

不知道网址是什么，如果是
https://ci.appveyor.com/api/buildjobs/av00fqnb1di2uc61/artifacts/BaiduPCS-Go-android-arm64.zip

但这只能下到本地，手机没root，无法将压缩包移到date目录下。

也更不是这个
https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts/BaiduPCS-Go-android-arm64.zip

所以请问网址该是什么？

**Comment by xxxman2008** [comment]
> 卡在这一步
> wget -O 1.zip https://xxx
> 
> 不知道网址是什么，如果是
> https://ci.appveyor.com/api/buildjobs/av00fqnb1di2uc61/artifacts/BaiduPCS-Go-android-arm64.zip
> 
> 但这只能下到本地，手机没root，无法将压缩包移到date目录下。
> 
> 也更不是这个
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts/BaiduPCS-Go-android-arm64.zip
> 
> 所以请问网址该是什么？

个人建议，手机上，你还是老老实实用  百度官方网盘客户端吧。。。费这个劲，你的时间成本 划不来。。同样的 ，作者为了修补、测试你提出的问题，他的时间也给你浪费了。。

**Comment by xxxman2008** [comment]
我昨天 ，花了点时间，去对比了一下   百度网盘官方PC客户端  和  此程序。
首先，我是一个 普通的 网盘客户，没有付费的。

测试的结果，百度网盘官方客户端，下载速度  快很多，稍微推测一下。。觉得 百度网盘客户端不是采用  HTTP接口的，而且可能引入  “P2P 分享” 的理念，所以，在我的 15G 下载测试里面，总体速度基本保持在 5M BPS（50M bps） 左右

而此Go 程序，基本上的总速度 ，不高于1M BPS （10M bps）。

在没有、或者不遵循 官方的 P2P 原则情况下， 百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。 

如果是把这个客户端作为一个 百度网盘命令行替代品，出于系统维护什么的 目的，是不错的。

但是，网上大部分宣传，什么 “绕过官方xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。

**Comment by dizys** [comment]
> 应该修复了, [82a3979](https://github.com/iikira/BaiduPCS-Go/commit/82a39798a360f1ee7280187db496c6f11ebddcfc)
> 可到这里下载使用, 并重新登录, https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> 
> 或者编译安装后重新登录

没有起效 😭

**Comment by huclengyue** [comment]
> 我昨天 ，花了点时间，去对比了一下 百度网盘官方PC客户端 和 此程序。
> 首先，我是一个 普通的 网盘客户，没有付费的。
> 
> 测试的结果，百度网盘官方客户端，下载速度 快很多，稍微推测一下。。觉得 百度网盘客户端不是采用 HTTP接口的，而且可能引入 “P2P 分享” 的理念，所以，在我的 15G 下载测试里面，总体速度基本保持在 5M BPS（50M bps） 左右
> 
> 而此Go 程序，基本上的总速度 ，不高于1M BPS （10M bps）。
> 
> 在没有、或者不遵循 官方的 P2P 原则情况下， 百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。
> 
> 如果是把这个客户端作为一个 百度网盘命令行替代品，出于系统维护什么的 目的，是不错的。
> 
> 但是，网上大部分宣传，什么 “绕过官方xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。

**免费用户用百度云官方的程序下载东西速度超过500K我都不信** 至于你说这个程序不高于不高于1M  那我这10M的速度是假的吗？

**Comment by UQJRlex** [comment]
> 我昨天 ，花了点时间，去对比了一下 百度网盘官方PC客户端 和 此程序。
首先，我是一个 普通的 网盘客户，没有付费的。
> 
测试的结果，百度网盘官方客户端，下载速度 快很多，稍微推测一下。。觉得 百度网盘客户端不是采用 HTTP接口的，而且可能引入 “P2P 分享” 的理念，所以，在我的 15G 下载测试里面，总体速度基本保持在 5M BPS（50M bps） 左右
> 
而此Go 程序，基本上的总速度 ，不高于1M BPS （10M bps）。
> 
在没有、或者不遵循 官方的 P2P 原则情况下， 百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。
> 
如果是把这个客户端作为一个 百度网盘命令行替代品，出于系统维护什么的 目的，是不错的。
> 
但是，网上大部分宣传，什么 “绕过官方xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。

先不说是否每次都能确保资源下载能够P2P，官方速度是什么样大家心里就没有数吗？而这个程序的速度在个人用时是经常超过1M/s的，不知道你是咋用的。
我的确付出时间成本了，但也成功上车了，个人认为自己的时间成本比不上经济成本。
至于麻烦开发者，算是道德绑架吗？先不说这个问题不是我首先发出来的，开发者开发程序修补bug的动机也是他个人的事，他对此也没表露任何怨言，也许他会为补上bug而高兴呢，又何来第三方的主观臆测？再说这个平台是友好交流的平台，又何必堵塞言路，再说俺也没有无理取闹。

**Comment by TTTPOB** [comment]
> 我昨天 ，花了点时间，去对比了一下 百度网盘官方PC客户端 和 此程序。
> 首先，我是一个 普通的 网盘客户，没有付费的。
> 
> 测试的结果，百度网盘官方客户端，下载速度 快很多，稍微推测一下。。觉得 百度网盘客户端不是采用 HTTP接口的，而且可能引入 “P2P 分享” 的理念，所以，在我的 15G 下载测试里面，总体速度基本保持在 5M BPS（50M bps） 左右
> 
> 而此Go 程序，基本上的总速度 ，不高于1M BPS （10M bps）。
> 
> 在没有、或者不遵循 官方的 P2P 原则情况下， 百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。
> 
> 如果是把这个客户端作为一个 百度网盘命令行替代品，出于系统维护什么的 目的，是不错的。
> 
> 但是，网上大部分宣传，什么 “绕过官方xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。

![image](https://user-images.githubusercontent.com/19909103/45936596-16784280-bfeb-11e8-8a08-d51e91e0782f.png)
多说无益

**Comment by shangming-wang** [comment]
> > 看来只能用pandownload了。也很好奇，pandownload怎么没事？
> 
> 我的pandownload也不能了，你用的哪个版本，能发个链接吗

直接从官网下载http://pandownload.com/
我没别的意思，就从我使用的情况来看，pandownload的下载速度比这个快。
我使用这个，下载速度一般都是1M/s，但是pandownload有4M/s
而且pandownload一开始就有4M/s，这个需要等一下才能达到1M/s

但是还是体谅开发者，毕竟个人免费开发出来给大家使用。给个赞b(￣▽￣)d
要不考虑下优化，把下载速度提升一点？ @iikira

**Comment by MewX** [comment]
最新版本仍然无效 BaiduPCS-Go version v3.5.5-devel

**Comment by genelocated** [comment]
> 最新版本仍然无效 BaiduPCS-Go version v3.5.5-devel

最新的更改还没有 release，自己编译一遍就正常了。

**Comment by xxxman2008** [comment]
HTTP方式的 下载，有所谓的 “热点”问题。
有些朋友的 资源，属于热点，所以可能获得比较好的速度。

在我的测试里面，总量15G的文件（22个），只有一个文件，达到我的带宽满载。
就像我 说的 “15G 测试”，我表明的是一种科学的 态度，至于有几位朋友，以偏概全 的 语言和回复，我就只当他们缺乏必要的科学教育，略过了。

同时，我也提出一种可能性，就是说，百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。“判断 referrer，判断agent，乃至判断 cookie”，很容易就能鉴别出第三方HTTP协议的客户端，也很容易的 ，可以自由的选择是 进行封杀 还是 睁一只眼闭一只眼。可能性，我想大家都清楚，即使不清楚的，看完我上面 的话，也清楚了。选择权在于个人，丰俭由己。

**Comment by civiliann** [comment]
出现31045来更新出现问题，请教
wget -O 1.zip https://ci.appveyor.com/api/buildjobs/av00fqnb1di2uc61/artifacts/BaiduPCS-Go-android-arm64.zip 
unzip 1.zip 
Archive:  1.zip
  inflating: BaiduPCS-Go后
$ ls
BaiduPCS-Go  downloads    storage      wget-logd (BaiduPCS-Go无颜色的 downloads和storage蓝色
$ BaiduPCS-Go
BaiduPCS-Go: command not found
$ cd ~/downloads && ./BaiduPCS-Go
bash: ./BaiduPCS-Go: Permission denied
$

**Comment by MingqiHuang** [comment]
> 
> 
> 出现 31045 来更新出现问题，请教
> wget -O 1.zip https://ci.appveyor.com/api/buildjobs/av00fqnb1di2uc61/artifacts/BaiduPCS-Go-android-arm64.zip
> unzip 1.zip
> Archive: 1.zip
> inflating: BaiduPCS-Go 后
> $ ls
> BaiduPCS-Go downloads storage wget-logd (BaiduPCS-Go 无颜色的 downloads 和 storage 蓝色
> $ BaiduPCS-Go
> BaiduPCS-Go: command not found
> $ cd ~/downloads && ./BaiduPCS-Go
> bash: ./BaiduPCS-Go: Permission denied
> $
> 最后是参考原来的步骤然后把 BaiduPCS-Go 替换新的就成功了，这样就下载两个。。

您得给可执行文件加上执行权限啊，Unix-like 系统新生成的文件都是没有执行权限的。
```bash
chmod +x BaiduPCS-Go
```

**Comment by MingqiHuang** [comment]
> 
> 
> HTTP 方式的 下载，有所谓的 “热点” 问题。
> 有些朋友的 资源，属于热点，所以可能获得比较好的速度。
> 
> 在我的测试里面，总量 15G 的文件（22 个），只有一个文件，达到我的带宽满载。
> 就像我 说的 “15G 测试”，我表明的是一种科学的 态度，至于有几位朋友，以偏概全 的 语言和回复，我就只当他们缺乏必要的科学教育，略过了。
> 
> 同时，我也提出一种可能性，就是说，百度官方，完全可以 很轻松的 控制任何一个 第三方客户端的下载速度。“判断 referrer，判断 agent，乃至判断 cookie”，很容易就能鉴别出第三方 HTTP 协议的客户端，也很容易的 ，可以自由的选择是 进行封杀 还是 睁一只眼闭一只眼。可能性，我想大家都清楚，即使不清楚的，看完我上面 的话，也清楚了。选择权在于个人，丰俭由己。

事实上更多的人使用这个客户端完全不是为了加速，而是为了更个性化地定制百度网盘，扩展出百度网盘没有的功能。在 Linux 环境下现在官方也没有推出客户端，难道我们只能使用网页版进行操作吗？那样功能太受限了（下载大文件都不行）。另外有些人需要在不同平台上下载（例如 Openwrt 路由器实现离线下载降低功耗）等等，这都是不同人的不同需求，很难通过单一的客户端实现。将两个性质完全不同的软件放在一起比较是没有意义的。我就是更喜欢在终端里完成大多数工作，而这是 PanDownload 或官方客户端无法完成的。比起下载速度，我更看重可扩展性，而此项目做的很好。

> 但是，网上大部分宣传，什么 “绕过官方 xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。

网上的宣传是别人做的，而不是项目作者做的宣传，这一点请您搞明白。

我使用这个客户端往往是 `BaiduPCS-Go download *` 这样的命令，这是大多数客户端无法具备的（即将弃用百度网盘）。另外在路由器上下载也极大地降低了功耗，下载耗时也变得不是那么重要了。

FoSS 就这一个好，你不满意你自己写，写出来可以 PR，作者没有义务使得这个软件符合所有人的要求，作者自己用着爽就够了。作者也没有义务给你修 bug，源代码都给你了，你还想要什么？

**Comment by xxxman2008** [comment]
> 事实上更多的人使用这个客户端完全不是为了加速，而是为了更个性化地定制百度网盘，扩展出百度网盘没有的功能。在 Linux 环境下现在官方也没有推出客户端，难道我们只能使用网页版进行操作吗？那样功能太受限了（下载大文件都不行）。另外有些人需要在不同平台上下载（例如 Openwrt 路由器实现离线下载降低功耗）等等，这都是不同人的不同需求，很难通过单一的客户端实现。将两个性质完全不同的软件放在一起比较是没有意义的。我就是更喜欢在终端里完成大多数工作，而这是 PanDownload 或官方客户端无法完成的。比起下载速度，我更看重可扩展性，而此项目做的很好。
> 
关于这个问题，请参考之前我的发帖，  “断章取义”的 成语，了解一下。 天朝人民 在沟通交流里，几乎100%会犯这种错误。。说太多没什么意思。


> > 但是，网上大部分宣传，什么 “绕过官方 xxxx，极速下载 xxx”。。。我只能 呵呵。呵呵呵。
> 
> 网上的宣传是别人做的，而不是项目作者做的宣传，这一点请您搞明白。
是谁给了你 无限发挥 想象的权力，又是谁，给你安装了 铝合金的眼睛，让你看到我说了“网上宣传是项目作者做的”？？  


> 我使用这个客户端往往是 `BaiduPCS-Go download *` 这样的命令，这是大多数客户端无法具备的（即将弃用百度网盘）。另外在路由器上下载也极大地降低了功耗，下载耗时也变得不是那么重要了。
> FoSS 就这一个好，你不满意你自己写，写出来可以 PR，作者没有义务使得这个软件符合所有人的要求，作者自己用着爽就够了。作者也没有义务给你修 bug，源代码都给你了，你还想要什么？

还是那句话，谁给了你 这种想象力？？陈诉一个事实或者个人的看法就是不满意？？？然后就要自己写？？？然后 还扯上  修bug？？？？小朋友，就事论事，你以为你是共产党，可以无限想象和扩张？？乱扯一通  我的原文里面 没有的东西。你的 脑子是 10块钱的黑人给你贴的么？？

**Comment by huclengyue** [comment]
我感觉github应该开发一个屏蔽功能，某个项目对屏蔽的人不可见

**Comment by MingqiHuang** [comment]
Block user & Report Abuse, I don't care, in fact.

**Comment by Xiaotouming** [comment]
[](url)
> 所以请问网址该是什么？
就是下载地址呗

https://github.com/iikira/BaiduPCS-Go/releases/download/v3.5.6/BaiduPCS-Go-v3.5.6-android-21-amd64.zip

**Comment by 2217092594** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized
[0] 提示: 当前下载最大并发量为: 100, 下载缓存为: 1024
[1] 加入下载队列: /软件/ps
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file

任务结束, 时间: 1s, 数据总量: 0B

**Comment by Latezly** [comment]
> > 事实上更多的人使用这个客户端完全不是为了加速，而是为了更个性化地定制百度网盘，扩展出百度网盘没有的功能。在Linux 环境下现在官方也没有推出客户端，难道我们只能使用网页版进行操作吗？那样功能太受限了（下载大文件都不行）。另外有些人需要在不同平台上下载（例如Openwrt 路由器实现离线下载降低功耗）等等，这都是不同人的不同需求，很难通过单一的客户端实现。将两个性质完全不同的软件放在一起比较是没有意义的。我就是更喜欢在终端里完成大多数工作，而这是PanDownload 或官方客户端无法完成的。比起下载速度，我更看重可扩展性，而此项目做的很好。
> 
> 关于这个问题，请参考之前我的发帖， “断章取义”的成语，了解一下。天朝人民在沟通交流里，几乎100%会犯这种错误。。说太多没什么意思。
> 
> > > 但是，网上大部分宣传，什么“绕过官方xxxx，极速下载xxx”。。。我只能呵呵。呵呵呵。
> > 
> > 
> > 网上的宣传是别人做的，而不是项目作者做的宣传，这一点请您搞明白。
> 
> 是谁给了你无限发挥想象的权力，又是谁，给你安装了铝合金的眼睛，让你看到我说了“网上宣传是项目作者做的”？？
> 
> > 我使用这个客户端往往是`BaiduPCS-Go download *`这样的命令，这是大多数客户端无法具备的（即将弃用百度网盘）。另外在路由器上下载也极大地降低了功耗，下载耗时也变得不是那么重要了。
> > FoSS就这一个好，你不满意你自己写，写出来可以PR，作者没有义务使得这个软件符合所有人的要求，作者自己用着爽就够了。作者也没有义务给你修bug，源代码都给你了，你还想要什么？
> 
> 还是那句话，谁给了你这种想象力？？陈诉一个事实或者个人的看法就是不满意？？？然后就要自己写？？？然后还扯上修bug？？？？小朋友，就事论事，你以为你是共产党，可以无限想象和扩张？？乱扯一通我的原文里面没有的东西。你的脑子是10块钱的黑人给你贴的么？？



> > 事实上更多的人使用这个客户端完全不是为了加速，而是为了更个性化地定制百度网盘，扩展出百度网盘没有的功能。在Linux 环境下现在官方也没有推出客户端，难道我们只能使用网页版进行操作吗？那样功能太受限了（下载大文件都不行）。另外有些人需要在不同平台上下载（例如Openwrt 路由器实现离线下载降低功耗）等等，这都是不同人的不同需求，很难通过单一的客户端实现。将两个性质完全不同的软件放在一起比较是没有意义的。我就是更喜欢在终端里完成大多数工作，而这是PanDownload 或官方客户端无法完成的。比起下载速度，我更看重可扩展性，而此项目做的很好。
> 
> 关于这个问题，请参考之前我的发帖， “断章取义”的成语，了解一下。天朝人民在沟通交流里，几乎100%会犯这种错误。。说太多没什么意思。
> 
> > > 但是，网上大部分宣传，什么“绕过官方xxxx，极速下载xxx”。。。我只能呵呵。呵呵呵。
> > 
> > 
> > 网上的宣传是别人做的，而不是项目作者做的宣传，这一点请您搞明白。
> 
> 是谁给了你无限发挥想象的权力，又是谁，给你安装了铝合金的眼睛，让你看到我说了“网上宣传是项目作者做的”？？
> 
> > 我使用这个客户端往往是`BaiduPCS-Go download *`这样的命令，这是大多数客户端无法具备的（即将弃用百度网盘）。另外在路由器上下载也极大地降低了功耗，下载耗时也变得不是那么重要了。
> > FoSS就这一个好，你不满意你自己写，写出来可以PR，作者没有义务使得这个软件符合所有人的要求，作者自己用着爽就够了。作者也没有义务给你修bug，源代码都给你了，你还想要什么？
> 
> 还是那句话，谁给了你这种想象力？？陈诉一个事实或者个人的看法就是不满意？？？然后就要自己写？？？然后还扯上修bug？？？？小朋友，就事论事，你以为你是共产党，可以无限想象和扩张？？乱扯一通我的原文里面没有的东西。你的脑子是10块钱的黑人给你贴的么？？



> > 事实上更多的人使用这个客户端完全不是为了加速，而是为了更个性化地定制百度网盘，扩展出百度网盘没有的功能。在Linux 环境下现在官方也没有推出客户端，难道我们只能使用网页版进行操作吗？那样功能太受限了（下载大文件都不行）。另外有些人需要在不同平台上下载（例如Openwrt 路由器实现离线下载降低功耗）等等，这都是不同人的不同需求，很难通过单一的客户端实现。将两个性质完全不同的软件放在一起比较是没有意义的。我就是更喜欢在终端里完成大多数工作，而这是PanDownload 或官方客户端无法完成的。比起下载速度，我更看重可扩展性，而此项目做的很好。
> 
> 关于这个问题，请参考之前我的发帖， “断章取义”的成语，了解一下。天朝人民在沟通交流里，几乎100%会犯这种错误。。说太多没什么意思。
> 
> > > 但是，网上大部分宣传，什么“绕过官方xxxx，极速下载xxx”。。。我只能呵呵。呵呵呵。
> > 
> > 
> > 网上的宣传是别人做的，而不是项目作者做的宣传，这一点请您搞明白。
> 
> 是谁给了你无限发挥想象的权力，又是谁，给你安装了铝合金的眼睛，让你看到我说了“网上宣传是项目作者做的”？？
> 
> > 我使用这个客户端往往是`BaiduPCS-Go download *`这样的命令，这是大多数客户端无法具备的（即将弃用百度网盘）。另外在路由器上下载也极大地降低了功耗，下载耗时也变得不是那么重要了。
> > FoSS就这一个好，你不满意你自己写，写出来可以PR，作者没有义务使得这个软件符合所有人的要求，作者自己用着爽就够了。作者也没有义务给你修bug，源代码都给你了，你还想要什么？
> 
> 还是那句话，谁给了你这种想象力？？陈诉一个事实或者个人的看法就是不满意？？？然后就要自己写？？？然后还扯上修bug？？？？小朋友，就事论事，你以为你是共产党，可以无限想象和扩张？？乱扯一通我的原文里面没有的东西。你的脑子是10块钱的黑人给你贴的么？？

我寻思您这态度好像是挺不看好的烂程序的啊？那你干嘛还要再issues里杠这么多？
你要看好那你干嘛还要杠这么多？
正好我工地里缺个出力气的你要不来试下？包吃包住工资详谈
