### ISSUE TITLE
请问有没有『断点续传』功能的开发计划？

### ISSUE THREAD

**Issue by gesund** [iikira/BaiduPCS-Go#4]
这个功能可以极大减少下载的焦虑和挫败感，希望可以在以后的版本中看到。

谢谢iikira，谢谢你的程序！

**Comment by iikira** [comment]
支持断点续传了啊, 触发的条件是, 下载文件未完成程序退出, 下一次下载到该文件时自动继续...

**Comment by gesund** [comment]
原来是这样，我刚开始用这个，还没碰到下载中断的情况。谢谢啦！
