### ISSUE TITLE
win10 CMD和PowerShell中，有一些中文无法输入上去？

### ISSUE THREAD

**Issue by al123xiaaaa** [iikira/BaiduPCS-Go#40]
比如打算输入"cd /我的视频/"，只能输成"cd /我的"，视频两个字输不上去

**Comment by iikira** [comment]
在windows上确实存在这个问题……
关闭这条issue了，因为与 [#20](https://github.com/iikira/BaiduPCS-Go/issues/20) 一样，等待修复，目前可以暂时使用通配符代替不能输入的中文。
