### ISSUE TITLE
获取目录信息错误, 获取目录下的文件列表, json 数据解析失败, EOF 任务结束, 时间: 254ms, 数据总量: 0B

### ISSUE THREAD

**Issue by Qxt-circle** [iikira/BaiduPCS-Go#401]
<img width="478" alt="2018-09-22 2 23 22" src="https://user-images.githubusercontent.com/26061932/45914133-338a0580-be73-11e8-8d89-f718142d7c3a.png">
昨晚利用[https://github.com/iikira/BaiduPCS-Go/issues/387](url)里修改appid的方式解决了no permission的问题，可以正常下载了，而今天json数据解析失败，不是不知道是什么鬼

v3.5.3
OS 10.13.6

**Comment by dragonfalls** [comment]
同样遇到这种情况，json数据解析失败，EOF，系统是macOS 10.13.6

**Comment by 2465068058** [comment]
一样的情况

**Comment by Qxt-circle** [comment]
获取当前用户空间配额信息: json 数据解析失败, EOF
BaiduPCS-Go quota 同样无法获取网盘配额
v3.5.3/3.5.5
OS 10.13.6

**Comment by dogname** [comment]
我也是这样,不过可以下载

**Comment by Qxt-circle** [comment]
我的不能下载，很难受╯﹏╰

**Comment by harekazewin** [comment]
在命令行下执行 ./BaiduPCS-Go --verbose d <foldername>没问题
进入cli执行d <foldername>就有问题

**Comment by Qxt-circle** [comment]
> 在命令行下执行 `./BaiduPCS-Go --verbose d foldername`没问题
> 进入cli执行 `d foldername`就有问题
> 
> Update: 极低概率可以成功下载 条件不明
> 
> 环境：Archlinux 使用最新master自编译

我试了`--verbose d foldername`，依然是json数据解析失败

**Comment by harekazewin** [comment]
> > 在命令行下执行 `./BaiduPCS-Go --verbose d foldername`没问题
> > 进入cli执行 `d foldername`就有问题
> > Update: 极低概率可以成功下载 条件不明
> > 环境：Archlinux 使用最新master自编译
> 
> 我试了`--verbose d foldername`，依然是json数据解析失败

我多试了几次 两种方式并没有区别 都可能失败 都可能成功

**Comment by Qxt-circle** [comment]
> > > 在命令行下执行 `./BaiduPCS-Go --verbose d foldername`没问题
> > > 进入cli执行 `d foldername`就有问题
> > > Update: 极低概率可以成功下载 条件不明
> > > 环境：Archlinux 使用最新master自编译
> > 
> > 
> > 我试了`--verbose d foldername`，依然是json数据解析失败
> 
> 我多试了几次 两种方式并没有区别 都可能失败 都可能成功

T_T都是概率……

**Comment by iikira** [comment]
是服务器的问题

**Comment by Qxt-circle** [comment]
> 是服务器的问题

我天，我开了热点试了问题解决了（捂脸

**Comment by Qxt-circle** [comment]
> 是服务器的问题

问题时断时续（哭），求问大大，是百度网盘服务器的问题吗？

**Comment by ficatudi** [comment]
> > 是服务器的问题
> 
> 问题时断时续（哭），求问大大，是百度网盘服务器的问题吗？

试试看这个https://www.speedpan.com/

**Comment by dragonfalls** [comment]
> > 是服务器的问题
> 
> 问题时断时续（哭），求问大大，是百度网盘服务器的问题吗？

 现在可以 cd , 可以下载指定文件，但不能 d / 或 d * ，不能 ls 。

**Comment by iikira** [comment]
现在还会出现这个问题吗？

**Comment by dragonfalls** [comment]
> 现在还会出现这个问题吗？

已经好了

**Comment by Qxt-circle** [comment]
> 现在还会出现这个问题吗？

换了一个Wi-Fi，目前没有同样问题出现
