### ISSUE TITLE
offlinedl list报错：36001， param error

### ISSUE THREAD

**Issue by MasayaSym** [iikira/BaiduPCS-Go#403]
offlinedl list报错：
查询离线下载任务列表, 遇到错误, 远端服务器返回错误, 代码: 36001, 消息: param error
___
offlinedl delete -all：
Incorrect Usage: flag provided but not defined: -all

**Comment by iikira** [comment]
先更新一下版本

**Comment by iikira** [comment]
新版本应该修复了，先关闭issue，如果有问题再打开吧
