### ISSUE TITLE
错误代码:31045

### ISSUE THREAD

**Issue by Kucashu** [iikira/BaiduPCS-Go#404]
错误提示：
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登 录, 消息: user not exists

错误场景：
在logout账号后再次登陆便会如此，无法下载

**Comment by harekazewin** [comment]
#399

**Comment by FateLight** [comment]
@harekazewin 不知道新ID能撑多久

**Comment by iikira** [comment]
与#399 一样，关闭了
