### ISSUE TITLE
获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

### ISSUE THREAD

**Issue by PoetKotori** [iikira/BaiduPCS-Go#405]
获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, **可能百度帐号登录状态过期, 请尝试重新登录**, 消息: user not exists

**Comment by jarryyen** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

**Comment by dizys** [comment]
same. thanks for your contribution. hoping for an update. lots of thanks

**Comment by iikira** [comment]
与#399 一样,关闭了
