### ISSUE TITLE
在树莓派中运行时，出现31045登陆过期错误代码

### ISSUE THREAD

**Issue by sastar** [iikira/BaiduPCS-Go#407]
在树莓派中运行时，出现31045登陆过期错误代码
树莓派架构：Linux raspberrypi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux
在win10 1803中则不会出现，可以正常登陆
所有都已重置appid

**Comment by Zhiwei1996** [comment]
感觉凉了 😶
换了appid 后爽了一天就不能用了，是不是被太多人疯狂扫 id 度娘察觉到怒封

**Comment by iikira** [comment]
与#399 一样，关闭了
