### ISSUE TITLE
百度账号登录过期

### ISSUE THREAD

**Issue by masterrite** [iikira/BaiduPCS-Go#409]
百度好像开始使用动态BDUSS了 明明手动获取了BDUSS并登录成功，然而在下载的时候依旧得到一个错误报告并提示登录过期。重新手动获取BDUSS的时候得到的却是另一个新的BDUSS。

**Comment by iBug** [comment]
参见 #387 最后一条评论

**Comment by CLAY45** [comment]
Ubuntu16.04
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

**Comment by luxikakashi** [comment]
> 参见 #387 最后一条评论

手机登录的依旧不行

**Comment by CLAY45** [comment]
> > 参见 #387 最后一条评论
> 
> 手机登录的依旧不行

修改appid也不行？

**Comment by Stele1024** [comment]
> > > 参见 #387 最后一条评论
> > 
> > 
> > 手机登录的依旧不行
> 
> 修改appid也不行？

不行了。刚刚修改了appid.还是提示这错误

**Comment by luxikakashi** [comment]
> > > 参见 #387 最后一条评论
> > 
> > 
> > 手机登录的依旧不行
> 
> 修改appid也不行？
266719也不行

**Comment by caodj** [comment]
我也遇到了这个问题

**Comment by nanfengguli** [comment]
有没有大神，解决一下啊，一样的问题

**Comment by nanfengguli** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

**Comment by H1July** [comment]
同，手机端和pc端都不可用。更新到最新版本还不行，各位大佬弄好之后提醒我一下，之前以为是我账号或者手机的问题。用了pc端发现有同样的问题。。。作者大大有时间的话优化一下。离不开了啊

**Comment by xhao79** [comment]
Ubuntu 18.04 同样的问题

**Comment by fangzheng821** [comment]
> 有没有大神，解决一下啊，一样的问题

pc端的下载新版本（v3.5.5-devel）后重新设置下appid（BaiduPCS-Go config set -appid 266719）就ok了

**Comment by CLAY45** [comment]
设置过了，Windows下没有问题，在Ubuntu下不能使用
| |
CLAY45
|
|
邮箱：18846936491@163.com
|
签名由网易邮箱大师定制
在2018年9月25日 15:11，fangzheng821<notifications@github.com> 写道：

有没有大神，解决一下啊，一样的问题

pc端的下载新版本（v3.5.5-devel）后重新设置下appid（BaiduPCS-Go config set -appid 266719）就ok了

**Comment by nanfengguli** [comment]
> 
> 
> > 有没有大神，解决一下啊，一样的问题
> 
> pc端的下载新版本（v3.5.5-devel）后重新设置下appid（BaiduPCS-Go config set -appid 266719）就ok了

还是不行。。。

**Comment by EpicKJ** [comment]
同样的问题 设置APPID仍然不能解决

**Comment by H1July** [comment]
> > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> 
> 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退

同，在双引号内加上bduss闪退，删除Appdate/Roaming/BaiduPCS-Go又能用了，但是问题仍没有解决

**Comment by BadBoy1314love** [comment]
有没有自动更新bduss的办法

**Comment by cnly39** [comment]
> > > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> > 
> > 
> > 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退
> 
> 同，在双引号内加上bduss闪退，删除Appdate/Roaming/BaiduPCS-Go又能用了，但是问题仍没有解决

我重复了删除、登陆、修改的动作，但问题并没有复现，目前我在使用3.5.5版本的客户端，bduss在“https://pan.baidu.com”通过"EditThisCookie"获取，json文件使用win10默认的codewriter编辑，希望对你们有帮助。

**Comment by lwh31415** [comment]
> > > > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> > > 
> > > 
> > > 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退
> > 
> > 
> > 同，在双引号内加上bduss闪退，删除Appdate/Roaming/BaiduPCS-Go又能用了，但是问题仍没有解决
> 
> 我重复了删除、登陆、修改的动作，但问题并没有复现，目前我在使用3.5.5版本的客户端，bduss在“[https://pan.baidu.com”通过"EditThisCookie"获取，json文件使用win10默认的codewriter编辑，希望对你们有帮助。](https://pan.baidu.com%E2%80%9D%E9%80%9A%E8%BF%87%22EditThisCookie%22%E8%8E%B7%E5%8F%96%EF%BC%8Cjson%E6%96%87%E4%BB%B6%E4%BD%BF%E7%94%A8win10%E9%BB%98%E8%AE%A4%E7%9A%84codewriter%E7%BC%96%E8%BE%91%EF%BC%8C%E5%B8%8C%E6%9C%9B%E5%AF%B9%E4%BD%A0%E4%BB%AC%E6%9C%89%E5%B8%AE%E5%8A%A9%E3%80%82)

修改pcs_config.json后，可以ls了，不再提示登录过期；我的pcs_config.json文件在其他目录，是通过everything找到的

**Comment by xingjohn** [comment]
> > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> 
> 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退

bcuss不一致，
![image](https://user-images.githubusercontent.com/28851128/46115882-c3410280-c22b-11e8-86f2-06b558576004.png)和
![image](https://user-images.githubusercontent.com/28851128/46115894-d0f68800-c22b-11e8-84c3-cf3480a03022.png)ni你有连个json文件

**Comment by nanfengguli** [comment]
> 
> 
> > > > > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> > > > 
> > > > 
> > > > 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退
> > > 
> > > 
> > > 同，在双引号内加上bduss闪退，删除Appdate/Roaming/BaiduPCS-Go又能用了，但是问题仍没有解决
> > 
> > 
> > 我重复了删除、登陆、修改的动作，但问题并没有复现，目前我在使用3.5.5版本的客户端，bduss在“[https://pan.baidu.com”通过"EditThisCookie"获取，json文件使用win10默认的codewriter编辑，希望对你们有帮助。](https://pan.baidu.com%E2%80%9D%E9%80%9A%E8%BF%87%22EditThisCookie%22%E8%8E%B7%E5%8F%96%EF%BC%8Cjson%E6%96%87%E4%BB%B6%E4%BD%BF%E7%94%A8win10%E9%BB%98%E8%AE%A4%E7%9A%84codewriter%E7%BC%96%E8%BE%91%EF%BC%8C%E5%B8%8C%E6%9C%9B%E5%AF%B9%E4%BD%A0%E4%BB%AC%E6%9C%89%E5%B8%AE%E5%8A%A9%E3%80%82)
> 
> 修改pcs_config.json后，可以ls了，不再提示登录过期；我的pcs_config.json文件在其他目录，是通过everything找到的

也可以进入baiduPCS-GO后输入env，还直接给出地址的

**Comment by H1July** [comment]
> > > > > > 应该是bduss的问题，好像因为百度更改了bduss有效时间，在pcs登陆后无法写入bduss，可以在”C:\Users\用户\AppData\Roaming\BaiduPCS-Go“（3.5以上）找到"pcs_config.json“文件，通过网页获取bduss（我用的“editthiscookie”插件获取的），粘贴到文件内。
> > > > > 
> > > > > 
> > > > > 是补上bduss吗，为什么我补上后，打开PCS-GO就秒退
> > > > 
> > > > 
> > > > 同，在双引号内加上bduss闪退，删除Appdate/Roaming/BaiduPCS-Go又能用了，但是问题仍没有解决
> > > 
> > > 
> > > 我重复了删除、登陆、修改的动作，但问题并没有复现，目前我在使用3.5.5版本的客户端，bduss在“[https://pan.baidu.com”通过"EditThisCookie"获取，json文件使用win10默认的codewriter编辑，希望对你们有帮助。](https://pan.baidu.com%E2%80%9D%E9%80%9A%E8%BF%87%22EditThisCookie%22%E8%8E%B7%E5%8F%96%EF%BC%8Cjson%E6%96%87%E4%BB%B6%E4%BD%BF%E7%94%A8win10%E9%BB%98%E8%AE%A4%E7%9A%84codewriter%E7%BC%96%E8%BE%91%EF%BC%8C%E5%B8%8C%E6%9C%9B%E5%AF%B9%E4%BD%A0%E4%BB%AC%E6%9C%89%E5%B8%AE%E5%8A%A9%E3%80%82)
> > 
> > 
> > 修改pcs_config.json后，可以ls了，不再提示登录过期；我的pcs_config.json文件在其他目录，是通过everything找到的
> 
> 也可以进入baiduPCS-GO后输入env，还直接给出地址的

PC端问题已解决，不能用记事本打开修改。我用notepad++打开修改后可正常打开了。但安卓端仍未就解决，请各位大佬指导下
