### ISSUE TITLE
31045_修复脚本 !Termux Only

### ISSUE THREAD

**Issue by PEdajilao** [iikira/BaiduPCS-Go#411]
瞎几把写的，出错找我1348292515@qq.com #吐舌doge
`wget http://www.pebycar.online/BaiduPCS-Go_31045_fix.sh`
`chmod +x BaiduPCS-Go_31045_fix.sh`
`./BaiduPCS-Go_31045_fix.sh`

注意：
1.此脚本认为，您将BaiduPCS-Go装在了[$HOME_PATH]/BaiduPCS-Go/下，
2.此脚本认为您的BaiduPCS-Go已经配置完成

**Comment by FlyRabbit** [comment]
麻烦直接给下脚本吧，你这网站糊了，境内境外都打不开

**Comment by shanshangzhiren** [comment]
我也想直接看一下你的脚本

**Comment by PEdajilao** [comment]
，，只能等网站修复了，没备份XD
那就一键指令如何？。。
*这里插些提醒
确定Termux出现的“句首”是$，如果是BaiduPCS…$就先执行exit；

如果第一步(pkg install wget…)出现E：xxxxxxxx，检查网络问题*
ping -w 5 termux.net
*，部分地区可能无法直连Termux.net...

现在根据自己架构行事~：
386:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPUpjqf ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

amd64:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPyY0Kr ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

armv5:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPc6IER ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

armv6:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPc6X2R ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

armv7:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPc69X5 ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

arm64:
cd ~/BaiduPCS-Go;a=" http://t.cn/EPUJAhE ";wget -q$a-O 1.zip;unzip -oqq 1.zip|unset a;rm 1.zip;chmod 755 ./BaiduPCS-Go;./BaiduPCS-Go config set -appid=266719;./BaiduPCS-Go logout -y;./BaiduPCS-Go login;./BaiduPCS-Go

**Comment by PEdajilao** [comment]
#受虐滑稽
