### ISSUE TITLE
本机走代理时无法连接

### ISSUE THREAD

**Issue by 416207298** [iikira/BaiduPCS-Go#413]
公司网络走的是http代理，当连接代理时，无法login，在输入login命令后会卡主不动。

**Comment by iikira** [comment]
你可以尝试使用bduss登录。如果ls、download等命令，都用不了，那就是代理的问题了

**Comment by 416207298** [comment]
请问如何在win上命令行BaiduPCS-Go用BDUSS登录呢？

**Comment by 416207298** [comment]
bduss登录的提示结果如下图：
![image](https://user-images.githubusercontent.com/19567041/46987901-b88dd500-d128-11e8-9abd-bc40b10de25e.png)
账号密码登录错误如下图：
![image](https://user-images.githubusercontent.com/19567041/46987912-c93e4b00-d128-11e8-929a-0b48075260fd.png)

**Comment by iikira** [comment]
网络超时！这是你代理的问题！
