### ISSUE TITLE
获取目录下的文件列表, 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

### ISSUE THREAD

**Issue by xingjohn** [iikira/BaiduPCS-Go#415]
使用baiduPCS3.5.0~3.5.5之间的所有版本
在登录成功之后，使用ls命令，报出这个错误。

**Comment by H1July** [comment]
同

**Comment by localhost5321** [comment]
我在win下也出现了这个问题，已解决。
再exe同目录下有个配置文件pcs_config.json，打开可以发现bduss为空的，将bduss填上即可。

**Comment by Ryensu** [comment]
重新登录后更改appid
config set -appid 266719

**Comment by xingjohn** [comment]
你好，谢谢您的回复，我今天下午是搞了好久。
这个config set -appid 266719也设置了
Bduss也设置了。但是还是无效。
我也请了一个已经高成功的人帮我远程配置， 但还是无效。
最后，这个哥们说我人品不行。

**Comment by xingjohn** [comment]
追回答，今天晚上回家zhi之后，家里的电脑配置之后，一切正常。

**Comment by Ryensu** [comment]
你可以输入config看看appid是否已经改成266719

**Comment by Declarcall** [comment]
@Ryensu ``` ./BaiduPCS-Go config set -appid 266719 ```
已改成 266719，然后执行了下 ``` ./BaiduPCS-Go ls / ```
报如下信息：
> 获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

**Comment by kokoola** [comment]
填写bduss，并修改appid为266719 就正常了。

**Comment by blackcater** [comment]
1. Download this version

https://ci.appveyor.com/project/iikira/baidupcs-go/build/138

2. `config set -appid=266719`

It works for me!

**Comment by xingjohn** [comment]
> 你可以输入config看看appid是否已经改成266719

谢谢你的提醒，我查看过了，这个266719是改成功的。
![image](https://user-images.githubusercontent.com/28851128/46115040-ebc6fd80-c227-11e8-8bcb-a7e57c76cf6e.png)

**Comment by MingqiHuang** [comment]
> 
> 
> > 你可以输入 config 看看 appid 是否已经改成 266719
> 
> 谢谢你的提醒，我查看过了，这个 266719 是改成功的。
> ![image](https://user-images.githubusercontent.com/28851128/46115040-ebc6fd80-c227-11e8-8bcb-a7e57c76cf6e.png)

注意到您的 `user_agent` 是以前的版本，求修改为 `netdisk;8.3.1;android-android` 再试一次？

p.s. 或许您应该在 <https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts> 下载对应平台的最新版本？

**Comment by xingjohn** [comment]
问题已经找到，是我设置的bcuss的数据不对，百度的bcuss是192位，如上图所示。
而我从浏览器的bcuss，我粘贴的时候，是双击选中粘贴，而这种情况下，这个192位的加密字符串有个“-”分割，造成我只是粘贴了部分字符串，所以会一直报登录过期。
后来使用多个工具获得bcuss，进行比对，发现了这种情况。现在问题已经解决。
总结一下，作为总结。
1.报：获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation ，解决方案：config set -appid=266719
2.报：获取目录下的文件列表, 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
解决方案：获取正确的bcuss，记得是192位啊，也就是字符床的长度是192位，获取方法很多。
1）谷歌浏览器，按F12，或者网页的前面的小锁
2）使用三方工具：http://tool.cccyun.cc/tool/bduss/index.html
希望对需要的人有所帮助。

**Comment by xingjohn** [comment]
![image](https://user-images.githubusercontent.com/28851128/46116067-cdafcc00-c22c-11e8-9eb0-89a85459a826.png)
补上加密字符串长度测试。

**Comment by xingjohn** [comment]
> > > 你可以输入 config 看看 appid 是否已经改成 266719
> > 
> > 
> > 谢谢你的提醒，我查看过了，这个 266719 是改成功的。
> > ![image](https://user-images.githubusercontent.com/28851128/46115040-ebc6fd80-c227-11e8-8bcb-a7e57c76cf6e.png)
> 
> 注意到您的 `user_agent` 是以前的版本，求修改为 `netdisk;8.3.1;android-android` 再试一次？
> 
> p.s. 或许您应该在 https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载对应平台的最新版本？

谢谢你的提示，这个选项，我昨天尝试过了。

**Comment by xingjohn** [comment]
> * Download this version
> 
> > https://ci.appveyor.com/project/iikira/baidupcs-go/build/138
> 
> * `config set -appid=266719`
> 
> It works for me!
> 
> [#399 (comment)](https://github.com/iikira/BaiduPCS-Go/issues/399#issuecomment-423703891)

谢谢你的提示，这个版本，我看了半天，不知道如何构建。

**Comment by xingjohn** [comment]
> 填写bduss，并修改appid为266719 就正常了。

谢谢你的提示，问题已经解决，已经在下面标出。

**Comment by xingjohn** [comment]
> > 重新登录后更改appid
> > config set -appid 266719
> 
> 不行呢..还是报错误

你的问题解决了吗？如果没有解决，可以看下面，我的总结提示。

**Comment by xingjohn** [comment]
> @Ryensu
> 
> ```
> ./BaiduPCS-Go --version
> BaiduPCS-Go version v3.5.5
> ```
> 填写了bduss
> `./BaiduPCS-Go login -bduss=TokenString`
> 百度帐号登录成功: Declarcall
> `./BaiduPCS-Go config set -appid 266719`
> 已改成 266719，然后执行了下 `./BaiduPCS-Go ls /`
> 报如下信息：
> 
> > 获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

您的问题解决了吗，如果没有解决，请看我下面的总结提示，希望对你有所帮助。

**Comment by H1July** [comment]
> > @Ryensu
> > ```
> > ./BaiduPCS-Go --version
> > BaiduPCS-Go version v3.5.5
> > ```
> > 填写了bduss
> > `./BaiduPCS-Go login -bduss=TokenString`
> > 百度帐号登录成功: Declarcall
> > `./BaiduPCS-Go config set -appid 266719`
> > 已改成 266719，然后执行了下 `./BaiduPCS-Go ls /`
> > 报如下信息：
> > > 获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
> 
> 您的问题解决了吗，如果没有解决，请看我下面的总结提示，希望对你有所帮助。

想请教下安卓下该如何修改？

**Comment by LambooZ** [comment]
请问Mac端遇到同样的问题（user not exists）如何解决？不清楚在哪里设置bcuss

**Comment by xingjohn** [comment]
> 请问Mac端遇到同样的问题（user not exists）如何解决？不清楚在哪里设置bcuss

我对mac系统不熟练，这个http://tool.cccyun.cc/tool/bduss/index.html也许可以帮助你。

**Comment by Declarcall** [comment]
https://github.com/iikira/BaiduPCS-Go/issues/387#issuecomment-422723027
```
./BaiduPCS-Go config set -appid 309847
```
新的appid 309847 可用，设置了下就一切OK 了
