### ISSUE TITLE
遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists

### ISSUE THREAD

**Issue by MiaoSu** [iikira/BaiduPCS-Go#417]
mac的系统
更改了 appid 为 266719 还是不起作用。

**Comment by juvevood** [comment]
Archlinux 3.5.5版本也报这个错

**Comment by cutecamel** [comment]
说白了，百度加了个cookie验证，如果你不久前登录过，再用这个PCS，cookie不一致就出错了。解决方法把pcs_config.json中的参数按照浏览器中的填好就ok了。
"bduss": "浏览器的",
"ptoken": "浏览器的",
"stoken": "浏览器的",
 "appid": [`[见#387]`](https://github.com/iikira/BaiduPCS-Go/issues/387#issuecomment-422723027)
"user_agent": "浏览器的“,

**Comment by juvevood** [comment]
> 说白了，百度加了个cookie验证，如果你不久前登录过，再用这个PCS，cookie不一致就出错了。解决方法把pcs_config.json中的参数按照浏览器中的填好就ok了。
> "bduss": "浏览器的",
> "ptoken": "浏览器的",
> "stoken": "浏览器的",
> "appid": [`[见#387]`](https://github.com/iikira/BaiduPCS-Go/issues/387#issuecomment-422723027)
> "user_agent": "浏览器的“,

解决了.赞一个!

**Comment by MiaoSu** [comment]
请教一下pcs_config.json这个文件在哪里？

**Comment by imleafz** [comment]
> 请教一下pcs_config.json这个文件在哪里？

进入baidu-pcs后输入env

**Comment by cutecamel** [comment]
> 于是我按照上面的加了之后并用工具找到这些参数后，pcs_go打不开了提示我
> `ATAL ERROR: config file error: config contents parse error`
先登录，pcs_config.json中会自动生成这些参数，再填浏览器中的

**Comment by MiaoSu** [comment]
我搞定了，谢谢谢谢谢谢各位大大们 ，啊哈哈哈哈们终于出来了

**Comment by MiaoSu** [comment]
> 器

恩，我删除了json文件，它自己有重新生成了一个，里面就啥都有了~！谢谢😊

**Comment by cutecamel** [comment]
> > > 请教一下pcs_config.json这个文件在哪里？
> > 
> > 
> > 进入baidu-pcs后输入env
> 
> 非常感谢，我找到了所在位置了，我的文件里没有:
> "bduss": "浏览器的",
> "ptoken": "浏览器的",
> "stoken": "浏览器的",
> "appid":
> "user_agent": "浏览器的“,这些参数，
> 于是我按照上面的加了之后并用工具找到这些参数后，pcs_go打不开了提示我
> `ATAL ERROR: config file error: config contents parse error`

注意编码，UTF8

**Comment by liguoqinjim** [comment]
我浏览器里面没看到ptoken，就没有改。
测试可用

**Comment by MiaoSu** [comment]
> 我浏览器里面没看到ptoken，就没有改。
> 测试可用

http://tool.cccyun.cc/tool/bduss/index.html
我用的这个

**Comment by javmain** [comment]
@MiaoSu 这个网站是哪里来的，安全吗？

**Comment by MiaoSu** [comment]
之前回复里的。安全不知道




| |
AlanUi@163.com
|
|
邮箱：alanui@163.com
|
在2018年09月27日 15:33，Javmain 写道：

@MiaoSu 这个网站是哪里来的，安全吗？

**Comment by javmain** [comment]
@MiaoSu 在浏览器中没发现 ptoken ，发现三个 stoken。这是什么问题。

**Comment by javmain** [comment]
ptoken 是不需要设置吗？明白了。stoken 怎么取。

**Comment by xjxj1** [comment]
我是按照以上都操作了，还是不管用，mac系统

**Comment by boris1993** [comment]
> ptoken 是不需要设置吗？明白了。stoken 怎么取。

我浏览器里ptoken也没有，就没修改

三个stoken的值应该是一样的，只是域名不同，如果有不一样的就重新登陆一下

> 我是按照以上都操作了，还是不管用，mac系统

放出错误信息才能帮你解决问题

**Comment by MiaoSu** [comment]
mac系统（我按照我遇到的操作来的），总结了一下上面大大给出的方法：

1.进入baidu-pcs后输入env，找到【pcs_config.json】文件，把它删掉。
2.打开PCS-go，再回到刚才包含有【pcs_config.json】的文件夹，发现重新生成了一个新的json文件。退出PCS-go。
3.根据 http://tool.cccyun.cc/tool/bduss/index.html 这网站（安全性暂不知道），可以找到你的bduss,ptoken,stoken的值。
4.打开新生成的pcs_config.json，把从网站上生成的你的值填写进去保存。
5.再次打开PCS-go，问题基本就解决了。

**Comment by cutecamel** [comment]
> ptoken 是不需要设置吗？明白了。stoken 怎么取。

ptoken是SCRC项，不填也可行。其他的有
![20180927162502200](https://user-images.githubusercontent.com/25879988/46133505-48033f00-c273-11e8-84f3-bc02ef40c990.png)
![20180927162540255](https://user-images.githubusercontent.com/25879988/46133513-4a659900-c273-11e8-8508-65c350c05fdb.png)

**Comment by blackcater** [comment]
- Download this version

> https://ci.appveyor.com/project/iikira/baidupcs-go/build/138

- `config set -appid=266719`

It works for me!

https://github.com/iikira/BaiduPCS-Go/issues/399#issuecomment-423703891

**Comment by huyi122** [comment]
> 说白了，百度加了个cookie验证，如果你不久前登录过，再用这个PCS，cookie不一致就出错了。解决方法把pcs_config.json中的参数按照浏览器中的填好就ok了。
> "bduss": "浏览器的",
> "ptoken": "浏览器的",
> "stoken": "浏览器的",
> "appid": [`[见#387]`](https://github.com/iikira/BaiduPCS-Go/issues/387#issuecomment-422723027)
> "user_agent": "浏览器的“,

厉害！厉害！我还以为不能用了呢

**Comment by HaoweiCh** [comment]
我就改了 一下 useragent 就能用了。。。没有这么复杂的。。。，，不过也是666

**Comment by zzzop** [comment]
> 我就改了 一下 useragent 就能用了。。。没有这么复杂的。。。，，不过也是666

请问你是直接用bduss登陆的吗，还是账号密码
