### ISSUE TITLE
删除部分Microsoft Visual C++ 运行库后，闪退

### ISSUE THREAD

**Issue by Niubaby1** [iikira/BaiduPCS-Go#419]
求教我。
BaiduPCS-Go-3.55
需要哪些Microsoft Visual C++库。
win10，版本号1809，系统版本17763.1 [Windows 10 Insider Preview 10.0.17763.1(rs5_release)]

**Comment by pongfcnkl** [comment]
删这玩意干啥？

**Comment by Niubaby1** [comment]
删除别的软件时手贱了。
重新安装Microsoft Visual C++ 2003、2005、2008、2012、2013、2017，X86_X64。
仍然闪退。
该怎么解决？

**Comment by iuimm** [comment]
为什么我还是旧版本的提示 获得错误啊

**Comment by iikira** [comment]
程序并不依赖那些运行库，或许是别的原因造成的？
打开cmd，把BaiduPCS-Go.exe拖进去执行，应该可以看到错误信息

**Comment by iikira** [comment]
这个问题和运行库无关
