### ISSUE TITLE
多个下载，第二个卡死

### ISSUE THREAD

**Issue by qiuranke** [iikira/BaiduPCS-Go#42]
centos7 默认安装,下载一个目录或者下载多个文件时，卡死无反应…

**Comment by iikira** [comment]
怎么个卡法，是下载一直没进度还是下载到最后速度变成0……

**Comment by qiuranke** [comment]
一直都没进度…

**Comment by iikira** [comment]
下载其他的文件也是这样吗?
以前也有好多人反馈这个问题，不过，我测试不出来……

**Comment by qiuranke** [comment]
1：我一次性的下载一个目录，提示有多个下载任务，一个下载完成后，第二提示开始，就是卡死状态，等了很久都没动。。
2：我同时下载两个压缩包，效果如上；
感觉应该是线程的问题，不知道哪里卡死了，对go还不是太熟悉。另外，建议可以增加多个任务可以同时下载。

**Comment by qiuranke** [comment]
我再多试几次，如果没有重现的话，就close了…

**Comment by iikira** [comment]
有时间还得测试一下下载……
另外"多个任务可以同时下载"，有了多线程下载，这个就没必要了……电脑估计会吃不消，而且终端下也不好输出进度和排版……

**Comment by qiuranke** [comment]
又刻意的测试下，发现没问题了，再发现了再反馈…可以通过多打开几个putty来实现多任务下载。还有，非常感谢…

**Comment by qiuranke** [comment]
这个问题可以归类为，下载的过程中突然没有速度

**Comment by iikira** [comment]
emmm……好吧

**Comment by iikira** [comment]
尝试修复长时间卡死不动的bug... [#af2f9d0](https://github.com/iikira/BaiduPCS-Go/commit/af2f9d07dae13d5ee5c9232bbe2f7091d15d28c4)
你可以试着编译运行程序, 看一下效果怎么样...
