### ISSUE TITLE
下载大文件速度基本不超过100K每秒，下载300M的文件需要两个小时

### ISSUE THREAD

**Issue by effzmt** [iikira/BaiduPCS-Go#420]
下载大文件速度基本不超过100K每秒，下载300M的文件需要两个小时
是被限速了吗？那跟百度自己客户端的下载速度没区别了

**Comment by gt-sun** [comment]
+1

**Comment by BadBoy1314love** [comment]
+1

**Comment by Dreametion** [comment]
+2

**Comment by SeAL80s** [comment]
自己网速问题吧。基本都在2-3M/s左右。或者自己参数设置问题

**Comment by BadBoy1314love** [comment]
我尝试了一下，在不同的局域网下，速度确实会有不同，有几倍的差距，但是。。。
也就是从200kb/s到了1mb/s多点的样子

**Comment by Pezeo** [comment]
稳定100KB没毛病

**Comment by iikira** [comment]
并不保证速度的!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

**Comment by BadBoy1314love** [comment]
应该只是局域网的原因，反正我现在已经完全不限速了
