### ISSUE TITLE
下载不了了

### ISSUE THREAD

**Issue by Etoakor** [iikira/BaiduPCS-Go#421]
获取路径信息错误, 获取文件/目录的元信息 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation, 路径: /p3

**Comment by mi78108** [comment]
我这里也是     获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by mi78108** [comment]
已解决 刚看到文档 config set -appid 266719

**Comment by wyu0725** [comment]
这个appid用不了了

**Comment by iikira** [comment]
和#387 一样，关闭了

**Comment by Smallbright8** [comment]
获取路径信息错误, 获取文件/目录的元信息, 遇到错误, 远端服务器返回错误, 代码:
 4, 消息: No permission to do this operation
