### ISSUE TITLE
下载速度疯狂跳跃极不稳定

### ISSUE THREAD

**Issue by whetherTsmile** [iikira/BaiduPCS-Go#422]
最快的时候慢速妥妥的，
最慢的时候甚至10K/S，
两个极端速度中间相差不到几秒

**Comment by MingqiHuang** [comment]
缓存大小和线程数设置不当会出现这种情况。请调整一下缓存大小（注意内存占用）和线程数（不要太大，也不能太小）。

**Comment by iikira** [comment]
并不保证速度的!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)
