### ISSUE TITLE
liner: invalid prompt

### ISSUE THREAD

**Issue by supeng123** [iikira/BaiduPCS-Go#423]
现在每次用terminal打开直接成下面的样子了，是我设置有问题吗？
![image](https://user-images.githubusercontent.com/14172633/46206800-d0f3a680-c357-11e8-80b5-069ddff55821.png)

**Comment by hlsky1988** [comment]
mac 没有问题啊，刚还在用

**Comment by supeng123** [comment]
为啥它每次自动跳到【process completed】

**Comment by iikira** [comment]
打开终端，手动定位程序并执行试一试，不要直接双击执行..

**Comment by iikira** [comment]
问一下 你的百度用户名是否有特殊字符？

**Comment by supeng123** [comment]
没有，是正常的纯英文字符
