### ISSUE TITLE
文件名有非GBK字符时会下载失败

### ISSUE THREAD

**Issue by Ouroboros** [iikira/BaiduPCS-Go#424]
`[170906] TVアニメ「僕のヒーローアカデミア」 2nd オリジナル・サウンドトラック (FLAC+CUE+TIFF).rar`

比如这个文件名里的`・`

```
BaiduPCS-Go:/ $ d "[170906] TVアニメ「僕のヒーローアカデミア」 2nd オリジナル・サウンドトラッ ク (FLAC+CUE+TIFF).rar"

[0] 提示: 当前下载最大并发量为: 100, 下载缓存为: 30000
[1] 加入下载队列: /[170906] TVアニメ「僕のヒーローアカデミア」 2nd オリジナル・サウンドトラッ ク (FLAC+CUE+TIFF).rar
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

```

**Comment by liuyang007** [comment]
通配符啊

**Comment by Ouroboros** [comment]
这算什么办法，根本就是绕过了bug，要是绕过bug我改名不就好了

**Comment by apocelipes** [comment]
试试tab键的自动补全的转义。
不过我一直未遇到过类似问题，希望补全信息，包括系统，golang和BaiduPCS-Go版本

**Comment by Ouroboros** [comment]
> 试试tab键的自动补全的转义。
> 不过我一直未遇到过类似问题，希望补全信息，包括系统，golang和BaiduPCS-Go版本

我知道问题出在哪了, 在win下cmd窗口不够宽的时候会自动换行, 像这样

```
  20     710.16MB  2018-10-06 16:53:20  [170906] TVアニメ「僕のヒーローアカデミア」 2nd オリジナル・サウンドトラッ 
```
```
ク (FLAC+CUE+TIFF).rar
```

会在第一行最后多出一个空格, 而我的文件名是从cmd里选取复制的, 所以也多了个空格
`ンドトラッ ク (FLAC+CUE+TIFF)`
在`ッ` 和 `ク` 中间

删掉那个`・`之后, 换行的位置刚好又不会加空格, 所以造成是这个字符引起的错觉

这应该是cmd的bug, 只有某些字符会增加额外的空格
