### ISSUE TITLE
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

### ISSUE THREAD

**Issue by LZQCN** [iikira/BaiduPCS-Go#429]
输入ls指令后出现：

> 获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by zghbssjzzhx** [comment]
+1
ls显示：
`获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation`

download显示：
`获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation`

**Comment by ftc300** [comment]
+1

**Comment by anshingy** [comment]
我的也是，是不是被封了？

**Comment by fofen** [comment]
+1

**Comment by DGDL** [comment]
+1

**Comment by DGDL** [comment]
没登陆按 ls 也一样

**Comment by bingdianfeishui** [comment]
[#387](https://github.com/iikira/BaiduPCS-Go/issues/387)
原来默认的app_id失效了,升级到新版,然后更新一下app_id
https://github.com/iikira/BaiduPCS-Go/releases

**Comment by jarryyen** [comment]
+1
ls显示：
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

download显示：
获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by jarryyen** [comment]
> [#387](https://github.com/iikira/BaiduPCS-Go/issues/387)
> 原来默认的app_id失效了,升级到新版,然后更新一下app_id, 见v3.5.6的更新日志
> https://github.com/iikira/BaiduPCS-Go/releases/tag/v3.5.6

已经更新了,问题依旧.....

**Comment by jarryyen** [comment]
> +1
> ls显示：
> `获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation`
> 
> download显示：
> `获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation`

删除BaiduPCS-Go的配置文件就可以了,Mac用户的配置文件在 /User/****/.config/BaiduPCS-Go/ ,删除这个文件夹就可以了

**Comment by YigaoFan** [comment]
> > [#387](https://github.com/iikira/BaiduPCS-Go/issues/387)
> > 原来默认的app_id失效了,升级到新版,然后更新一下app_id, 见v3.5.6的更新日志
> > https://github.com/iikira/BaiduPCS-Go/releases/tag/v3.5.6
> 
> 已经更新了,问题依旧.....

更新日志里面写了：更换失效的默认app_id, 对于不是全新安装此程序的用户, 仍然需要手动更改默认的app_id。如何手动也写了。

**Comment by FYBTT** [comment]
进入到BaiduPCS-Go以后,输入env,就能看到用户的配置文件,恩,删除即可
BAIDUPCS_GO_CONFIG_DIR="/home/bear/.config/BaiduPCS-Go"

**Comment by zlcbs** [comment]
## 解决错误代码4, No permission to do this operation
```
BaiduPCS-Go config set -appid 266719

**Comment by cute-angelia** [comment]
> config set -appid 266719

这个是什么 appid, 个人可以申请吗, 是否个人申请稳定一些

**Comment by iikira** [comment]
和#387 一样，关闭了
