### ISSUE TITLE
请教“以下文件可能无法导出:”是什么原因？

### ISSUE THREAD

**Issue by isaac850904** [iikira/BaiduPCS-Go#430]
谢谢iikira为我们提供的baidupcs-go，真的很好用。

我最近遇到一个问题，就是我一个目录里有2000个文件，基本都是同时上传的，使用export命令，76个文件正常，其余都在“以下文件可能无法导出:”这条线以下。

并且我试了一下，只有这76个文件可以秒传到其他网盘，其余1900多个文件使用“rapidupload”命令，都是说“秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 31079, 消息: 秒传文件失败”

请问这是什么原因？有什么办法可以解决吗？

谢谢！

**Comment by isaac850904** [comment]
太感谢了！！
请问我需要下载新的版本才能使用这些功能吗？我看github上的最新版本还是v3.5.6
<https://github.com/iikira/BaiduPCS-Go/commit/438052bf650ace2038d824cafcc33881e0e3f47e>


iikira <notifications@github.com> 于2018年11月12日周一 上午10:25写道：

**Comment by iikira** [comment]
暂时不能用了, #537
