### ISSUE TITLE
下载完毕如何关闭检验文件有效性 

### ISSUE THREAD

**Issue by 674273563** [iikira/BaiduPCS-Go#438]
每次下完检验文件时 电脑会出现卡顿  估计是硬盘高速读写 老硬盘会特别明显 如何关掉检验文件有效性？
而且文件已经下完 就算检验文件失败 但文件已下好  就算不检验也无所谓 该解压解压 该看就看 如果无法解压 无法观看 也还是要重下

**Comment by TiDragon** [comment]
MD5跟服务器对比，验证错误会删除已下载文件并重下，然后继续再完成后验证，成了死循环。
