### ISSUE TITLE
获取文件/目录的元信息: 遇到错误代码，31021

### ISSUE THREAD

**Issue by songying2013** [iikira/BaiduPCS-Go#447]
获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31021, 消息: network error

**Comment by yuaoze** [comment]
同样错误

**Comment by Autliety** [comment]
same issues reported.

**Comment by BadBoy1314love** [comment]
获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31296, 消息: internal error

**Comment by liyanhou** [comment]
> 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31296, 消息: internal error

+1

**Comment by fofen** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31209, 消息: internal error

**Comment by ericjwg** [comment]
现在已经好了。百度那边的问题。

**Comment by BadBoy1314love** [comment]
我现在也好了

**Comment by fofen** [comment]
是的，已经好了。百度那边的问题。

**Comment by Logmos** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by Usernamezhx** [comment]
again

**Comment by iikira** [comment]
是服务器的问题

**Comment by zzzop** [comment]
刚办续费会员就出现这个，尴尬
