### ISSUE TITLE
fg命令无法使用嘛？

### ISSUE THREAD

**Issue by xerxesnoPT** [iikira/BaiduPCS-Go#449]
树莓派arm v7 3.5.6版本 .开tmux用bg后台下载. 想用fg命令查看下载进度发现无法使用。issue #202 有提到新增fg跟bg。但是fg无法使用

**Comment by xerxesnoPT** [comment]
嗯 我现在下载的话就是使用 ```download filename --bg``` 这样的.然后使用bg命令后只能看到当前任务
类似 
```sh
Task ID  FILES
1        file1
2        file2
```
这样。使用什么命令能把这些任务调到前台显示详细下载信息？

**Comment by apocelipes** [comment]
作者暂时不准备实现fg，因为没有明确的需求理由，之前我的pr里有过讨论。
你可以使用非交互式命令进行前台下载，目前后台的任务是无法调度回前台的

**Comment by xerxesnoPT** [comment]
好的。感谢

**Comment by Bubbleinpit** [comment]
> 作者暂时不准备实现fg，因为没有明确的需求理由，之前我的pr里有过讨论。
> 你可以使用非交互式命令进行前台下载，目前后台的任务是无法调度回前台的

那么download命令的--bg参数开启后台下载后，如何查看当前的下载速度呢？
