### ISSUE TITLE
远端服务器返回错误

### ISSUE THREAD

**Issue by ckbkdj** [iikira/BaiduPCS-Go#450]
远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by ckbkdj** [comment]
window平台下

**Comment by imcom** [comment]
+1

**Comment by imcom** [comment]
尝试了先 logout, 浏览器重新登录, 用新的 bduss 再 登录, 也不可以, 应该是被限制了

**Comment by jypjypjypjyp** [comment]
最新版解决了。详细请看#387

**Comment by imcom** [comment]
升级到最新版, 然后更新一下 appid 就好了

**Comment by imcom** [comment]
谢谢~~~
