### ISSUE TITLE
[报错]安卓Termux源的Hash entry缺失

### ISSUE THREAD

**Issue by thanksshu** [iikira/BaiduPCS-Go#451]
报错内容：
"W:No Hash entry in Release file /data/data/com.termux/files/usr/var/lib/apt/lists/partial/termux.iikira.com_dists_stable_Release"
请问这要怎么解决呢？

**Comment by Lurito** [comment]
去 Releases 里直接下载安装

**Comment by thanksshu** [comment]
@Lurito 好的，谢谢了。
