### ISSUE TITLE
大文件上传异常

### ISSUE THREAD

**Issue by desmond-li** [iikira/BaiduPCS-Go#454]
v3.5.6-windows-x64
分别测试上传900M和25G的文件，在无秒传时都出现上传量减少的情况，即前一秒上传了100M，下一秒变成98M，反复几次后才会继续增加，但上传速度都在1-2M/s。900M的花了40分钟才传完，25G文件上传量一直在130M上下波动，无法上传，但不会有任何错误提示。

![1](https://user-images.githubusercontent.com/19582804/47014838-f6691880-d17d-11e8-8351-7b681e2e99ba.png)
![2](https://user-images.githubusercontent.com/19582804/47014840-f701af00-d17d-11e8-85f6-a0db9f64b2d5.png)

**Comment by landall** [comment]
我这里也遇到了类似的情况，上传24GB的文件，在16G进度时突然抖动并不断倒退到15.4G左右，然后开始波动。这是分片传送失败整体进度调整还是其他的问题？

**Comment by desmond-li** [comment]
> 
> 
> 我这里也遇到了类似的情况，上传24GB的文件，在16G进度时突然抖动并不断倒退到15.4G左右，然后开始波动。这是分片传送失败整体进度调整还是其他的问题？

你还能传十几G，我每次只传到100M左右就出现问题，而且大文件分片上传md5可能对不上，等新方法出现吧，现在的上传模式对大文件不友好

**Comment by landall** [comment]
> > 我这里也遇到了类似的情况，上传24GB的文件，在16G进度时突然抖动并不断倒退到15.4G左右，然后开始波动。这是分片传送失败整体进度调整还是其他的问题？
> 
> 你还能传十几G，我每次只传到100M左右就出现问题，而且大文件分片上传md5可能对不上，等新方法出现吧，现在的上传模式对大文件不友好

我最终用了大概5倍左右的流量成功上传上去了，然后md5修正失败，下次再传同一个文件时无法正确秒传。传上去的文件目前看是正确的。

**Comment by iikira** [comment]
新增设置上传最大并发量, 0007020252c3d84f2227cad0f65a88e98c4b7e3a
出现这个问题，可能是因为以前的上传最大并发量，使用了下载最大并发量的配置，并发量太高就导致上传异常。先关闭了，如果有问题再打开
