### ISSUE TITLE
树梅派使用BaiduPCS-Go-v3.5.6-linux-armv7新版本为什么无法正常使用？

### ISSUE THREAD

**Issue by nongbin** [iikira/BaiduPCS-Go#455]
rt
[树梅派的登陆之后不显示网盘的路径，树梅派是armv7架构，我使用的版本是否是错误的！无法下载文件提示]
“[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在任务结束, 时间: 1s, 数据总量: 0B
”``

**Comment by nongbin** [comment]
![2018-10-16-202349_641x175_scrot](https://user-images.githubusercontent.com/24525140/47016534-8b6e1080-d182-11e8-9201-02d4af0e05c6.png)

**Comment by nongbin** [comment]
![2018-10-16-202411_304x32_scrot](https://user-images.githubusercontent.com/24525140/47016828-4e564e00-d183-11e8-93f1-0137633652c7.png)

**Comment by nongbin** [comment]
![2018-10-16-203550_622x89_scrot](https://user-images.githubusercontent.com/24525140/47016888-78a80b80-d183-11e8-9edd-e2d7195cb869.png)

**Comment by iikira** [comment]
`./BaiduPCS-Go ls` 查看目录下的文件
你使用的版本没有错，出现这个错误的原因是网盘的目录下没有这个文件
