### ISSUE TITLE
cookie是放在哪里？

### ISSUE THREAD

**Issue by daiaji** [iikira/BaiduPCS-Go#457]
我打算丢u盘当便携版用
cookie位置能设定吗？
或者弄个便携的选项？

**Comment by Lurito** [comment]
用 `env` 命令查看程序环境变量，其中的 `BAIDUPCS_GO_CONFIG_DIR` 项的值就是配置文件的位置（Windows 系统下默认是 `%APPDATA\BaiduPCS-Go`），其中的 `pcs_config.json` 中就保存了 BDUSS 等信息。

将配置文件复制到程序目录后，程序会优先读取程序目录中的配置文件。重启程序后执行 `env` 命令，若 `BAIDUPCS_GO_CONFIG_DIR` 变更为程序目录，说明操作成功。

**Comment by daiaji** [comment]
@Lurito BaiduPCS-Go:/$ config set --savedir %HOMEPATH%\Downloads
        名称                      值                   建议值
           描述
  appid              266719                                        百度 PCS 应用
ID
  enable_https       false                              true       启用 https

  user_agent         netdisk;8.3.1;android-android                 浏览器标识

  cache_size         30000                          1024 ~ 262144  下载缓存, 如
果硬盘占用高或下载速度慢, 请尝试调大此值
  max_parallel       100                              50 ~ 500     下载最大并发
量
  max_download_load  1                                  1 ~ 5      同时进行下载
文件的最大数量
  savedir            %HOMEPATH%Downloads                           下载文件的储
存目录

保存配置成功!
这是变量不能用 还要反义？

**Comment by Lurito** [comment]
> @Lurito
> 
> ```
> BaiduPCS-Go:/$ config set --savedir %HOMEPATH%\Downloads
>         名称                      值                   建议值
>            描述
>   appid              266719                                        百度 PCS 应用
> ID
>   enable_https       false                              true       启用 https
> 
>   user_agent         netdisk;8.3.1;android-android                 浏览器标识
> 
>   cache_size         30000                          1024 ~ 262144  下载缓存, 如
> 果硬盘占用高或下载速度慢, 请尝试调大此值
>   max_parallel       100                              50 ~ 500     下载最大并发
> 量
>   max_download_load  1                                  1 ~ 5      同时进行下载
> 文件的最大数量
>   savedir            %HOMEPATH%Downloads                           下载文件的储
> 存目录
> 
> 保存配置成功!
> ```
> 这是变量不能用 还要反义？

这个应该是把 `\` 当做转义符号了，而程序中制定下载目录时，需要把 Windows 下的反斜杠 `\` 替换为斜杠 `/` 。

另外，经试验，（至少在 Windows Server 2003 SP2 系统上）下载目录并不支持 `%HOMEPATH%` 变量。如果使用这一变量，程序会将文件下载到程序目录下的 %HOMEPATH% 文件夹。

所以应该设置绝对路径：

```
config set --savedir C:/Users/Administrator/Downloads
```

如果使用的是 Windows XP/2003 或更早的系统，路径中会含有空格，可以用转义反斜杠转义 `\` ，或用引号引起来：

```
config set --savedir 'C:/Documents and settings/Administrator/Downloads'
或
config set --savedir C:/Documents\ and\ settings/Administrator/Downloads
```

在设置目录或者下载文件的时候，常常会遇到路径中带有空格或其他特殊符号（如 `[ ]`）的情况，都可以用上述两种方法之一来解决。

**Comment by iikira** [comment]
2楼正解

**Comment by iikira** [comment]
2楼正解

**Comment by daiaji** [comment]
@iikira 路径不能用变量吗？
这么搞 便携基本上就再见了……

**Comment by Lurito** [comment]
> @iikira 路径不能用变量吗？
> 这么搞 便携基本上就再见了……

可以设为相对于程序的路径，不输绝对路径即可。

**Comment by daiaji** [comment]
@Lurito 不
我不希望下载文件夹和程序在一个盘符……
相对路径帮不了我

**Comment by Lurito** [comment]
> @Lurito 不
> 我不希望下载文件夹和程序在一个盘符……（哪一层相对路径都在U盘里……）
> 相对路径帮不了我

创建一个包含以下内容的 bat 文件：

``` batch
@echo off
./BaiduPCS-Go.exe set config set --savedir %HOMEPATH%/Downloads > nul
./BaiduPCS-Go.exe
```

然后每次插入新电脑的时候用执行这个脚本就行了。

**Comment by Lurito** [comment]
写出来了：

创建一个 vbs 文件，名字随便：

``` vbs
Set oShell = CreateObject( "WScript.Shell" )
sHomeDir=Replace(oShell.ExpandEnvironmentStrings("%USERPROFILE%"),"\","/")
oShell.Run("bdyun.bat " & sHomeDir), 1, TRUE
```

再在同一个目录下创建一个 bat，名字要和上面第三行一样：

``` batch
@echo off
.\BaiduPCS-Go.exe config set --savedir %1/Downloads > nul
.\BaiduPCS-Go.exe
```

然后每次插入新电脑的时候用执行 vbs 脚本就行了。

----

为什么要用两个脚本呢？其实这不是我本意。其实本来想通过这样一个 vbs 一步到位的：

``` vbs
Set oShell = CreateObject( "WScript.Shell" )
sHomeDir=Replace(oShell.ExpandEnvironmentStrings("%USERPROFILE%"),"\","/")

oShell.Run(".\BaiduPCS-Go.exe config set --savedir " & sHomeDir & "/Downloads > nul"), 1, TRUE
oShell.Run(".\BaiduPCS-Go.exe"), 1, TRUE
```

但无奈，第三行的窗口总是一闪而过，下载目录也没改成，不知道是哪里出了问题。希望有懂 vbs 的能指教一下，不胜感激。
