### ISSUE TITLE
可以增加一个直接下载别人分享链接(公开和私密的分享链接)的功能吗? 就是不用先保存到自己的百度云再下载

### ISSUE THREAD

**Issue by liuzhuoling2011** [iikira/BaiduPCS-Go#459]

**Comment by LondyGhost** [comment]
这怎么可能  又不是下载器  这个是属于网页百度网盘命令行模式

**Comment by zwczou** [comment]
实现 别人分享保存到自己网盘的功能就可以了

**Comment by yoli799480165** [comment]
我觉得这个功能太有必要了，建议加入。我是后台作业系统，自动抓取分享链接自动下载到本地的。现在都是先要导入到自己的网盘里，然后才能下载到本地，实在麻烦。虽然我自己弄了个网页自动导入，但是还是希望作者加入这个功能吧。

**Comment by iikira** [comment]
此问题已记录, #444, (暂无计划)
