### ISSUE TITLE
能不能实现从挂载的google drive中把文件上传到百度云

### ISSUE THREAD

**Issue by 1405040117** [iikira/BaiduPCS-Go#461]
我在google drive存了很多文件，最近需要把里面的文件导入到百度云，昨天我尝试了把google drive通过rclone挂载在到我的VPS上，然后把挂载的本地盘中的文件进行上传，但是上传百度云的时候一直显示0的速度，不知道是不是这样的操作这个脚本不支持。

**Comment by iikira** [comment]
猜测rclone不能提供完整的文件操作指令，例如 pread等
打开调试，可以看到错误信息
```
BaiduPCS-Go -verbose upload ...
```

**Comment by SCKC1** [comment]
多问一句，有没有把百度云上传到google drive的方法？

**Comment by 1405040117** [comment]
> 多问一句，有没有把百度云上传到google drive的方法？

先把百度云里面的下载到VPS上，再上传google drive，再把vps上的文件删除，上传google drive的脚本的话github上很多，我能想到的就是这种方法。

**Comment by zzzop** [comment]
小文件应该可以，我传过。不过秒传的时候应该是相当于把文件下载下来校验了一遍，太多的话没试过，可能需要调整挂载的参数吧

**Comment by 1405040117** [comment]
> 猜测rclone不能提供完整的文件操作指令，例如 pread等
> 打开调试，可以看到错误信息
> 
> ```
> BaiduPCS-Go -verbose upload ...
> ```

对了，还有一个问题，我用SSH客户端连接上之后启动上传，关闭SSH客户端连接，这个上传进程好像会自动停止掉。

**Comment by 1405040117** [comment]
> 小文件应该可以，我传过。不过秒传的时候应该是相当于把文件下载下来校验了一遍，太多的话没试过，可能需要调整挂载的参数吧

应该是，我等下再看看rclone的文档，我测试的文件是20G。。。
