### ISSUE TITLE
空的文本文件无法下载

### ISSUE THREAD

**Issue by Songxuewen** [iikira/BaiduPCS-Go#462]
[48] 检验文件有效性出错, 该文件校验失败, 文件md5值与服务器记录的不匹配, 重试 3/3
[48] 已删除校验失败的文件

可能是因为MD5验证问题

**Comment by Songxuewen** [comment]
没有更多信息，就提示MD5有问题，估计空文件MD5验证会出错

**Comment by iikira** [comment]
空文件是0字节的文件吗，发一下截图

**Comment by sukeyisme** [comment]
[3] 下载文件错误, Content-Length is zero

任务结束, 时间: 22.321s, 数据总量: 0B
以下文件下载失败:

**Comment by sukeyisme** [comment]
空文件

**Comment by sukeyisme** [comment]
@iikira 空文件能下载下来吗？
