### ISSUE TITLE
建议增加文件改名功能

### ISSUE THREAD

**Issue by SCKC1** [iikira/BaiduPCS-Go#464]
建议增加文件改名功能，逐一改名、批量改名，不知道能否实现。

**Comment by Lurito** [comment]
要将当前目录下的 [SomeSubTeam]example.mp4 重命名为 example.mp4，可以通过以下命令实现：

```
BaiduPCS-Go mv '[SomeSubTeam]example.mp4' example.mp4
```

批量改名功能可以结合 Shell 或 Batch 实现。如要将当前目录下的 example1.mp4, example2.mp4 ... example9.mp4 九个文件重命名为 [SomeSubTeam]example*.mp4，在 Linux 下可以直接在 Shell 中输入如下代码：

``` bash
for i in {1..9}; do
    BaiduPCS-Go mv "example${i}.mp4" "[SomeSubTeam]example${i}.mp4"
done
```

在 Windows 系统下可以在 CMD 中输入：

``` batch
@echo off
set i=1
:bk

BaiduPCS-Go.exe mv "example%i%.mp4" "[SomeSubTeam]example%i%.mp4"
if %i% lss 9 (
    set /a i+=1
    goto bk 
)
```

**Comment by SCKC1** [comment]
谢谢！
