### ISSUE TITLE
经常性的下载出错

### ISSUE THREAD

**Issue by rootpophome** [iikira/BaiduPCS-Go#468]
403 Forbidden
以前是不会这样的
可能是屏蔽了api

**Comment by xjzsq** [comment]
貌似是直接把百度云账号给拉黑了...  
我在其他的下载工具上登上账号就显示账号已被限制  
换个账号就没问题

**Comment by rootpophome** [comment]
悲剧了...
真有可能是直接拉黑....
不过文件夹的话还是可以直接下载
总之先谢了

**Comment by iikira** [comment]
和#460 一样，关闭了
