### ISSUE TITLE
好东西 一定要挺住啊

### ISSUE THREAD

**Issue by mi78108** [iikira/BaiduPCS-Go#47]
很好的项目，解决了linux 下的百度网盘很多的问题，用起来还那么的舒服，希望一定保持下去啊!

**Comment by iikira** [comment]
谢谢支持

**Comment by CyshallChan** [comment]
闷声发大财，不要在公共的地方到处宣传就行了。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flash-egg** [comment]
好东西，必须star

**Comment by WencaiLi** [comment]
之家已经在宣传了
