### ISSUE TITLE
分享文件时如何设置提取码

### ISSUE THREAD

**Issue by isaac850904** [iikira/BaiduPCS-Go#471]
share s <文件/目录1> <文件/目录2> ...
请问只能不带密码分享文件吗？如何分享文件时带提取码？

谢谢

**Comment by iikira** [comment]
#243 有提到这个问题，请勿再开相同的issue

**Comment by isaac850904** [comment]
收到了，非常感谢！

iikira <notifications@github.com> 于2018年10月26日周五 上午8:56写道：
