### ISSUE TITLE
關於任務下載停止或對資料夾進行動作停止之可能原因

### ISSUE THREAD

**Issue by Ray941216** [iikira/BaiduPCS-Go#48]
我發現當一天對同一名稱資料夾進行下載超過某流量時，疑似伺服器會將電腦的ip ban 掉，會無法透過此程式進行動作，需要回到官方的軟體進行操作。
我想建議作者可能可以動態調低並行的數量，讓伺服器不會覺得是ddos 攻擊
另外關於app_id是否可能也是影響本問題的因素還無法驗證，我不知道這id是否有特別的設計，因此無法協助驗證

**Comment by iikira** [comment]
动态调低下载并发量……我想想……目前可通过set命令设置最大下载并发量. 另外我只知道app_id是百度pcs应用id, 这个值不对的话百度服务器拒绝一切服务……

**Comment by iikira** [comment]
……
这个下载接口比较特别，应该不是什么ddos攻击而是人家百度故意的限制，不让你用……

**Comment by Ray941216** [comment]
我感覺這個接口有點像是p2p的模式，如果同時對同一個伺服器發出大量請求（類似 DOS），伺服器應該會自動將這個ip ban掉，至於百度限制的話我覺得也是有可能⋯⋯
不過這倒是可以透過vpn更換ip來解決，我只是在想說看到很多人問了很類似的問題，想分享一下我看到的以及我的解法。
當然如果說動態的導向一些vpn，這樣是最完美的

**Comment by iikira** [comment]
不是很清楚……问一下，"無法透過此程式進行動作"怎么说，是下载到一半速度就变成0了吗，还是……

**Comment by Ray941216** [comment]
意思是我下指令後完全沒有輸出，隔一段時間會得到 forbidden 或是 timeout, 正常的回應時間應該不超過1分鐘，超過一分鍾的情況通常就是被ban 了

**Comment by iikira** [comment]
原来如此......这应该是程序的缺陷, 我尝试修复, af2f9d07dae13d5ee5c9232bbe2f7091d15d28c4, 70ada66289da26fba2d400d5b4f13e2e7a331a6f
你可以试着编译安装程序, 看看效果怎么样吧......

**Comment by Ray941216** [comment]
我認為程序應該是沒有缺陷，應該是被百度限制存取的可能性較大，透過ip 更換的手法可以解除問題，但是原本的ip 不知道實際會被ban多久，但我確定至少要相隔24小時

**Comment by iikira** [comment]
知道了，还得多多测试……

**Comment by iikira** [comment]
出行这种情况的原因可能是下载时程序过多重复建立网络连接造成的，新版本做了一些优化，现在不会经常碰到这种问题了吧

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
