### ISSUE TITLE
请教分享多个文件，如何有独立的分享链接？

### ISSUE THREAD

**Issue by isaac850904** [iikira/BaiduPCS-Go#483]
如有10个文件，用share s +10个文件路径，产生的是一个分享链接，里面含10个文件
请问想让有10个独立的分享链接，只能手动10次share s 文件路径吗？

能不能让软件一个文件分享完了再分享下一个？记得cmd下可以用“ & ”来连接2个命令，一个运行完后运行下一个，baidupcs-go有类似命令吗？

非常感谢你的付出！这软件太好用了！

**Comment by mu228** [comment]
> 如有10个文件，用share s +10个文件路径，产生的是一个分享链接，里面含10个文件
> 请问想让有10个独立的分享链接，只能手动10次share s 文件路径吗？
> 
> 能不能让软件一个文件分享完了再分享下一个？记得cmd下可以用“ & ”来连接2个命令，一个运行完后运行下一个，baidupcs-go有类似命令吗？
> 
> 非常感谢你的付出！这软件太好用了！

你能下载吗？速度怎么样？ID号是多少？换了好多不能用

**Comment by Lurito** [comment]
> 如有10个文件，用share s +10个文件路径，产生的是一个分享链接，里面含10个文件
> 请问想让有10个独立的分享链接，只能手动10次share s 文件路径吗？

是

> 能不能让软件一个文件分享完了再分享下一个？记得cmd下可以用“ & ”来连接2个命令，一个运行完后运行下一个，baidupcs-go有类似命令吗？

没有

**Comment by isaac850904** [comment]
请问可以增加多条命令接续运行这个功能吗？

谢谢！
