### ISSUE TITLE
[报错]安卓Termux下，在非根目录会出现无法使用Tab等的问题

### ISSUE THREAD

**Issue by thanksshu** [iikira/BaiduPCS-Go#484]
版本：
BaiduPCS-Go version v3.5.6

现象：
在Termux下启动BaiduPCS-Go，于非根目录（例如：“/我的资源”）按下“上箭头”或其他功能按键会打出“^[[A”等，导致无法正常使用。
好像有些目录还是好用的。

图示：
<img src="https://s1.ax1x.com/2018/10/28/ic5f78.jpg" alt="ic5f78.jpg" border="0" />

pcs_config.json:
"workdir": "/我的资源"                 
13   }
14  ],
15  "appid": 266719,                        
16  "cache_size": 60000,                     
17  "max_parallel": 128,                     
18  "max_download_load": 1,                  
19  "user_agent": "netdisk;8.3.1;android-and    roid",
 20  "savedir": "/sdcard/Download",
 21  "enable_https": true
 22 }

Verbose：
什么也没说…或许我并不会用…

**Comment by iikira** [comment]
字体太大了，缩放即可

**Comment by thanksshu** [comment]
@iikira 谢谢了，还真是这个问题，之前缩放得不够。
