### ISSUE TITLE
无法使用代理

### ISSUE THREAD

**Issue by iMcG33k** [iikira/BaiduPCS-Go#485]
在~/.zshrc中添加了如下内容:
alias proxy='export all_proxy=socks5://127.0.0.1:1086;http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;'
alias unproxy='unset all_proxy'

proxy之后用curl测试如下:
➜  ~ curl ip.cn
当前 IP: 211.254.***.** 来自: 韩国

版本:
BaiduPCS-Go-v3.5.6-darwin-osx-amd64

**Comment by Lurito** [comment]
#70

**Comment by iMcG33k** [comment]
@Lurito  
➜  ~ set HTTP_PROXY=socks5://localhost:1086
➜  ~ ./BaiduPCS-Go-v3.5.6-darwin-osx-amd64/BaiduPCS-Go
提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
BaiduPCS-Go:/ test$ ll
获取目录下的文件列表: 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?****: read tcp 172.16.*.**:54778->112.80.248.56:80: read: connection reset by peer
BaiduPCS-Go:/ test$ exit
➜  ~ set HTTP_PROXY=http://localhost:1087
➜  ~ ./BaiduPCS-Go-v3.5.6-darwin-osx-amd64/BaiduPCS-Go
提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
BaiduPCS-Go:/ test$ ll
获取目录下的文件列表: 网络错误, Get http://pcs.baidu.com/rest/2.0/pcs/file?****: read tcp 172.16.*.**:54809->112.80.248.56:80: read: connection reset by peer
BaiduPCS-Go:/ test$

**Comment by iikira** [comment]
已增加代理设置, 0007020252c3d84f2227cad0f65a88e98c4b7e3a

**Comment by 0ut0fcontrol** [comment]
编译最新版, 添加代理, 正常使用, 非常感谢.
```
BaiduPCS-Go config set --proxy=socks5://localhost:1080
```

**Comment by amaothree** [comment]
Incorrect Usage: flag provided but not defined: -proxy

**Comment by 0ut0fcontrol** [comment]
two -

**Comment by 0ut0fcontrol** [comment]
抱歉，我试了一下，-config和--config都可以。
我说的最新版并不是最新的realease，而是楼上作者commit之后的版本。
