### ISSUE TITLE
限速1mb???

### ISSUE THREAD

**Issue by WildBot000** [iikira/BaiduPCS-Go#486]
前几天403forbidden所以一个礼拜没敢动账号，但是现在下载东西无论是wifi还是4G好像速度都过不了1mb,我是不是被盯上了？

**Comment by Songxuewen** [comment]
> 403改ua可以解决，速度上不去可能是用的人多了，也可能你是被限速了，百度云会员真的是坑，不仅不能加速，而且还不能达到慢速，等以后工作了就买谷歌云盘了。

? 如何更改UA呢？

**Comment by iikira** [comment]
并不保证速度的!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

403的问题请到#460 讨论

**Comment by nicangtianws** [comment]
> > 403改ua可以解决，速度上不去可能是用的人多了，也可能你是被限速了，百度云会员真的是坑，不仅不能加速，而且还不能达到慢速，等以后工作了就买谷歌云盘了。
> 
> ? 如何更改UA呢？

config set -user_agent="Mozilla;5.0"

**Comment by nomil9** [comment]
> > > 403改ua可以解决，速度上不去可能是用的人多了，也可能你是被限速了，百度云会员真的是坑，不仅不能加速，而且还不能达到慢速，等以后工作了就买谷歌云盘了。
> > 
> > 
> > ? 如何更改UA呢？
> 
> config set -user_agent="Mozilla;5.0"

若上述无效，可试试下面这个
config set -user_agent="netdisk;8.12.9;android-android"

**Comment by lazyZ** [comment]
> 
> 
> > > > 403改ua可以解决，速度上不去可能是用的人多了，也可能你是被限速了，百度云会员真的是坑，不仅不能加速，而且还不能达到慢速，等以后工作了就买谷歌云盘了。
> > > 
> > > 
> > > ? 如何更改UA呢？
> > 
> > 
> > config set -user_agent="Mozilla;5.0"
> 
> 若上述无效，可试试下面这个
> config set -user_agent="netdisk;8.12.9;android-android"

修改user_agent的方法无用了
