### ISSUE TITLE
文件校验出错

### ISSUE THREAD

**Issue by Miloxing** [iikira/BaiduPCS-Go#488]
下完后校验文件总是md5和服务器上不符然后重下，最后下载失败

**Comment by iikira** [comment]
下载其他的文件正常吗？
建议更换网络或隔一段时间再试试

**Comment by Miloxing** [comment]
> 下载其他的文件正常吗？
> 建议更换网络或隔一段时间再试试

就是视频文件出错，别的格式的文件没问题

**Comment by hswmartin** [comment]
> 下完后校验文件总是md5和服务器上不符然后重下，最后下载失败

你应该是个老司机，你下的是被百度替换成8秒视频的文件，你下个健康的视频就没这问题了

**Comment by landall** [comment]
@iikira 被屏蔽的文件、图片、视频，除了下载之后解决，有其他方法来找出来么？我看文件的meta信息好像没有任何异常。但百度网盘自己似乎能扫描出来哪些文件被屏蔽了。

**Comment by iikira** [comment]
@landall 去百度网盘官方的客户端看缩略图。。
