### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hobmgcode** [iikira/BaiduPCS-Go#49]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6f672e]

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson.(*Json).Map(...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson/simplejson.go:176
github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson.(*Json).CheckGet(...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson/simplejson.go:165
github.com/iikira/BaiduPCS-Go/baidupcs.checkErr(0x0, 0x8e9, 0xe00, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/util.go:9 +0x5e
github.com/iikira/BaiduPCS-Go/baidupcs.PCSApi.FilesDirectoriesMeta(0x8d16f8, 0x4, 0x0, 0x0, 0x0, 0x8d7df9, 0xd, 0xc0423b2280, 0x12, 0x0, ...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/file_directory.go:47 +0x4c9
github.com/iikira/BaiduPCS-Go/command.parsePath(0xc042420e48, 0x1, 0xc04206d110, 0xc042018070, 0x4109b1, 0x52da300, 0x46d739)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/util.go:60 +0x1df
github.com/iikira/BaiduPCS-Go/command.getAbsPath(0x0, 0x0, 0xb7bbb0, 0xc042104c00, 0xc042420e50, 0xc04206d198)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/util.go:37 +0x40
github.com/iikira/BaiduPCS-Go/command.RunLs(0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/ls.go:12 +0x57
main.main.func9(0xc0421dd080, 0xc04206d280, 0x7e0c17)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:322 +0x52
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x83b580, 0x93a880, 0xc0421dd080, 0xc04203df00, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:490 +0xd9
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x8d0ef9, 0x2, 0x0, 0x0, 0xc0420db340, 0x2, 0x2, 0x8edbfe, 0x53, 0xc042074500, ...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:210 +0xa9c
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc042057520, 0xc042229c20, 0x2, 0x2, 0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:255 +0x6ff
main.main.func1(0xc0420acc60)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:76 +0x3bb
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x82ca00, 0xc0421740d0, 0xc0420acc60, 0xc042080c60, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:492 +0x83
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc042057520, 0xc042046180, 0x1, 0x1, 0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:264 +0x63c
main.main()
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:516 +0x234a

**Comment by iikira** [comment]
ls就退出了是吗
目前可在cmd命令提示符运行程序可以捕获错误信息

**Comment by hobmgcode** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6f672e]

goroutine 1 [running]:
github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson.(*Json).Map(...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson/simplejson.go:176
github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson.(*Json).CheckGet(...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/bitly/go-simplejson/simplejson.go:165
github.com/iikira/BaiduPCS-Go/baidupcs.checkErr(0x0, 0x8e9, 0xe00, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/util.go:9 +0x5e
github.com/iikira/BaiduPCS-Go/baidupcs.PCSApi.FilesDirectoriesMeta(0x8d16f8, 0x4, 0x0, 0x0, 0x0, 0x8d7df9, 0xd, 0xc0423b2280, 0x12, 0x0, ...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/baidupcs/file_directory.go:47 +0x4c9
github.com/iikira/BaiduPCS-Go/command.parsePath(0xc042420e48, 0x1, 0xc04206d110, 0xc042018070, 0x4109b1, 0x52da300, 0x46d739)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/util.go:60 +0x1df
github.com/iikira/BaiduPCS-Go/command.getAbsPath(0x0, 0x0, 0xb7bbb0, 0xc042104c00, 0xc042420e50, 0xc04206d198)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/util.go:37 +0x40
github.com/iikira/BaiduPCS-Go/command.RunLs(0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/command/ls.go:12 +0x57
main.main.func9(0xc0421dd080, 0xc04206d280, 0x7e0c17)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:322 +0x52
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x83b580, 0x93a880, 0xc0421dd080, 0xc04203df00, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:490 +0xd9
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.Command.Run(0x8d0ef9, 0x2, 0x0, 0x0, 0xc0420db340, 0x2, 0x2, 0x8edbfe, 0x53, 0xc042074500, ...)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/command.go:210 +0xa9c
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc042057520, 0xc042229c20, 0x2, 0x2, 0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:255 +0x6ff
main.main.func1(0xc0420acc60)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:76 +0x3bb
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x82ca00, 0xc0421740d0, 0xc0420acc60, 0xc042080c60, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:492 +0x83
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0xc042057520, 0xc042046180, 0x1, 0x1, 0x0, 0x0)
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:264 +0x63c
main.main()
        /Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:516 +0x234a

**Comment by iikira** [comment]
以前忽略了错误判断, 现在已修复, 85ac162925b0fa63e95f796b4ec6c553baade940
可编译运行程序, 看一下效果怎么样...

**Comment by hobmgcode** [comment]
编译后  win64 invalid character '<' looking for beginning of value

**Comment by iikira** [comment]
错误原因为json数据解析失败, 一般情况下不会有这种错误的，尝试重新登录帐号......

**Comment by hobmgcode** [comment]
3.2.2 好使 @iikira  加油 棒棒哒

**Comment by YanChuanRui** [comment]
@iikira 
help就失败了。。也是这个类似的提示。。

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x83c7297]

github.com/iikira/BaiduPCS-Go/pcsliner.(*PCSLiner).Pause(0x19316d20, 0x190f58d8, 0x1)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/pcsliner/pcsliner.go:44 +0x37
main.main.func1(0x192e00b0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:321 +0x540
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.HandleAction(0x84795c0, 0x192677a8, 0x192e00b0, 0x19236fc0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:492 +0x62
github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli.(*App).Run(0x192cea80, 0x1900c110, 0x1, 0x1, 0x0, 0x0)
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/vendor/github.com/urfave/cli/app.go:264 +0x509
main.main()
	/Users/apple/go/src/github.com/iikira/BaiduPCS-Go/main.go:1817 +0x4677
