### ISSUE TITLE
下载文件错误 ，403 Forbiddden

### ISSUE THREAD

**Issue by leslieFYJC** [iikira/BaiduPCS-Go#493]
![default](https://user-images.githubusercontent.com/37894637/47759682-b2cced80-dceb-11e8-9589-04eae454a19f.PNG)

**Comment by rhotov** [comment]
百度已经采取措施了，目前只能用速盘还有点速度。

**Comment by baronvv** [comment]
同样的错误，咋办。

**Comment by HisZ** [comment]
同样错误...

**Comment by iikira** [comment]
和#460 一样，关闭了

**Comment by alexwwang** [comment]
use `--locate` in download to make it downloadable, slow however.
