### ISSUE TITLE
是否支持自定义默认下载目录

### ISSUE THREAD

**Issue by newdee** [iikira/BaiduPCS-Go#494]
默认下载目录好像不是在网盘所在的download目录下，而是在home目录下的Download里以用户名命名的文件夹下面。
要求如题

**Comment by iikira** [comment]
```
BaiduPCS-Go config set -savedir 此处替换下载目录
```

**Comment by newdee** [comment]
解决了，谢谢

**Comment by lucky13820** [comment]
我想问下，我把下载目录替换为 /Users/我的名字/Downloads/ 之后，下载的文件还是会在以百度用户名命名的文件夹下面。我想把它直接改成 Downloads 文件夹，但是就是不成功。
