### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by zyouzi** [iikira/BaiduPCS-Go#495]
一段提示：访问下载链接, 需将下载器的 User-Agent 设置为: "netdisk;1.0"
![image](https://user-images.githubusercontent.com/39607814/47777198-2e9c5980-dd2f-11e8-9910-9ef7f67024e4.png)
可是已经设置为netdisk;1.0

**Comment by iikira** [comment]
那个是提取链接的功能，可使用别的下载器访问那些链接，访问前需先设置下载器的 User-Agent。
若是要直接下载，则执行 `d -locate 文件目录`
