### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by alitime** [iikira/BaiduPCS-Go#499]
获取路径信息错误, 获取文件/目录的元信息: 网络错误, Post https://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&method=meta: proxyconnect tcp: dial tcp [::1]:8118: connect: connection refused

Mac安装了privoxy，8118是privoxy默认的端口，怎么解决？

**Comment by iikira** [comment]
这是你代理的问题或代理配置的问题
