### ISSUE TITLE
Tab自动补全

### ISSUE THREAD

**Issue by lzjqsdd** [iikira/BaiduPCS-Go#5]
您好!百度网盘中文资源比较多，所以输入下载资源比较麻烦，不知道未来是否考虑提供补全功能？

**Comment by redapple0204** [comment]
这个功能很麻烦啊。。又不是本地文件

**Comment by iikira** [comment]
一直有这个想法……你暂时用通配符代替下吧

**Comment by lzjqsdd** [comment]
恩，终端下习惯了Tab补全，手打总觉的有些不适应。加油！ #

**Comment by lzjqsdd** [comment]
好久没更新，刚换了环境装上pcsgo发现可以自动补全了，赞！
