### ISSUE TITLE
可否加个下载失败日志

### ISSUE THREAD

**Issue by asiaon123** [iikira/BaiduPCS-Go#50]
有的时候下载文件夹,如果文件很多的话,某些情况下可能会遇到网络或其他的原因,导致一个或多个文件下载失败,可否加个日志,这样不至于不知道那些失败掉了

**Comment by iikira** [comment]
可以考虑
不过下载失败的可以运行相同的命令，会自动跳过已下载的文件……

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

程序已加入任务队列化, 失败支持重试了, 改天加上自定义重试次数的功能
另外, 新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
