### ISSUE TITLE
如果提示403可以尝试

### ISSUE THREAD

**Issue by lfmwuy** [iikira/BaiduPCS-Go#501]
1 更改版本号
config set -user_agent="netdisk;8.3.1;android-android"
(引用的)
2 更换appid
309847 和 310646 都可以用(引用)
BaiduPCS-Go config set -appid 266719
不过在本人使用第一种方法无解后
第二种可以使用
不过效果不是很好
有些是0B，直接不动，不过好歹不会再出现连下载都下载不到的情况

**Comment by xqzr** [comment]
310646有效

**Comment by songfish** [comment]
310646有效

**Comment by zuokaiyi1** [comment]
非常感谢第一种方法有效

**Comment by iikira** [comment]
请到#460 讨论，关闭了
