### ISSUE TITLE
使用appveyor等在线服务提供latest build

### ISSUE THREAD

**Issue by mistzzt** [iikira/BaiduPCS-Go#51]
建议配置下CI，这样用户可以下载最新编译版。

**Comment by iikira** [comment]
我倒想考虑用百度网盘提供latest build……

**Comment by mistzzt** [comment]
我的本意是让appveyor等平台进行编译。
按您所说的*百度网盘*，那和github release没区别呢。

**Comment by iikira** [comment]
还是有一点区别...github的上传，不挂代理传不上去，下载也慢.........

**Comment by mistzzt** [comment]
看来您认为使用ci部署不太有必要… 那就关了

**Comment by iikira** [comment]
第一次用那个，不会用，有时间研究研究……
