### ISSUE TITLE
要如何限制上传线程的速度?能不能增加上传也断点续存.

### ISSUE THREAD

**Issue by qasqasq12** [iikira/BaiduPCS-Go#513]
我用两台电脑上传,同样的命令 u --norapid --nosplit

一台是老电脑用xp,上传稳定在280k,很少崩溃重新上传

一台用64位的win10,上传可以飘到1-2m,大部分时间在8,900k,但常常上传几十m就崩溃重新上传了,最高那次也就去到500m,从没成功上传过超过500m的文件.我就是把xp用的32位版go复制过来win10用也不行

另外上传的时候不能断网,只要网络断开了换了ip,就会重新上传,如果加上断点续存就好了,也不怕win10高速上传崩溃.

**Comment by iikira** [comment]
上传的断点续传只能在启用分片上传时有效。因为服务器储存的是文件的分片，一个文件分片可以很小，分片上传完成后才会被服务器记录下来，利用这一点可以实现断点续传

**Comment by iikira** [comment]
1.暂不支持限速
2.不清楚

**Comment by SeAL80s** [comment]
为啥上传要限速呢，百度自己都不限速，为啥我们要帮它呢@qasqasq12

**Comment by hswmartin** [comment]
我用服务器上传几十M/S都没崩溃过，崩溃还是看下报错信息对症下药吧，不应该是速度的问题

**Comment by qasqasq12** [comment]
> 我用服务器上传几十M/S都没崩溃过，崩溃还是看下报错信息对症下药吧，不应该是速度的问题

看我的命令,单线程,你试试 u --norapid --nosplit上传一个大于1G的文件试试.
并且没有错误报告,或者我不知道那里找,因为没有报错,就是传到几十m到百多m的时候重新重0开始上传,一直这样.不过你的是几十m/s的速度可能不一样,因为可能还没崩溃就传完了,我的是最高2m/s的速度.

**Comment by qasqasq12** [comment]
> @qasqasq12 是系统问题吧。我上传从没因速度快出错过，上传的话用Chrome更快。用baidupcs-go几百k不等，用Chrome一般1-2M。用pcs批量上传崩溃过。

chrome是谷歌浏览器网页登陆百度网盘上传吗?
