### ISSUE TITLE
應該不需要編譯出 Android 版本的 binary

### ISSUE THREAD

**Issue by joeky888** [iikira/BaiduPCS-Go#514]
我不是 100% 確定

但我想應該不需要特別編譯出 Android 版本的 binary

只要是 `GOOS=linux` 的靜態編譯就可以在 Android 上執行了

比方說

```yaml
$ file BaiduPCS-Go
BaiduPCS-Go: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=gne3PEpzEv2SIlUVhBTD/VssNcRd-7n33NoiLQsXX/sH2lrGDNT0szYU-qUoXZ/U3LkYC7VkIGe-mQ5mYYS, stripped
                                           ^這個                       ^跟這個
```

這邊如果看到的是 x86-64 statically linked，

那就表示這個文件它可以在 Linux-X64 以及 Android-X64 平臺上執行。

我在 aarch64 的手機上跟 X86_64 的 Android 平板上用 termux 測試可執行 `GOOS=linux` 的靜態二進制文件。

**Comment by iikira** [comment]
发布页面已经说明了：Android 5.0 以上的设备请不要下载使用linux版本的, 否则网络请求可能会出现问题.

**Comment by joeky888** [comment]
知道了，謝謝
