### ISSUE TITLE
好像失效了

### ISSUE THREAD

**Issue by TaceyWong** [iikira/BaiduPCS-Go#515]
百度帐号登录成功: 
BaiduPCS-Go > ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by weer0026** [comment]
设置下`BaiduPCS-Go config set -appid 266719`, 文档上有说。

**Comment by goxofy** [comment]
> 设置下`BaiduPCS-Go config set -appid 266719`, 文档上有说。

好像这个设置了之后只能ls，没法download，提示   “下载文件错误, 403 Forbidden”

**Comment by xtgjzwj** [comment]
讲了，来着百度的恶意。亲自测试，下载超过1g直接403
开了会员之后80m/s，还不限制下载

**Comment by iikira** [comment]
参见#387
