### ISSUE TITLE
 31326, config set -user_agent "netdisk"无效

### ISSUE THREAD

**Issue by Mackel123** [iikira/BaiduPCS-Go#517]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:123

config set -user_agent "netdisk"将浏览器识别改为netdisk无效

**Comment by SCKC1** [comment]
config set -user_agent="Mozilla;5.0"
试试~

**Comment by Mackel123** [comment]
> config set -user_agent="Mozilla;5.0"
> 试试~

也失效了

**Comment by iikira** [comment]
新的commit修改了错误提示，实际上和#460 的问题是一样的，关闭了
