### ISSUE TITLE
有多少人是超级会员也被限速或者禁止下载？

### ISSUE THREAD

**Issue by pongfcnkl** [iikira/BaiduPCS-Go#523]

**Comment by hswmartin** [comment]
超级会员也会被限，看是否被限很简单，“lt 随便一个文件”，如果只显示两条下载链接，肯定被限了，没被限的号有七八条

**Comment by hswmartin** [comment]
超级会员可以突破限速
![image](https://user-images.githubusercontent.com/21002122/48246640-262cd880-e42b-11e8-82ee-3c79bfad6847.png)

**Comment by pongfcnkl** [comment]
> 
> 
> 超级会员可以突破限速
> ![image](https://user-images.githubusercontent.com/21002122/48246640-262cd880-e42b-11e8-82ee-3c79bfad6847.png)

是没有403了，但是不知道为什么500KB/S都没突破

**Comment by baituxiao** [comment]
> 超级会员也会被限，看是否被限很简单，“lt 随便一个文件”，如果只显示两条下载链接，肯定被限了，没被限的号有七八条

😆我lt就一条

**Comment by iikira** [comment]
d -locate 的下载方式针对网盘会员进行优化, https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a

试一试吧!

**Comment by hswmartin** [comment]
> d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> 
> 试一试吧!

这个版本可以用代理了，牛，百度会把下载过多的IP随机给出错误链接，用代理换个地址下就正常了。
其实会员不用d -locate也可以很快，download.go里面改一下
![image](https://user-images.githubusercontent.com/21002122/48326970-2de0bd00-e677-11e8-9a1a-b28e3ba28585.png)

**Comment by pongfcnkl** [comment]
> 
> 
> d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> 
> 试一试吧!

这速度可以

**Comment by qasqasq12** [comment]
> d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> 
> 试一试吧!

这个怎么升级?直接update命令吗?

**Comment by iikira** [comment]
> > d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> > 试一试吧!
> 
> 这个怎么升级?直接update命令吗?

编译安装

**Comment by qasqasq12** [comment]
> > > d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> > > 试一试吧!
> > 
> > 
> > 这个怎么升级?直接update命令吗?
> 
> 编译安装

不懂啊,要什么工具?如何操作?

**Comment by pongfcnkl** [comment]
> 
> 
> > > > d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> > > > 试一试吧!
> > > 
> > > 
> > > 这个怎么升级?直接update命令吗?
> > 
> > 
> > 编译安装
> 
> 不懂啊,要什么工具?如何操作?

这个地方直接下载
https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by qasqasq12** [comment]
> > > > > d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> > > > > 试一试吧!
> > > > 
> > > > 
> > > > 这个怎么升级?直接update命令吗?
> > > 
> > > 
> > > 编译安装
> > 
> > 
> > 不懂啊,要什么工具?如何操作?
> 
> 这个地方直接下载
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

看着一堆文件不知道怎么操作

**Comment by pongfcnkl** [comment]
> > > > > > d -locate 的下载方式针对网盘会员进行优化, [0007020](https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a)
> > > > > > 试一试吧!
> > > > > 
> > > > > 
> > > > > 这个怎么升级?直接update命令吗?
> > > > 
> > > > 
> > > > 编译安装
> > > 
> > > 
> > > 不懂啊,要什么工具?如何操作?
> > 
> > 
> > 这个地方直接下载
> > https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> 
> 看着一堆文件不知道怎么操作

所以我得把饭喂在你嘴里吗？
