### ISSUE TITLE
可以利用“手动秒传文件”转存或遍历服务器已存在的文件吗？

### ISSUE THREAD

**Issue by lweo** [iikira/BaiduPCS-Go#525]
长度加MD5就能转存？获取互联网上分享的资源文件字节大小好像不好搞。。

有没有一些技巧？

异想天开下……

**Comment by iikira** [comment]
可以的

**Comment by qasqasq12** [comment]
很多不行,比如第一次上传的文件都是md5可能不正确,就无法秒传到别的账户.go的修复没试过成功,只能用 --nosplit命令上传的文件才可以秒传,但不能超过2G.

如果是别人的分享文件,百度盘也不用秒传,直接打开地址保存了,不是分享的文件,你怎么获得字节大小和md5码呢?

**Comment by iikira** [comment]
只需文件大小和md5即可尝试秒传, 没有技巧~

**Comment by lweo** [comment]
@qasqasq12 
我是想获取 私密分享的文件
