### ISSUE TITLE
远端服务器返回错误

### ISSUE THREAD

**Issue by Hellostarry** [iikira/BaiduPCS-Go#527]
请输入接收到的验证码 > 993953
百度帐号登录成功: cf郑天
BaiduPCS-Go:/ cf郑天$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错 误, 代码: 4, 消息: No permission to do this operation
BaiduPCS-Go:/ cf郑天$

**Comment by Hellostarry** [comment]
求解

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/blob/master/README.md#解决错误代码4-no-permission-to-do-this-operation
