### ISSUE TITLE
文件名如果包含空格，就会出现文件或目录不存在

### ISSUE THREAD

**Issue by pankan8069151** [iikira/BaiduPCS-Go#529]
一个小bug，因为经常下载电影，然后电影的英文命名较长，中间可能有空格，导致文件无法下载，每次都是先进百度盘改名，然后再下载。

**Comment by tzh979215144** [comment]
使用通配符可以解决你的问题吗？
例如文件名为：antWowen 720p.mp4
下载：d antWowen*
注意，*是在英文输入法下打的

**Comment by yuanxiayouwo** [comment]
你好。
这不是BUG。
linux终端里的空格和win系统含义不同，
使用英文双引号""，例如"Adobe/Adobe Photoshop CS6"，下载。

**Comment by iikira** [comment]
参见[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
