### ISSUE TITLE
方向键无法调用历史命令

### ISSUE THREAD

**Issue by SeAL80s** [iikira/BaiduPCS-Go#53]
版本3.2.2,在进入BaiduPCS-Go环境后，方向键无法调用历史命令，比如之前ls，download，upload的文件或目录。版本3.2.1是可以的，是bug还是其他考量？

**Comment by iikira** [comment]
测试没问题啊，麻烦你提供更多信息……

**Comment by SeAL80s** [comment]
现在没问题了，不知道当时怎么抽风的

**Comment by iikira** [comment]
是bug...
