### ISSUE TITLE
我有个帐号怎么登陆不上去

### ISSUE THREAD

**Issue by imj2** [iikira/BaiduPCS-Go#530]
我有个帐号怎么登陆不上去，其他帐号都可以正常登陆，这个帐号一输入验证码后就直接跳转到登陆页面，然后右边的已登录用户列表就消失了！

**Comment by iikira** [comment]
提供一下截图

**Comment by imj2** [comment]
> 提供一下截图
[https://img.alicdn.com/imgextra/i3/95249875/O1CN01PEzjnG2MoncoZrOxq_!!95249875.jpg](url)

**Comment by pongfcnkl** [comment]
用bduss登陆呢？

**Comment by iikira** [comment]
请到那里反馈: https://github.com/liuzhuoling2011/baidupcs-web

**Comment by imj2** [comment]
> 用bduss登陆呢？

不懂这操作！
