### ISSUE TITLE
可否跳过 fixmd5

### ISSUE THREAD

**Issue by xdxdy** [iikira/BaiduPCS-Go#531]
可否不进行 md5 修复，以节省时间？

**Comment by iikira** [comment]
上传加上-nofix 参数

https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a, 这个commit新增修复文件md5功能 (fixmd5), 并取消上传完成后修复md5的功能
