### ISSUE TITLE
秒传文件接口已更新

### ISSUE THREAD

**Issue by iikira** [iikira/BaiduPCS-Go#537]
slice-md5不能忽略了. 所以，export，fixmd5等功能不能用了

**Comment by isaac850904** [comment]
啊太惨了，就是说以后都不能用秒传功能了？

**Comment by isaac850904** [comment]
slice-md5是block list里面的吗？需要整个加进去？
"block_list": [
                        "8da0ac878f3702c0768dc6ea6820d3ff",
                        "3c1eb99b0e64993f38cd8317788a8855"
                    ]

**Comment by iikira** [comment]
不是的
