### ISSUE TITLE
3.2.2-windows-x64版本默认的是单个文件下载,请问怎么设置多个文件同时下载啊

### ISSUE THREAD

**Issue by jaythc** [iikira/BaiduPCS-Go#54]
另外在下载的时候,不能暂停或者取消下载啊.请问如何暂停或者取消啊
还有在下载一个目录的时候, 下载完其中一个文件,不能自动下载下一个文件,得手动按enter才会下载下一个文件. 请问可以设置自动下载所有文件吗

**Comment by iikira** [comment]
目前不支持暂停下载，取消下载需要关闭程序，然后到下载的目录删掉文件……
有了多线程下载，多个文件同时下载就不必要了，程序会被系统杀掉的……
另外不能自动下载下一个文件，没测试出来，麻烦提供更多信息，比如截图……

**Comment by jaythc** [comment]
![snipaste_2018-02-11_19-40-43](https://user-images.githubusercontent.com/29886008/36072980-0da58592-0f64-11e8-9862-d0c8f09cd6bf.jpg)


不能自动下载下一个文件,截图已经提供了,如图所示,下载到30.71M的时候,就停住了,得手动按enter才会下载下一个文件.

**Comment by iikira** [comment]
尝试修复这种卡住不动的问题, c8a026cebf78f1d8d147e9c25a9c7e33adf76ffe
可编译安装程序试试效果...

**Comment by jaythc** [comment]
![default](https://user-images.githubusercontent.com/29886008/36075861-69e0bb12-0f8f-11e8-8d9b-76cf33699c2c.png)

你好,我按照格式填写上传的文件夹, 可一直提示unknow respons data file saved path not found .
我把保存在网盘的路径换了,也不管用,

**Comment by iikira** [comment]
忘记回复了, 抱歉啊,
已修复, b524e7c086c7544cedf7a5790e395ab91c88f2ce

**Comment by jaythc** [comment]
![bug](https://user-images.githubusercontent.com/29886008/36471846-e25fdeb8-172a-11e8-8a97-a50776e240e6.jpg)
![image](https://user-images.githubusercontent.com/29886008/36471909-1a1677c2-172b-11e8-9446-04357f39648c.png)

无法下载新保存的文件夹，提示文件不存在。既不能下载，也不能进入该文件夹。实际上文件夹是存在的，里面内容也不为空。

**Comment by jaythc** [comment]
原来如此啊，程序把它按照两个文件夹来处理了，所以找不到文件夹。

**Comment by iikira** [comment]
下载暂停的问题, 已经记录了  #25 ,

另外, 新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.

https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)
