### ISSUE TITLE
请问回收站操作是哪个版本可以用？

### ISSUE THREAD

**Issue by isaac850904** [iikira/BaiduPCS-Go#540]
看到这里说可以操作回收站了
https://github.com/iikira/BaiduPCS-Go/commit/0007020252c3d84f2227cad0f65a88e98c4b7e3a

看了最新版本还是3.5.6
https://github.com/iikira/BaiduPCS-Go/releases

3.5.6试了一下
说没有这个命令

是还没有发布吗？谢谢！

**Comment by pongfcnkl** [comment]
不会用help?
![img_20181116_123021](https://user-images.githubusercontent.com/24273319/48597966-811a7e80-e99b-11e8-8762-03d9cd536629.jpg)

**Comment by pongfcnkl** [comment]
https://ci.appveyor.com/project/iikira/baidupcs-go/history

**Comment by iikira** [comment]
嗯 没发布
