### ISSUE TITLE
登录后可以维持多久不断开

### ISSUE THREAD

**Issue by kzxuan** [iikira/BaiduPCS-Go#541]
OS: Windows Server 2008

采用账号、密码方式，在命令行下直接登录，近两个礼拜内在命令行内的直接操作都是有效的，是否有人知道这样的登录可以维持多久不断开？谢谢

**Comment by pongfcnkl** [comment]
百度抽风容易失效

**Comment by kzxuan** [comment]
> 据说是十年

👌好的，非常棒的程序，谢谢

**Comment by jiangjiangflies** [comment]
> 据说是十年

这个牛逼了
