### ISSUE TITLE
在android上运行无法生成配置文件

### ISSUE THREAD

**Issue by pyg2007** [iikira/BaiduPCS-Go#547]
把可执行文件放入/system/bin，使用root运行BaiduPCS-Go后无法生成配置文件

**Comment by iikira** [comment]
提供一下详细的错误信息

**Comment by pyg2007** [comment]
重载配置错误: open /system/bin/pcs_config.json: read-only file system

**Comment by pyg2007** [comment]
重载配置错误: open /system/bin/pcs_config.json: read-only file system
