### ISSUE TITLE
离线下载失效

### ISSUE THREAD

**Issue by xiongxiongya** [iikira/BaiduPCS-Go#549]
代码: 36020, 消息: Invalid source url
代码: 36026, 消息: invalid magnet link

均失效了 不知道是哪里的问题，麻烦了

**Comment by 1608637229** [comment]
> 代码: 36020, 消息: Invalid source url
> 代码: 36026, 消息: invalid magnet link
> 
> 均失效了 不知道是哪里的问题，麻烦了

14号百度官方微博在微博上发布消息称暂时关闭百度网盘的离线下载功能，什么再开时间未定。
老哥不看新闻吗？百度没了离线还不如开个会员用微云。普通会员基本满速，也有3t空间。

**Comment by xiongxiongya** [comment]
额，我留校呢 没新闻看啊。。我这周回来突然发现用不了 就问下

**Comment by xiongxiongya** [comment]
额，我留校呢 没新闻看啊。。我这周回来突然发现用不了 就问下
