### ISSUE TITLE
下载某些文件时下载速度为0，一直无响应

### ISSUE THREAD

**Issue by xsharh** [iikira/BaiduPCS-Go#55]
在下载.txt,.propertity,jar等文件时，下载速度为0，一直无响应,关闭之后重新打开又可继续，但类似情况出现的次数比较频繁

**Comment by zisee** [comment]
也有同样问题

**Comment by iikira** [comment]
是刚开始就没速度还是下载到一半就没速度……

**Comment by zisee** [comment]
刚开始就没有速度

**Comment by iikira** [comment]
@zisee 下载进度条有没有出来了, 如果出来了, 麻烦截个图, 我看看......

**Comment by zisee** [comment]
![qq 20180212125505](https://user-images.githubusercontent.com/9462444/36084028-fdd577d6-0ff3-11e8-956f-6cb2c10d003f.png)

**Comment by iikira** [comment]
好吧，我测试一下

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
