### ISSUE TITLE
logout之后，命令行中依然显示用户名

### ISSUE THREAD

**Issue by hyh19962008** [iikira/BaiduPCS-Go#550]
RT，win64版本

**Comment by iikira** [comment]
你没有确认退出吧
```
logout -y
```

**Comment by hyh19962008** [comment]
![](https://www.swuplaf.cn/cf.jpg)

**Comment by iikira** [comment]
测试正常, 提供一下版本号

**Comment by hyh19962008** [comment]
v3.5.6

**Comment by Metroyuan** [comment]
再输一次logout(或其他操作)提示 未设置任何百度账号 之后就不显示了啊

**Comment by iikira** [comment]
新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 应该修复了这个问题, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
