### ISSUE TITLE
这个appid是如何申请的？

### ISSUE THREAD

**Issue by soease** [iikira/BaiduPCS-Go#551]
在哪里申请？我们自己去申请一个，现在的基本都被封了

**Comment by pongfcnkl** [comment]
开超级会员可解封
![qq 20181121164233](https://user-images.githubusercontent.com/24273319/48829183-a26cd780-edac-11e8-8bc4-e6f5fd2f8c71.jpg)

**Comment by iikira** [comment]
现在不开放申请了
