### ISSUE TITLE
Why is it?

### ISSUE THREAD

**Issue by OrsonFloyd** [iikira/BaiduPCS-Go#553]
It would turn to 0B/s until I restart it.

**Comment by iikira** [comment]
Add `-verbose` and `-status` flags would see more information.
[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

**Comment by OrsonFloyd** [comment]
谢谢啊
