### ISSUE TITLE
C盘的文件目录只有部分能上传啊，其他都显示未检测到文件，，？？？

### ISSUE THREAD

**Issue by HDDLDR** [iikira/BaiduPCS-Go#554]

**Comment by pongfcnkl** [comment]
权限问题？

**Comment by iikira** [comment]
能否提供一下操作示例

**Comment by HDDLDR** [comment]
BaiduPCS-Go: 用户名$ upload C:/Program Files/666.txt  /我的文档
未检测到上传文件，请检查文件路径活通配符是否正确。
BaiduPCS-Go: 用户名$ upload C:/O/666.txt  /我的文档
（1），，，
（2），，，
秒传失败,,

是权限问题吗，管理员运行后还是这样

**Comment by iikira** [comment]
路径有空格 参见https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by HDDLDR** [comment]
BaiduPCS-Go: 用户名$ upload C:/O/666.txt /我的文档
（1），，，
（2），，，
秒传失败,,
这个是没有空格的啊，，，emmmm??

**Comment by HDDLDR** [comment]
加引号，反斜杠还是未检测到，，，，emmmm??

**Comment by iikira** [comment]
（1），，，
（2），，，

这个是什么意思

**Comment by HDDLDR** [comment]
![0a53da3a96944445c848485bd1c542a](https://user-images.githubusercontent.com/30253942/49632264-0d1a4600-fa30-11e8-9da5-56a2282a9e53.png)
