### ISSUE TITLE
31023

### ISSUE THREAD

**Issue by HDDLDR** [iikira/BaiduPCS-Go#555]
秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 31023

**Comment by 674273563** [comment]
操 我还以为是救命appID

**Comment by Yaspee** [comment]
见 https://github.com/iikira/BaiduPCS-Go/issues/460

**Comment by iikira** [comment]
是不是秒传大于20GB的文件呢

**Comment by iikira** [comment]
不支持秒传大于20GB的文件
