### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by mack2050** [iikira/BaiduPCS-Go#559]
我是在群晖的NAS上装了DOCKER容器来使用的，装好了，能打开看到界面，点击文件下载在下载列表里能看到，但是完全没有速度，不知道是不是需要做端口映射，如果需要端口号是多少？上传试过传了一个大文件，应该是盘里有的文件，所以秒传上去了.再查了一下,感觉是不是和存储的位置有关系,因为位置不对或位置不可写应该也是不行的,在容器里添加卷的时候添加了一个文件夹/nas/baidu 装载路径我写的/baidu,但我登到机器上去试了/baidu下被写保护,不能写,这有什么办法解决么?我把目录又重新设了一下，设到了/docker目录下，我试着下载了一下文件，我发现文件还是没有下载，但是下载的那个文件所带路径里的目录是创建了的，也证明了/docker下是可写的，但就是没有文件进来，我下的是很小的照片文件，只有几M，看下载状态栏里完成没有流量。

**Comment by iikira** [comment]
下载没有速度的，建议开通会员
至于你描述的其他问题，就不是本程序的问题了
