### ISSUE TITLE
3.56版windows 中文搜狗输入法不会跟随，不显示中文候选字

### ISSUE THREAD

**Issue by suveng** [iikira/BaiduPCS-Go#562]
中文搜狗输入法不会跟随，不显示中文候选字

**Comment by pongfcnkl** [comment]
这个你应该找搜狗吧

**Comment by InoryLwc** [comment]
其实不单止是baidupcs-go好不好，是整个cmd在用搜狗输入中文时，都不会显示候选字的，经测试，微软自带的可以。

**Comment by suveng** [comment]
哇，好厉害啊。




| |
suveng
|
|
邮箱：suveng@163.com
|

Signature is customized by Netease Mail Master

在2019年02月06日 18:06，InoryLwc 写道：

其实不单止是baidupcs-go好不好，是整个cmd在用搜狗输入中文时，都不会显示候选字的，经测试，微软自带的可以。

**Comment by junlovejing** [comment]
其实是win10新版CMD的问题。打开个CMD右键，属性，勾选使用旧版控制台就行了

**Comment by iikira** [comment]
参考楼上的回复哦
