### ISSUE TITLE
[feature request] 执行文字档中的数个命令

### ISSUE THREAD

**Issue by ppsspp-gamer** [iikira/BaiduPCS-Go#565]
希望能执行文字档内的命令，让重复的动作自动化，例如：

**myCmd.txt 内容为** 

config config set -appid=266719
cd cd /apps/baidu_shurufa
config config set -appid=265486
d  movie.mp4

**执行这些命令，只要打**

exec myCmd.txt 

**不需要复杂的语法，或是完整的错误处理，
只要把文字档内容，一行一行读到阵列，
然后一行一行执行到完，就非常方便了***

**Comment by iikira** [comment]
此问题已记录, #239
