### ISSUE TITLE
之前问过一次，可是问题还是没有解决

### ISSUE THREAD

**Issue by includeEverything** [iikira/BaiduPCS-Go#567]
![1](https://user-images.githubusercontent.com/38358110/49289397-9be20c80-f4de-11e8-84ac-14b781df6e2d.jpg)
![2](https://user-images.githubusercontent.com/38358110/49289403-a0a6c080-f4de-11e8-9c00-aeeb01d9ad88.jpg)

像这样，有中括号的文件根本上传不了

**Comment by iikira** [comment]
中括号需要转义才行
另外新的commit消除了中括号的转义问题，可编译安装试一试
