### ISSUE TITLE
断点下载以后，虽可继续下载 但完成后提示MD5验证失败，自动删除重新下载

### ISSUE THREAD

**Issue by magnusguo** [iikira/BaiduPCS-Go#568]
断点下载以后，虽可继续下载 但完成后提示MD5验证失败，自动删除重新下载

**Comment by qasqasq12** [comment]
加参数 --nocheck

**Comment by magnusguo** [comment]
> 加参数 --nocheck
晚了 现在已经自动重新下载了 而且使尽各种方法全是403 求支招 谢谢

**Comment by pongfcnkl** [comment]
403的话
开会员，并且加参数 -locate
