### ISSUE TITLE
下载速度非常慢，和之前差距很大

### ISSUE THREAD

**Issue by LambooZ** [iikira/BaiduPCS-Go#574]
之前一般都在8MB/s，最近只有几kb，是哪里的问题呢

**Comment by pongfcnkl** [comment]
开超级会员
并且下载带d -locate

**Comment by iikira** [comment]
并不保证速度的，如果觉得速度很慢，可以开通网盘会员!

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

**Comment by LambooZ** [comment]
已经开通了～
