### ISSUE TITLE
代码: 31066, 消息: 文件或目录不存在

### ISSUE THREAD

**Issue by jj3380** [iikira/BaiduPCS-Go#577]
![wx20181209-123339](https://user-images.githubusercontent.com/45726174/49693475-f817f100-fbae-11e8-9e52-a21eb070c426.png)

* pls be noted red underlined 【 0B 】 

为什么会0B，尝试了下载所有文件，都代码31066

**Comment by iikira** [comment]
不支持下载序号，请替换成文件名
不支持计算目录的大小
