### ISSUE TITLE
[检测BDUSS有效性网络错误] 所有百度相关网站都打不开, 其他网站都正常

### ISSUE THREAD

**Issue by FaiChou** [iikira/BaiduPCS-Go#58]
```
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp: lookup tieba.baidu.com on 192.168.0.1:53: read udp 192.168.0.107:59635->192.168.0.1:53: i/o timeout
```

系统:Mac

chrome和Safari打不开百度所有链接, baidu.com tieba.baidu.com 等. 使用百度网盘, 刷新一直loading.

打开小飞机全局模式, 百度网盘可以刷新, 但是所有百度链接还是打不开.

启用了chrome的隐身模式, 能够打开百度.

连接到手机的热点, 也能打开百度.

凝似ip和bduss被百度锁定了?

有相似经历吗? 如何解决?

**Comment by iikira** [comment]
有啊，不过我是所有网站都打不开😊

**Comment by iikira** [comment]
新版本优化了下载的网络连接数量, 下载新版试试效果, 应该不会经常出现这种问题了...
