### ISSUE TITLE
切换目录的时候出现错误代码31301，无法切换。

### ISSUE THREAD

**Issue by GoGoogle** [iikira/BaiduPCS-Go#581]
获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file

连cd /都不行，回到根目录不行，但可以下载当前目录里面的文件。

**Comment by 18355166248** [comment]
我也遇到了 能解决么

**Comment by GoGoogle** [comment]
> 我也遇到了 能解决么

我不知道是什么原因引起的，但感觉退出账号再登录的话，应该就可以解决了，我一直没退出账号，是想找到是什么原因，不退出能否解决。

**Comment by TkzcM** [comment]
AppID没有根目录权限，换回266719就可以了

**Comment by GoGoogle** [comment]
> AppID没有根目录权限，换回266719就可以了

非常感谢，已解决。
