### ISSUE TITLE
上传文件失败,代码: 31062

### ISSUE THREAD

**Issue by yaojiwei123** [iikira/BaiduPCS-Go#585]
[1] ↑ 79.95KB/79.95KB 79.95KB/s in 1.003s ............[1] 上传文件失败, 分片上
传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31062, 消息: file name is
invalid

**Comment by iikira** [comment]
文件名不能包含以下字符，请检查：
\ ? | " > < : *

**Comment by yaojiwei123** [comment]
@iikira 谢谢提醒
