### ISSUE TITLE
天杀的Baidu，万年不用的小号，下载了一个大文件就被拉黑了

### ISSUE THREAD

**Issue by dssszw** [iikira/BaiduPCS-Go#587]
刚下完一个文件，准备再下第二个，直接就403了。。。。
还有什么好的解决办法，难道只能花10块钱开会员？？

**Comment by dssszw** [comment]
下载了有5G左右，下了差不多10多分钟
难道是速度太快，时间太长，被抓住了？
有什么设置方法可以活的久点？

**Comment by pongfcnkl** [comment]
某宝租号，两三块钱一个月。。。。

**Comment by shulin-li** [comment]
> 某宝租号，两三块钱一个月。。。。

请问哪里有卖的。。我问的卖的都是微博账号登录 但是pcs不支持微博登录。。。

**Comment by pongfcnkl** [comment]
> 
> 
> > 某宝租号，两三块钱一个月。。。。
> 
> 请问哪里有卖的。。我问的卖的都是微博账号登录 但是pcs不支持微博登录。。。

某宝。。。。不支持微博但是支持bduss。。。

**Comment by shulin-li** [comment]
> > > 某宝租号，两三块钱一个月。。。。
> > 
> > 
> > 请问哪里有卖的。。我问的卖的都是微博账号登录 但是pcs不支持微博登录。。。
> 
> 某宝。。。。不支持微博但是支持bduss。。。

啊？我就是用bduss但是还是登录不了啊？

**Comment by shulin-li** [comment]
> > > 某宝租号，两三块钱一个月。。。。
> > 
> > 
> > 请问哪里有卖的。。我问的卖的都是微博账号登录 但是pcs不支持微博登录。。。
> 
> 某宝。。。。不支持微博但是支持bduss。。。

抱歉,不知道为什么又可以了,可能是我第一次bduss复制错了吗。。。。。

**Comment by lonee8** [comment]
> 某宝租号，两三块钱一个月。。。。

这么便宜，给个关键字，找不到。

**Comment by pongfcnkl** [comment]
> 
> 
> > 某宝租号，两三块钱一个月。。。。
> 
> 这么便宜，给个关键字，找不到。



> 
> 
> > 某宝租号，两三块钱一个月。。。。
> 
> 这么便宜，给个关键字，找不到。

某云vip

**Comment by lonee8** [comment]
> 某云vip

最便宜的6.8，weibo登陆的那个说9块，就根本没见过两三块的。

**Comment by noobsnd** [comment]
>           刚下完一个文件，准备再下第二个，直接就403了。。。。
> 还有什么好的解决办法，难道只能花10块钱开会员？？

如果你网盘内文件都不重要或者文件很少的话，你可以试试去将账号注销了（因为注销要把文件全部删完），之后又去百度注册它，然后再用软件登陆就会发现又不限速了  ╮(￣▽￣)╭

**Comment by redapple0204** [comment]
@noobsnd 注销还要验证手机身份证之类的，且不说麻烦，我才不想把信息给百度呢= =

**Comment by iikira** [comment]
请在 #460 处讨论
