### ISSUE TITLE
目录无法操作

### ISSUE THREAD

**Issue by rexyan** [iikira/BaiduPCS-Go#589]
输入 ls 后显示内容如下:

```
获取目录下的文件列表: json 数据解析失败, readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html>
<hea|..., bigger context ...|<html>
<head>
<meta http-equiv="Content-Type" conte|...
```

**Comment by iikira** [comment]
应该是网络的问题，请检查网络并重试

**Comment by XJLZ** [comment]
> 输入 ls 后显示内容如下:
> 
> ```
> 获取目录下的文件列表: json 数据解析失败, readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html>
> <hea|..., bigger context ...|<html>
> <head>
> <meta http-equiv="Content-Type" conte|...
> ```

我也出现这个问题，怎么解决的啊，网络没问题
