### ISSUE TITLE
403错误问题

### ISSUE THREAD

**Issue by wonathan** [iikira/BaiduPCS-Go#595]

**Comment by wonathan** [comment]
![_20181220140226](https://user-images.githubusercontent.com/9854708/50266804-09d77f00-0460-11e9-870f-28e9deb2f1bf.png)

**Comment by EpicKJ** [comment]
我也遇到这个问题……下了个东西下到90%停止了，再下发现就403了。是不是凉了……

**Comment by wangling12** [comment]
同

**Comment by assumecs** [comment]
我也遇到了，然后登录一下官方客户端随便下载点文件，再用命令行就能下载了，不过目前还不知道能不能正常下载完。

**Comment by matrixlea** [comment]
同

**Comment by renzhe00** [comment]
t同

**Comment by iikira** [comment]
参见 #460
