### ISSUE TITLE
更新报错 json数据解析失败

### ISSUE THREAD

**Issue by wilbur-oo** [iikira/BaiduPCS-Go#596]
MacbookPro:10.14.2
BaiduPCS-Go version v3.5.6-devel

检测更新中, 稍候...
json数据解析失败: readObjectStart: expect { or n, but found R, error found in #1 byte of ...|Request for|..., bigger context ...|Request forbidden by administrative rules. Please m|...

**Comment by iikira** [comment]
看你的关键字 `Request forbidden by administrative rules`, 是你网络的问题
