### ISSUE TITLE
我也遇到403-重试1/3的问题了。发现一个细节，不知道有没有帮助

### ISSUE THREAD

**Issue by matrixlea** [iikira/BaiduPCS-Go#597]
![image](https://user-images.githubusercontent.com/42026728/50301564-a894c780-04c2-11e9-8734-50f36993f39d.png)
![image](https://user-images.githubusercontent.com/42026728/50301609-c2360f00-04c2-11e9-9bcb-5513abf31863.png)
下载的时候 ，我看到appid 显示的还是以前的 APPID，但是配置上面显示的APPID 是我改过的APPID。这是导致403的原因么？先给你们看一下。

**Comment by i0Ek3** [comment]
同样无法使用！

**Comment by Heelc** [comment]
这个问题解决了吗？

**Comment by TkzcM** [comment]
下载时显示的 AppID 是保存文件时使用的 AppID ，不会影响下载

**Comment by iikira** [comment]
403 的问题请在 #460 讨论
