### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lengyanyu258** [iikira/BaiduPCS-Go#60]
When I use `go get -u -v .` or `go build`, there is an error following here:
```bash
$ go build
# github.com/json-iterator/go
../github.com/json-iterator/go/feature_reflect_extension.go:248: field.Tag.Lookup undefined (type reflect.StructTag has no field or method Lookup)
```
The last commit: e368f99f08c5c419e0b0c029c88c0b244355a3e2

**Comment by iikira** [comment]
尝试更新golang

**Comment by lengyanyu258** [comment]
old: `go version go1.6.2 linux/amd64`
new: `go version go1.9.4 linux/amd64`
It worked!
Thank you so much.
