### ISSUE TITLE
旧路由器的运行与下载速度问题

### ISSUE THREAD

**Issue by garywill** [iikira/BaiduPCS-Go#607]
我的一个旧路由器，64M RAM ，内核2.6.22.19。

下载mipsel 3.5.6，无法正常使用，说网络错误。查issue后据说一是内核版本不够(要2.6.23差一点点啊），二是等待go修复。

然而，下载@liuzhuoling2011编译的3.6.1却可以正常运行，（这是为什么呢？）

可是，下载速度很慢。（我是用U盘不是硬盘不知道这点有没有影响，程序也放U盘里）
最快300多k，断断续续，下载4M左右就中断一分钟。平均起来70k/s左右。
调整线程为1或100好像没有什么变化。调大缓存到6MB也没有什么改进。
(同样的网络在电脑上运行baidupcs-go，速度有1-2MB/s)

**Comment by iikira** [comment]
不建议在路由器上使用本程序，尤其是老旧的设备，程序运行的性能无法保证
