### ISSUE TITLE
tree 命令得到的树状目录怎么保存本地啊？？？求大神帮忙来看

### ISSUE THREAD

**Issue by devinte** [iikira/BaiduPCS-Go#613]
请问用树命令怎么把树状目录保存到本地呢我用t> d：/downloads / word.txt结果提示获取目录下的文件列表：遇到错误，远端服务器返回错误，代码：31062，消息：文件名无效
说文件名不合法，应该怎么操作啊望大神们赐教啊

**Comment by PEdajilao** [comment]
use "./BaiduPCS-Go t|dd of=1.txt"

**Comment by hv0905** [comment]
>> 只能在bash/cmd下使用,Baidupcs-go的cli不能用
先 exit 退出cli
然后 ./baidupcs-go tree >> filename.txt

**Comment by iikira** [comment]
树状目录怎么保存本地参考楼上的回复
另外注意一下文件路径是否含有特殊字符

**Comment by CWgneD** [comment]
懂了懂了，感谢大佬~
因为在bpcs客户端运行tree命令时，
如果想要保存需要百度网盘文件的读写权限（做不到）
所以在本地运行
BaiduPCS-go tree >> 1.txt
就能将文件保存至手机/电脑内
