### ISSUE TITLE
update 返回403forbidden

### ISSUE THREAD

**Issue by Xiaotouming** [iikira/BaiduPCS-Go#614]
安卓6.0,Termux

**Comment by DT9025A** [comment]
403+1

下载大文件时突然速度变0，然后重新下载时就显示403了
___(:3」∠)___

**Comment by zege** [comment]
403+1

**Comment by pongfcnkl** [comment]
403目前只能开会员

**Comment by fsZhuangB** [comment]
**### 搬运一下**
https://github.com/iikira/BaiduPCS-Go/issues/460#issuecomment-450294985
解决方案在这里

**Comment by iikira** [comment]
原先的update更新源已经无法使用，新的commit已将更新源更换为github releases

**Comment by Ecalose** [comment]
已经不能通过软件源更新了吗？
