### ISSUE TITLE
请求自选链接下载

### ISSUE THREAD

**Issue by redapple0204** [iikira/BaiduPCS-Go#62]
实测这下列四个连接前缀下载速度较快
https://yqall02.baidupcs.com/file/
https://allall01.baidupcs.com/file/
https://allall02.baidupcs.com/file/
http://nj02all01.baidupcs.com/file/

**Comment by iikira** [comment]
目前本项目的下载文件的原理并不是提取直链, 提取直链的请参考: https://github.com/iikira/baidu-tools/
