### ISSUE TITLE
登陸後無法正常使用，error code 31045

### ISSUE THREAD

**Issue by Ipasss** [iikira/BaiduPCS-Go#622]
用BDUSS登陸後進行的跟帳號有關的任何操作都會顯示31045，有開VPN，不確定問題在哪
另外，可以告訴我要怎麼在commander裡面使用複製和貼上嗎? alt+space只能編輯已有的文字，無法從外部複製貼上，我目前是用手打BDUSS登入的
![bduss](https://user-images.githubusercontent.com/40817925/51267409-a0b04080-19f8-11e9-9eb6-2f04c85ff2ec.PNG)

**Comment by evolutionboy** [comment]
我刚下载使用的，xubuntu18.04 长期支持版，64位。
命令行下使用，一样是

请输入接收到的验证码 > 220869
百度帐号登录成功: 扶得起的新阿斗
BaiduPCS-Go:/ 扶得起的新阿斗$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
BaiduPCS-Go:/ 扶得起的新阿斗$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
BaiduPCS-Go:/ 扶得起的新阿斗$ -v
BaiduPCS-Go version v3.5.6
BaiduPCS-Go:/ 扶得起的新阿斗$ l
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
BaiduPCS-Go:/ 扶得起的新阿斗$ web
web 客户端功能为实验性功能, 测试中, 打开 http://localhost:8080 查看效果
^C
chen@chen-E6410:~/下载/BaiduPCS-Go-v3.5.6-linux-amd64$

**Comment by InoryLwc** [comment]
> 用BDUSS登陸後進行的跟帳號有關的任何操作都會顯示31045，有開VPN，不確定問題在哪
> 另外，可以告訴我要怎麼在commander裡面使用複製和貼上嗎? alt+space只能編輯已有的文字，無法從外部複製貼上，我目前是用手打BDUSS登入的
> ![bduss](https://user-images.githubusercontent.com/40817925/51267409-a0b04080-19f8-11e9-9eb6-2f04c85ff2ec.PNG)

其实直接右键就可以粘贴了，如果右键之后没有反应，先别急，用方向键左右移动光标试试看是不是出来了。同样，复制显示的结果只要选中变白之后右键就到剪贴板了，你可以打开一个文本试试粘贴。

**Comment by evolutionboy** [comment]
我上一条是发在此问题中的。
当时也是这种情况。
过了半月后，再登陆成功了，使用正常。又过了一天，又出了同样问题，退出重新登陆又好了。所以此问题看来不大，好用。

**Comment by iikira** [comment]
旧版的登录功能不能用了，更新v3.5.6及以上，试一试
