### ISSUE TITLE
有些问题请教一下

### ISSUE THREAD

**Issue by weargle** [iikira/BaiduPCS-Go#63]
## 首先祝你新年快乐！！！

感谢你的百度登录源码我终于登录百度网盘了，我看了这个项目源码发现你在config.json保存了ptoken和stoken，请问它们有啥作用

**Comment by iikira** [comment]
目前没有用……

**Comment by weargle** [comment]
那你为啥保存啊

**Comment by iikira** [comment]
以后可能会用到啊

**Comment by iikira** [comment]
可以用通配符，看readme

**Comment by weargle** [comment]
![20180216155711](https://user-images.githubusercontent.com/26951765/36298242-176c72f8-1332-11e8-877b-02bf131f7ca0.png)
请教下，这个红色矩形圈住的这个变量是post参数还是表单

**Comment by iikira** [comment]
post元数据，两个都可以

**Comment by weargle** [comment]
跟着你写的请求结果"error_code":"110001"，你遇到过吗，怎么解决

**Comment by iikira** [comment]
应该是百度贴吧的签名错误……签名规则参考https://github.com/iikira/baidu-tools

**Comment by weargle** [comment]
找到了，是sign，但我看不到，如果可以你能简单说下它的计算吗，麻烦了

**Comment by iikira** [comment]
https://github.com/iikira/baidu-tools/tree/master/tieba/tiebautil

你看下源码吧

**Comment by weargle** [comment]
谢谢，成功了

**Comment by weargle** [comment]
请问https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=260149&path=" +  path这段URL是获取下载链接的吗，如何获取，我试下get、post都不能获取

**Comment by iikira** [comment]
要带上cookie的

**Comment by weargle** [comment]
带上BDUSS？我带上了，head方法请求到文件信息，get方法是一直在处于运行，post是500状态码

**Comment by iikira** [comment]
这就奇怪了，网址没问题啊……正常情况下用get方法会直接返回文件内容……

**Comment by weargle** [comment]
不知道，get请求一直在发送请求代码那边，没法继续向下执行，我明天在试试，麻烦你了

**Comment by weargle** [comment]
下载成功了，谢谢，但下载过程中发现服务器那边不是一直连续传过来，导致出现读取超时，想问下你怎么解决的，还是你没有遇到

**Comment by weargle** [comment]
在下载过程会突然拿不到数据，导致报读取时间超时情况，请问你有这种情况吗？你是如何解决的

**Comment by iikira** [comment]
是不是每获取262144B的数据就会卡一次……重新连接解决

**Comment by weargle** [comment]
对。我也是这样解决
