### ISSUE TITLE
无法下载与提取直链

### ISSUE THREAD

**Issue by RedsPower** [iikira/BaiduPCS-Go#631]
可以确定账号已登录，但每次下载总报403（服务器拒绝访问）错误，提取直链也不能用
提取直链时的错误：
遇到错误, 远端服务器返回错误, 代码: 31074, 消息: directory can't be downloaded
此错误是在一次下载中突然出现的

**Comment by iikira** [comment]
403问题参见 #460 
提取直链不支持目录，这是网盘接口的限制，换成文件试一试
