### ISSUE TITLE
Windows 64bit 3.5.6 下载速度0K

### ISSUE THREAD

**Issue by Caesar-Kindle** [iikira/BaiduPCS-Go#634]
![image](https://user-images.githubusercontent.com/19633597/51793090-eddba180-21b2-11e9-9e9c-8fcfb8590409.png)
尝试了N个文件都一样emmmmm（似乎换过了网络环境也一样，3.5.2大约在2019年1月开始突然0K，更新后仍然0K）

**Comment by Caesar-Kindle** [comment]
![image](https://user-images.githubusercontent.com/19633597/51793173-13b57600-21b4-11e9-90e7-3ded1fa71352.png)
启用调试后，下载便满屏都是debug

**Comment by aplmikex** [comment]
appid改266719试试

**Comment by Caesar-Kindle** [comment]
> appid改266719试试

已设置，无效

**Comment by iikira** [comment]
可能是下载受到了限制，参考#460 （未解决）

**Comment by iikira** [comment]
可能是下载受到了限制，参考#460 （未解决）
