### ISSUE TITLE
作者能不能弄个限速设置

### ISSUE THREAD

**Issue by hao365** [iikira/BaiduPCS-Go#635]
这么暴力下载，谁也烦啊，被封是早晚的事，
为啥不弄个限速呢，只要比他自己的windows客户端快一点就行，反正是Linux后台默默的下。

**Comment by xf1** [comment]
自己设置成单连接下载就好了。
BaiduPCS-Go config set -max_parallel=1

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已增加上传、下载设置限速
