### ISSUE TITLE
安卓端通过源码更新出现403

### ISSUE THREAD

**Issue by Ecalose** [iikira/BaiduPCS-Go#636]
检测更新中, 稍候...
检测到新版本: v3.5.6
是否进行更新 (y/n): y
准备下载更新: BaiduPCS-Go-v3.5.6-android-21-arm64.zip
下载发生错误: 403 Forbidden
安装是通过软件源安装

**Comment by Ecalose** [comment]
检测更新中, 稍候...
检测到新版本: v3.5.6
是否进行更新 (y/n): y
准备下载更新: BaiduPCS-Go-v3.5.6-android-21-arm64.zip
下载发生错误: 403 Forbidden

**Comment by UQJRlex** [comment]
听说作者换源了。

**Comment by iikira** [comment]
请手动更新吧
