### ISSUE TITLE
建议添加文件列表序号操作

### ISSUE THREAD

**Issue by jth445600** [iikira/BaiduPCS-Go#64]
我在树莓派3平台上重新编译了一遍，在使用的过程中，我发现一个问题，输入文件全名很不方便，而且我的网盘中有很多的视频教程，在下载时更是不方便。
我觉得可以通过文件列表前的序号进行操作。
![image](https://user-images.githubusercontent.com/24479489/36238571-618c547e-123e-11e8-950f-cb7530b70439.png)

比如，我们可以直接输入
`download 0`
来下载 `1 课程介绍.mov `

**Comment by jth445600** [comment]
@iikira

**Comment by iikira** [comment]
在考虑了……

**Comment by jth445600** [comment]
我相信完善这个功能后，会变得十分方便。

**Comment by mogu1121** [comment]
看了#41 这个更方便

**Comment by jth445600** [comment]
然而两个月过去了，并没有什么改变，这个功能很难实现吗？我不懂go。

**Comment by mogu1121** [comment]
希望也支持 0-3,8,11-13

**Comment by iikira** [comment]
@jth445600 主要想直接实现tab补全路径功能。cli程序不适合加太多简便操作...

**Comment by jth445600** [comment]
就是因为命令行，才应该简便操作。我用手机juice ssh连接服务器下载百度网盘里的东西，文件名又都是中文标点加空格。手机粘贴复制很麻烦，打字更麻烦，有时候还得添加反斜杠。

**Comment by iikira** [comment]
可以用通配符啊
