### ISSUE TITLE
[windows] 使用SetFileValidData快速分配文件空间

### ISSUE THREAD

**Issue by myfreeer** [iikira/BaiduPCS-Go#646]
版本: BaiduPCS-Go-v3.5.6-windows-x64

在下载大文件时，BaiduPCS会花费较长时间分配文件空间，任务管理器中显示大量硬盘写入。
Windows API 中的[SetFileValidData](https://docs.microsoft.com/zh-cn/windows/desktop/api/fileapi/nf-fileapi-setfilevaliddata)可以跳过分配文件空间的填0过程，减小硬盘写入，减小下载前的等待时间，需要提权运行。

参考实现：
* <https://github.com/mzhou/setfilevaliddata/blob/master/setfilevaliddata/main.c>
* <https://github.com/aria2/aria2/blob/master/src/AbstractDiskWriter.cc>

**Comment by daiaji** [comment]
要为此提权不是很没必要吗？

**Comment by myfreeer** [comment]
> @daiaji 要为此提权不是很没必要吗？

1. 对于较大的文件，通过填0分配文件在机械硬盘上会消耗大量时间，在固态硬盘上会增大写入磨损
2. 可以判断是否提权，若已提权，则使用`SetFileValidData`，否则使用传统方式
