### ISSUE TITLE
建议修改开源协议

### ISSUE THREAD

**Issue by acbetter** [iikira/BaiduPCS-Go#65]
先感谢作者开发这么好的项目

Apache License 2.0 是不是太松了，容易被不良商家滥用，建议修改为更严格的开源协议如 GPL v3 等等。。

**Comment by iikira** [comment]
不是很懂开源协议，使用这个协议是因为改了别人写的下载器，协议也就跟着人家了……再说了要滥用的话，人家才不管你什么协议……
有时间的话，考虑重写下载器……
