### ISSUE TITLE
退出登录后重新登录失败

### ISSUE THREAD

**Issue by Sunybyjava** [iikira/BaiduPCS-Go#650]
无论是用账号密码登录还是使用 BDUSS 登录都会报以下错误：

> 检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: lookup tieba.baidu.com on 127.0.1.1:53: read udp 127.0.0.1:49966->127.0.1.1:53: i/o timeout

这是由于什么情况造成的？

**Comment by iikira** [comment]
检查你的dns 127.0.1.1 是否有效
