### ISSUE TITLE
[Windows] fixmd5 命令不存在

### ISSUE THREAD

**Issue by wordlesswind** [iikira/BaiduPCS-Go#652]
上传完大文件后，程序自动修复 MD5 失败，于是想手动试试，但发现命令不存在。

```
BaiduPCS-Go:/ account$ fixmd5 file
未找到命令: fixmd5
运行命令 BaiduPCS-Go help 获取帮助
```

**Comment by CL-Jeremy** [comment]
有自动修复 MD5 机制的版本还未将 fixmd5 独立出来（仅可以选择不自动修复），有 fixmd5 的版本还是开发版需要自行编译（无法自动修复 MD5，只能在上传以后使用 fixmd5），我是双版本共存的。服务器上我上传量太小基本用不到分片上传，如果不是数 GB 的文件的话可以关掉分片上传选项。
