### ISSUE TITLE
下载整个文件夹时，速度非常慢

### ISSUE THREAD

**Issue by jth445600** [iikira/BaiduPCS-Go#66]
下载单个文件时，设置300个并发下载，速度虽然不稳定，但是还是很快的。但是下载文件夹时，速度变得非常慢，甚至停止下载。使用版本v3.3.Beta3
![image](https://user-images.githubusercontent.com/24479489/36466779-bc091194-1716-11e8-822d-035495189a49.png)

**Comment by iikira** [comment]
速度慢的问题正在解决......你可以先尝试设置更高的并发量, 比如500......

**Comment by jth445600** [comment]
@iikira 辛苦了，希望这个项目能不断完善，并坚持下去。您可以在README末尾放个支付宝二维码，方便捐赠。

**Comment by iikira** [comment]
谢谢支持

**Comment by iikira** [comment]
尝试修复下载多个文件速度慢的bug, 160af1573fd373ef6bf44274ca04852e7dac6bd5, 可以编译运行程序试试效果,
原因可能在于, 下载最大并发量没有调整好, 感谢反馈啊...

**Comment by iikira** [comment]
下载新版本试试效果，如果还用问题请新开issue...
