### ISSUE TITLE
【询问】上传功能是否可以认为是足够可靠的？

### ISSUE THREAD

**Issue by mo-han** [iikira/BaiduPCS-Go#662]
嘛，下载另有办法，而且我本身不是下载狂人。
上传倒是一直用的挺多的，个人感觉这个程序的上传是所有类似软件中做的最好的，既对命令行友好，又能保证速度。
但是一直不清楚这个上传到底有多可靠，我上传的东西大多数都没有重新下载验证过。只在很久以前有过一次集中测试，测试结果当然是没问题的。不过后来百度封了下载，不知道上传会不会受到影响。
我家里服务器上还是万年没更新的老版本：BaiduPCS-Go version v3.5.3

**Comment by iikira** [comment]
相应的算法未仔细测试，目前未发现上传文件损坏的情况
