### ISSUE TITLE
macOS Mojave 10.14.3 检测BDUSS有效性网络错误

### ISSUE THREAD

**Issue by arfaWong** [iikira/BaiduPCS-Go#665]
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp [2400:da00:5f26:400::6f2d:b2f]:80: connect: network is unreachable

**Comment by arfaWong** [comment]
登录的时候为什么会使用了百度的 ipv6 地址？

**Comment by Benny233** [comment]
> 检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp [2400:da00:5f26:400::6f2d:b2f]:80: connect: network is unreachable

你找到解决方法了吗

**Comment by arfaWong** [comment]
@Benny233 网络问题。我这里的问题是 `tieba.baidu.com` 这个域名被解析到一个我无法访问的 ipv6 地址了。
