### ISSUE TITLE
在ios12上运行出错

### ISSUE THREAD

**Issue by wutaijieing** [iikira/BaiduPCS-Go#666]
iPad:~/BaiduPCS-Go root# ./BaiduPCS-Go-arm64
Killed: 9

只有这个arm64的才有提示，其他版本提示cpu错误
设备信息如下：
iPad:~/BaiduPCS-Go root# uname -a
Darwin iPad 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:31:58 PST 2018; root:xnu-4903.232.2~1/RELEASE_ARM64_T8011 iPad7,1 arm64 J120AP Darwin
系统ios12.1.1

**Comment by iikira** [comment]
没有设备，没办法测试呢

**Comment by FanstasCw** [comment]
你好，怎么在ios12上运行

**Comment by puppywang** [comment]
Jailbreak

**Comment by iikira** [comment]
v3.6已发布, 应该修复这个问题了
