### ISSUE TITLE
一次就被封了

### ISSUE THREAD

**Issue by yangqi52717** [iikira/BaiduPCS-Go#667]
我今天用了一下，下载了一个win7，速度7MB/s，然鹅一个文件下载完，就被封了，现在官方客户端也没速度

**Comment by Yueeeeee** [comment]
发现被封了之后,赶紧来issues找办法,没想到办法没找到,找到了安慰,老铁不哭

**Comment by zhangwenqiang123** [comment]
听说充个会员就好了

**Comment by iikira** [comment]
此类问题请移步#460 讨论
