### ISSUE TITLE
最新的版本编译成ARM出错，NAS上用不了了。

### ISSUE THREAD

**Issue by lonee8** [iikira/BaiduPCS-Go#67]
有空的话检查一下。

**Comment by iikira** [comment]
第三方包的问题，已反馈，临时处理方法，将 BaiduPCS-Go /vendor/github.com/v2pro/plz/reflect2/reflect2_amd64.s 改名为 reflect2.s 即可

**Comment by iikira** [comment]
已修复, 8afee34b377d8d1addf35614dcf5a710368082bf
