### ISSUE TITLE
请问go写的ngrok对应架构的android版的怎么编译呀

### ISSUE THREAD

**Issue by Sesprie** [iikira/BaiduPCS-Go#670]
我尝试编译ngrok，想在android版本上用但总是post请求的时候报错, 但是编译的windows版的ngrok使用是正常的
我之前下载过其他android版本baidupcs-go的好像也是这个错误，
BaiduPCS-Go-v3.5.6-android-21-arm64.zip
只有这个版本可以在我手机上使用
     ▄███████████▄       OS: Android 7.1.1
  ██ █████████████ ██    Baseband: msm
  ██ █████████████ ██    Kernel: aarch64 Linux 3.10.84-perf-g5f97e29
  ██ █████████████ ██    Uptime: 6d 15h 41m
     █████████████       CPU: AArch64 Processor rev 4 (aarch64)
      ███████████        GPU: AArch64 Processor rev 4 (aarch64)
       ██     ██         RAM: 2181MiB / 3580MiB
这是手机型号，
GOOS=linux GOARCH=arm make release-client
GOOS=linux GOARCH=arm64 make release-client
这两条编译命令都尝试过，
报错如下
 control recovering from failure dial tcp: lookup xxx.com on [::1]:53: read udp [::1]:38815->[::1]:53: read: connection refused # 网址隐藏掉了
可以帮忙看一下么，谢谢了

**Comment by jinjiachen** [comment]
安卓上直接能用啊，不能再自己编辑，termux了解下

 

From: noreply@github.com [mailto:noreply@github.com] On Behalf Of Sesprie
Sent: Thursday, March 21, 2019 4:05 PM
To: iikira/BaiduPCS-Go <BaiduPCS-Go@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [iikira/BaiduPCS-Go] 请问go写的长须对应架构的android版的怎么编译呀 (#670)

 

我尝试编译ngrok，想在android版本上用但总是post请求的时候报错
我之前下载过其他android版本的好像也是这个错误，但是编译的windows使用是正常的
BaiduPCS-Go-v3.5.6-android-21-arm64.zip
只有这个版本可以在我手机上使用
▄███████████▄ OS: Android 7.1.1
██ █████████████ ██ Baseband: msm
██ █████████████ ██ Kernel: aarch64 Linux 3.10.84-perf-g5f97e29
██ █████████████ ██ Uptime: 6d 15h 41m
█████████████ CPU: AArch64 Processor rev 4 (aarch64)
███████████ GPU: AArch64 Processor rev 4 (aarch64)
██ ██ RAM: 2181MiB / 3580MiB
这手机型号，
GOOS=linux GOARCH=arm make release-client
GOOS=linux GOARCH=arm64 make release-client
这两条编译命令都尝试过，
报错如下
control recovering from failure dial tcp: lookup xxx.com on [::1]:53: read udp [::1]:38815->[::1]:53: read: connection refused # 网址隐藏掉了
可以帮忙看一下么，谢谢了

**Comment by Sesprie** [comment]
嗯，就是在termux上打开的，那条报错信息就是termux中的打印日志
./ngrok -config=ngrok.cfg -log=stdout 8022

**Comment by jinjiachen** [comment]
我用过没问题啊，你下的BAIDUPCS是什么架构的，是ARM吗

**Comment by Sesprie** [comment]
啊，我可能没表达清楚，baidupcs-go用的正常，想请问一下怎么编译ngrok的android对应的版本

**Comment by jinjiachen** [comment]
据我所知 ngrok这个是起内网穿透作用的吧 没用过，但是我推荐FRP 这个作用相同 用起来更方便 还有ARM版

**Comment by iikira** [comment]
如果android已root，创建文件`/etc/resolv.conf` 并写入内容
```
nameserver 8.8.8.8
```
应该就能用了

或者，
GOOS一定要设置成android，不可以linux，重新编译。
参考: http://www.iikira.com/2017/08/09/golang-compile-jc-2/
