### ISSUE TITLE
登录成功后直接断开，重回登录界面

### ISSUE THREAD

**Issue by onetailalen** [iikira/BaiduPCS-Go#671]
每次登陆后都重回登录界面，控制台显示以下信息

百度帐号登录成功:                                                                                                                                                  
globalSessions 0xc0008f7260                                                                                                                                
成功解锁                                                                                                                                                       
保存配置成功                                                                                                                                                     
Websocket连接断开: EOF  

是否是因为百度网盘屏蔽了

**Comment by 965929275** [comment]
我也遇到了这个问题，请问您是如何解决的？

**Comment by onetailalen** [comment]
百度网盘登录以后把用户名设置一下，我本来没设置，后来设置了英文用户名，就可以登录了






在 2019-04-17 00:03:59，"Tricky" <notifications@github.com> 写道：


我也遇到了这个问题，请问您是如何解决的？
