### ISSUE TITLE
在Linux下载时远程ssh慢或卡死

### ISSUE THREAD

**Issue by RealJt12** [iikira/BaiduPCS-Go#672]
首先感谢作者的付出，给大家开发出这么优秀的工具。我把程序放在Linux中，通过远程ssh来操作下载，下载中会导致ssh很慢，下载进度/网速等信息输出很慢，再开一个ssh远程卡死。

**Comment by linux0ne** [comment]
远程端是什么系统   什么硬件   不会是raspberry pi 吧？

**Comment by RealJt12** [comment]
在mac上通过ssh操作linux上部署的baidupcs-go程序，linux系统配置为i3 8100 + Deepin，在同一路由器下

**Comment by linux0ne** [comment]
i3的处理器能力是够了， 不知道内存是多少？   一般意义上讲“卡死”  是线程分配和缓存调节方面的问题

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已增加上传、下载设置限速
