### ISSUE TITLE
登陆错误代码-1

### ISSUE THREAD

**Issue by yuyishenyuan** [iikira/BaiduPCS-Go#673]
版本3.5.6
环境Windows10
登陆时报错：
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: proxyconnect tcp: dial tcp 127.0.0.1:1080: connectex: No connection could be made because the target machine actively refused it.
登陆时需要开启vpn，关闭vpn就登陆失败，vpn代理端口1080

**Comment by iikira** [comment]
是代理设置的问题，参照#677
