### ISSUE TITLE
最新下载的没有网页端了吗

### ISSUE THREAD

**Issue by xiaobaizx** [iikira/BaiduPCS-Go#674]
root@kali:/mnt/BaiduPCS-Go-v3.5.6-linux-amd64# ./BaiduPCS-Go ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

登录成功了 输入什么都是报错

**Comment by hhxxhg** [comment]
看看 #387有惊喜

**Comment by iikira** [comment]
参见#387
