### ISSUE TITLE
不能登录了

### ISSUE THREAD

**Issue by easy-boy** [iikira/BaiduPCS-Go#677]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: proxyconnect tcp: dial tcp 127.0.0.1:1080: connect: connection refused

archlinux

**Comment by wallena3** [comment]
刚才测试可以登录

**Comment by Yifei0727** [comment]
`dial tcp 127.0.0.1:1080` 
是你代理的问题吧？ 
`connection refused` 应该是你的代理没启动
去掉代理 `config set --proxy=''` 试试

**Comment by easy-boy** [comment]
好的，我再试试

在 2019/4/3 上午9:59, 張艺飞 写道:

dial tcp 127.0.0.1:1080
是你代理的问题吧？
connection refused 应该是你的代理没启动
去掉代理 config set --proxy='' 试试

**Comment by iikira** [comment]
测试正常，是你代理设置的问题
