### ISSUE TITLE
获取分享列表失败

### ISSUE THREAD

**Issue by fuck2ky** [iikira/BaiduPCS-Go#678]
列出分享列表失败: 列出分享列表: json 数据解析失败, baidupcs.shareListJSON.List: baidupcs.ShareRecordInfoList: baidupcs.ShareRecordInfo.FsIds: []string: ReadString: expects " or n, but found 7, error found in #10 byte of ...|"fsIds

**Comment by awayme** [comment]
我也遇到同样的错误了
列出分享列表失败: 列出分享列表: json 数据解析失败, baidupcs.shareListJSON.List: baidupcs.ShareRecordInfoList: baidupcs.ShareRecordInfo.FsIds: []string: ReadString: expects " or n, but found 5, error found in #10 byte of ...|"fsIds":[5123222909|..., bigger context ...|time":0,"expiredTime":0,"expiredType":1,"fsIds":[5196413338],"ip":1939336,"is_card":0,"name"|...

版本：BaiduPCS-Go-v3.5.6-linux-amd64
操作系统：Ubuntu 16.4 LTS

另外问一下开发大神，有可能实现命令来生成加密分享么，现在的分享链接是非加密的
