### ISSUE TITLE
代码: 31064, 消息: file is not authorized

### ISSUE THREAD

**Issue by ZLZ-Nancy** [iikira/BaiduPCS-Go#679]

**Comment by ZLZ-Nancy** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized

执行ls命令时报错

**Comment by iikira** [comment]
你应该是修改了appid，将其改回266719即可

**Comment by Oaroyal** [comment]
BaiduPCS-Go config set -appid 266719执行后再重新登录是ok的，cd以及ls返回都是ok的，但下载具体文件，直接就403 禁止，

**Comment by iikira** [comment]
下载异常，移步#460 讨论哦（未解决）

**Comment by GaryDoooo** [comment]
> 你应该是修改了appid，将其改回266719即可

改了appid，重新登录，还是这个31326错误。。。没遇到403.
