### ISSUE TITLE
下载文件错误，406 Not Acceptable

### ISSUE THREAD

**Issue by wstlxx** [iikira/BaiduPCS-Go#683]
所有设备都是如此，一小时前还没有问题！是不是上面动手了

**Comment by wstlxx** [comment]
等了一会儿自己就好了，看看大佬知不知道是怎么回事OTL

**Comment by iikira** [comment]
可能是请求过于频繁

**Comment by Oaroyal** [comment]
果然大家都遇到了问题，昨天上午用的时候还是很麻利，刚才退出后，能重新登录，但列文件或目录，
cd /
获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file
ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized

**Comment by CRISTIANO-HAO** [comment]
> 果然大家都遇到了问题，昨天上午用的时候还是很麻利，刚才退出后，能重新登录，但列文件或目录，
> cd /
> 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file
> ls
> 获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized
[0] 提示: 当前下载最大并发量为: 100, 下载缓存为: 65536
[1] 加入下载队列: /视频/.。。。
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file
