### ISSUE TITLE
秒传功能只给一个md5sum参数无法上传成功

### ISSUE THREAD

**Issue by Sesprie** [iikira/BaiduPCS-Go#684]
刚试了下BaiduPCS-Go ru -length=xxx -md5sum=xxx /test，显示
秒传文件失败, 消息: 秒传文件: 遇到错误, 远端服务器返回错误, 代码: 31079, 消息: 秒传文件失败

但是尝试
BaiduPCS-Go ru -length=xxx -md5sum=xxx -slicemd5=xxx /test
可以上传成功

请问export可以导出slicemd5么

**Comment by iikira** [comment]
可以了，参见#537

**Comment by Sesprie** [comment]
好，明白了，谢谢  ：)
