### ISSUE TITLE
去掉代理 config set --proxy='' 命令无效

### ISSUE THREAD

**Issue by yuyishenyuan** [iikira/BaiduPCS-Go#685]
参见问题#673 的回复
去掉代理 config set --proxy='' 命令无效
Incorrect Usage: flag provided but not defined: -proxy

**Comment by pongfcnkl** [comment]
直接删除pcs_config.json配置文件试试看？
另外是最新版吗？

https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by yuyishenyuan** [comment]
> 直接删除pcs_config.json配置文件试试看？
> 另外是最新版吗？
> 
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
请问这个配置文件在哪里？我是用的windows 10

**Comment by yuyishenyuan** [comment]
> 直接删除pcs_config.json配置文件试试看？
> 另外是最新版吗？
> 
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
是最新版本，用过VPN，我怀疑是我的电脑的设置，但是没找到在哪儿~pcs_config.json文件proxy配置是空的。

**Comment by pongfcnkl** [comment]
> > 直接删除pcs_config.json配置文件试试看？
> > 另外是最新版吗？
> > https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> > 是最新版本，用过VPN，我怀疑是我的电脑的设置，但是没找到在哪儿~pcs_config.json文件proxy配置是空的。

vpn是哪个？ss还是系统自带的？

**Comment by yuyishenyuan** [comment]
> > > 直接删除pcs_config.json配置文件试试看？
> > > 另外是最新版吗？
> > > https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> > > 是最新版本，用过VPN，我怀疑是我的电脑的设置，但是没找到在哪儿~pcs_config.json文件proxy配置是空的。
> 
> vpn是哪个？ss还是系统自带的？

SSR
