### ISSUE TITLE
安卓的教程该更新了

### ISSUE THREAD

**Issue by mikuxs** [iikira/BaiduPCS-Go#69]
curl -L https://github.com/iikira/BaiduPCS-Go/releases/download/beta-v1/baidupcs_go-beta-v1-
到这个卡了

**Comment by iikira** [comment]
这个是第一个版本的示例，确实挺老……更换链接即可

**Comment by mikuxs** [comment]
萌新一个，不太懂，是把最新的文件下载连接替换掉上面这个吗？

**Comment by iikira** [comment]
是啊，希望你清楚这条命令是什么意思

**Comment by mikuxs** [comment]
谢谢
