### ISSUE TITLE
关于文件下载完成后的文件校验

### ISSUE THREAD

**Issue by Tdickson3** [iikira/BaiduPCS-Go#690]
下载了一个29GB的文件，用了十分钟左右，但是校验已经过去差不多半个多小时了，仍然在校验，这种情况正常吗？

**Comment by pongfcnkl** [comment]
下载之前用-nocheck关掉

**Comment by iikira** [comment]
结果怎么样了

**Comment by Tdickson3** [comment]
> 结果怎么样了

一个小时之后，直接Ctrl + C解决了😂

**Comment by AhFook** [comment]
應該趁它未校對完畢，急急把視頻抄去別的地方。
校對完畢便任它刪除原来的版本。反正抄本已經可以用了。

**Comment by iikira** [comment]
更新了校验文件算法, 05ebf1c97e5a6dc3aa8d5ffe85aa60de4d73a68b
应该不会无期限校验文件了

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 尝试修复了原有的校验文件算法, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧
