### ISSUE TITLE
Linux客户端如何设置代理

### ISSUE THREAD

**Issue by jth445600** [iikira/BaiduPCS-Go#691]
有没有大佬给个示例，怎么在Linux平台上给BaiduPCS-Go客户端添加代理，HTTP和socket5都行

**Comment by SCGabriel** [comment]
> 有没有大佬给个示例，怎么在Linux平台上给BaiduPCS-Go客户端添加代理，HTTP和socket5都行

Google proxychains和proxychains-ng项目
