### ISSUE TITLE
请求增加一个上传限速功能

### ISSUE THREAD

**Issue by PyzmxU** [iikira/BaiduPCS-Go#692]
这是我用过最好的百度客户端，安装在软路由器上，日夜不停的上传，家用上传宽带10M较小，希望增加一个上传限速功能，不影响日常使，非常感谢 ：〉

**Comment by landall** [comment]
> 这是我用过最好的百度客户端，安装在软路由器上，日夜不停的上传，家用上传宽带10M较小，希望增加一个上传限速功能，不影响日常使，非常感谢 ：〉

用软路由的系统命令限速岂不是更方便?
