### ISSUE TITLE
我老是下着下着就下不动了，速度降为0

### ISSUE THREAD

**Issue by widon1104** [iikira/BaiduPCS-Go#694]
我老是下着下着就下不动了，速度降为0
这是怎么回事，能够恢复吗？

**Comment by pongfcnkl** [comment]
最新版开超级会员 
https://ci.appveyor.com/project/iikira/baidupcs-go/history

没钱的话百度搜百度网盘超级会员有低价出租

**Comment by iikira** [comment]
下载异常问题，请移步#460 讨论（未解决）
