### ISSUE TITLE
macos 下载文件不完整问题

### ISSUE THREAD

**Issue by ZHANGLIANGGIT** [iikira/BaiduPCS-Go#695]
![image](https://user-images.githubusercontent.com/16606476/56850834-844a6b00-693a-11e9-85db-74c001188125.png)
已经设置了appid,也将文件移动到了/apps/baidu_shurufa
使用 d 命令下载一个700+M的文件时，只下载了1.7M之后，就提示下载完成了。

**Comment by ZHANGLIANGGIT** [comment]
PCS小白，求大佬指点下。tks

**Comment by iikira** [comment]
你这个文件应该是被屏蔽了，登录官方的网盘看一下

**Comment by szh21566** [comment]
> 你这个文件应该是被屏蔽了，登录官方的网盘看一下
被屏蔽的文件还能找回来吗？仿佛直接给我删掉了啊，里面东西没了😢

**Comment by iikira** [comment]
@szh21566 屏蔽一般是指，文件被替换成温馨提示、8秒温馨提示等。联系网盘的客服，有一点点点可能找回来吧

**Comment by szh21566** [comment]
好的，谢谢巨佬！


| |
沈志豪
|
|
szh21566@163.com
|
签名由网易邮箱大师定制


在2019年05月17日 12:18，iikira<notifications@github.com> 写道：

@szh21566 屏蔽一般是指，文件被替换成温馨提示、8秒温馨提示等。联系网盘的客服，有一点点点可能找回来吧
