### ISSUE TITLE
下載文件夾內的文件

### ISSUE THREAD

**Issue by heilok1014** [iikira/BaiduPCS-Go#697]
如題 把cd轉了我的資源後 想下載資源內文件夾的文件 應該輸入甚麼命令才對？

**Comment by iikira** [comment]
直接输入文件名即可

**Comment by heilok1014** [comment]
對不起 問得不好 假如要下載圖裡面的檔案或是幾層資料夾內的檔案應該輸入甚麼命令？
![螢幕截圖 2019-04-28 下午10 38 30](https://user-images.githubusercontent.com/50070822/56865948-6a765a00-6a06-11e9-9fd8-406d440cb442.png)

**Comment by iikira** [comment]
可以使用通配符下载哦

```
BaiduPCS-Go d *
```

会自动下载文件夹里层的文件
