### ISSUE TITLE
windows怎么用啊？？

### ISSUE THREAD

**Issue by changecj** [iikira/BaiduPCS-Go#699]
GOROOT=/usr/local/go1.10.4
go=$GOROOT/bin/go

脚本里要找go的路径，我用Windows的路径
D:\Program Files (x86)\go

不行，第一步就起不来，求指点！！

**Comment by changecj** [comment]
Windows上怎么用，教程写的是双击：运行程序，哪个文件也没写？

build.sh吗？

双击运行完啥也没有，一直报 no directory!!!

**Comment by pongfcnkl** [comment]
windows不是最简单的？
https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
直接下载BaiduPCS-Go-windows-386.zip
解压双击baidupcs-go,exe就行了

**Comment by changecj** [comment]
> windows不是最简单的？
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts
> 直接下载BaiduPCS-Go-windows-386.zip
> 解压双击baidupcs-go,exe就行了

太感谢了！！！
