### ISSUE TITLE
希望添加磁盘缓存功能 [已解决]

### ISSUE THREAD

**Issue by AlioDream** [iikira/BaiduPCS-Go#7]
- 有些字打不出来，不过无伤大雅

- 高速下载时磁盘占用率100%，希望添加磁盘缓存功能

**Comment by iikira** [comment]
好!

**Comment by dxvgef** [comment]
为什么不能直接给出下载地址让我们用别的下载工具下载呢？

**Comment by redapple0204** [comment]
@dxvgef 别的工具效率很低啊

**Comment by iikira** [comment]
@dxvgef 这个下载是要带着cookie信息才能给下载的……所以……

**Comment by iikira** [comment]
增加了 [#444df06](https://github.com/iikira/BaiduPCS-Go/commit/444df06991b14ef0fb784a3d08acefff0748718a)

**Comment by AlioDream** [comment]
编译测试正常.磁盘占用率没那么高了
但是..停不下来...不知道是不是我编译问题
![6 m z 1x2zwx0uqxsq vdi](https://user-images.githubusercontent.com/19420642/35197085-c6efa050-ff15-11e7-8518-5d746fe8832a.png)
![xghfu31cn 5nkhnpm pbv h](https://user-images.githubusercontent.com/19420642/35197091-ce25acca-ff15-11e7-8aa9-ba280671d1a5.png)
知道有这个问题的话就关闭吧.

**Comment by iikira** [comment]
可能是你的cache_size设的太高了……我看一下……

**Comment by AlioDream** [comment]
800000确实大但是没超出推荐值 (摊手

**Comment by iikira** [comment]
一万就差不多了吧……

**Comment by AlioDream** [comment]
试了三次，分别是缓存设置2w，20w，80w
下载时对应的磁盘占用率: 2w:100%  20w:80%  80w:60%
对应结果: 2w:正常完成 20w:正常完成 80w:超出文件大小还在下载

另外设置80w测试时发现个有趣的现象，大量占用磁盘的好像是读操作，写入确实有缓存
![3uxes wiimipf4 78reat29](https://user-images.githubusercontent.com/19420642/35260832-5f4204f0-0048-11e8-817d-474bca64b37b.png)

**Comment by iikira** [comment]
。。。

下载停不下来的问题应该修复了: [#f1a37ca](https://github.com/iikira/BaiduPCS-Go/commit/f1a37ca512dfe6502d247fdde82a996a3e6a5e09)

另外cache_size不要设置太高了，因为，我发现并没有什么意义。。

**Comment by hzc54188** [comment]
哥机械硬盘快要爆炸了啦

**Comment by hzc54188** [comment]
小白表示没有找到设置cache_size选项呢，作者大人能给出操作说明吗

**Comment by iikira** [comment]
@hzc54188 编译安装吧，还没发布呢……

**Comment by AlioDream** [comment]
没问题了，测试磁盘占用在可接受范围内。
(￣▽￣)／~

**Comment by reaCodes** [comment]
SSD有必要修改cache_size的值吗？

**Comment by iikira** [comment]
有必要的

**Comment by reaCodes** [comment]
我是觉得没什么差别的，无论是下载速度还是磁盘占用上。请问，一般SSD这个值设置在多少合适，总感觉这是玄学😄

`cache_size = 30000`

---
![image](https://user-images.githubusercontent.com/13817254/39954215-31d05a02-55ee-11e8-9ee1-b68790ca79ae.png)
`cache_size = 90000`

---
![image](https://user-images.githubusercontent.com/13817254/39954230-77714cb0-55ee-11e8-86b4-e6aedc673bc5.png)

**Comment by reaCodes** [comment]
@iikira 请问这里的数值单位是什么，b还是B？

**Comment by iikira** [comment]
字节

**Comment by reaCodes** [comment]
那就是B了

**Comment by iikira** [comment]
只是推荐值，自行设置
