### ISSUE TITLE
功能建议： 增加代理设置

### ISSUE THREAD

**Issue by uniyu** [iikira/BaiduPCS-Go#70]
目前我在用3.2.2
不论是shadowsocks全局代理还是 proxifier全局，这个软件都不会走代理
希望作者能添加手动设置代理的功能

**Comment by iikira** [comment]
增加了代理配置项, 从终端环境变量获取代理, 21dba4910321da3392e61002a6f74eaa562d0720, 可以更新版本试试
在苹果系统，设置 ALL_PROXY 即可
```
export ALL_PROXY=socks5://127.0.0.1:1080
```

其他的操作系统，未测试，建议你网上搜索一下

**Comment by uniyu** [comment]
windows 10 系统， 3.3beta4
不能走代理
ALL_PROXY  HTTP_PROXY  HTTPS_PROXY 都设置过了

**Comment by iikira** [comment]
那就奇怪了，明天测试一下……

**Comment by iikira** [comment]
试试将socks5转成http代理

**Comment by iikira** [comment]
亲测可用
设置代理示例 (windows):
```
set HTTP_PROXY=socks5://localhost:1086
```
如果上面的不可用: 
```
set HTTP_PROXY=http://localhost:1087
```
端口号改成你自己的...

**Comment by linyf2008** [comment]
建议单列代理功能。很多时候其他应用不用代理，不想为单独一个程序设置全局的代理。

**Comment by linux0ne** [comment]
> 亲测可用
> 设置代理示例 (windows):
> 
> ```
> set HTTP_PROXY=socks5://localhost:1086
> ```
> 
> 如果上面的不可用:
> 
> ```
> set HTTP_PROXY=http://localhost:1087
> ```
> 
> 端口号改成你自己的...

linux下，可以在终端里设置环境变量，这样GO程序就可以自动识别调用了，可是windows下，怎么设置这个代理的环境变量呢？

windows下，代理功能一般都是在在浏览器里设置代理的。
