### ISSUE TITLE
代码：31326，被百度拉黑了，就没法儿再用了吗？

### ISSUE THREAD

**Issue by changecj** [iikira/BaiduPCS-Go#700]
消息：user is not authorized,hitcode:123

我就下了一个1.6G的电影，最高飚到6M/S，然后再下就不行了

看来这个是会被封的啊，那这个软件的意义也不大了啊，这么好的软件，感觉用不了，太可惜了。

**Comment by pongfcnkl** [comment]
这个方法试试？
https://loli.today/archives/279
还是被限那就超级会员吧
