### ISSUE TITLE
安卓端更新问题

### ISSUE THREAD

**Issue by yuannuan** [iikira/BaiduPCS-Go#702]
软件源更新问题
测更新中, 稍候...
检测到新版本: v3.5.6
准备下载更新: BaiduPCS-Go-v3.5.6-android-21-arm64.zip
下载发生错误: 403 Forbidden
手动安装可以更新，但一更改appid下载目录就会强行变成
savedir       /data/data/com.termux/files/home/BaiduPCS-Go/download                 下载文件的储存目录

**Comment by pongfcnkl** [comment]
最好清除配置文件在手动更
https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by yuannuan** [comment]
> 最好清除配置文件在手动更
> https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

请问手动替换要如何操作

**Comment by pongfcnkl** [comment]
@yuannuan 
下载改名，然后复制下载的路径
直接cp 路径/xxx xxx
就好了

**Comment by yuannuan** [comment]
@pongfcnkl COPYRIGHT:
  (c) 2016-2018 iikira.
BaiduPCS-Go > cp /sdcard/BaiduPCS-Go-v3.5.6-android-21-arm64.zip
----
  BaiduPCS-Go cp - 拷贝文件/目录

USAGE:
  BaiduPCS-Go cp <文件/目录> <目标文件/目录>
  BaiduPCS-Go cp <文件/目录1> <文件/目录2> <文件/目录3> ... <目标目录>

CATEGORY:
  百度网盘

DESCRIPTION:

  注意: 拷贝多个文件和目录时, 请确保每一个文件和目录都存在, 否则拷 贝操作会失败.

  示例:

  将 /我的资源/1.mp4 复制到 根目录 /
  BaiduPCS-Go cp /我的资源/1.mp4 /

  将 /我的资源/1.mp4 和 /我的资源/2.mp4 复制到 根目录 /
  BaiduPCS-Go cp /我的资源/1.mp4 /我的资源/2.mp4 /

**Comment by pongfcnkl** [comment]
@yuannuan 没理解吗？
下载之后用解压软件解压，改名，比如原来是BaiduPCS-Go，那就直接改成a
ctrl+c退出
然后复制路径或者手打路径，用CP命令直接覆盖
比如cp /sdcard/download/2 2

**Comment by yuannuan** [comment]
@pongfcnkl 谢谢大佬指导
