### ISSUE TITLE
大佬啥时候能做个115的

### ISSUE THREAD

**Issue by 781015928** [iikira/BaiduPCS-Go#705]
百度河蟹太厉害

**Comment by pongfcnkl** [comment]
加密压缩防和谐

**Comment by 781015928** [comment]
> 加密压缩防和谐

成本太高了，我不是用来存，主要是用来下的

**Comment by pongfcnkl** [comment]
> 
> 
> > 加密压缩防和谐
> 
> 成本太高了，我不是用来存，主要是用来下的

115除了开车好像也没什么用吧，还不如做onedrive

**Comment by 781015928** [comment]
> > > 加密压缩防和谐
> > 
> > 
> > 成本太高了，我不是用来存，主要是用来下的
> 
> 115除了开车好像也没什么用吧，还不如做onedrive更简单点

对头，开车服务，有app 有pc

**Comment by iikira** [comment]
没计划

**Comment by hhxxhg** [comment]
> > > 加密压缩防和谐
> > 
> > 
> > 成本太高了，我不是用来存，主要是用来下的
> 
> 115除了开车好像也没什么用吧，还不如做onedrive更简单点

onedrive不是被墙了吗

**Comment by SCGabriel** [comment]
> 百度河蟹太厉害

115盘在chrome等浏览器都有别人写的插件，可以很简单的把下载导入aria2的rpc，为什么还要专门去写一个客户端？建议询问前可以问一下Google先

**Comment by landall** [comment]
> > > 加密压缩防和谐
> > 
> > 
> > 成本太高了，我不是用来存，主要是用来下的
> 
> 115除了开车好像也没什么用吧，还不如做onedrive更简单点

Onedrive的速度目前有很大问题。而且很多人不愿意花钱……至于白嫖的Onedrive for Business，速度就更成问题了。另外Onedrive不太可能支持秒传，所以其实上传文件非常慢。我正在写Baidu网盘到Onedrive的搬家工具，感觉实际用起来不太适合存大文件。

**Comment by landall** [comment]
> > > > 加密压缩防和谐
> > > 
> > > 
> > > 成本太高了，我不是用来存，主要是用来下的
> > 
> > 
> > 115除了开车好像也没什么用吧，还不如做onedrive更简单点
> 
> onedrive不是被墙了吗

只有网页被墙了，API照常用。不过大部分API都实现得不全，分享啥的都没人去实现。

**Comment by pongfcnkl** [comment]
> 
> 
> > > > 加密压缩防和谐
> > > 
> > > 
> > > 成本太高了，我不是用来存，主要是用来下的
> > 
> > 
> > 115除了开车好像也没什么用吧，还不如做onedrive更简单点
> 
> Onedrive的速度目前有很大问题。而且很多人不愿意花钱……至于白嫖的Onedrive for Business，速度就更成问题了。另外Onedrive不太可能支持秒传，所以其实上传文件非常慢。我正在写Baidu网盘到Onedrive的搬家工具，感觉实际用起来不太适合存大文件。

我用windows客户端速度基本上能保持最大宽带，秒传对我来说没啥用，很多文件都是私有文件。
