### ISSUE TITLE
更正一下403 forbidden的问题

### ISSUE THREAD

**Issue by xxxmailk** [iikira/BaiduPCS-Go#706]
准确一点说是……开个超级会员就可以继续用这个下载了。
常年在linux上下镜像文件，作者帮了大忙。

**Comment by HallWoodZhang** [comment]
确实是这样，我今天也是使用Linux下载训练集失败，去官网充了个超级会员就行了。
其实我一直不反对百度收费，但是我是一个Linux用户，强制让所有用户用客户端下载大文件对于我来说非常不适。

**Comment by dxh007** [comment]
今天用的时候突然403了，然后我冲了一个月的超级会员，立马就可以用这个工具了。

**Comment by QuentinChansey** [comment]
所以意思到底是怎样，你们讲得好含糊啊，是充了然后可以无限使用这个工具的意思吗?

**Comment by pongfcnkl** [comment]
> 
> 
> 所以意思到底是怎样，你们讲得好含糊啊，是充了然后可以无限使用这个工具的意思吗?

意思是充30块钱就行

**Comment by jeerychris** [comment]
又花了30大洋

**Comment by QuentinChansey** [comment]
我发现等几天它自己有速度的时候，就不要把线程数设那么高就行了，然后一直用就不会触发限速机制，就不用充钱了

**Comment by whutliqi** [comment]
请问线程数一般设置到多少才不会被发现呢？

**Comment by whutliqi** [comment]
> 我发现等几天它自己有速度的时候，就不要把线程数设那么高就行了，然后一直用就不会触发限速机制，就不用充钱了

请问线程数一般设置成多少才不会被发现呢？

**Comment by sky96111** [comment]
> > 我发现等几天它自己有速度的时候，就不要把线程数设那么高就行了，然后一直用就不会触发限速机制，就不用充钱了
> 
> 请问线程数一般设置成多少才不会被发现呢？

似乎是每月超过10g异常流量就会触发限速

**Comment by GaryDoooo** [comment]
> > > 我发现等几天它自己有速度的时候，就不要把线程数设那么高就行了，然后一直用就不会触发限速机制，就不用充钱了
> > 
> > 
> > 请问线程数一般设置成多少才不会被发现呢？
> 
> 似乎是每月超过10g异常流量就会触发限速

我一直小水管慢慢下，10G也不行？

**Comment by landall** [comment]
我是在有超级会员的情况下做压力测试，结果403了。。。。目前已经四五天了，都没有恢复。。。。
没403之前大概会保持4MB/s的速度。我用3.3G的文件下载了估计有几百次吧，然后悲剧……

**Comment by sayainchina** [comment]
一般我都是用来搬运百度的东西到谷歌那边才用的，搬运一次给一次钱
