### ISSUE TITLE
网络请求错误

### ISSUE THREAD

**Issue by Charleschen1027** [iikira/BaiduPCS-Go#708]
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: net/http: TLS handshake timeout

**Comment by iikira** [comment]
https握手超时，重试操作吧

**Comment by freehuoshan** [comment]
我也遇到这个错误了，先是ls 提示重新登录　user noexist, 然后重新登录，无法登录的
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login: unexpected EOF
BaiduPCS-Go > ^C
