### ISSUE TITLE
下载大文件时速度突然降为零，然后系统死机

### ISSUE THREAD

**Issue by daisuki4gh** [iikira/BaiduPCS-Go#709]
遇到的问题：下载大文件时（一般单个超过2GB时容易发生），下载速度先是达到带宽极限，然后在十几秒内骤降为零，然后系统（Mac OS ）中各种程序失去响应，只能强行手动关机。
在排除故障中发现：BaiduPCS-Go占用的虚拟内存有点异常，我硬盘500G、物理内存10G，看到它的虚拟内存却有530GB（见截图），是否跟此有关呢？谢谢！

![QQ20190514-222658](https://user-images.githubusercontent.com/40634329/57707114-9f86db80-7699-11e9-8fe8-bda44753b504.png)

```
系统版本：macOS Sierra 版本10.12.6 （64位 ）
客户端版本：BaiduPCS-Go - 百度网盘客户端 for darwin/amd64 v3.3.2
```

**Comment by iikira** [comment]
BaiduPCS-Go版本挺旧的，更新一下看看情况

**Comment by daisuki4gh** [comment]
> BaiduPCS-Go版本挺旧的，更新一下看看情况

后来更新版本后貌似没有再出现，谢谢。

**Comment by iikira** [comment]
那就先关闭啦
