### ISSUE TITLE
出现connection reset by peer导致下载失败

### ISSUE THREAD

**Issue by 1113260501** [iikira/BaiduPCS-Go#71]
read tcp 10.0.0.4:37530->58.217.200.64:80: read: connection reset by peer (跳过...)
有可能和昨晚的网盘维护有关

**Comment by iikira** [comment]
是的，不知好了没有

**Comment by iikira** [comment]
好了吧

**Comment by 1113260501** [comment]
好了，不过速度没有以前稳定了
