### ISSUE TITLE
31045错误，消息: user not exists

### ISSUE THREAD

**Issue by OliverCWY** [iikira/BaiduPCS-Go#711]
今天突然出现这个问题，单文件可以下载不能下载文件夹
重新登陆、添加stoken bduss后仍然无效

**Comment by OliverCWY** [comment]
很迷。。。有的时候可以有的时候不行

**Comment by poly000** [comment]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
小黑屋账户（403），appid=266719

**Comment by HongnianZhang** [comment]
我也回到了，好像换手机号登陆会好些

**Comment by poly000** [comment]
> 
> 
> 我也回到了，好像换手机号登陆会好些

我试了一下 仍然是无规律出错

**Comment by leviBar** [comment]
今天我也发现了，估计是百度搞什么东西了。

**Comment by poly000** [comment]
> 
> 
> 今天我也发现了，估计是百度搞什么东西了。

有没有试过官方客户端

**Comment by Zangwill** [comment]
同样遇到 31045 错误：
```bash
$ ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists
```

**Comment by PromiseChan** [comment]
######我的解决方法#########
    设置 appid=266719     
    
    重新登录

    然后会自动返回到根目录

    遇到403 设置 config set -appid=265486

   在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip  即可下载
   
   用 cd 进入不了baidu_shurufa ，会重新变成31045

**Comment by zzzop** [comment]
相同情况，设置里改了浏览器的useragent，stoken，ptoken也不行，出现频率太高了，下载文件夹会漏掉很多文件。加个重试功能比较好，或者文件夹下载后显示出错文件

**Comment by pe200012** [comment]
Same problem here. 退出账号后连登入都不行了。

**Comment by pionxzh** [comment]
試試改User Agent, 到瀏覽器複製下就可以了

**Comment by OliverCWY** [comment]
> 試試改User Agent, 到瀏覽器複製下就可以了

没用的 我试过了

**Comment by Dr-Bluemond** [comment]
Same issue

**Comment by pyyzcwg2833** [comment]
同样遇到了这个问题，之前修改appid的方案已经失效了

**Comment by lkhtest** [comment]
appid被封杀了吧，我也是这个问题。。百度真的是恶心

**Comment by share18x** [comment]
bduss登录也不行了

**Comment by poly000** [comment]
目前仍然是不定时出错...登陆大概也是

**Comment by Xionghaizi001** [comment]
> 
> 
> ######我的解决方法#########
> 设置 appid=266719
> 重新登录
> 然后会自动返回到根目录
> 遇到403 设置 config set -appid=265486
> 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> 用 cd 进入不了baidu_shurufa ，会重新变成31045

这个方法亲测无效，考虑试下更换IP地址或者MAC地址

**Comment by PromiseChan** [comment]
> > ######我的解决方法#########
> > 设置 appid=266719
> > 重新登录
> > 然后会自动返回到根目录
> > 遇到403 设置 config set -appid=265486
> > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> 
> 这个方法亲测无效，考虑试下更换IP地址或者MAC地址

有没有先用appid=266719, 然后再用appid=265486,  我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了

**Comment by poly000** [comment]
> 
> 
> > > ######我的解决方法#########
> > > 设置 appid=266719
> > > 重新登录
> > > 然后会自动返回到根目录
> > > 遇到403 设置 config set -appid=265486
> > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > 
> > 
> > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> 
> 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了

有没有试多次l，看看还有没有错误
不然的话“解决了”“还是不行”emmm

**Comment by Xionghaizi001** [comment]
> 
> 
> > > ######我的解决方法#########
> > > 设置 appid=266719
> > > 重新登录
> > > 然后会自动返回到根目录
> > > 遇到403 设置 config set -appid=265486
> > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > 
> > 
> > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> 
> 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了

测试依然无效……怕是我的电脑或者账号被拉黑了……

**Comment by poly000** [comment]
> 
> 
> > > > ######我的解决方法#########
> > > > 设置 appid=266719
> > > > 重新登录
> > > > 然后会自动返回到根目录
> > > > 遇到403 设置 config set -appid=265486
> > > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > > 
> > > 
> > > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> > 
> > 
> > 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了
> 
> 测试依然无效……怕是我的电脑或者账号被拉黑了……

有没有再试几次...目前似乎是机率出错

**Comment by Xionghaizi001** [comment]
> 
> 
> > > > > ######我的解决方法#########
> > > > > 设置 appid=266719
> > > > > 重新登录
> > > > > 然后会自动返回到根目录
> > > > > 遇到403 设置 config set -appid=265486
> > > > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > > > 
> > > > 
> > > > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> > > 
> > > 
> > > 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了
> > 
> > 
> > 测试依然无效……怕是我的电脑或者账号被拉黑了……
> 
> 有没有再试几次...目前似乎是机率出错

在我这是100%出错……前段时间只要重新拨号就能用，现在干脆就不让用了

**Comment by poly000** [comment]
> 
> 
> > > > > > ######我的解决方法#########
> > > > > > 设置 appid=266719
> > > > > > 重新登录
> > > > > > 然后会自动返回到根目录
> > > > > > 遇到403 设置 config set -appid=265486
> > > > > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > > > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > > > > 
> > > > > 
> > > > > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> > > > 
> > > > 
> > > > 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了
> > > 
> > > 
> > > 测试依然无效……怕是我的电脑或者账号被拉黑了……
> > 
> > 
> > 有没有再试几次...目前似乎是机率出错
> 
> 在我这是100%出错……前段时间只要重新拨号就能用，现在干脆就不让用了

emmm...再试试？（ 我这里接近99%出错但还能用

**Comment by PromiseChan** [comment]
> > > > > > > ######我的解决方法#########
> > > > > > > 设置 appid=266719
> > > > > > > 重新登录
> > > > > > > 然后会自动返回到根目录
> > > > > > > 遇到403 设置 config set -appid=265486
> > > > > > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > > > > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > > > > > 
> > > > > > 
> > > > > > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> > > > > 
> > > > > 
> > > > > 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了
> > > > 
> > > > 
> > > > 测试依然无效……怕是我的电脑或者账号被拉黑了……
> > > 
> > > 
> > > 有没有再试几次...目前似乎是机率出错
> > 
> > 
> > 在我这是100%出错……前段时间只要重新拨号就能用，现在干脆就不让用了
> 
> emmm...再试试？（ 我这里接近99%出错但还能用

真有随机的感觉，我多次测试，有时候能下载，有时候不能

**Comment by poly000** [comment]
> 
> 
> > > > > > > > ######我的解决方法#########
> > > > > > > > 设置 appid=266719
> > > > > > > > 重新登录
> > > > > > > > 然后会自动返回到根目录
> > > > > > > > 遇到403 设置 config set -appid=265486
> > > > > > > > 在 根目录下执行 d apps/baidu_shurufa/xxxxx.zip 即可下载
> > > > > > > > 用 cd 进入不了baidu_shurufa ，会重新变成31045
> > > > > > > 
> > > > > > > 
> > > > > > > 这个方法亲测无效，考虑试下更换IP地址或者MAC地址
> > > > > > 
> > > > > > 
> > > > > > 有没有先用appid=266719, 然后再用appid=265486, 我用其他电脑再试了一次, 没改appid,还是会有问题,改了两次,就可以下载了
> > > > > 
> > > > > 
> > > > > 测试依然无效……怕是我的电脑或者账号被拉黑了……
> > > > 
> > > > 
> > > > 有没有再试几次...目前似乎是机率出错
> > > 
> > > 
> > > 在我这是100%出错……前段时间只要重新拨号就能用，现在干脆就不让用了
> > 
> > 
> > emmm...再试试？（ 我这里接近99%出错但还能用
> 
> 真有随机的感觉，我多次测试，有时候能下载，有时候不能

除了随机的可能性...我猜想是百度服务器出错

**Comment by Psbin** [comment]
同样 估计是baidu修改了什么 现在总是这个报错

**Comment by kerraway** [comment]
测试 ls 命令，时好时坏，会不会是灰度测试，负载打到升级前的服务器就正常，打到升级后的服务就失败。

**Comment by daisuki4gh** [comment]
ls 命令，也是报错，` 
>>ls
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31045, 消息: 操作失败, 可能百度帐号登录状态过期, 请尝试重新登录, 消息: user not exists`

**Comment by cxmda** [comment]
只能登录，其他的都不能做....

**Comment by yuritry** [comment]
同样的问题

**Comment by Xionghaizi001** [comment]
> 除了随机的可能性...我猜想是百度服务器出错

但是隔壁PanDownload还能跑起来（雾

**Comment by blackJJdog** [comment]
入夜渐微凉，繁花落地成霜。

**Comment by pe200012** [comment]
刚才再试了一次又可以了，感觉像随机报错

**Comment by Dr-Bluemond** [comment]
虽然ls不了，但是复制完整路径还是可以下载的
（文件放入输入法文件夹，appid=265486）

**Comment by jth445600** [comment]
最后还是凉凉

**Comment by symant233** [comment]
same here

**Comment by iikira** [comment]
应该是服务器的问题，先观察几天吧~

**Comment by changbowen** [comment]
> 虽然ls不了，但是复制完整路径还是可以下载的
> （文件放入输入法文件夹，appid=265486）

复制完整路径真的可以下欸

**Comment by zzzop** [comment]
应该是文件夹获取的问题，会员下载单文件没有问题，还好google到了获取所有文件路径的方法。。。

**Comment by qdzzyb2014** [comment]
上传也好用

**Comment by DemonJudy** [comment]
重启了一下客户端又能下了，很迷

**Comment by poly000** [comment]
多次ls或者跑一次tree再看看问题解决了没吧。。

**Comment by Xionghaizi001** [comment]
今天打开又能直接下载了，不过ls的时候还是会报错，要试好几次

**Comment by CliveHe** [comment]
### `ls`操作报错之后，使用完整路径就可以下载
>例如：
>
>- 我第1次`ls`是`遇到错误, 远端服务器返回错误, 代码: 31045`
>- 第2次正常显示目录和文件
>- 然后第3次`ls`又是`遇到错误, 远端服务器返回错误, 代码: 31045`
>- 第4次又可以正常显示目录和文件。。。。
>- **......**

我继续重复操作都是这个规律，于是我就猜想如果奇数次的操作都有毛病，偶数次的操作没问题，那么我在偶数次的时侯用完整路径下载试一试
所以我就在它显示`遇到错误, 远端服务器返回错误, 代码: 31045`之后，用完整路径下载，果然就成功了。。。

不过下了不到一个小时好像就被百度黑名单了，进度条卡住不动了
`↓ 26.48MB/39.92MB 0B/s in 36m17.82s, left - ..................`
重新下载就提示31066错误，上面提到的`ls`规律也不准确了
`获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在`

**Comment by zzzop** [comment]
> ### `ls`操作报错之后，使用完整路径就可以下载
> > 例如：
> > 
> > * 我第1次`ls`是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > * 第2次正常显示目录和文件
> > * 然后第3次`ls`又是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > * 第4次又可以正常显示目录和文件。。。。
> > * **......**
> 
> 我继续重复操作都是这个规律，于是我就猜想如果奇数次的操作都有毛病，偶数次的操作没问题，那么我在偶数次的时侯用完整路径下载试一试
> 所以我就在它显示`遇到错误, 远端服务器返回错误, 代码: 31045`之后，用完整路径下载，果然就成功了。。。
> 
> 不过下了不到一个小时好像就被百度黑名单了，进度条卡住不动了
> `↓ 26.48MB/39.92MB 0B/s in 36m17.82s, left - ..................`
> 重新下载就提示31066错误，上面提到的`ls`规律也不准确了
> `获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在`

文件路径没弄错吗，我现在用完整路径下载了3000个文件了还没出错，应该只是获取目录有问题了

**Comment by poly000** [comment]
> 
> ### `ls`操作报错之后，使用完整路径可能可以下载
> 
> > 例如：
> > 
> > * 我第1次`ls`是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > * 第2次正常显示目录和文件
> > * 然后第3次`ls`又是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > * 第4次又可以正常显示目录和文件。。。。
> > * **......**
> 
> 我继续重复操作都是这个规律，于是我就猜想如果奇数次的操作都有毛病，偶数次的操作没问题，那么我在偶数次的时侯用完整路径下载试一试
> 所以我就在它显示`遇到错误, 远端服务器返回错误, 代码: 31045`之后，用完整路径下载，果然就成功了。。。
> 
> 不过下了不到一个小时好像就被百度黑名单了，进度条卡住不动了
> `↓ 26.48MB/39.92MB 0B/s in 36m17.82s, left - ..................`
> 重新下载就提示31066错误，上面提到的`ls`规律也不准确了
> `获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在`

emmm...应该仍然是随机 奇数偶数可能是凑巧 文件路径同问

**Comment by CliveHe** [comment]
> > ### `ls`操作报错之后，使用完整路径可能可以下载
> > > 例如：
> > > 
> > > * 我第1次`ls`是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > > * 第2次正常显示目录和文件
> > > * 然后第3次`ls`又是`遇到错误, 远端服务器返回错误, 代码: 31045`
> > > * 第4次又可以正常显示目录和文件。。。。
> > > * **......**
> > 
> > 
> > 我继续重复操作都是这个规律，于是我就猜想如果奇数次的操作都有毛病，偶数次的操作没问题，那么我在偶数次的时侯用完整路径下载试一试
> > 所以我就在它显示`遇到错误, 远端服务器返回错误, 代码: 31045`之后，用完整路径下载，果然就成功了。。。
> > 不过下了不到一个小时好像就被百度黑名单了，进度条卡住不动了
> > `↓ 26.48MB/39.92MB 0B/s in 36m17.82s, left - ..................`
> > 重新下载就提示31066错误，上面提到的`ls`规律也不准确了
> > `获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在`
> 
> emmm...应该仍然是随机 奇数偶数可能是凑巧 文件路径同问

已经403了[捂脸]
`下载文件错误, 403 Forbidden, 重试 1/3`

**Comment by signigelchan** [comment]
遇到同样的问题。

**Comment by jeerychris** [comment]
+1, 有时ls可以，有时31045，好难受啊

**Comment by ttimasdf** [comment]
也许可以加入一个重试机制？

**Comment by poly000** [comment]
> 
> 
> 也许可以加入一个重试机制？

BaiduPCS-Go $@ |grep 31405

**Comment by freehuoshan** [comment]
已经可以完全正常使用

**Comment by jth445600** [comment]
今天直接403了

**Comment by poly000** [comment]
> 
> 
> 今天直接403了

黑号。我有个脚本可以自动改appid和用/apps/baidu_shurufa解决。
<b><b>[BaiduPCS-Go-easy2use](https://github.com/poly000/BaiduPCS-Go-easy2use)</b></b>

**Comment by iikira** [comment]
好像没问题了
