### ISSUE TITLE
错误代码: -1, 消息: 网络请求失败 unexpected EOF

### ISSUE THREAD

**Issue by freehuoshan** [iikira/BaiduPCS-Go#713]
[1] 加入下载队列: /apps/baidu_shurufa/west1
[1] 获取路径信息错误, 获取文件/目录的元信息: 网络错误, Post https://pcs.baidu.com/rest/2.0/pcs/file?app_id=265486&method=meta: unexpected EOF

退出后也无法重新登录 

请输入密码(输入的密码无回显, 确认输入完成, 回车提交即可) > 
错误代码: -1, 消息: 网络请求失败, Post https://wappass.baidu.com/wp/api/login:

**Comment by freehuoshan** [comment]
看到之前也有人遇到这个问题，他们使用了代理，但是我这里没有使用任何代理

配置如下:

appid              265486                               百度 PCS 应用ID                                       
  enable_https       true                      true       启用 https                                            
  user_agent         "Mozilla;5.0"                        浏览器标识                                            
  cache_size         30000                 1024 ~ 262144  下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值  
  max_parallel       100                     50 ~ 500     下载最大并发量                                        
  max_download_load  1                         1 ~ 5      同时进行下载文件的最大数量                            
  savedir            /home/free/Downloads                 下载文件的储存目录                                    

尝试删除 config 文件依然无效。

**Comment by maorl** [comment]
我也是同样的问题……

**Comment by iikira** [comment]
测试正常，看情况应该是网络的问题，本地或百度服务器的网络有问题
