### ISSUE TITLE
下载文件校验失败问题

### ISSUE THREAD

**Issue by qbsencom** [iikira/BaiduPCS-Go#714]
下载了几个2g内的电影，只有一个成功，其他都提示MD5校验失败，改了后缀名称也是一样，（下载一半后我用播放器能打开视频文件，但下载完成校验MD5失败后就自动给删了），所以能否在设置项增加一个下载文件后是否校验MD5设置以供用户自行选择？

**Comment by pongfcnkl** [comment]
-nocheck

**Comment by iikira** [comment]
楼上正解，下载时加上-nocheck参数

**Comment by Justsoos** [comment]
建议作者把这个选项更新到 wiki 和首页里，下载 xG 后被程序秒删，再去下，就被百度限速了，变成了死链
