### ISSUE TITLE
上传进度显示问题

### ISSUE THREAD

**Issue by wangqr** [iikira/BaiduPCS-Go#715]
我在上传一个500MB的文件时，显示的已上传大小在100MB到400MB之间快速来回波动，而且有时增长速度显著大于右边显示的上传速率（也大于物理带宽），这是否是某种异常？

**Comment by wangqr** [comment]
由于1.5h后它仍在来回波动，我也不确定它是否仍在上传，上传任务已经取消了

**Comment by carolkey** [comment]
我也遇见了这种问题，比如上传 500M大小的文件，然后显示已经上传了300M，然后又显示292M，然后又一点一点加到300M，然后又跳到292M，周而复始，但是网速是有在跳动的

**Comment by iikira** [comment]
应该是上传最大并发量太高了，旧版使用了下载并发量的配置，新版支持单独设置上传并发量了，请更新后重试

**Comment by carolkey** [comment]
单独设置上传并发参数有更新到文档吗

**Comment by iikira** [comment]
没有, 但是程序本身自带了帮助

查看帮助：
```
BaiduPCS-Go config set -h
```

查看当前配置：
```
BaiduPCS-Go config
```

设置上传并发量为8：
```
BaiduPCS-Go config set -max_upload_parallel 8
```

**Comment by carolkey** [comment]
好的谢谢，不过文档最好补齐全，方便查找~
