### ISSUE TITLE
请问ExitCode有相应设置咩？或者Error有统一的识别方法不？

### ISSUE THREAD

**Issue by landall** [iikira/BaiduPCS-Go#716]
想在脚本里调用BaiduPCS-Go实现一个按文件搬运到其他盘的工具，想问一下有没有ExitCode或者安静模式可供集成用?

**Comment by iikira** [comment]
还没有呢

**Comment by landall** [comment]
有没有什么简易的土办法能知道出错了？光靠经验容易被海量日志给埋掉^_^

**Comment by fzxiao233** [comment]
> 
> 
> 有没有什么简易的土办法能知道出错了？光靠经验容易被海量日志给埋掉^_^

如果你是Python的话可以用PIPE直接读取输出流来判断

**Comment by landall** [comment]
> > 有没有什么简易的土办法能知道出错了？光靠经验容易被海量日志给埋掉^_^
> 
> 如果你是Python的话可以用PIPE直接读取输出流来判断

输出流也缺乏统一的特征来管理啊。感觉这个程序在设计时没太考虑面向集成方面的调用，输出的格式每个模块也不太统一，输出还是比较面向人类。目前我用得方法是单个文件调用一次BaiduPCS-Go然后看该出现的那个下载文件是否在那里，然后上传。
