### ISSUE TITLE
下载文件错误, 403 Forbidden, 重试

### ISSUE THREAD

**Issue by klcb2010** [iikira/BaiduPCS-Go#718]
![QQ截图20190522210159](https://user-images.githubusercontent.com/32628414/58176432-d16cf300-7cd4-11e9-9c2d-a564db4c079a.jpg)
真要开会员吗？

**Comment by klcb2010** [comment]
手机端下载没问题 但是更新
![Screenshot_20190522-210942](https://user-images.githubusercontent.com/32628414/58176973-09286a80-7cd6-11e9-837f-c42f582200f8.png)
失败

**Comment by jth445600** [comment]
同样的问题

**Comment by fuxianli** [comment]
两小时前出现同样问题，改appid没用

**Comment by jth445600** [comment]
开超级会员吧

**Comment by pongfcnkl** [comment]
https://github.com/iikira/BaiduPCS-Go/issues/460

**Comment by klcb2010** [comment]
应该是触发了限速，这个比山寨云更危险！放弃算了

**Comment by qbsencom** [comment]
今天突然也是这样了

**Comment by Axun** [comment]
应该是封了，昨天下午就一直这样。还发现会生成一个 apps/NearMe网盘 这个文件夹

**Comment by davidlauhn** [comment]
我的前两天也这样，然后现在没这样了，但是速度没了

**Comment by jth445600** [comment]
可以使用pandownload，
![image](https://user-images.githubusercontent.com/24479489/58393647-09569c00-802f-11e9-92b1-c762dba808fc.png)这个工具可以使用远程aria2c，可以把百度网盘的内容下载到远程vps，速度还挺快。

**Comment by iphonelover** [comment]
我下午还可以下载呢，晚上就不行了

**Comment by leening3436** [comment]
> 我的前两天也这样，然后现在没这样了，但是速度没了

我也是，现在下载没问题，但是没有速度

**Comment by AhFook** [comment]
一時時的，要看運氣。
今日算OK的。

**Comment by joostshao** [comment]
http://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/2.0.2/baidunetdisk_linux_2.0.2.deb

用这个试试？

**Comment by iikira** [comment]
建议开通会员哦
