### ISSUE TITLE
错误31326 hitcode122

### ISSUE THREAD

**Issue by UQJRlex** [iikira/BaiduPCS-Go#719]
最近这两天下载时，速度会突然变成0，而越来越频繁，几乎不能正常下载了，到现在彻底不行了：

> 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:122

appid改成265486，且只在/apps/baidu_shurufa下载的方法，这么快就失效了。

也许我号被黑了，等几天再说吧，这个月快过去了，下个月考虑买会员了。

**Comment by iikira** [comment]
此类问题请移步#460 讨论
