### ISSUE TITLE
v3.3.Beta4 好像真的是负优化

### ISSUE THREAD

**Issue by kerraway** [iikira/BaiduPCS-Go#72]
> v3.3.Beta4 更新日志
> 优化文件下载, (之前可能做了负优化...);

实测发现，同样的文件，v3.3.Beta4 一直没速度，换回 v3.3.Beta3 就有速度，两者配置一样。所以，你有可能真的做了负优化 :( 。

另外一个问题，下载文件夹，某个文件下载中，终止程序，然后再打开程序重下，刚刚的文件没有下载完毕，程序有可能判断其下载完毕，跳过，然后下载下一个文件，最后查看具体文件，才发现该问题。

**Comment by iikira** [comment]
v3.3.Beta4 优化了连接数量，减少网络瘫痪的几率，同时下载速度可能会降低，尝试调整下载并发量……
关于第二个问题，有时间看一下……

**Comment by Gegoiuty** [comment]
跳过的时候，能否校验一下文件的 md5，这样就不会跳过未完成的下载。

**Comment by iikira** [comment]
百度服务器记录的md5不一定是真实的，所以没加上md5校验，但可以考虑校验别的，比如crc32...

**Comment by cnritng** [comment]
我也是新版的没速度,很久以前的版本beta-v3.2有速度,但经常出现503 Service Temporarily Unavailable,最后下载下来的rar文件是损坏的

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.

**Comment by urugang** [comment]
用md5校验，有的文件是一致的，有的不一致。 CRC校验怎么做，网盘文件里没有这个信息.

**Comment by iikira** [comment]
请求下载时可得到这个信息
