### ISSUE TITLE
百度超级会员众筹

### ISSUE THREAD

**Issue by vipzrx** [iikira/BaiduPCS-Go#723]
感谢作者开发维护这个插件!

现在很容易各种黑号.每天花大量时间在等待下载和寻找各种破解限速的问题上. 速度只有10几K. 

打算找人合买个百度网盘超级会员

1 注册一个新的百度会员,合买的人,共同拥有帐号和密码

2 和买人数限制为5人

有意请添加 微信  185 5010 5795 备注 百度会员

能否结合作者的这个插件,利用一个vps 远程登录的方式,共享一个 百度网盘超级会员帐号?

**Comment by pongfcnkl** [comment]
租一个。。。3.8一个月

**Comment by xmsz** [comment]
朋友圈超级会员一年150 在纠结

**Comment by MichaelPorter0** [comment]
问题是开了会员我也只有200K啊

**Comment by pongfcnkl** [comment]
> 
> 
> 问题是开了会员我也只有200K啊

要超级会员，会员可能没用

**Comment by iBreaker** [comment]
买一个超级会员  200多，又不贵

**Comment by xmsz** [comment]
> 买一个超级会员 200多，又不贵

现在是用处不大(非必须资产)，但是要用到的时候就很尴尬

**Comment by shiqwang** [comment]
200多块钱 纠结啥呢，都办好几年了。。。
