### ISSUE TITLE
目前BaiduPCS-GO应该已经被封锁了，现提供一个新的办法，可以满速下载一个月，不需要担心封号问题

### ISSUE THREAD

**Issue by Skilling-Kiss** [iikira/BaiduPCS-Go#726]
到微信公众号Get Something Useful上点title就有了，新建的公众号，想没事的时候给大家分享点有用的东西吧，

**Comment by HallWoodZhang** [comment]
没必要，百度也是要吃饭的，充会员用就行了，用这个主要是Linux上没有客户端

**Comment by landall** [comment]
最好的办法就是买会员……

**Comment by Skilling-Kiss** [comment]
> 没必要，百度也是要吃饭的，充会员用就行了，用这个主要是Linux上没有客户端

主要是没需要，一周可能都下载不了几个文件，开会员有什么用，难道下载一个文件10块钱？

**Comment by losignrsoe** [comment]
关键是 买了会员，也没有树莓派上的客户端呀。

**Comment by tiger233** [comment]
买了普通会员也限速。除非超级会员，30一个月
