### ISSUE TITLE
拜拜了，BaiduPCS-Go

### ISSUE THREAD

**Issue by tangmengqiu** [iikira/BaiduPCS-Go#729]
最近一周测试都是 0kb/s和 100kb/s之间反复横跳，已经和客户端的速度差不多了，看来百度官方已经出手了，感谢曾经拥有这么方便的下载途径，再见！！！

**Comment by xianxuhua** [comment]
我也是

**Comment by landall** [comment]
> 最近一周测试都是 0kb/s和 100kb/s之间反复横跳，已经和客户端的速度差不多了，看来百度官方已经出手了，感谢曾经拥有这么方便的下载途径，再见！！！

拜拜了，把BaiduPCS-Go当速度破解工具的用户……对于当Linux客户端的用户而言，一切都毫无影响。

**Comment by WithoutFox1** [comment]
> > 最近一周测试都是 0kb/s和 100kb/s之间反复横跳，已经和客户端的速度差不多了，看来百度官方已经出手了，感谢曾经拥有这么方便的下载途径，再见！！！
> 
> 拜拜了，把BaiduPCS-Go当速度破解工具的用户……对于当Linux客户端的用户而言，一切都毫无影响。

意思是Linux的速度毫无影响 ???
