### ISSUE TITLE
下载文件时发生错误: 403 Forbidden (跳过...)

### ISSUE THREAD

**Issue by unlimitedLoop** [iikira/BaiduPCS-Go#73]
无法下载任何文件，服务器验证升级了？

**Comment by iikira** [comment]
不清楚……

**Comment by unlimitedLoop** [comment]
看来我的一个号被百度拉黑了，换了个账号就可以正常下载

**Comment by iikira** [comment]
可以试试重新登录吧

**Comment by unlimitedLoop** [comment]
试过了，我甚至在不同的机器上重新登录，也是一样的403

**Comment by iikira** [comment]
emmmm...用官方的客户端正常不

**Comment by unlimitedLoop** [comment]
这么个情况，我想下载一个视屏文件，大概1G多，很久之后发现没有速度，之后重新下载出现403，后面换了账号，下载一个小文件，下载成功，然后重新下载这个视屏文件，中途没有速度，重新下载又出现403，这应该是百度那边动态检测，发现你下载速度长时间超出限制就对你的账号进行限制

**Comment by iikira** [comment]
下载换了算法, 24f0fd19a2979c5377534fd2ce5c3ac4ac13c510, 你可以编译运行程序看看效果怎么样...……

**Comment by unlimitedLoop** [comment]
`go get -u -v github.com/iikira/BaiduPCS-Go`编译最新版本
然后用了一个新的账号重新试了一下，文件1G多，在下载到370M的时候，没有速度了，之后重新，出现403，与之前的情况一样

**Comment by iikira** [comment]
好吧…...不太清楚…尝试调低一点下载线程试试，比如50……

**Comment by o0shine0o** [comment]
请问有遇到并解决这个问题的吗

**Comment by mursoudayo** [comment]
同样情况，今天突然就显示403，换了个号下载快下完的时候就没速度了，重新登录又是403。

**Comment by lucky13820** [comment]
我今天也遇到这个问题了，文件快下载玩的时候就没速度了。然后就 403 了

**Comment by xiaoyu233** [comment]
我也出现了403，不过我改`user_agent`为`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 `后，把`max_parallel`降点，一个账号可以了，另一个还是不行。

<img width="1250" alt="user_agent" src="https://user-images.githubusercontent.com/24972990/47475557-811cd800-d84e-11e8-8c7a-1178efff6a79.png">

**Comment by jelly54** [comment]
> 我也出现了403，不过我改`user_agent`为`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 `后，把`max_parallel`降点，就可以了。
> 
> 百度似乎对IP进行了限制，我阿里的VPS上下载，就一直403，切换到家里Nas上就可以了
> 
> <img alt="user_agent" width="1250" src="https://user-images.githubusercontent.com/24972990/47475557-811cd800-d84e-11e8-8c7a-1178efff6a79.png">
> 
> <img alt="2018-10-25 2 20 15" width="700" src="https://user-images.githubusercontent.com/24972990/47479906-2640ac00-d861-11e8-974a-b977a93c8d6a.png">

我试过你的方法了，不好使，，希望有解决办法

**Comment by excitingduckduckgo** [comment]
> > > 我也出现了403，我不过改`user_agent`为`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 `后，把`max_parallel`降速点，就可以了。
> > > 百度似乎对IP进行了限制，我阿里的VPS上下载，就一直403，切换到家里纳斯上就可以了
> > > <img alt="用户代理" width="1250" src="https://user-images.githubusercontent.com/24972990/47475557-811cd800-d84e-11e8-8c7a-1178efff6a79.png">
> > > <img alt="2018-10-25 2 20 15" width="700" src="https://user-images.githubusercontent.com/24972990/47479906-2640ac00-d861-11e8-974a-b977a93c8d6a.png">
> > 
> > 
> > 我试过你的方法了，不好使,,希望有解决办法
> 
> 十月份时候，刚出现403换用户代理后有用，不过现在好像百度直接限制普通用户的流量，超过就出现严重的断流，我这边也一样

现在似乎只能使用小号，但我虚拟手机号也没那么多

**Comment by iikira** [comment]
这个问题太老了，无法定位具体的出错，建议使用最新版本，下载出现问题了再反馈吧
