### ISSUE TITLE
我遇到一个文件下载一半卡住了。。。

### ISSUE THREAD

**Issue by landall** [iikira/BaiduPCS-Go#733]
[1] 准备下载: /Anime/Anime2010-Unseen/被淘汰的/[HKG][Nogizaka Haruka no Himistu Purezza][01][BIG5][RV10].rmvb
[1] 将会下载到路径: /home/centos/Downloads/[HKG][Nogizaka Haruka no Himistu Purezza][01][BIG5][RV10].rmvb

[1] ↓ 129.74MB/133.76MB 0B/s in 58s, left - ............

这种情况下我该怎么提交debug信息？运行平台是CentOS 7 x64

**Comment by pongfcnkl** [comment]
分享一下看看

**Comment by landall** [comment]
> 分享一下看看

链接：https://pan.baidu.com/s/1RIJa-IQtj8kH8vN43rjhmQ 
提取码：ih3p 
复制这段内容后打开百度网盘手机App，操作更方便哦

刚才又遇到一个文件，马路须加学园里也有一集是一个现象，卡了好几个小时了。

**Comment by landall** [comment]
> 分享一下看看

链接：https://pan.baidu.com/s/1P3L9X6cExE7nE0veRE4u1A 
提取码：3hlg 
复制这段内容后打开百度网盘手机App，操作更方便哦

这是HKG那个动画。

**Comment by pongfcnkl** [comment]
@landall 
用官方客户端好像也下不了，卡在129.76mb不动
建议联系百度看看吧
![TIM截图20190623162925](https://user-images.githubusercontent.com/24273319/59973571-62850180-95d4-11e9-8c69-7c4122cd61e3.png)

**Comment by landall** [comment]
> @landall
> 用官方客户端好像也下不了，卡在129.76mb不动（九成概率百度网盘掉数据了吧）
> 建议联系百度看看吧
> 
> ![TIM截图20190623163326](https://user-images.githubusercontent.com/24273319/59973628-ec34cf00-95d4-11e9-812c-be6bf12caac7.png)

还真是。。。。

**Comment by iikira** [comment]
看起来不是BaiduPCS-Go的问题。。
