### ISSUE TITLE
今天突然就上传不了了

### ISSUE THREAD

**Issue by zzjyg** [iikira/BaiduPCS-Go#734]
之前也出现过，重复几次也能上传，今天就一直失败，这个号还是超级会员，难道是被封了，能查到吗
![image](https://user-images.githubusercontent.com/51195245/59737624-f1baae00-9290-11e9-8b56-51d7104e361b.png)

**Comment by zzjyg** [comment]
百度网盘客户端倒是可以上传

**Comment by gzlock** [comment]
我用baidupcs-go也上传不了，在百度盘的网页也上传失败

**Comment by gzlock** [comment]
找到原因了，是我改成电脑chrome的user-agent所以上传失败，改回原来的就可以了

**Comment by yiuty** [comment]
偶尔碰到过(概率未知)，将文件重命名后再传，又可以传了。
如果还是不行的话，只有重新打包，再传了。

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 更新了上传功能, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧
