### ISSUE TITLE
update 错误

### ISSUE THREAD

**Issue by dengcb** [iikira/BaiduPCS-Go#738]
获取版本列表错误: 错误代码: -21, 消息: 未知错误

**Comment by ZERO4579** [comment]
同上，以及下载时找不到文件或目录...请求帮助！

**Comment by pongfcnkl** [comment]
现在只能手动更新。。。
https://ci.appveyor.com/project/iikira/baidupcs-go

**Comment by zengqlleo** [comment]
> 现在只能手动更新。。。
> https://ci.appveyor.com/project/iikira/baidupcs-go

所以现在更新只能从source build了？

**Comment by pongfcnkl** [comment]
@zengqlleo 
点Artifacts下载之后直接替换
