### ISSUE TITLE
设置文件可以放在别的地方么

### ISSUE THREAD

**Issue by Virace** [iikira/BaiduPCS-Go#74]
就是这个文件 pcs_config.json

或是说那种 在windows这种关掉控制台就删除记录的

**Comment by Virace** [comment]
还有这个 pcs_command_history.txt

**Comment by iikira** [comment]
现在还不能, 为什么会有这种需求呢,?

**Comment by Virace** [comment]
没有就不麻烦了，稍微有点洁癖= =
