### ISSUE TITLE
无法复制粘贴指令 以及  对中文输入法支持不好

### ISSUE THREAD

**Issue by Satanepigone** [iikira/BaiduPCS-Go#740]
在cli交互模式下不支持复制粘贴，对中文输入法的支持也不完善（看不见选词框），文件名是中文的时候只能疯狂tab，小列表还好， 一个目录几百个文件的时候会抽筋的。

**Comment by lizr2004** [comment]
您是windows吗，这是windwos的bug...

**Comment by Satanepigone** [comment]
是的....
