### ISSUE TITLE
SVIP都限速2.7m/s，百度牛逼啊

### ISSUE THREAD

**Issue by MooeKayo** [iikira/BaiduPCS-Go#741]
SVIP限速2.7m/s，go pd和idm都试过，无论多大线程都突破不了2.7,账号为年费svip
![QQ截图20190706224010](https://user-images.githubusercontent.com/28668856/60757574-10fe5d00-a03f-11e9-9e2c-3a43dc0e51db.png)

**Comment by lib-xdown** [comment]
请使用 xdown 下载,
https://xdown.xyz

**Comment by fuck2ky** [comment]
超会一直都有限速，过一段时间会恢复的，我现在搞了二十多个账号轮流用

**Comment by anuxs** [comment]
2.7M/S，是不是wifi没有连接5G wifi？5G wifi 才能跑满百兆光纤 。

**Comment by iikira** [comment]
原因可能是本地带宽、设备等
