### ISSUE TITLE
使用xdown下载超过10G大小文件

### ISSUE THREAD

**Issue by lib-xdown** [iikira/BaiduPCS-Go#742]
首先去
https://labs.nazo.moe/netdisk.html
解析链接地址.复制,

然后去
https://xdown.xyz
下载.
新建任务,复制进去

即可下载

![M3{@5}$F F1SLC(N~PYF~}A](https://user-images.githubusercontent.com/52403944/60767772-da801b00-a0ee-11e9-8325-0513db213070.png)
![KHTLD `(5 5A(T@8`O(}6G](https://user-images.githubusercontent.com/52403944/60767775-de13a200-a0ee-11e9-8153-8918ae9f278f.png)

**Comment by lsyyktv** [comment]
满速。。厉害

**Comment by iikira** [comment]
很棒！但这里打广告不适宜

**Comment by mxhellor** [comment]
不能解析了，怎么回事？难道又一个被封了？靠，shit
