### ISSUE TITLE
403...怎么破

### ISSUE THREAD

**Issue by KiritoGuugk** [iikira/BaiduPCS-Go#744]

**Comment by pongfcnkl** [comment]
开超级会员

**Comment by donly** [comment]
> 开超级会员

实测，不行✋

**Comment by pongfcnkl** [comment]
> > 开超级会员
> 
> 实测，不行

我这里没问题，非会员没一会就不动了，超级会员下的很快
你是不是在appveyor下载的？

**Comment by donly** [comment]
应该是别的因素，我公司电脑不行，自己电脑又可以

**Comment by pongfcnkl** [comment]
> 
> 
> 应该是别的因素，我公司电脑不行，自己电脑又可以

可能你们公司拦截了吧

**Comment by iikira** [comment]
下载异常，移步#460 噢
