### ISSUE TITLE
卡最后1%

### ISSUE THREAD

**Issue by DeanJing** [iikira/BaiduPCS-Go#745]
[3] ↓ 399.29MB/400.00MB 0B/s in 45m38.55s, left - .......................

**Comment by pongfcnkl** [comment]
文件分享下

**Comment by cmmei** [comment]
我下载视频已经一半了，卡住没速度了。

**Comment by coderandprobie** [comment]
我的也是

**Comment by Godsing** [comment]
同样遇到：
410.13MB/410.46MB 0B/s in 10h24m45.41s 
等了 10 小时了，我要哭了

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 更新了下载器，试一试呢
如果下载卡住了，尝试一下重新下载
如果重新下载报错了，可能是下载受到了限制，参考#460 （未解决）
