### ISSUE TITLE
文件名或者文件夹名带有空格时候，分享链接错误：返回：-3

### ISSUE THREAD

**Issue by ldj46118** [iikira/BaiduPCS-Go#747]
创建分享链接：遇到错误，远端服务器返回错误，代码：-3，消息：文件不存在，请刷新页面后重试

**Comment by ldj46118** [comment]
用share s 命令分享 文件名或者文件夹名带有空格时候 返回：-3 错误

**Comment by pongfcnkl** [comment]
不要手动输入，用TAB自动填充

**Comment by ldj46118** [comment]
感谢您百忙之中的回复，请问哪个命令可以实现TAB键自动填充替换掉空格键呢?感谢您!-------- 原始邮件 --------主题：Re: [iikira/BaiduPCS-Go] 文件名或者文件夹名带有空格时候，分享链接错误：返回：-3 (#747)发件人：666666666666 收件人：iikira/BaiduPCS-Go 抄送：ldj46118 ,Author 不要手动输入，用TAB自动填充



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iikira/BaiduPCS-Go/issues/747?email_source=notifications\u0026email_token=AMVBBAKRI3226DJM2HRJIOLQA26Q3A5CNFSM4IFHBSGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2SK5YQ#issuecomment-514109154",

"url": "https://github.com/iikira/BaiduPCS-Go/issues/747?email_source=notifications\u0026email_token=AMVBBAKRI3226DJM2HRJIOLQA26Q3A5CNFSM4IFHBSGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2SK5YQ#issuecomment-514109154",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ldj46118** [comment]
路径带空格已经解决，文件名带多个空格还是返回：-3
