### ISSUE TITLE
现在是从源头上封禁了下载吗？

### ISSUE THREAD

**Issue by allwillbeok** [iikira/BaiduPCS-Go#751]
403 错误是不是意味着百度从服务器端彻底封禁了超速下载？只要检测到你不是vip就不让你下载，管你客户端怎么花里胡俏都没用，总是绕不过服务器验证
如果真是这样一切外部工具是不是凉了啊？

**Comment by iikira** [comment]
此类问题请移步#460 讨论

**Comment by pongfcnkl** [comment]
花钱租号就行
