### ISSUE TITLE
卸载3.3.5安装3.3.6解决不了【network error】

### ISSUE THREAD

**Issue by WaysonWood** [iikira/BaiduPCS-Go#752]
最新版本，64位， @卸载3.3.5安装3.3.6解决不了【network error】
![csgoERROR1](https://user-images.githubusercontent.com/17807886/62449524-fd105d00-b79c-11e9-8577-a41bdaace621.png)

**Comment by WaysonWood** [comment]
![csgoERROR2](https://user-images.githubusercontent.com/17807886/62450151-575ded80-b79e-11e9-8c5c-6562fe3ff4ee.png)
不是指令的问题，是不是账号被封了？

**Comment by iikira** [comment]
这是网盘服务器的问题，换个时间再试试呢
