### ISSUE TITLE
安卓端登录问题

### ISSUE THREAD

**Issue by happytommyl** [iikira/BaiduPCS-Go#754]
安卓端termux，登录时用户名无法提交。

BaiduPCS-Go > login
请输入百度用户名(手机号/邮箱/用户名), 回车键提交 >**********^M^M^M^M^M^M^M^M^M^M^M

按回车就是输入^M，无法提交

**Comment by iikira** [comment]
测试正常，可能是终端环境的问题
用ctrl+j试试吧

**Comment by pongfcnkl** [comment]
用bduss登陆
