### ISSUE TITLE
有办法转移用户登录信息吗？

### ISSUE THREAD

**Issue by tyhunter** [iikira/BaiduPCS-Go#757]
例如像rclone一样是把用户登陆内容放在rclone.conf里面的，只要备份了这个就能保证转移设备时不用重新登录账户

**Comment by iikira** [comment]
`BaiduPCS-Go env` 可查看配置文件的路径

**Comment by tyhunter** [comment]
@iikira 感谢，搞定了~
顺便问下什么时候能在cli下面直接添加别人分享的链接到自己网盘~
辛苦开发
