### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by poly000** [iikira/BaiduPCS-Go#758]
```
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp 103.235.46.140:80: connectex: A connection attempt failed because the connected party did not properly respond afte
r a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by iikira** [comment]
网络超时，重试或者更换网络环境

**Comment by poly000** [comment]
> 
> 
> 网络超时，重试或者更换网络环境

``检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试``

**Comment by poly000** [comment]
> 
> 
> > 网络超时，重试或者更换网络环境
> 
> `检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试`

使用用户名和密码登录无问题……

**Comment by poly000** [comment]
> 
> 
> > 网络超时，重试或者更换网络环境
> 
> `检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试`

然后使用重新登录时获取的BDUSS突然好了…… 我看看历史

**Comment by poly000** [comment]
> 
> 
> > > 网络超时，重试或者更换网络环境
> > 
> > 
> > `检测BDUSS有效性错误代码: 1, 消息: 用户未登录或登录失败，请更换账号或重试`
> 
> 然后使用重新登录时获取的BDUSS突然好了…… 我看看历史

应该还是网络问题？……
再次登录时没报错

**Comment by poly000** [comment]
```
似乎是网络问题
```

**Comment by poly000** [comment]
又双提交了没用的issues……
丢人（

**Comment by mo-han** [comment]
一点不丢人
我刚刚也遇到了
研究了一下
tieba.baidu.com这个域名指向两个IP
103.235.46.140
103.235.46.139
其中139那个反应神速
而140那个几乎残废难得成功返回也要好几分钟
我建议在本地hosts文件里面把这个域名的地址写死

**Comment by mo-han** [comment]
一点不丢人
我刚刚也遇到了
研究了一下
tieba.baidu.com这个域名指向两个IP
103.235.46.140
103.235.46.139
其中139那个反应神速
而140那个几乎残废难得成功返回也要好几分钟
我建议在本地hosts文件里面把这个域名的地址写死
