### ISSUE TITLE
下载到一半，后面没速度了。

### ISSUE THREAD

**Issue by 17768810** [iikira/BaiduPCS-Go#759]
下载到一半，后面没速度了。

**Comment by iikira** [comment]
关掉软件，重新打卡再下载试试

**Comment by 17768810** [comment]
[1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:123, 重试 2/3

新的错误。。。。

**Comment by iikira** [comment]
这是被限制下载了，参见 #460

**Comment by joostshao** [comment]
我又充值了一年，争取明年让百度从纳斯达克退市！谢谢
