### ISSUE TITLE
下载目录时，文件结束后有时不会自动继续

### ISSUE THREAD

**Issue by jochne** [iikira/BaiduPCS-Go#76]
会停在↓ 1.18GB/1.18GB 11.93KB/s in 22m21.862s ..............这个界面

需要手动输入一下空格才会显示出下载完成以及进行下一个任务下载

**Comment by iikira** [comment]
知道了, 很奇怪,....

**Comment by iikira** [comment]
https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
