### ISSUE TITLE
ui问题

### ISSUE THREAD

**Issue by tangge233** [iikira/BaiduPCS-Go#761]
文件列表中的某个文件名称过长时，会导致一些ui显示问题，希望作者可以修复一下。

**Comment by iikira** [comment]
什么显示问题啊

**Comment by tangge233** [comment]
![image](https://user-images.githubusercontent.com/50769997/64057913-4bffb580-cbd6-11e9-86cc-a021edfc9cab.png)
就像这个样子

**Comment by tangge233** [comment]
对不起，搞错项目了
