### ISSUE TITLE
2019-8-31超级会员下载速度跟没有会员一样了

### ISSUE THREAD

**Issue by zzjyg** [iikira/BaiduPCS-Go#763]
之前都可以满速，不知道百度网盘又改了什么东东，windows

**Comment by pongfcnkl** [comment]
![QQ截图20190831180442](https://user-images.githubusercontent.com/24273319/64062514-d3224d00-cc19-11e9-94d0-1bfc203f7d66.png)
我这里能满速（家里是100M宽带）

**Comment by zzjyg** [comment]
> ![QQ截图20190831180442](https://user-images.githubusercontent.com/24273319/64062514-d3224d00-cc19-11e9-94d0-1bfc203f7d66.png)
> 我这里能满速（家里是100M宽带）

![image](https://user-images.githubusercontent.com/51195245/64064606-55206f00-cc36-11e9-968f-8633c07e807e.png)
我这之前能满速的，今天就不行了，速度来回跳，平均1m左右，跟没有会员一样，三个号都这样

**Comment by pongfcnkl** [comment]
> 
> 
> > ![QQ截图20190831180442](https://user-images.githubusercontent.com/24273319/64062514-d3224d00-cc19-11e9-94d0-1bfc203f7d66.png)
> > 我这里能满速（家里是100M宽带）
> 
> ![image](https://user-images.githubusercontent.com/51195245/64064606-55206f00-cc36-11e9-968f-8633c07e807e.png)
> 我这之前能满速的，今天就不行了，速度来回跳，平均1m左右，跟没有会员一样，三个号都这样

1m的话那你应该查一下本地的情况吧，比如有没有防火墙或第三方在限速，另外手机上试试，还是不行那路由器有没有问题。

**Comment by Anti-Venom95** [comment]
我被31326了 然后充值了普通会员 发现依然是下载失败

**Comment by pongfcnkl** [comment]
> 
> 
> 我被31326了 然后充值了普通会员 发现依然是下载失败 感觉自己上当了

现在普通会员没啥用，要超级会员才行，或者租号

**Comment by eryczou** [comment]
同样的问题，普通会员已经没用，升级到超级会员可用

**Comment by FateLight** [comment]
同，已经黑号

**Comment by bigbluecat** [comment]
之前是超级会员，后来到期了，隔了两天续费超级会员后好像还是限速200k

**Comment by 0987363** [comment]
超级会员一样不稳定

默认线程100的时候，速度从几十k到几十m来回跳
线程设到300，速度才稳定到20m，可是还是不能满速。

以前默认100线程的时候，速度接近40m，带宽满速

**Comment by 0987363** [comment]
超级会员虽然能下，但是还是限速，单线程200kb。。。

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
