### ISSUE TITLE
代码: 31326, 消息: user is not authorized, hitcode:123

### ISSUE THREAD

**Issue by jaythc** [iikira/BaiduPCS-Go#764]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:123

![image](https://user-images.githubusercontent.com/29886008/64064915-02e14d00-cc3a-11e9-8cc0-9791d6c210ce.png)
windows3.6版本

**Comment by hjie** [comment]
我也碰到了，下了一半，突然这样了

**Comment by JoeyTeng** [comment]
试试改 UA？我刚刚：
`config set -user_agent="netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia"`
就好了

**Comment by yifengyou** [comment]
> 试试改 UA？我刚刚：
> `config set -user_agent="netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia"`
> 就好了

并没有什么鸟用。依然会报错！

**Comment by yifengyou** [comment]
![image](https://user-images.githubusercontent.com/19882390/64072263-349bf780-ccbe-11e9-87b7-a05954deff24.png)

**Comment by iikira** [comment]
这是下载被限制了，参见#460

**Comment by tiger233** [comment]
我的充了会员也不行。难道普通会员也被限速了？

**Comment by CoreJK** [comment]
我改UA后可以用了，启用了https，其他的没改动
就改了这两个参数，普通会员。

**Comment by xtulnx** [comment]
> 我改UA后可以用了，启用了https，其他的没改动
> 就改了这两个参数，普通会员。

请问 UA 设置的是什么内容？
