### ISSUE TITLE
国内能不能搞一个wine软件商店，一起把win应用打包好发布到wine软件商店里,从商店里安装软件?

### ISSUE THREAD

**Issue by ZihaoXingstudy** [iikira/BaiduPCS-Go#765]
国内的360软件商店for linux，优麒麟,新支点,deepin等公司和linux个人爱好者能不能合作一起搞一个wine软件商店.

大家一起把大量常用的windows软件应用用wine打包并优化好发布到wine软件商店里,linux用户都可以从wine软件商店里下载和安装软件,拓展linux上的应用生态，让linux系统上有更多软件可以用,提高linux操作系统的使用体验?

https://www.zhihu.com/question/343841048

**Comment by iikira** [comment]
???

**Comment by iikira** [comment]
本项目支持linux版本的

**Comment by ZihaoXingstudy** [comment]
linux上的软件有点少，没有多少公司和个人为linux系统开发软件啊

**Comment by fuck2ky** [comment]
没啥用，而且linux真不是用来干这些的，要用windows用虚拟机就行了，多大点事
