### ISSUE TITLE
要么高速下载要么被封不能用，能不能可以有低速的选项，保持一直可用？

### ISSUE THREAD

**Issue by GaryDoooo** [iikira/BaiduPCS-Go#767]
我可以在云主机上面一直开着下，多下会儿倒是没关系。现在可以下载的时候非常快，但是被封了就彻底不能用。赶脚必须要SVIP才能用这个软件。。。[痛苦]

**Comment by GaryDoooo** [comment]
我今天下载了几个G的文件，非常快，然后又上传了几个G，非常快。过了一个多小时再下载，就“代码: 31326, 消息: user is not authorized, hitcode:119” 了。然后试了改appid，download --locate 都不行（这个命令小文件可以，大文件不行）。

**Comment by GaryDoooo** [comment]
所以，如果可以小水管一直稳定保证用也不错啊。

**Comment by pongfcnkl** [comment]
既然有云主机那直接搭个网盘

**Comment by Yifei0727** [comment]
使用单线程下载呗

**Comment by GaryDoooo** [comment]
> 使用单线程下载呗

把线程设置到1，还是用--locate？

**Comment by iikira** [comment]
下载时加上 `-locate`参数试一试

**Comment by GaryDoooo** [comment]
> 下载时加上 `-locate`参数试一试

3Q!

**Comment by hitxiaomi** [comment]
开通svip之后马上可以下载了．．．

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
建议设置最大下载并发量为1
```
BaiduPCS-Go config set -max_parallel 1
```
