### ISSUE TITLE
Linux 软链接无法上传

### ISSUE THREAD

**Issue by wmm131333** [iikira/BaiduPCS-Go#771]
Linux服务器上有目录a，建立软链接目录a-->目录b，使用BaiduPCS-Go上传目录b时显示上传速度为0，一直卡住不动。
![微信截图_20190905173812](https://user-images.githubusercontent.com/1886721/64330728-098a0e80-d004-11e9-99a5-089b4f2f773d.png)

**Comment by xiaoran27** [comment]
我也碰到同样的问题，现在是跳过软连接目录(自己判断)

**Comment by landall** [comment]
软连接在百度云里没有对应的实现……Windows的快捷方式好歹是个文件。
