### ISSUE TITLE
错误代码31326

### ISSUE THREAD

**Issue by BigBaiNB** [iikira/BaiduPCS-Go#773]
[1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:123

**Comment by narakuzi** [comment]
下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104
遇到同样的错误

**Comment by Hbzzw** [comment]
same here

**Comment by Hbzzw** [comment]
#767

**Comment by lowking** [comment]
一样的错误，同一个账号，在win10上用就正常的下载
mac上就提示
> 指令：download -locate 1/001.pdf
> [1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

> 指令：d 001.pdf
> [1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:117

**Comment by lorcx** [comment]
我是第一次在win10上能下载，中断以后在下载就不行了报31326

**Comment by jjwung** [comment]
我也遇到这个了，第一次能下载（几天前），现在不行了~！

**Comment by chinchew** [comment]
+1 不知道怎么解决

**Comment by landall** [comment]
这是被服务端黑名单了，我已经好多天了还没放出来……第一推荐的做法是先买超级会员试试。我被封时就是超级会员，可能压力测试太作死了，目前完全没放出来的意思。

**Comment by cjlsuper** [comment]
> 这是被服务端黑名单了，我已经好多天了还没放出来……第一推荐的做法是先买超级会员试试。我被封时就是超级会员，可能压力测试太作死了，目前完全没放出来的意思。

+1  感觉是进黑名单了

**Comment by landall** [comment]
我上一个黑名单没被放出来，这次又因为另外的原因被黑名单了，orzzzz
我用HEAD指令大量请求文件来查看是否有被8秒的，然后被黑名单了，其他api都正常，下载就会403，这次连80kb/s都不给了，直接403

**Comment by share18x** [comment]
我是svip下载失败QAQ

**Comment by iikira** [comment]
此下载错误已记录, #772
