### ISSUE TITLE
上传时文件夹的路径不能带空格

### ISSUE THREAD

**Issue by shiogami-satsuki** [iikira/BaiduPCS-Go#776]
如图所示，将文件夹改名后成功
![image](https://user-images.githubusercontent.com/12044683/64845228-31005d00-d63c-11e9-9eaf-92db53b42e8e.png)
貌似并不是引号的锅

**Comment by landall** [comment]
--vebose贴一下请求的url

**Comment by zzustu** [comment]
Windows下路径分割符 "\" 代表转义字符，请使用 "\\" 或 "/" 试试

**Comment by worksg** [comment]
今天在Linux上也遇到这个问题，看了下相关的源码，上传时对路径调用了filepath.Glob函数做通配符解析
https://github.com/iikira/BaiduPCS-Go/blob/master/internal/pcscommand/upload.go#L127
```golang
                                    // filepath.Glob函数在Windows和Linux上的行为不一样
		globedPaths, err := filepath.Glob(localPaths[k]) 
		if err != nil {
			fmt.Printf("上传文件, 匹配本地路径失败, %s\n", err)
			continue
		}
```

golang官方文档里的相关说明
https://golang.org/pkg/path/filepath/#Match
https://golang.org/pkg/path/filepath/#Glob

Linux上能对特殊字符做转义，不过Windows上把转义符号解释成路径分隔符了

    On Windows, escaping is disabled. Instead, '\\' is treated as path separator.

同一份源代码在Windows和Linux上的执行后的布尔值并不一样
https://play.golang.org/p/WV5N82HFqTk

![image](https://user-images.githubusercontent.com/37355296/68138182-19ba5d80-ff63-11e9-8162-d67a7b0ab8fa.png)


![image](https://user-images.githubusercontent.com/37355296/68137987-ce07b400-ff62-11e9-8aec-f4e88bd10c74.png)
