### ISSUE TITLE
请问是否可以关闭秒传检测

### ISSUE THREAD

**Issue by Tdickson3** [iikira/BaiduPCS-Go#779]
上传一个25G左右的文件，检测秒传中这个状态已经很久了。可不可以不检测秒传，直接上传。
![image](https://user-images.githubusercontent.com/44915990/65888694-883f5500-e3d2-11e9-85a3-f066469cc0a0.png)

**Comment by pongfcnkl** [comment]
-norapid

**Comment by iikira** [comment]
上传文件时加上 `-norapid` 参数
