### ISSUE TITLE
 undefined: strings.Builder

### ISSUE THREAD

**Issue by ghostry** [iikira/BaiduPCS-Go#78]
go get -u -v github.com/iikira/BaiduPCS-Go

github.com/iikira/BaiduPCS-Go (download)
github.com/iikira/BaiduPCS-Go/pcspath
github.com/iikira/BaiduPCS-Go/pcsconfig
\# github.com/iikira/BaiduPCS-Go/pcspath
src/github.com/iikira/BaiduPCS-Go/pcspath/util.go:14:14: undefined: strings.Builder
src/github.com/iikira/BaiduPCS-Go/pcspath/util.go:37:14: undefined: strings.Builder
\# github.com/iikira/BaiduPCS-Go/pcsconfig
src/github.com/iikira/BaiduPCS-Go/pcsconfig/baidu.go:47:14: undefined: strings.Builder

**Comment by iikira** [comment]
使用了go1.10的新功能，所以要升级go1.10

https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9
