### ISSUE TITLE
代码: 31326, 消息: user is not authorized, hitcode:104

### ISSUE THREAD

**Issue by zhhqiang3** [iikira/BaiduPCS-Go#785]
遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104,

**Comment by i1sfish** [comment]
同出现该问题

**Comment by tuchuants** [comment]
同出现此问题。

**Comment by xwsheng** [comment]
同样问题

**Comment by zjcnm** [comment]
同样问题~

**Comment by iikira** [comment]
```
config set -user_agent ""
```
清空 User-Agent 试一试

**Comment by zhhqiang3** [comment]
@iikira
![image](https://user-images.githubusercontent.com/20870394/66978207-8f0cde00-f0db-11e9-9e9f-b50072e8e801.png)
成功了谢谢
 @zjcnm @xwsheng @tuchuants @i1sfish

**Comment by pongfcnkl** [comment]
> 
> 
> ```
> config set -user_agent ""
> ```
> 
> 清空 User-Agent 试一试

这个能下，但是速度很慢。

**Comment by zjcnm** [comment]
可以了 ~现在超级会员下载也有限制了吗~

**Comment by brizer** [comment]
> ```
> config set -user_agent ""
> ```
> 
> 清空 User-Agent 试一试

很强！

**Comment by hs413447685** [comment]
> ```
> config set -user_agent ""
> ```
> 
> 清空 User-Agent 试一试

你好请问，在群晖 docker 里面怎么 运行 这个组命令

**Comment by cratylus** [comment]
> > ```
> > config set -user_agent ""
> > ```
> > 
> > 
> > 清空 User-Agent 试一试
> 
> 你好请问，在群晖 docker 里面怎么 运行 这个组命令

docker里直接修改配置文件，再restart就行了。
