### ISSUE TITLE
遇到错误, 远端服务器返回错误, 代码: 31326, 消息: anti hotlinking

### ISSUE THREAD

**Issue by honghaoaa1230** [iikira/BaiduPCS-Go#788]
当前配置:
         名称              值          建议值                              描述
  cache_size           30000        1024 ~ 262144  下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值
  max_parallel         100            50 ~ 500     下载最大并发量
  max_upload_parallel  8               1 ~ 100     上传最大并发量
  max_download_load    1                1 ~ 5      同时进行下载文件的最大数量
  savedir              D:/Download                 下载文件的储存目录
  enable_https         false            true       启用 https
  user_agent                                       浏览器标识
  proxy                                            设置代理, 支持 http/socks5 代理
  local_addrs                                      设置本地网卡地址, 多个地址用逗号隔开

**Comment by pongfcnkl** [comment]
#785

**Comment by showxu** [comment]
感觉是最近才出的问题，开了超级会员也没用

**Comment by iikira** [comment]
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧

**Comment by fengyuentau** [comment]
不开会员的时候还好好的。我挂着下载看速度不行，然后开了个超级会员反而遇到这个问题了。重设user-agent不管用，logout也不管用，删掉再跑也不管用。

**Comment by 456vv** [comment]
这个问题在最版本中一样发生
[1] 下载文件失败, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: anti hotlinking

**Comment by roberChen** [comment]
BaiduPCS-Go version v3.6.2-devel
[1] 下载文件失败, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: anti hotlinking

下载结束, 时间: 1.573s, 数据总量: 0B
