### ISSUE TITLE
超级会员也炸了？

### ISSUE THREAD

**Issue by pongfcnkl** [iikira/BaiduPCS-Go#789]
下载文件错误, 下载单个文件: json 数据解析失败, readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html>
<he|..., bigger context ...|<html>
<head><title>500 Internal Server Error</tit|..., 重试 1/3

[2] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 10098, 消息: access denied, 重试 2/3

**Comment by iikira** [comment]
测试正常，似乎是服务器的问题
