### ISSUE TITLE
下载速度变成 0 kb 的问题

### ISSUE THREAD

**Issue by cj-neo** [iikira/BaiduPCS-Go#792]
一开始下载正常速度也很快，但一阵子后下载速度变成 0 kb，关掉重开之后重新开始下载，只跑玩列表就卡住无法下载，有人和我一样的情形吗？后来发现换个 IP 用同帐号还是可以正常下载，我有买超级会员登入，难道现在连超级会员也开始限制下载量了吗 @@"

**Comment by showxu** [comment]
是的

**Comment by iikira** [comment]
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

**Comment by cj-neo** [comment]
> 尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

還是會顯示錯誤，但可以正常下載，如下圖
![圖片 73](https://user-images.githubusercontent.com/35209118/68255575-96832f80-0068-11ea-8c08-75ab2caad9f0.png)

**Comment by iikira** [comment]
那个错误好像是服务器丢数据了，去官方客户端下载看看

**Comment by cj-neo** [comment]
> 那个错误好像是服务器丢数据了，去官方客户端下载看看

官方客户端下載一切正常

**Comment by cj-neo** [comment]
剛又多下載了幾個檔案發現幾個問題，部份小檔案無法下載（速度0K）大檔案可以下載但是速度偏慢（同樣環境用官方下載幾M 但用 BaiduPCS-Go 只有幾百K），謝謝！

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
