### ISSUE TITLE
sf命令有点问题

### ISSUE THREAD

**Issue by yiuty** [iikira/BaiduPCS-Go#795]
Windows版的软件用sf 不能使用*通配符，Linux版可以使用。
[1] open *.rar: The filename, directory name, or volume label syntax is incorrect.
win版的一直都是这个提示，sf后面的对象必须指定到具体的文件名。
sf * 或者 sf *.* 之类的都不行
Linux版可以正常使用sf *.rar。

**Comment by iikira** [comment]
Windows的通配符可不好用，建议指定到具体的文件名
