### ISSUE TITLE
编译出现 410 gone 错误

### ISSUE THREAD

**Issue by 275761919** [iikira/BaiduPCS-Go#796]
在 `go version go1.13.3 linux/amd64` 下执行命令 `go get -u -v github.com/iikira/BaiduPCS-Go` 会出现如下错误：
```verifying github.com/iikira/Baidu-Login@v1.2.1: github.com/iikira/Baidu-Login@v1.2.1: reading https://sum.golang.org/lookup/github.com/iikira/!baidu-!login@v1.2.1: 410 Gone```

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by iikira** [comment]
测试正常，看起来是网络的问题

**Comment by 275761919** [comment]
把 `~/go/pkg/mod/cache/download/github.com/iikira/!baidu-!login/@v/v1.2.1.zip.tmpxxxxxxxx` 重命名成 `v1.2.1.zip` 后，又出现 
```
build github.com/iikira/BaiduPCS-Go: cannot load github.com/iikira/Baidu-Login: unzip ~/go/pkg/mod/cache/download/github.com/iikira/!baidu-!login/@v/v1.2.1.zip: case-insensitive file name collision: "cmd/Baidu_Login" and "cmd/baidu_login"
```
这个错误

**Comment by 275761919** [comment]
`v1.2.1.zip.tmpxxxxxxxxx` 一共有3个，3个的sha256sum都一样，网络问题是不是可能性不太大

**Comment by 275761919** [comment]
另一台电脑就没问题。。。。

**Comment by 275761919** [comment]
应该是 go 版本问题，我降级到g1.10.4就没有问题，go1.12，go1.13均有问题

**Comment by iikira** [comment]
试一试清除go module, 路径在 `$GOPATH/pkg/mod` 或者 `$HOME/go/pkg/mod`

或者关闭go module
```
export GO111MODULE=off
```

**Comment by 275761919** [comment]
关闭go module之后确实也可以了，关了有什么影响吗

**Comment by iikira** [comment]
没有影响，那个只是新的包管理工具
