### ISSUE TITLE
tree命令太慢

### ISSUE THREAD

**Issue by 8546KB** [iikira/BaiduPCS-Go#797]
如果网盘里文件(文件夹)过多,tree命令跑完要很久.能否解决一下这个问题.

**Comment by 8546KB** [comment]
win10系统

**Comment by owlfeng1021** [comment]
tree 没有多的参数 全跑完再快也其实没有多大用    主要是不能转文件流
参照 linux里面的tree命令  tree > file  以及选层级和指定类型的文件 等参数
