### ISSUE TITLE
31066

### ISSUE THREAD

**Issue by spartaxie** [iikira/BaiduPCS-Go#798]
[2] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

**Comment by iikira** [comment]
文件名输入错误，可能时文件名中有空格，参见[常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

>使用双引号扩起文件名，或者在空格, 小括号, 中括号, 特殊字符前加一个反斜杠"\"
另外, 建议在命名文件时, 不要使用这些字符==
