### ISSUE TITLE
2019/10/24突然速度很慢（平时10%不到而且很卡），并且频繁下载文件错误, 403 Forbidden, 重试

### ISSUE THREAD

**Issue by detectRecog** [iikira/BaiduPCS-Go#799]
作为超级会员，这半年多了，传数据下电影用着极其的爽。

今天突然频繁 403 Forbidden, 重试
并且速度慢了很多而且最后1%卡得要死

想问问大家，只有我一个人这样么？

**Comment by detectRecog** [comment]
哪位高手有解决办法没？

**Comment by leviBar** [comment]
> 作为超级会员，这半年多了，传数据下电影用着极其的爽。
> 
> 今天突然频繁 403 Forbidden, 重试
> 并且速度慢了很多而且最后1%卡得要死
> 
> 想问问大家，只有我一个人这样么？

我也是这个问题，大于1G 的 有一半可以下载，一半下载失败。已经有1-2周了，也是超级会员。目前还没好的办法。

**Comment by detectRecog** [comment]
> > 作为超级会员，这半年多了，传数据下电影用着极其的爽。
> > 今天突然频繁 403 Forbidden, 重试
> > 并且速度慢了很多而且最后1%卡得要死
> > 想问问大家，只有我一个人这样么？
> 
> 我也是这个问题，大于1G 的 有一半可以下载，一半下载失败。已经有1-2周了，也是超级会员。目前还没好的办法。

多d几次就可以下载，但是很慢，我是放在/apps/baidu_shurufa下面的 不知道是不是换个目录会有效果

**Comment by detectRecog** [comment]
"netdisk;P2SP;2.0.12.59;netdisk;9.0.0;red;iPhone-iPhone;12_1_2"
，然后就不会403了，速度还是比较慢

点到为止，看懂的去set试一下，看不懂的也别问

**Comment by leviBar** [comment]
> "netdisk;P2SP;2.0.12.59;netdisk;9.0.0;red;iPhone-iPhone;12_1_2"
> 可以set试一下，然后就不会403了，速度还是比较慢
> 
> 效果并不稳定，继续找解决方案中

http://blog.sina.com.cn/s/blog_542268bd0102yjlq.html
我用这个方案，重试 大约6-7次 会成功一次

**Comment by leviBar** [comment]
> "netdisk;P2SP;2.0.12.59;netdisk;9.0.0;red;iPhone-iPhone;12_1_2"
> 可以set试一下，然后就不会403了，速度还是比较慢
> 
> 效果并不稳定，继续找解决方案中

刚才试了下你的方式，大部分3次左右会成功，如果能增加重试次数 就好了。

**Comment by tokimemo** [comment]
昨天还是能用的, 今天应该又败毒那边应该又调整过了, 现在开多少线程都没用, 速度只有1M左右 SVIP

**Comment by linker999** [comment]
是的 昨天开始就不行了

**Comment by mackgim** [comment]
一样情况了。能下的速度极低，不能下的，返回 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122。 是SVIP啊

**Comment by tokimemo** [comment]
今天又测试了下, 发现上传速度没有任何限制, 然而下载限制更大了, 今天自由几百K了.很明显是败毒是有针对性的行动.

**Comment by tokimemo** [comment]
另外, 现在下载任务超过2就会疯狂403, 反正开多了也没用

**Comment by zzjyg** [comment]
config set --user_agent="Mozilla;5.0"
试试吧  万一好用呢

**Comment by detectRecog** [comment]
好不好用我不清楚 我先关了这个 再问下去也没意思了
