### ISSUE TITLE
download下载拉取资源请求经常出现错误:User is not authoriatical,hitcode:401(2019-10-25)

### ISSUE THREAD

**Issue by wuyuansushen** [iikira/BaiduPCS-Go#800]
默认是3次请求，经常3次请求都会出现以上错误，导致无法下载，要手动尝试下载十几次之后，随缘遇到一个下载链接能用才能进行下载，但是一旦下载链接获取成功后，对下载速度没有影响(基本满带宽)

**Comment by wuyuansushen** [comment]
默认是3次请求，经常3次请求都会出现以上错误，导致无法下载，要手动尝试下载十几次之后，随缘遇到一个下载链接能用才能进行下载，但是对网速没有影响

**Comment by 8T15Bin** [comment]
试一下 config set -user_agent "" 
有可能是因为用过pandownload和switch user agent插件导致
我是这么解决的

**Comment by wuyuansushen** [comment]
> 试一下 config set -user_agent ""
> 有可能是因为用过pandownload和switch user agent插件导致
> 我是这么解决的

亲测有效，但是你发的命令有问题，标准执行应该是config set -user_agent=""

**Comment by SettingDust** [comment]
config set --enable_https=true

**Comment by wsng911** [comment]
BaiduPCS-Go config set -appid=265486
BaiduPCS-Go config set -user_agent=""

**Comment by sdjk** [comment]
BaiduPCS-Go config set -appid=265486
这个修改会导致无法获取目录

**Comment by marklove5102** [comment]
果然牛皮。

> BaiduPCS-Go config set -appid=265486
> BaiduPCS-Go config set -user_agent=""

**Comment by brightgems** [comment]
果然能用，谢谢

BaiduPCS-Go config set -user_agent=""

**Comment by leviBar** [comment]
> 果然能用，谢谢
> 
> BaiduPCS-Go config set -user_agent=""

我改成这样，有些能用，有些还是不行，svip，最新版本

**Comment by zhangliukun** [comment]
> config set --enable_https=true

在win7使用的时候命令有效

**Comment by zhangliukun** [comment]
> > 试一下 config set -user_agent ""
> > 有可能是因为用过pandownload和switch user agent插件导致
> > 我是这么解决的
> 
> 亲测有效，但是你发的命令有问题，标准执行应该是config set -user_agent=""

在macos系统中亲测有效

**Comment by iikira** [comment]
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新
