### ISSUE TITLE
windows定时任务

### ISSUE THREAD

**Issue by dexterque** [iikira/BaiduPCS-Go#803]
![image](https://user-images.githubusercontent.com/10069761/67996947-c7d8b580-fc8c-11e9-92a8-d6069709e982.png)

请教一下：
我想在添加一个定时任务 打开baidupcs软件 再执行 `d 电影名.mp4`
能实现吗？

**Comment by iikira** [comment]
能的

**Comment by dexterque** [comment]
> 能的

试了不行鸭……

**Comment by iikira** [comment]
试一试这样
```
F:\BaiduPCS-Go-windows-amd64\BaiduPCS-Go.exe d 电影名.mp4
```

先手动执行一遍看看结果，然后再加入定时任务

**Comment by dexterque** [comment]
> 试一试这样
> 
> ```
> F:\BaiduPCS-Go-windows-amd64\BaiduPCS-Go.exe d 电影名.mp4
> ```
> 
> 先手动执行一遍看看结果，然后再加入定时任务

可以的，多谢楼主 :)
