### ISSUE TITLE
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104

### ISSUE THREAD

**Issue by lucky-lee** [iikira/BaiduPCS-Go#804]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:104
下载的时候遇到这个问题，是下载了一个2.4g的视频

**Comment by pongfcnkl** [comment]
https://github.com/iikira/BaiduPCS-Go/issues/802

**Comment by mn19941219** [comment]
亲测可行
./BaiduPCS-Go config set -user_agent=""

**Comment by iikira** [comment]
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

**Comment by marklove5102** [comment]
目前自己编译 ， 结果一样。 不能下。

**Comment by marklove5102** [comment]
HEAD 现在位于 df2029c 调整子模块结构

**Comment by mh710774265** [comment]
"pcs_ua": "",
 "pan_ua": "",
能解释下这两个作用范围吗？。。

**Comment by iikira** [comment]
> "pcs_ua": "",
> "pan_ua": "",
> 能解释下这两个作用范围吗？。。

pcs_ua 访问 pcs.baidu.com 使用的user_agent
pcs_ua 访问 pan.baidu.com 使用的user_agent
这两个都有默认的预设

**Comment by iikira** [comment]
说明一下，只是尝试修复了不能下载大文件的问题，并没有解决限制下载的问题。。

**Comment by landall** [comment]
> 说明一下，只是尝试修复了不能下载大文件的问题，并没有解决限制下载的问题。。

这几天百度好像还在改，经常今天好用的协议明天就挂了，好烦……

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧
