### ISSUE TITLE
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

### ISSUE THREAD

**Issue by wsng911** [iikira/BaiduPCS-Go#807]
尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试

_Originally posted by @iikira in https://github.com/iikira/BaiduPCS-Go/issues/804#issuecomment-549671896_
 下载哪一个？

**Comment by pongfcnkl** [comment]
你是哪个系统就下哪一个。。。

**Comment by wsng911** [comment]
感觉不好使呢 跟之前情况一样

**Comment by SeasonG-CN** [comment]
> 尝试修复了，到https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts 下载测试版使用试一试
> 
> _Originally posted by @iikira in [#804 (comment)](https://github.com/iikira/BaiduPCS-Go/issues/804#issuecomment-549671896)_
> 下载哪一个？

**如果你是64位Windows系统,下载"BaiduPCS-Go-windows-amd64"就好了**
