### ISSUE TITLE
下载小文件成功，下载大文件失败；错误信息”遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122“

### ISSUE THREAD

**Issue by ZMGGMZ** [iikira/BaiduPCS-Go#808]
小文件可以下载成功，较大的文件会下载失败。。
用的是度娘vip账号。
BaiduPCS-Go版本用了最新的release版本和https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts下获取的beta版本，都出现同样的情况。。

**Comment by pongfcnkl** [comment]
多重试几次就行

**Comment by ZMGGMZ** [comment]
😂多试几次，换文件，都还是不行。。
试了下别人说的置空掉UA，也还是不行。。

**Comment by iikira** [comment]
此问题已记录, #802
