### ISSUE TITLE
下载文件遇到错误,代码: 31209,data not exists in any region

### ISSUE THREAD

**Issue by karma-sun** [iikira/BaiduPCS-Go#809]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31209, 消息:data not exists in any region

但是同一文件直接用百度云官方网页版可以下载

**Comment by iikira** [comment]
文件分享一下

**Comment by marklove5102** [comment]
这个我遇到过 pcs弹出来的地址丢谷歌浏览器 能下 pcs 不能下。

**Comment by marklove5102** [comment]
同一账号 
ua 默认
[3] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122, 重试 2/3

ua
User-Agent: Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
网页
http://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Fapps%2Fbaidu_shurufa%2XXXXXX.zip
http://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=266719&path=%2Fapps%2Fbaidu_shurufa%2XXXXXX.zip
均可下载

**Comment by karma-sun** [comment]
刚试了又不报错了，可能是百度云的问题
