### ISSUE TITLE
超大文件没速度，而且退出时卡

### ISSUE THREAD

**Issue by zisee** [iikira/BaiduPCS-Go#81]

**Comment by iikira** [comment]
超大文件具体是多大呢，目前只发现苹果系统下载大文件时退出慢，与苹果的写文件方法有关...

**Comment by iikira** [comment]
不好意思，刚刚没看到图片，退出时卡是因为程序预先在磁盘创建这12g的文件，下载速度慢可以尝试调整下载线程……

**Comment by iikira** [comment]
No response from reporter.

https://github.com/iikira/BaiduPCS-Go/releases

[关于下载的简单说明](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%85%B3%E4%BA%8E%E4%B8%8B%E8%BD%BD%E7%9A%84%E7%AE%80%E5%8D%95%E8%AF%B4%E6%98%8E)

新版本重构了下载器, 并移除了旧的下载器, 如有新的问题, 重新开 issue 吧.
