### ISSUE TITLE
百度VIP，下载速度不到100K？

### ISSUE THREAD

**Issue by yuritry** [iikira/BaiduPCS-Go#810]
不知道什么原因，用百度超级会员，下载速度只有100K，而且部分文件出现错误：下载文件错误, 403 Forbidden。

**Comment by yuritry** [comment]
是不是已经被百度封了？

**Comment by pongfcnkl** [comment]
现在第三方基本上都被封杀了，只能用官方的吧

**Comment by sayainchina** [comment]
就算是svip也会被ban

**Comment by iikira** [comment]
这个版本太老了，看不出具体的错误，[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧

**Comment by FFFcat** [comment]
> 这个版本太老了，看不出具体的错误，[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新, 先关闭了, 如遇到新问题或问题依旧, 重新开issue吧

用了3.6.1的版本也是这样，有403，能下也200多k。。开了超级会员
