### ISSUE TITLE
分享下载时，文件名包含 & 会提示参数错误无法下载

### ISSUE THREAD

**Issue by cheshuai123** [iikira/BaiduPCS-Go#811]
![image](https://user-images.githubusercontent.com/22605709/68555379-7b4d6100-0468-11ea-9ec1-da4aaaf64c79.png)
将名称中的 & 改为空格后，分享下载已没有问题。
![image](https://user-images.githubusercontent.com/22605709/68556240-59ee7400-046c-11ea-9cd5-2a0ec612cfd5.png)

**Comment by yuritry** [comment]
用baidupcs-go 还能下载吗？

**Comment by cheshuai123** [comment]
> 用baidupcs-go 还能下载吗？

我是在云主机上用的。网速无所谓，慢慢跑😂

**Comment by yuritry** [comment]
我在vps上跑，速度是0。

**Comment by iikira** [comment]
未能复现此问题，按理来说应该跟&号没有关系的啊😂

**Comment by cheshuai123** [comment]
之前问题自己改名解决了所以没截问题的图，刚测试的：
![image](https://user-images.githubusercontent.com/22605709/69469947-8d1af680-0dce-11ea-8462-fd0c4810f763.png)
这个是测试文件链接：
链接:https://pan.baidu.com/s/1sei-46DPkTqX_mhFmfbewg 提取码:n1eq
执行命令： 
share s '09th 夏のFree&Easy'    (分享没问题）
d '09th 夏のFree&Easy' --share  (下载报错）
可能之前表述有问题，应该是文件夹或文件名中包含 &  导致的😂
不过能手动解决，不是大问题。这种情况应该也不多

**Comment by iikira** [comment]
应该修复了，再试一试呢

**Comment by cheshuai123** [comment]
> 应该修复了，再试一试呢

刚更新版本后测试确时已修复，感谢大佬！
