### ISSUE TITLE
弱弱的问一句开发者大大，新版本什么时候出来呀

### ISSUE THREAD

**Issue by wsng911** [iikira/BaiduPCS-Go#813]

**Comment by pongfcnkl** [comment]
开超级会员用官方吧

**Comment by shunjiankongbai** [comment]
问题是已经是SVIP了，就想在ubuntu上用而已

**Comment by pongfcnkl** [comment]
> 
> 
> 问题是已经是SVIP了，就想在ubuntu上用而已

百度网盘不是已经出linux版的了？

**Comment by sayainchina** [comment]
官方太狗，我都已经是svip，但是没有命令行版，我能怎么办0 0

**Comment by gdw1986** [comment]
> 官方太狗，我都已经是svip，但是没有命令行版，我能怎么办0 0

 一样...现在有会员速度还是不稳，不开心

**Comment by fr0zenrain** [comment]
用官方Linux版吧，这样真的好累啊。

**Comment by iikira** [comment]
[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases) 已更新
