### ISSUE TITLE
上传文件失败, 分片上传—文件分片及上传: 网络错误, http 响应 错误, 400 Bad Request, 重试 1/3

### ISSUE THREAD

**Issue by yinggcy** [iikira/BaiduPCS-Go#814]
用的是腾讯云的1Mb小油管. 不会尝试重试..  是什么导致出现这种错误? 有没有解决办法?
![捕获1](https://user-images.githubusercontent.com/31366576/69001636-4dab6080-091d-11ea-9bbe-ef337aaf0b43.PNG)

**Comment by iikira** [comment]
此问题已记录, #782, 原因未知。。
