### ISSUE TITLE
获取文件/目录的元信息, 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file

### ISSUE THREAD

**Issue by sev769** [iikira/BaiduPCS-Go#818]
咋回事啊，很久以前就有了，然后没问过了，今天更新下程序还是用不了。。

**Comment by sev769** [comment]
获取目录下的文件列表, 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized, 路径: /

**Comment by sev769** [comment]
> 咋回事啊，很久以前就有了，然后没问过了，今天更新下程序还是用不了。。

然后没用过了，错字

**Comment by iikira** [comment]
将appid改回266719
```
config set -appid 266719
```

**Comment by wsng911** [comment]
终于更新了，但为什么我还是不能下载啊。
BaiduPCS-Go config set -appid=265486
BaiduPCS-Go config set -user_agent=""
还有哪里需要配置的

**Comment by iikira** [comment]
@wsng911 appid应设置为266719，否则无法使用
```
BaiduPCS-Go config set -appid=266719
```
