### ISSUE TITLE
测试下载比实际下载快

### ISSUE THREAD

**Issue by WeidiDeng** [iikira/BaiduPCS-Go#82]
首先感谢作者写的这个百度云工具
但如图所示
![测试下载](https://user-images.githubusercontent.com/28780594/37254001-2728aa8c-2574-11e8-8404-095fb75b9f2d.JPG)
![实际下载](https://user-images.githubusercontent.com/28780594/37254021-57ead596-2574-11e8-977e-e618a900775f.JPG)
两者的速度不同

**Comment by iikira** [comment]
测试下载和下载的实现原理是一样的……速度慢的问题，怀疑是百度搞鬼. 目前没有想到较好的解决办法.

**Comment by WeidiDeng** [comment]
把临时文件删了重下又好了，感觉对单个文件下载速度要比遍历下整个文件夹快，还是谢谢了😂😆
