### ISSUE TITLE
查看正在下载的任务

### ISSUE THREAD

**Issue by fifiand1** [iikira/BaiduPCS-Go#820]
我是远程下载的，putty远程连接断开后，下次能恢复查看正在下载的任务吗

**Comment by mingjun97** [comment]
ssh远程连接断开后会导致进程退出。断开后BaiduPCS-Go应该会被关闭，下载就停止了。因为BaiduPCS-Go支持断点续传，所以下次登陆后也可以继续下载。

使用如下方法可以避免断开连接后进程被关闭：
1. 使用nohup指令，即`nohup ./BaiduPCS-Go download xxxx &`，该方法不能以交互模式启动。下载过程中可以使用`cat nohup.out`来查看输出的日志。
2.使用screen程序，通过切换screen来保证ssh断开后进程不被关闭。下次登陆后可以重新attach进该screen。
