### ISSUE TITLE
配置文件路径可以指定吗

### ISSUE THREAD

**Issue by liuzhuoling2011** [iikira/BaiduPCS-Go#825]
比如说可以启动的时候指定配置文件的路径为当前目录, 这样便携一些

**Comment by iikira** [comment]
设置环境变量 `BAIDUPCS_GO_CONFIG_DIR` 试一试

**Comment by zzjyg** [comment]
运行前在当前文件夹里建一个文件pcs_config.json就行了，空文件就行
