### ISSUE TITLE
bduss登陆报错

### ISSUE THREAD

**Issue by dbv** [iikira/BaiduPCS-Go#826]
检测BDUSS有效性网络错误, Post http://tieba.baidu.com/c/s/login: dial tcp [2400:da00:5f26:400::6f2d:b2f]:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by iikira** [comment]
网络超时，重试吧

**Comment by bsp789** [comment]
用3.5.6登录并用3.6.1下载
