### ISSUE TITLE
开了超级会员也没速度

### ISSUE THREAD

**Issue by zhaibin18** [iikira/BaiduPCS-Go#827]
百度客户端下载能有十几兆，用BaiduPCS-Go就是有200K，是正常吗？

**Comment by pongfcnkl** [comment]
正常

**Comment by wsng911** [comment]
换APPID，APPID决定下载速度，刚发现的

**Comment by zhaibin18** [comment]
求获得appid的方法。

**Comment by wsng911** [comment]
> 求获得appid的方法。

推荐应用ID：250528（官方）、265486、309847；

**Comment by Nixiabing** [comment]
> > 求获得appid的方法。
> 
> 推荐应用ID：250528（官方）、265486、309847；

修改了反而打不开自己的网盘目录啊

**Comment by wsng911** [comment]
> > > 求获得appid的方法。
> > 
> > 
> > 推荐应用ID：250528（官方）、265486、309847；
> 
> 修改了反而打不开自己的网盘目录啊

那就改回去好了，我一般直接在批处理改，改完随时恢复。

@echo off
color 27
cls

BaiduPCS-Go who
BaiduPCS-Go config set -appid=309847
BaiduPCS-Go config set -user_agent=""
BaiduPCS-Go config set -savedir="D:\下载"
ECHO UPDATE|BaiduPCS-Go 

start BaiduPCS-Go

**Comment by Nixiabing** [comment]
> > > > 求获得appid的方法。
> > > 
> > > 
> > > 推荐应用ID：250528（官方）、265486、309847；
> > 
> > 
> > 修改了反而打不开自己的网盘目录啊
> 
> 那就改回去好了，我一般直接在批处理改，改完随时恢复。
> 
> @echo off
> color 27
> cls
> 
> BaiduPCS-Go who
> BaiduPCS-Go config set -appid=309847
> BaiduPCS-Go config set -user_agent=""
> BaiduPCS-Go config set -savedir="D:\下载"
> ECHO UPDATE|BaiduPCS-Go
> 
> start BaiduPCS-Go

309847这个还可以用，其他两个都不行了；
还有就是下载速度还是受到200k/s的限制。——BaiduPCS-Go 3.6.8

**Comment by wsng911** [comment]
> > > > > 求获得appid的方法。
> > > > 
> > > > 
> > > > 推荐应用ID：250528（官方）、265486、309847；
> > > 
> > > 
> > > 修改了反而打不开自己的网盘目录啊
> > 
> > 
> > 那就改回去好了，我一般直接在批处理改，改完随时恢复。
> > @echo off
> > color 27
> > cls
> > BaiduPCS-Go who
> > BaiduPCS-Go config set -appid=309847
> > BaiduPCS-Go config set -user_agent=""
> > BaiduPCS-Go config set -savedir="D:\下载"
> > ECHO UPDATE|BaiduPCS-Go
> > start BaiduPCS-Go
> 
> 309847这个还可以用，其他两个都不行了；
> 还有就是下载速度还是受到200k/s的限制。——BaiduPCS-Go 3.6.8

778750

**Comment by zzjyg** [comment]
什么都不要改  加 --locate参数

**Comment by wsng911** [comment]
> 什么都不要改 加 --locate参数

怎么做

**Comment by ahan** [comment]
> > 什么都不要改 加 --locate参数
> 
> 怎么做

直接在下载命令后面加，例如：
`d Green.Complete.720p.HDTV.iPAD.AAC.x264-CHDPAD/ --locate`

**Comment by Code-Fight** [comment]
> > > 什么都不要改 加 --locate参数
> > 
> > 
> > 怎么做
> 
> 直接在下载命令后面加，例如：
> `d Green.Complete.720p.HDTV.iPAD.AAC.x264-CHDPAD/ --locate`

加这个参数 开始好用 到后面就慢了 咋回事

**Comment by gdw1986** [comment]
> > > > 什么都不要改 加 --locate参数
> > > 
> > > 
> > > 怎么做
> > 
> > 
> > 直接在下载命令后面加，例如：
> > `d Green.Complete.720p.HDTV.iPAD.AAC.x264-CHDPAD/ --locate`
> 
> 加这个参数 开始好用 到后面就慢了 咋回事

一样

**Comment by benworushi** [comment]
> 什么都不要改 加 --locate参数

有用，速度在10M左右了

**Comment by yuritry** [comment]
把问题直接提给百度。

**Comment by iikira** [comment]
做了一个SVIP下载的小调查, 参考一下呢, #858

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
