### ISSUE TITLE
关于百度云破解下载的两个姿势

### ISSUE THREAD

**Issue by wsng911** [iikira/BaiduPCS-Go#829]
1、BaiduPCS-Go，这是我用着最方便的了，曾经。现在要调整APPID=265486、309847，设置User_agent=“”才能正常使用，但速度不稳定，连续下载后容易被限速。
2、IDM+油猴+百度云下载助手，浏览器用的Chrome，按网上的教程操作即可。懒人可以去搜奔跑的奶酪的修改版。如果不成功，问题只会出现在两个方面，浏览器和油猴插件。
期待作者尽快更新新版本，修复速度问题。

**Comment by pongfcnkl** [comment]
开超级会员用官方客户端

**Comment by wsng911** [comment]
> 开超级会员用官方客户端

有钱，任性。

**Comment by wsng911** [comment]
778750

**Comment by KingZhengWei** [comment]
用的Windows系统发现下载速度几十kb/s 是不是现在不能用了

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
