### ISSUE TITLE
文件上传已传数据不增反降

### ISSUE THREAD

**Issue by gayhub-dev** [iikira/BaiduPCS-Go#830]
版本:3.6.1
cmd: upload -p 200  wtf.rar /
3.40GB/5.01GB 2.22MB/s
一会儿又会变成
3.16GB/5.01GB 2.25MB/s
出现概率极大,不知道是不是网络原因,传个5G的文件可能实际上传了15G数据

**Comment by iikira** [comment]
上传最大并发量太大了，(-p 值)，导致上传失败，不断重试，尝试调小该值

**Comment by gayhub-dev** [comment]
> 上传最大并发量太大了，(-p 值)，导致上传失败，不断重试，尝试调小该值

调小了之后上传速度只有几十-几百K了...美西的vps,不知道为什么这么慢,ping很稳定

**Comment by iikira** [comment]
可能是vps和百度网盘服务器连接不畅

**Comment by gayhub-dev** [comment]
连接应该还算稳定的，偶尔超时(不到1%)，现在只能手动中断上传再重新开始，这样速度又恢复正常了
