### ISSUE TITLE
限速严重

### ISSUE THREAD

**Issue by Nixiabing** [iikira/BaiduPCS-Go#831]
一上200k/s就被疯狂限速，
也是醉了。

**Comment by wsng911** [comment]
config set -appid=778750
低调，千万低调，我留着防身用的。

**Comment by callmelord** [comment]
你冲个最便宜的会员试一试，这东西被小白用户搞坏了

**Comment by nooblym** [comment]
超级会员香港阿里稳定150kb左右，求破

**Comment by dmwin72015** [comment]
现在这种个人开发的基本上没啥用了，和官方速度没啥太大区别，

**Comment by LucaLush** [comment]
开个最便宜的会员用官方客户端都有个200K/s了，还需要折腾吗？

**Comment by yuritry** [comment]
如果是超级会员，直接把问题提给百度。凭什么限速？

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
