### ISSUE TITLE
linux版本命令行无法下载

### ISSUE THREAD

**Issue by janglichao** [iikira/BaiduPCS-Go#832]
使用download命令如下错误：
![image](https://user-images.githubusercontent.com/1237692/70763107-e5ba2f80-1d8d-11ea-9ede-af67a3782765.png)
使用locate命令如下错误：
![image](https://user-images.githubusercontent.com/1237692/70763210-4b0e2080-1d8e-11ea-967d-8af55d8f8481.png)

**Comment by janglichao** [comment]
download命令：
[1] 获取路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

任务结束, 时间: 105ms, 数据总量: 0B

locate命令：
[0] 获取下载链接: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在.....
提示: 访问下载链接, 需将下载器的 User-Agent 设置为: netdisk;2.2.51.6;netdisk;10.0.63;PC;android-android

**Comment by iikira** [comment]
这是找不到文件的错误，文件路径是否正确啊

**Comment by iikira** [comment]
测试正常
