### ISSUE TITLE
关于增加超时重试功能的建议

### ISSUE THREAD

**Issue by lizkes** [iikira/BaiduPCS-Go#833]
在使用“--locate”方式进行下载时，下载速度有时会变成0kb/s（在 #792 中有提到，以及分片上传时的0kb/s问题 #782 ）。
这时退出下载，再重新下载的话，由于断点续传功能会继续下载，而且速度恢复正常。
所以希望作者可以增加一个超时重试功能，在一定时间内下载速度维持0kb/s（或某一个指定值以下）时停止下载并重新下载（也即重试），应该可以解决这种类似的限速问题。

**Comment by zzjyg** [comment]
反正是命令行的，自己写个脚本就行了，百度一搜一大把

**Comment by le0-VV** [comment]
> 反正是命令行的，自己写个脚本就行了，百度一搜一大把

怎么在macOS zsh里写脚本，能给个方向吗？

**Comment by zzjyg** [comment]
zsh不了解，百度一下说是兼容bash？这是bash的思路
count=600
./1.sh &  #这里写下载的命令
echo $!
pid=$!
while true
do
echo $count
sleep 1
if ! ps -p $pid > /dev/null
then
   echo "done"
   exit 0
fi
((count--))
if [ $count -eq 0 ]; then
    echo "redo"
    $0 $@
fi
done

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
