### ISSUE TITLE
对文件夹路径过深下载速度慢的看法

### ISSUE THREAD

**Issue by WeidiDeng** [iikira/BaiduPCS-Go#84]
如题，下载文件夹时路径过深时速度会非常慢，但经测试，删掉下载的临时文件后，分别手动输入下载各个文件，速度还是很快的（不删掉之前的临时文件依然很慢）

现有的downloadDirectory实现方式是递归下载文件夹和里面的文件，我想能不能换一种实现方式，当下载某个目录时，首先遍历各个目录，输出一个每行都是需要下载的文件的网盘地址的文本文件，再调用RunDownload下载每行的各个文件

ps：作者可以贴个二维码，愿意资助。

**Comment by iikira** [comment]
按理来说临时文件应该不会对下载速度造成影响的啊，还有这个部分迟早要被我重构……如果有时间的话, 嘻嘻…

**Comment by iikira** [comment]
唉对了，存在临时文件时，下载慢的话，尝试调高下载缓存应该可以提速，程序是根据写入磁盘的数据计算下载速度的，并非实际的下载速度.

**Comment by iikira** [comment]
已更换文件夹下载的实现方法, c4fd746f08ce100fa093549abfebe75f3d3af0c2, 和你所描述的差不多了...
编译安装程序可看到效果...

**Comment by WeidiDeng** [comment]
测试下载速度确实有所好转，不过发现当目录树分支过多的时候，只遍历完一条字树就开始下载，再接着遍历，而且测试下载会建立许多空文件夹。。。

**Comment by iikira** [comment]
测试下载不会建立空目录了吧, 95f3f7857e106aaee6d2ba05c5c46ba4cd6c93fc
目前下载就是一层层遍历的啊, 到最后应该都会下载完的...

**Comment by WeidiDeng** [comment]
测试后发现，路径深或子目录文件多速度依然慢，我又不会go语言，看不懂具体实现，请问dlist和download 文件1 文件2等等，有什么区别

**Comment by iikira** [comment]
dlist是队列, download是下载用的, 不过这应该和速度慢没什么关联啊

**Comment by WeidiDeng** [comment]
这样速度还是很慢，我想会不会是因为下载目录时，要首先调用FilesDirectoriesMeta，将获取到的文件添加到dlist里，而直接使用
`download 文件1 文件2`
下载多个文件时，跳过了FilesDirectoriesMeta，速度就没受到影响。因此我想是不是和cookie有关，百度记录使用FilesDirectoriesMeta次数，达到一定次数就限速。我打开下载临时文件的downloader_downloading发现内容是记录分块下载的进度，按理和限速没有关系。但必须把这个文件和下载的部分文件删除速度才恢复。

我不太懂编程，我的话也不一定对，您要有时间就看看。

**Comment by iikira** [comment]
尝试修复此bug, 160af1573fd373ef6bf44274ca04852e7dac6bd5, 
原因可能在于, 下载最大并发量没有调整好, 感谢反馈啊...

**Comment by WeidiDeng** [comment]
现在速度正常了，感谢修复
