### ISSUE TITLE
为什么BaiduPCS-Go meta和本地md5sum获得的MD5不一致？

### ISSUE THREAD

**Issue by listln** [iikira/BaiduPCS-Go#845]
BaiduPCS-Go meta 显示md5
本地执行md5sum
1.两者不一致，
2.远程下载到本地，检查MD5和源文件又是相同的？？
为什么远程会不一致 怎么解

怎么知道上传文件完整？

**Comment by gMan1990** [comment]
[修复文件MD5](https://github.com/iikira/BaiduPCS-Go#%E4%BF%AE%E5%A4%8D%E6%96%87%E4%BB%B6MD5) 可行吗？

**Comment by iikira** [comment]
这是百度网盘api的问题，BaiduPCS-Go尝试检测该问题，然后会在meta命令输出显示` md5(可能不正确) `

可以试一试楼上的修复文件MD5功能

**Comment by gMan1990** [comment]
@iikira 借楼问下，离线下载了`magnet:?xt=urn:btih:9171721704F9C274242F187B49DEF1B72E0EE9C0`
然后下载`钢铁侠1.Iron Man.2008.BluRay.1080p.x264.AC3.2Audios.中英特效-DiaosMan.mp4`文件，下载完成有个校验，然后说什么失败就把下好的文件删了，后来使用`-nocheck`跳过校验解决了。想问下这个校验失败是bug还是正常的？

**Comment by amstc** [comment]
@iikira 现在好像md5总是不对了，无论直接在浏览器网页上传，或是用BaiduPCS-Go的--norapid --nosplit上传，百度显示的md5和本地计算的不一样，meta里
“md5 (可能不正确)”
和
“md5 (截图请打码)”
这两种的情况现在和本地都不一样了，fixmd5把(可能不正确)修复成(截图请打码)后，显示的和本地还是不一样。似乎百度改了hash算法。

**Comment by amstc** [comment]
@iikira 编译了你的新commit，现在md5显示正确了
