### ISSUE TITLE
只希望我的SVIP能在这个软件上高速的下载

### ISSUE THREAD

**Issue by jth445600** [iikira/BaiduPCS-Go#850]
狠心购买了一年的SVIP，平时需要在vps上使用，但是发现虽然开通了SVIP在这个工具上使用，依旧速度非常慢，有时候还报
“遇到错误, 远端服务器返回错误, 代码: 31326, 消息: user is not authorized, hitcode:117,”
的错误。

基本上不能用

**Comment by wsng911** [comment]
先用IDM+Chrome吧

**Comment by wsng911** [comment]
一定用BaiduPCS-Go的话也可以，
config set -appid=778750
onfig set -user_agent=""
速度有些飘，我这里慢的几K，快的1M，400K+比较多

**Comment by jth445600** [comment]
> 先用IDM+Chrome吧

求教

**Comment by pongfcnkl** [comment]
vps不能装Windows吗？

**Comment by jth445600** [comment]
> vps不能装Windows吗？

不能，小鸡

**Comment by jth445600** [comment]
> 一定用BaiduPCS-Go的话也可以，
> config set -appid=778750
> onfig set -user_agent=""
> 速度有些飘，我这里慢的几K，快的1M，400K+比较多

还是报错

**Comment by zzjyg** [comment]
加 --locate 参数  d xxx --locate ....

**Comment by mingjun97** [comment]
> 加 --locate 参数 d xxx --locate ....

好用！非常感谢！

**Comment by ZERO-000** [comment]
> > 加--locate参数d xxx --locate ....
> 
> 好用！非常感谢！

怎么用？

**Comment by jth445600** [comment]
只能一段时间，后边又会乱码报错  -locate

**Comment by yuritry** [comment]
反映给百度。我就是SVIP，用baidupcs-go , 下载速度受限。直接在网页版里给百度提，告诉他们，用的是linux系统，第三方客户端。
我们是SVIP，为什么限速？

**Comment by zz10001** [comment]
国庆过后就没速度了

**Comment by pongfcnkl** [comment]
> 
> 
> 反映给百度。我就是SVIP，用baidupcs-go , 下载速度受限。直接在网页版里给百度提，告诉他们，用的是linux系统，第三方客户端。
> 我们是SVIP，为什么限速？

没用，他们只会让你用官方客户端

**Comment by yuritry** [comment]
都反映，他们才会重视

**Comment by mo-han** [comment]
我租来的svip号可以满速下载（百兆家宽）
用的就是加--locate参数的下载命令

**Comment by zz10001** [comment]
> 我租来的svip号可以满速下载（百兆家宽）
> 用的就是加--locate参数的下载命令

ubuntu系统嘛，什么版本的baidupcs啊·

**Comment by mo-han** [comment]
@zz10001 就最新版嘛
而且我寻思跟版本没关系的
最近有一大批电影要下
本来打算几十KB拖到猴年马月随意
后来想想算了不跟百度赌气了
花3块钱租了一个共享的svip账号
然后就把家里带宽跑满一晚上把电影全拖下来了

**Comment by zz10001** [comment]
你的是什么linux还是win啊，linux话方便给个最新的链接嘛

**Comment by mo-han** [comment]
@zz10001 ubuntu
下载链接这里不就有吗

**Comment by zz10001** [comment]
> @zz10001 ubuntu
> 下载链接这里不就有吗

我下载版本还是限速。。

**Comment by mo-han** [comment]
@zz10001 所以说不是软件问题

**Comment by zz10001** [comment]
就是版本问题，有的（3.61）我可以下载不过限速，有的403forbidden（3.56）

**Comment by mo-han** [comment]
@zz10001 我说限速不是软件的问题

**Comment by zz10001** [comment]
好的

**Comment by TomLiu-GitHub** [comment]
有一个专门用来下载的工具叫做pandownload,但是不开源

**Comment by iikira** [comment]
做了一个SVIP下载的小调查, 参考一下呢, #858

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
