### ISSUE TITLE
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122

### ISSUE THREAD

**Issue by wpby** [iikira/BaiduPCS-Go#851]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122

./BaiduPCS-Go config set -enable_https="true" 和 ./BaiduPCS-Go config set -user_agent="" 
都没有效果。求大佬指导

**Comment by Jade-Zeng** [comment]
我今天也是哎，不知道原因

**Comment by wpby** [comment]
> 我今天也是哎，不知道原因

你的解决了吗

**Comment by zzjyg** [comment]
我前几天超会过期了提示这个，开通就好了

**Comment by ZERO-000** [comment]
我是开了超级会员的也变成这样了，所以现在是开了超级会员也不行了是吗，呜呜呜

**Comment by Bubbleinpit** [comment]
下载请求数量超过阈值，[wiki](https://github.com/iikira/BaiduPCS-Go/wiki/%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5%E5%B7%B2%E7%9F%A5%E7%9A%84%E9%94%99%E8%AF%AF%E5%88%97%E8%A1%A8#%E8%BF%9C%E7%AB%AF%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E9%94%99%E8%AF%AF-%E4%BB%A3%E7%A0%81-31326-%E6%B6%88%E6%81%AF-user-is-not-authorized-hitcodexxx)中有提到

**Comment by yuritry** [comment]
开了SVIP的，直接在网页里，把问题提给百度。

**Comment by Yifei0727** [comment]
@Bubbleinpit 
不是吧, 我好久没用,刚才上去下个系统镜像就出这个错误了

**Comment by wpby** [comment]
@Bubbleinpit 就下载一个文件
@Yifei0727  ./BaiduPCS-Go config set -enable_https="true" 我的还是不行啊

**Comment by iikira** [comment]
做了一个SVIP下载的小调查, 参考一下呢, #858 
另外，此问题和 #802 一样，先关闭了
