### ISSUE TITLE
关于baidupcs-go 被百度限速的问题

### ISSUE THREAD

**Issue by yuritry** [iikira/BaiduPCS-Go#852]
目前百度对第三方客户端进行了限速。对于baidupcs-go ，即使是开了SVIP，一样没速度，报错。
建议开了SVIP的，直接把问题反馈给百度。百度网页版右上角有一个意见反馈按钮，点击进入，写下意见和要求，填好邮箱，发送给他们。一般第二天就会有反馈，但短期内基本不会有结果，需要持续不断反映。

这是我最近一次反馈：
我是超级用户，用linux下第三方客户端，原来下载一直没问题，最近下载被限速了，应该是被你们公司限速了。我想知道怎么解决以及什么时候解决？
跟你们公司网盘管理人员和技术人员反映一下，了解一下。这种情况怎么解决，总得给个办法，不能一封了之。 

这是他们的答复：
您好，百度网盘正不懈努力优化产品，请多给我们工程师gg们一点时间，一定会让您享受更快速的使用体验，感谢您对百度网盘的支持！

**Comment by pongfcnkl** [comment]
这反馈估计没啥用

**Comment by yuritry** [comment]
反映多了，就有用了。除非百度网盘要关了。

**Comment by iikira** [comment]
参考一下 #858 呢~

**Comment by pongfcnkl** [comment]
想太多，Linux版的百度网盘到现在都还没有更新

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
