### ISSUE TITLE
“该文件校验失败, 文件md5值与服务器记录的不匹配"后不应该马上删除已下载文件

### ISSUE THREAD

**Issue by Ouroboros** [iikira/BaiduPCS-Go#853]
下载视频时不时会有这个错误，但是根本不影响观看，反而是下载花了半天，删除只用了半秒

至少有个选项禁用，或者删除之前提示

**Comment by zzjyg** [comment]
--nocheck       下载文件完成后不校验文件
你说的是这个吧？

**Comment by Ouroboros** [comment]
> --nocheck 下载文件完成后不校验文件
> 你说的是这个吧？

是这个

**Comment by kerraway** [comment]
同样的问题，下载完就报

> 检验文件有效性出错, 该文件校验失败, 文件md5值与服务器记录的不匹配, 重试 1/3
> 已删除校验失败的文件

不知道是不是接口返回的 md5 值变了，只能暂时用 --nocheck 应付一下。
