### ISSUE TITLE
请问这款客户端能上传4G以上的文件吗？

### ISSUE THREAD

**Issue by railannad** [iikira/BaiduPCS-Go#854]
https://pan.baidu.com/buy/center?version=6.8.9.1&tag=8&ssnerror=0&privilege=vipacceleration&traceid=&pri_extra=homepage&bduss=&from=guanjia&errmsg=Auth%20Login%20Sucess#/svip

百度网盘会员中心原文是“开通网盘超级会员后，使用网盘Windows及Mac客户端进行文件上传时，单文件最高达20G。” 
他只写了Windows和mac，但是以防万一我还是问一下：有超级会员的情况下，能上传4G以上的文件吗？

**Comment by iikira** [comment]
能的

**Comment by railannad** [comment]
> 能的

好的，感谢！
