### ISSUE TITLE
出现错误了 31064

### ISSUE THREAD

**Issue by LaplaceSoda** [iikira/BaiduPCS-Go#855]
获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消 息: file is not authorized

**Comment by LaplaceSoda** [comment]
无法获取目录下的文件列表应该怎么处理

**Comment by Xuyiyang23333** [comment]
我也是，上传的文件名为“test”，也报31062。

**Comment by iikira** [comment]
将appid改回266719即可
`config set -appid 266719`

**Comment by liangqi** [comment]
> config set -appid 266719

也遇到同样问题，上述设置可以工作。谢谢。
可否添加到已知问题列表？
