### ISSUE TITLE
无法上传文件，报错31062，已确认过文件名是否合法

### ISSUE THREAD

**Issue by Xuyiyang23333** [iikira/BaiduPCS-Go#856]
我在阿里云的轻应用实例服务器上使用BaiduPCS-Go，打算把下载的番剧上传到百度网盘，但提示文件名不合法。
于是我在/root目录下新建了个文件，名叫test，尝试上传，依然失败了。
![F723B26F-D5C2-42DB-B82B-E64BDD69FA74](https://user-images.githubusercontent.com/44458111/72685205-d4014000-3b22-11ea-8868-1edbf09ce756.png)
![8717DA50-AC21-45B0-BD56-26F463F13F72](https://user-images.githubusercontent.com/44458111/72685206-d499d680-3b22-11ea-99dc-a357b9d7e04b.png)

**Comment by iikira** [comment]
保存路径`.\`不合法，应为`./`

**Comment by Xuyiyang23333** [comment]
> 保存路径`.\`不合法，应为`./`

原来如此，抱歉打扰了。
