### ISSUE TITLE
开了svip超级会员还被封。某度疯了，别再建议大家充SVIP了。

### ISSUE THREAD

**Issue by fulgenssequar** [iikira/BaiduPCS-Go#857]
贵度网盘的高层工程师们我知道你们在看。

互联网运营商的奋斗啊，当然要靠自己的努力，也要考虑用户的选择。
如果没有这些开源社区支持的优秀产品，我怎么会一直用树莓派挂种子，却依然充了你们的svip呢？
虽然从树莓派上可抓取的隐私少一点，而且不太方便做p2p肉鸡，
可是既然都说免费网盘不好做，贵度的其他产品又是那么个德行，
所以对收费用户是不是应该稍微宽容一点呢？

某度在微不足道的方面，对svip确实不乏照顾。
例如检测到我用的是没装风扇的树莓派客户端，
所以为了防止板子过热，好心地替我做了限速设置，
只要速度超过1m/s，立刻给降为0。

因为树莓派cpu有限
所以虽然我做了md5修复
1g的文件下载完成后校验总是失败
为了让我加 --nocheck 设定，节省本地计算量。

然而电视剧下载5集之后，我又遇到了这种玩意儿：
```shell
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122
```
毕竟百度是家中国的公司，即使是svip，也不许你过中国年一直看洋剧。
总之，某度工程师，勤谨敬业，抵制开源，抵制洋剧，干(sang)得(xin)漂(bing)亮(kuang)

**Comment by zzjyg** [comment]
我的也是N个账号轮番被封，症状就是用网盘客户端显示网络异常，昨天刚恢复一个，今天又有一个进去了，不知道什么时候能恢复，我靠！

**Comment by iikira** [comment]
参考一下 #858 呢~

**Comment by fulgenssequar** [comment]
更新:
用了locate之后速度提高了不少，但是不知道时间长会不会被封，因为储存卡容量有限，并没有长时间持续下载。以下持续更新中。

**Comment by fulgenssequar** [comment]
更新：
加 --locate 之后部分文件网址 x509 证书错误，qd2.cache.baidupcs.com 这个网址证书无效。

**Comment by fulgenssequar** [comment]
更新：config set --enable_https=false 可从此避免证书错误

**Comment by iikira** [comment]
原来的下载模式不好用了, 新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新默认的下载模式, 稍稍有一些改进, 重新尝试一下, 先关闭了, 如果有问题再开issue吧
