### ISSUE TITLE
[作者] 关于百度网盘SVIP用户无法高速下载的小调查

### ISSUE THREAD

**Issue by iikira** [iikira/BaiduPCS-Go#858]
近期多个百度网盘SVIP用户反馈使用本软件时，无法实现高速下载，现做一个小调查。

1. 首先将BaiduPCS-Go版本升级到[v3.6.1](https://github.com/iikira/BaiduPCS-Go/releases/tag/v3.6.1)

2. 下载时加上参数`-locate`
```
BaiduPCS-Go d -locate <文件/目录路径1>
```

3. 比较和不加`-locate`参数的下载，哪种下载方式速度更快。

如果加上参数`-locate`的下载速度更快，下一版本将默认使用`-locate`下载方式。

**Comment by iikira** [comment]
可在此反馈一下两种下载方式的下载速度对比结果

**Comment by zzjyg** [comment]
以下是我的一些使用经验，仅供参考~~~~

一句话，不加跟无会员没区别，加了就飞起

不过要是账号被封（百度网盘官方客户端下载会显示网络异常）加了locate也无用，几十k或者0，这时候加share参数一般还可以高速下载，我平时都是这几个参数来回尝试，都不行了就换号等解封了（一般1-2天就恢复了）。
至于被封原因我也不知道，可能是我用的比较多吧，我的超会账号比较多，不同服务器从来也不共用，但基本都是轮番被封，出来一个进去一个，出来一个，哎哟进去俩！

最后感谢作者大大开发这么好的工具。命令行下载，仅此一家啊！！

**Comment by iikira** [comment]
> 以下是我的一些使用经验，仅供参考~~~~
> 
> 一句话，不加跟无会员没区别，加了就飞起
> 
> 不过要是账号被封（百度网盘官方客户端下载会显示网络异常）加了locate也无用，几十k或者0，这时候加share参数一般还可以高速下载，我平时都是这几个参数来回尝试，都不行了就换号等解封了（一般1-2天就恢复了）。
> 至于被封原因我也不知道，可能是我用的比较多吧，我的超会账号比较多，不同服务器从来也不共用，但基本都是轮番被封，出来一个进去一个，出来一个，哎哟进去俩！
> 
> 最后感谢作者大大开发这么好的工具。命令行下载，仅此一家啊！！
> 
> 正好有测试账号，补个图吧
> 客户端
> ![image](https://user-images.githubusercontent.com/51195245/72821271-413fdd00-3cab-11ea-8eb9-5902868ef661.png)
> 
> locate参数
> ![image](https://user-images.githubusercontent.com/51195245/72821315-4ef56280-3cab-11ea-9622-24dbe4ffb811.png)
> 
> share参数
> ![image](https://user-images.githubusercontent.com/51195245/72821429-74826c00-3cab-11ea-9e71-5f89191890e1.png)

感谢反馈~

**Comment by PlayerYao** [comment]
质的提升
不加只有200+k,加了参数之后可以到10M左右
![image](https://user-images.githubusercontent.com/43835273/72860944-64967680-3d03-11ea-81cb-8394242fa7e7.png)

**Comment by zz10001** [comment]
> 如果加上参数`-locate`的下载速度更快，下一版本将默认使用`-locate`下载方式。

使用的共享svip账号，没加-locate 和加了天差地别，
![TIM截图20200122144112](https://user-images.githubusercontent.com/39954774/72871678-78070900-3d26-11ea-81a5-1c8cc56547b0.png)
![image](https://user-images.githubusercontent.com/39954774/72873116-f4e7b200-3d29-11ea-8ed3-b826b59f741d.png)

**Comment by zz10001** [comment]
使用的共享svip，加了-locate和没加区别有点大
![image](https://user-images.githubusercontent.com/39954774/72873229-3bd5a780-3d2a-11ea-894b-444dd10a0330.png)
![TIM截图20200122144112](https://user-images.githubusercontent.com/39954774/72873251-4e4fe100-3d2a-11ea-972e-00e8d0439d91.png)

**Comment by wsng911** [comment]
![2020-01-22_17-57-51](https://user-images.githubusercontent.com/55266732/72884480-25871600-3d41-11ea-8bc2-5e0a2844d9f1.jpg)
下载速度确实提高了 但是出现校验 基本校验都失败 然后被删除了

**Comment by kdrx** [comment]
-locate 速度是svip，不加是p。

**Comment by zz10001** [comment]
> 下载速度确实提高了 但是出现校验 基本校验都失败 然后被删除了

末尾加-nocheck跳过验证

**Comment by Fangshing87** [comment]
反馈，普通账号，加了-locate 1.5M/s，不加就是30k/s(服务器在美国芝加哥 带宽是下1Gbps,上500Mbps)

**Comment by Sesprie** [comment]
版本3.6.1
加上`-locate`后 速度很快，但是下载到快完成的时候就没有速度了，
![image](https://user-images.githubusercontent.com/22644587/73172777-bfcecb80-413e-11ea-9ddf-9bcd864d3a45.png)

**Comment by as7212325** [comment]
加入locate后速度600k 不加0k
![image](https://user-images.githubusercontent.com/17666812/73188293-9a9d8580-415d-11ea-9447-4866bff35f8e.png)

**Comment by fulgenssequar** [comment]
利益相关：svip已充
1. 加了 --locate 后，白天的速度稳定在4m/s， 但快下载完成时速度会骤降到500kb/s左右. (因为是廉价路由器所以不知道有没有跑满带宽)
2. 大文件加 --nocheck 是必须的
3. 因为树莓派储存卡容量有限，所以不知道一直用--locate下载会不会被封。如果被封再来更新。

**Comment by zz10001** [comment]
> 3\. 因为树莓派储存卡容量有限，所以不知道一直用--locate下载会不会被封。如果被封再来更新。

我已经被封了，下了500g左右，速度50m/s下载的。不过应该是共享账号的问题

**Comment by ZERO-000** [comment]
加了 -locate ，前两天下载还有7、8m/s，但是今天不知道为什么就变成了几十kb/s

**Comment by fakrui** [comment]
--locate 希望增加可选下载链接 --locate下载时有概率坏包 3.6.1 locate 提直链无法修改请求头

**Comment by fakrui** [comment]
下载速度没有locate 提直链到Firefox快，大过频繁用--locate 会提示错误 
不能常用一个ip下，更换ip会正常
坏包真的得避免 配置无法直接编辑

**Comment by jth445600** [comment]
![image](https://user-images.githubusercontent.com/24479489/73447662-22021900-4357-11ea-80a0-744a0c36f7b4.png)

**Comment by fulgenssequar** [comment]
更新：加了 --locate 之后部分文件下载网址（qd2.cache.baidupcs.com）证书错误，去掉 --locate 之后可以下(当然速度另说)：
![canvas](https://user-images.githubusercontent.com/23030620/73608500-ab874480-45fe-11ea-861e-752bec8bcec7.png)

**Comment by awsl233** [comment]
有SVIP,跟楼上的楼上一样，代码: 31626, 消息: user is not authorized, hitcode:122
爽了一天 现在无论有没有locate都错误了

**Comment by bowenqiang** [comment]
有svip，不加locate全程速度几百K， 加了locate一开始可以20多M，然后降速为一两M，最后又是几百K。（上海电信200Mbs带宽）

**Comment by poor567** [comment]
活动买的svip
用的N1小钢炮
baidupcs老灯修改版已废
用原作者的＋--locate速度略有提高

**Comment by cjzswang5** [comment]
aliyun服务器华南1区，有svip，不加locate以几百k速度下了10G多的文件，再下4G左右zip文件直接“代码31326”无法下载，加了之后可以下载，速度1MB/s左右。

**Comment by cjzswang5** [comment]
下完1个之后又不行了"connectoin reset by peer"。

**Comment by getvalue** [comment]
`[1] 下载文件错误, Get https://qd2.cache.baidupcs.com/file/02e666469sc8f044018a7624b02cd562?bkt=en-2e2b5030dd6ff0375a356ca9ab0f6f7291fd2138ada1a2e4e6d12d8cacd7ff0ecfb190287acdcbac&xcode=4a8f3970de0035709f3592ec9a153637f8244eeb16b926bc245600a62f1689d0097af733c3fc18fb5d3ac15c36773ed09717ec4418c70769&fid=1940926388-250528-392353022197105&time=1581039535&sign=FDTAXGERQlBHSKfa-DCb740ccc5511e5e8fedcff06b081203-i8kl4S5Irjes3dtzo1ZHdI3YPu0%3D&to=h0&size=10459129146&sta_dx=10459129146&sta_cs=43&sta_ft=mkv&sta_ct=0&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2Cshandong%2Ccnc&ctime=1581038795&mtime=1581038795&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=10459129146&vuk=1940926388&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-6308f05e2d3970002e27be291ece11d397ec631c5503a17d5639424b73a74fa6ed19f2b20442cb4c&expires=8h&rt=pr&r=950541654&mlogid=867458559769500174&vbdid=-&fin=Brave.Father.Online.Our.Story.of.Final.Fantasy.XIV.2019.1080p.BluRay.x264-WiKi.mkv&bflag=h0,5,47,304,1,304,19-h0&rtype=1&devuid=O|C14F37F150F36F3AD9DF5728E8C5EB0B&dp-logid=867458559769500174&dp-callid=0.1.1&tsl=0&csl=0&fsl=-1&csign=R12KlkrELazVRotMfYPZD9Uydp8%3D&so=1&ut=1&uter=1&serv=1&uc=566704430&ti=26fa64dbec2882240afec503d0f3d57c5f14505c79f877c9305a5e1275657320&reqlabel=250528_l_833025fb072522231569478421979407_-1_6a4c292268b17af5468d281f83d5b9f1&by=themis: x509: certificate is valid for baidu.com, click.hm.baidu.com, cm.pos.baidu.com, log.hm.baidu.com, update.pan.baidu.com, wn.pos.baidu.com, *.91.com, *.aipage.cn, *.aipage.com, *.apollo.auto, *.baidu.com, *.baidubce.com, *.baiducontent.com, *.baidupcs.com, *.baidustatic.com, *.baifae.com, *.baifubao.com, *.bce.baidu.com, *.bcehost.com, *.bdimg.com, *.bdstatic.com, *.bdtjrcv.com, *.bj.baidubce.com, *.chuanke.com, *.dlnel.com, *.dlnel.org, *.dueros.baidu.com, *.eyun.baidu.com, *.fanyi.baidu.com, *.gz.baidubce.com, *.hao123.baidu.com, *.hao123.com, *.hao222.com, *.im.baidu.com, *.map.baidu.com, *.mbd.baidu.com, *.mipcdn.com, *.news.baidu.com, *.nuomi.com, *.safe.baidu.com, *.smartapps.cn, *.ssl2.duapps.com, *.su.baidu.com, *.trustgo.com, *.xueshu.baidu.com, apollo.auto, baifae.com, baifubao.com, dwz.cn, mct.y.nuomi.com, www.baidu.cn, www.baidu.com.cn, not qd2.cache.baidupcs.com, 重试 3/3`
不添加-locate 可以正常下载但速度会很慢
`[1] ↓ 345.19MB/9.74GB 535.15KB/s in 5m43s, left 5h7m5s ...............`

**Comment by clszzyh** [comment]
加与不加都无法下载，SVIP，最小版本，appid = 266719

一直提示 
```
[1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122, 重试 1/3
```

安轨!

**Comment by MQL9011** [comment]
下载一个7G的大文件，不加locate，速度就100K
加了locate,目前速度拉满 10MB/s ，不知道后续会不会被封账号。。。

**Comment by MQL9011** [comment]
![image](https://user-images.githubusercontent.com/11871158/74218559-54abfa00-4ce5-11ea-81b2-cac2d1c509f0.png)

不动了。。。奇怪

**Comment by saiyasaibing** [comment]
> ![image](https://user-images.githubusercontent.com/11871158/74218559-54abfa00-4ce5-11ea-81b2-cac2d1c509f0.png)
> 
> 不动了。。。奇怪

我这里也是，刚试了下载一个文件用上了-locate。下着下着就不动了，0kb/s.

**Comment by saiyasaibing** [comment]
用的是3.6.1 加上了-locate之后刚开始速度很快。下载到一半左右的时候出现一下message
.2020/02/11 10:56:01 Unsolicited response received on idle HTTP channel starting with "n\xe5\xf0\x17\xb1(k\xfcQbV=\x93\xa0(\x99\u05cfc\x10\x91\xfa\xb5\x02U\xf1\x03\xfer\x00ɣ߃\x8fj\x00\a\xcd\xc7f\xa8\xcf\\Յt\xa3\x86pe\xaa\xf5\xa3\x02\vt\x00\xdd>\xce\x04\x9c|\xad\x8c/\xcd\v\x9f\x8a\xa7\x8d\x81\xd9L\xe0\xa4?\xd7\xf2\x96\x06z\xf9\xb3\x88y^L\x18\x9f[\x87\x00\xd7\x00lp\xab\x00\x0f$\x89\xa0[\xb7E\xf7U\x05L\x00\xb2\f[DO\xf4\xaeq\xd0\xfd\x14\xbfl)\xc8c\xa5\xda\x1e\x14\x0f\x87\xe0\xf3\x9dA\xe3\x8f\xfc\xd0\x14\xbb\x9d{\x9fV\xf0\x84qe\x13\x80\x93\x05^\xefJ)p\xfa\x9d\xb6\x91\xb61\xd1S9Еt#\xb5\x147`RM\xffjw\x04ۙ\xcd\xec\x8d7b:|\xc1\xff\xf1/_\x8f&\xc0\x9c\xc7Y\x1b\xa6N\xeb\u07b3\f\b\xb7D\x15\x81\xa6d%\x9b\x9f\xaf\xd7\x00\x00\x03\x00\x00\x03\x00\x14\x11\x00\x00#8A\x9a\x874\xa4\xc1\x11\xff\x00\x00\x03\x00\x00\x03\x00\x12\xed\x122\xc0\xc6>\xb3y\x83ʖnL\xee\xa3\xe0\xfe\\\xb7\n\xfa\xa9\xddYx\xed\xee`Uﲜ\x05\xed\xe0F\x19\x83/\xfc\xc2{\x8c\xcc\x05\x00\xbd\xa6:\xbad\xb3?o\xbf`\xc7;X\u007f\xf4/ʤߌ\xa1ŀ\tj\n\xbbn\x17!\x06\x10;\xb7\x91N\t\xc7ﶉ\xc7p\xf5\x1a\xa9\xff\"\xd1rx\x85Ab\x8azl\xa93\xd37z\x81\x9f\x85\xcb]\xa6}T2k$\r\xe7_Vi5\x99D/2\x05~\xf8\xbb\xbc\xca\xf8\xa29\x89\xf4\x91\xbd\b\xb5\xe2U\x1fxA\x98\xed\x95\xcb\x12ђ\x97\x97\x11\x15\xd6k%\x1duЮ\xbc\xf0C\x8b\xb4$\xe1\v}\xe4\x14j\x85\xb0s\x84bD\xfb\x8ar\f\x1aY\xb0\x86a\x11\x8cWi\xf5FħT\xe2\x98~𝆓Յ\xa8\xeb\x18v\x9f!\x14\x11\x06\xe9\xa8\xf2\xa5\b\x9fF\xfb\xe5y\xd2B0,Mi\x9fg\xd2\x06\x9f\xb7j\xb4w\xb2L\xafB\xab\xdcK\x10\xa8\xb9mkQ\xb3\xac'A\xc7̦&\x84\xf9~G\xd6\x13J\xd8\xc45\xb9S\xb8l\xd0%\xc3\xcf1\x80)l\x13saK\f\x82\x82\x8aQAD\f\\\u007f\xb2\x9b\xdf\xc8\xf1\x14\x1d\xaa\x8e\xcb\xc3C\xd9/,!\x81ߦ\fe\u008aI\x18\xc4\x04m9G\x12\xa0\xd7[xs'\\\xff8J\xa3d\x00\xeb\xeb\xcfܣ\xf8\b-\xbaȲ\xda;\xb6ށp\xcf\xf1\xa0\x87\x16\x8e6v\x92\x99t\xfd2\x12\x0e5\x8f\x1bP9\xae\x159og\x83\xc0\xf9S\x9f\xb3t\x81\x02?\xb9\xce\xe0\x83\xff\x86\xb1gc\x84\xb4\xe7\xea^n\x8d\x92\xf5\"WO\xfb'\xc7ZO\x85Ş\xa8*\xe3\xaa\x00\xbc\xb2T=8\xac^\x8c\xcfd\x1c\xb9\xc0v\x06\xb3ץ?a{S:\xb5\xd7e?\xd1\xf5A\x9a\x8b\x9fg\xd5Hk\x13\xa9\x81\x9fg\xedRM\xc9\xe3\x93^\x8c^M\x0f\fX\x9e\v\x1f\xf1\x83\xfa\x9e\x89J\xd7\xd20\xa1\a/\x12d6\xf0\xd9\xffFRb|K\xf0\x93\x8d\xf1\x02J\xbd\xf5\xe54\x9d\x00\xa4\xf1\xdb\xe2ԇG.\xb4\b\x9b\x8aZFP=\x9c$\xe4b\x83\x17\xe1\x1d\xe5\xe6E\xace\xbd\xc0Q\xa8\x9d\xc0\x9a\xa2\x93\xf7\x93M\x1a\x95\\3;\xbb$\x91as\xe6v\x9aL\x1f3\xb0U\xa6\x90\xd2t\xf2X\x89\xfa\xaaؑ\xe3P\x88\xb0\x85\xce?\xf9\x94[\xd7\xea\xef6\x9d\xb0\xf8\x1e\b\xddQ|\xc9\x05\x00\x96[C}\xf2\bM\x97K\xfe\x85\x8a\xaa\xb8\b\xee!e\xb4\x84j\xaa\x19\u007f^\x90\xe4\x1b\x8ax\x84\xde\xe7\x82\xf8\xd4\xc1\x1d\faa=\xab9YD\nl\x91\xca\xd9&\r\xa0\x8e0\f\xa2{\x84镻\x86o\xa0\xa9\xc8\xe8\x8f!\x1d.ei\xea\xe3k\xe2Q`\u007f\x13\xde,\xaf\x9e\aǁ\x1b\xe2Ȇw\x92\xbe&\xd0W\xfe{۞\x9dKPr\xf7\x80\xb0\xd8\x12\xa5\x1f\xff]\xcc\xec\xbcl\x80\xaa҉\x1b^pԱ$\xc6\x13^w+x\xc8m|,\x8e\u0083\xcd\bM\xe3\xc67a\xe1l\x18\x0ew\x88\x9f\x1c\xa6\xd8\xea\xf8\x87\xff\x86&b1\xaa\x99v0T\xddU\xcc\xe9\x18\xcb\a\xcd[\xf1O\xc5J3\xb42eW\xa2\xff%\x91\xde\xc0\x8c\x10\x86E\x9a\xa2z\xb4\xff\x10\x9b!\x84\xac\xe5D\x86\xbe\xbfM;\xa0\xe5\vi\x0e\x9e\\ڎo!\xec\x02X6\u007fa:|\xe1\x92!.:\xa8G\r\xc0\x1a\x0f\a|$\xad\x80F\xf9\xd7'3&\xbfY\xb2.\x18\x95\xa4\x15>\xe2\x168\x9f\x05\xbfY\x8b\x90Ȓ\xb2\xa6\xa1\xc2O'\xb3\x8a\x8f\xbaF\xeb\x1e#\beF\x83S^\xc9\xec\xfe2\x00\xeb\xd5\x03\f\x85\x00N\xee\xc0\x1cf\xf7|\x0e(\x86\x8a\xa9\tM\x9d=X\x03\"\x1ej\xed\xfa/\x8d >\x19@f\xf2)\x84u6\xe3\xe9'^\xeb5\xcbH\x8d\xdd\xf0呇\x93\xf2\xc4\nͧ\xcaf\xd8d\xa1Y\xe9\xed\xe1i<\xf8J\x1b\x01(\xbb\x0e\xefD;\xec\x96Ң\x1c\xcbU\xb2:p7m\x85G\xaaNA\bk\xa9N֙\xbb\xef屧\xb5\v\x94/lV\x96>\"\x0e\xde/I\xd43)\x9dCQ<K\xc3\x1c\xbe\xac\xfb\xe6\xd2\xfcީ!\bM\xe4\xe4\xce[ƕ\x03%\xbb\xd7\x19@Y\xb9lS\x01(8t\x1d\xbf\xc3j\xbf\x01\x9f\xfd\x895\x81\x1aV>:\x04M<\x05\x06\xcc\a\x97\x96J\x90\xc5\x15˞f\t\xf3\xf4k\xab\xc5k\x83\x10\xd2&~+j|T\x8b\xca\xe0\xd8ww\xf8\x10*_\xf2\xbc\xc6\x0f\xf6r\xe0\xb6J\xb3\xf8\x1b͒\x92\u007f\xe1\x8b?\x05\xd0\xe0\xb5!\arD\xaaa\xc6z?ayȺ\n\xaas\n\xbc\x97p\xa3\x1by\x8f\xe8<\"\xf6\x8c\x13p)\x15b\xad\xd64\xf5_Y\xa6\xc7K\xb4\xcbL\xb9F\xe0~\xc3\r$\x18@\xc9\tﺥj\xac\xbdE\x9f\x99Y\xe3\xe8ډ\x94\xe5RMI\x1eM\xceb\xf0\xca@\x06\xfd\xc5rG\x90\xba\xd3e\xeb\b\xda D\"\"Ϟe\xbaV\x04&&I\xcdf\xc5\xe5;!\x8cP\x14x\xa2\x8a\xdc\xc6\x03\xb4\x1e\xbfE\x03\xa0\x17\xf3\xb55\xb87\x8b\x92\x82]Z\x9c\x1d\x13L\xc4N\x9cܱS/\xa5h\"z\xe6\x1cމ\x954\xed9\x90\xabe\x0f\xcf\x01\x85M\x19\x93\xe0\xf1\xcb\xe0\xa5wO\xe1ɍ\xacXD\x1c:\xca\x19\x94H}\xc3x\t\xbd\x87S\x1f0\xac\x02\xb7\xac\xb6\xc6{v\x9d]\x96\xediU\x18\xaf\xe6\x1f\xc85sQ*xn\xa51@\xf4\xd7\x1a\xc1\xdf\x14]Y\xe5i\x87\xe4E3\x99\\\xcb\x0f\a'I\x148\x9d\x06a\\\xb7w6h\x86\x02\xfcImG\xb0`\xeeD`р\xd5k\xa0/\xfa\xbc\x8eP\x9e\xf5\xb4Z\xd30\x82\xa6\x15\xda\xee!\xdd\xc9<\x1c\xc6\xd0[\n\xe0J\x18\x11HȱҎ\x1fZ9p?ΕiILs!\xf9\xf3r2_\xe4\x94y\xd2\x1f\x1c{,\a\x17h\xd7E\xebC\x10\x02\xbd\xc0\x12\x9d\x17\x9a\xc5~\xcc\xdez\xb0\xfb\xcb\x12\xcf\xe0\xfb\xe5/U\xf4\xca,\xe7\xc1C\x05\xfb\xc1>ɮ\xdd\x01M\xb7\x86(\x92nyDE,PqT\xc7İe\x15\xd8\xd6c\x98\x14\x80N\xaas\x9e\x9ecK\xbf<\xd6\xf4\x9c-\xec[\xb3\xb0\x91\xb0?/f\xe8\xb2\xc2`\x85e\xf46\xba\xb2\x00\xfb\xafj\xd6\x1a=\xe6;\xde[\xfdy\x84U.\xe9/\xffE\x98\x0fw\xa0*\xf3\xc8փ\x9cf\x10\x06\xdae\x94C\xf9\xed\x9c:\xc4\xc5d0\x16\xd2\t\xe8\x17ľE\xb7W\x88\x85\x02\a\xec\x93Z2\xed\x1fh\xa4]A6\x96fn\xed^\rz$IN\x1f\x83ͬ\xa1\xeb\xc2\xd3E\xe1\xed\x9c\xf6r\xb9\x0ec\xc8\xd0\xd0\xd3\xd2x\xf9;f\xf0\x1b\xfeBB\x0e\x00ÐFi\r\xafMa\x12\xbf\xd0\xf0FW\xd2ў\xa4\xdfV\xcf+\xa4\x8c\xdbn\xaf\x0ff\xfc\xaa5\xdaሏ{\x9e\xcbP\xbe\x9fAx\xab̛]\u007f\xceI~\xac@\\r\x1b\xabe\xd8R7'\u007f\xf7\x90\xd9͎(M\xf0J\xef\xb9#=\x85UW֤\xe5\xf8\xc1\x1c\xba~}\x84ה\x84\xa0\f=\xf8\xa9\xe5_\x8eԩ\xd0\x19~\xd4%#\xb1\xaf\x19\xc2,/T1\x10\xdd\v\xcf^\xd1w\xb1\xb96\xe6\x8e\xda*\x88\xe9{\xdbݑ\x19\xf5%\x83\x88\xab$\xb2\xbe툽\x97\x9c(=\xa2\x99\xf5\xb4\a\x95A\xbf%\xdeY\x99\x91\xb7\xd0E\xf6\xea-;\xa6\x95\x92\x95\xc2\xda\xeaMN\x925\x1aj>\x99\xf9\x1ahc\x85!\xaaypQ.\x18\xb1\x8eG\x04O\x9f\a\x89\x1dc\x14\xecW\n\xf3\x1c\xc5\xe6\x8b\x14\xfe3B_V\xc5g\xdd7\x88\xe0SO\x93\x02x\xff\u007f\xb5\xb9\x1a\xc1 \xf2\xed3:D\xac\xda\xfe\xe7\xffC\xf0.ł\x81\xdcc\xa2sm\xbb[\x9fsU\xd6e\xeb\xf8\xf73\xd1t\xae'~\xb3\xf5\x9d\x84\xe3®\x0f\xf4u\xcc\f\x89?*\xcfȳ\x9b\x83\f\x1d\x9b\x1c\xe4}\xf3F\x8bUj\x90n\xe2\xc1\xc3_\v1Eb\xdb\xfb\xac!\x9f>I\x86mh\xc9K\xc7?\xb2\xb87\xff\xe3\xc1\xb8\xaf\xf0\x19\x9a\xd0n\x12i\xffm\xed\xac\x88\x11^\x90\x88H\x00yؓ\x8d\x81\xfd\xc4:p\x17\x11T\bu\xba\x8e$k|\xfd\xe5،\x1c\xebʁn\x95\xc5Ȍ\xe6\x0f\xefo\x8d\xaf\xd1<\x93\xba\x8f%\x10\x00P\xab\xea\xf7\xbe\xfb;\x03\xd1\xefh\xc4\xcd\xcdKu\xab>\xfaE\x1fsy\xca\x1f\xa9\x1dW2\x95E#\xf2\xe7\x8bv\xd7\xf7\xe9\xf0\xfbFh~\x00I\xdf\x01\x80\xe7r\x85\x1e\x018\xf8K\xd0շPt\xf3\xcdo\xb5\x88\\\xdf̓ ;uȕrh\xd9i\xc0`\av\xb6n\x87\xd2.\xaa@\x05\x80v\x81\x89\xa1Jy?\x9d\xe9\xd8\x17\xb27\xef\x80t\xb4c\xe3(|tQ\xe5O\xfchRH|\x1c1\xe5K\xd5\xe4\x06\xfc\xd8x)0\xa0t\xcb\x12jE~\xe8L\xee\x1eMڛ\r\xf3|&Ӛ\xa7\xbc\xb8\x80o\xb30*\xa3\xae\x81Q\xfc\x13\xff\xb4\xabD\xd3\xf9o\xe1)\x83\x82)#\u007f\x02\x01\xfd\xd6\xe8\xe0F\xd8\aI\xb9\x9e\x03\xcf\xfb\xee,3\x15̝N\x1b\xb3$\xc9\a\xe1$0L\x04j\x92!ⵅ9\xebh\xa2\xd6-\xa6>\x9f\xaf\rg\xa2e(\"\xdbq\x1a\xfcD\n\xa5\x11\x80?(\xec\x87\xe7|+\x15\xccj\x89|\xc3\fKOl\x1c`\x17cU:v\xdf\x03\x04d\xff'\n){f=\xe6Z\x1c\xf8V\xeb\xefcu[*L\x90\x1cu\x1d}y}\xcbD\x1fm\xe4(G?\\;˳"; err=<nil>
然后速度就开始下降，下降到0b/s

**Comment by jku1995** [comment]
SVIP,不加基本没速度,加了之后能跑满带宽,在快结束的时候速度消失,但是结束重新敲一遍下载命令就会接着下载,速度也很不错

**Comment by A1exInamin** [comment]
![](https://i.postimg.cc/Y9J6m7zS/image.png)

SVIP账号被封禁了;(

**Comment by fulgenssequar** [comment]
> ![](https://camo.githubusercontent.com/d722445408315a5cf950998a7fb0827e54a76b2a/68747470733a2f2f692e706f7374696d672e63632f59394a366d377a532f696d6167652e706e67)
> 
> SVIP账号被封禁了;(
> 
> （账号是我自己的，没外借过，只用官方客户端和 BaiduPCS-Go）

狗够不着盘子，于是掀了桌子 （盘子上写着四个字：用户隐私）

**Comment by Karblue** [comment]
我昨天刚开个svip 下了一部电影 今天再来 --locate 直接 hitcode:122 不加locate 没速度 现在吃相这么难看? 速度都不给了?

**Comment by sify21** [comment]
有svip，下载110M的zip文件，不加locate100k左右；加locate2M左右的速度下了108M，然后速度变为为0

**Comment by Nisekoi5** [comment]
SVIP,不加locate 500KB以下，加了参数之后可以到最快28M(带宽上限)。不过有个问题就是每个文件下载到大约90%左右的时候速度就会降下来变得慢吞吞的。

**Comment by ddclaus** [comment]
同大多数网友一样，版本3.61，SVIP，不加locate基本就是不能下载，加了locate，大文件运气好能顺利全速下载完成，大多数时候就是快要下完了速度就变0了。如果退出重开续传的话，就说31326 122。
顺便感谢一下作者，无论今后这个神器还好不好用。

**Comment by jth445600** [comment]
讨论了这么长时间了，能不能告诉我，还没有用旧？

**Comment by Zehop** [comment]
SVIP几个月没用了
不加-locate直接报错如下:
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122
加了跑满10M/s 真绝了 先这样用着吧

**Comment by laris** [comment]
开始慢速 10M-20M

过几个小时就限速了

```
[86] ↓ 268.50MB/477.46MB 363.64KB/s in 7m25s, left 9m48s ............

  #   STATUS           RANGE            LEFT    SPEEDS      ERROR
  0  下载中    {40501248-57671680}    17170432  147456  <nil>
  1  下载中    {68681728-115343360}   46661632  524288  <nil>
  2  网络错误  {115343360-173015040}  57671680       0  403 Forbidden
  3  成功      {230686720-230686720}         0       0  <nil>
  4  网络错误  {461373440-500656128}  39282688       0  403 Forbidden
  5  成功      {346030080-346030080}         0       0  <nil>
  6  等待响应  {346030080-403701760}  57671680       0  403 Forbidden
  7  成功      {461373440-461373440}         0       0  <nil>
[86] ↓ 269.12MB/477.46MB 743.43KB/s in 7m26s, left 4m46s ............

  #   STATUS           RANGE            LEFT    SPEEDS      ERROR
  0  下载中    {40894464-57671680}    16777216  262144  <nil>
  1  下载中    {68681728-115343360}   46661632  262144  <nil>
  2  网络错误  {115343360-173015040}  57671680       0  403 Forbidden
  3  成功      {230686720-230686720}         0       0  <nil>
  4  网络错误  {461373440-500656128}  39282688       0  403 Forbidden
  5  成功      {346030080-346030080}         0       0  <nil>
  6  网络错误  {346030080-403701760}  57671680       0  403 Forbidden
  7  成功      {461373440-461373440}         0       0  <nil>
[86] ↓ 269.50MB/477.46MB 670.70KB/s in 7m27s, left 5m17s ............

  #   STATUS           RANGE            LEFT    SPEEDS      ERROR
  0  下载中    {40894464-57671680}    16777216       0  <nil>
  1  下载中    {68878336-115343360}   46465024  212991  <nil>
  2  网络错误  {115343360-173015040}  57671680       0  403 Forbidden
  3  成功      {230686720-230686720}         0       0  <nil>
  4  网络错误  {461373440-500656128}  39282688       0  403 Forbidden
  5  成功      {346030080-346030080}         0       0  <nil>
  6  网络错误  {346030080-403701760}  57671680       0  403 Forbidden
  7  成功      {461373440-461373440}         0       0  <nil>
```

**Comment by kmiit** [comment]
没svip，加locate就飙车了,1.5g之后打回小黑屋
换一个文件后  [1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122

**Comment by lightnoway** [comment]
> 下载一个7G的大文件，不加locate，速度就100K
> 加了locate,目前速度拉满 10MB/s ，不知道后续会不会被封账号。。。

该账号存在违规行为,暂时无法下载

**Comment by Liberations** [comment]
d * -locate 比较快

**Comment by dbshao** [comment]
> 加与不加都无法下载，SVIP，最小版本，appid = 266719
> 
> 一直提示
> 
> ```
> [1] 下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122, 重试 1/3
> ```
> 
> 安轨!

我也是一样的情况 崩溃

**Comment by iikira** [comment]
已更新默认的下载模式, https://github.com/iikira/BaiduPCS-Go/commit/fea1d7352aed20d54915aee2349500e4bfd54bdc

各位可以使用一下看看效果, 这里可以下载测试版：https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by Wistral** [comment]
SVIP, 一开始能满速11MB/s下载, 下了大概10G左右就给我🈲了!!!?
只能继续用官方2MB/s下载了, 百度你行

**Comment by JIAZM** [comment]
> 
> 
> SVIP, 一开始能满速11MB/s下载, 下了大概10G左右就给我🈲了!!!?
> 只能继续用官方2MB/s下载了, 百度你行

都办了SVIP为什么还要用这个软件呢

**Comment by Wistral** [comment]
> > SVIP, 一开始能满速11MB/s下载, 下了大概10G左右就给我🈲了!!!?
> > 只能继续用官方2MB/s下载了, 百度你行
> 
> 都办了SVIP为什么还要用这个软件呢

应该官方的不能满速啊 囧rz

**Comment by JIAZM** [comment]
> 
> 
> > > SVIP, 一开始能满速11MB/s下载, 下了大概10G左右就给我🈲了!!!?
> > > 只能继续用官方2MB/s下载了, 百度你行
> > 
> > 
> > 都办了SVIP为什么还要用这个软件呢
> 
> 应该官方的不能满速啊 囧rz

我这边100Mbps的网是能占满带宽的啊

**Comment by sify21** [comment]
> > SVIP, 一开始能满速11MB/s下载, 下了大概10G左右就给我u7981了!!!?
> > 只能继续用官方2MB/s下载了, 百度你行
> 
> 都办了SVIP为什么还要用这个软件呢

因为我用fedora, 百度linux客户端运行不起来
