### ISSUE TITLE
文档里写的是上传同样文件时候会覆盖文件，上传同样目录会将目录内的文件重命名

### ISSUE THREAD

**Issue by hulichao** [iikira/BaiduPCS-Go#861]
实际上：
BaiduPCS u a.txt       a.txt
生成的是 a.txt/a.txt
BaiduPCS u a.txt b
生成的是 b/a-xxxxxxxxxxx.txt

其实，我的需求是做成自动同步盘，就差完全覆盖这一步了（😂）

**Comment by zzzop** [comment]
我也是没找到覆盖上传的方法，就是完全同样的文件有时候也不能秒传，可能是因为md5变了，结果就被重命名了

**Comment by iikira** [comment]
这个问题应该修复了, 不会自动重命名了, https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7

**Comment by iikira** [comment]
新版本 [v3.6.2](https://github.com/iikira/BaiduPCS-Go/releases) 已更新
