### ISSUE TITLE
ppc64le的Ubuntu系统下使用BaiduPCS-Go

### ISSUE THREAD

**Issue by Seanseattle** [iikira/BaiduPCS-Go#862]
我在下载了amd64和386版本的运行都出现：bash: ./BaiduPCS-Go: cannot execute binary file: Exec format error 问题。
.build.sh把ppc64le注释掉了，是用不了吗？

**Comment by iikira** [comment]
发布页未提供ppc64le的可执行文件，可参照[编译/交叉编译帮助](https://github.com/iikira/BaiduPCS-Go/wiki/%E7%BC%96%E8%AF%91-%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E5%B8%AE%E5%8A%A9)，自行编译

或者到https://ci.appveyor.com/project/iikira/baidupcs-go 下载
