### ISSUE TITLE
文件目录大小全是0B

### ISSUE THREAD

**Issue by Yofo-me** [iikira/BaiduPCS-Go#863]
如图，成功登录后，界面显示的所有文件和文件夹的大小全是0B，而且进行删除操作后发现被删除的文件还在 

 😭  😭  😭 

![Snipaste_2020-02-05_12-39-40](https://user-images.githubusercontent.com/55388087/73811526-a3085700-4814-11ea-8fac-efec0b53738b.png)

**Comment by iikira** [comment]
请到这里反馈: https://github.com/liuzhuoling2011/baidupcs-web/issues
