### ISSUE TITLE
获取直链时rand计算问题

### ISSUE THREAD

**Issue by Erope** [iikira/BaiduPCS-Go#866]
作者新年好！

获取直链时，rand参数代表经过sha1计算而来的校验值，但关键的ebrcUYiuxaZv2XGu7KIYKxUrqfnOfpDF这个值未做交代，这个值是逆向而来的么？

UA修改为不同平台(如Mac)后和官方百度云管家的rand计算结果不一样，会出现用户未认证，推测可能是sha1的这个盐值不一样，所以想问问rand的算法和盐值是怎么来的。

感谢作者一直以来的努力！

**Comment by iikira** [comment]
对的，通过逆向分析百度网盘android客户端得来的
目前推测ua不同，rand的算法也不同，服务端通过ua来判断应使用哪种rand算法，未研究其他平台的算法，你可以研究一下

**Comment by siair** [comment]
rand 算法解决了吗？

BDUSS的SHA1 + 用户UID + sk + 当前Unix时间(s) + devuid
这个字符串的 SHA1 值即为 rand 的值

关键参数是 sk，其次是 devuid

**Comment by Erope** [comment]
> rand 算法解决了吗？
> 
> BDUSS的SHA1 + 用户UID + sk + 当前Unix时间(s) + devuid
> 这个字符串的 SHA1 值即为 rand 的值
> 
> 关键参数是 sk，其次是 devuid

devuid好解决，这个值是可以自己定的;
不过其他就难解决了，最近Mac平台获取的link也变成慢速链接了(ENFI害的);
目前，各平台普通orVIP用户获取的都是低速link，就没有研究意义了。
所以现在也不准备深入研究下去了。
