### ISSUE TITLE
BaiduPCS-Go又双叒叕出问题了

### ISSUE THREAD

**Issue by ZH-XiJun** [iikira/BaiduPCS-Go#867]
下载文件下载得好好的，竟然跳到0kb/s，然后我就重新打开了一下，结果还是0kb/s。于是我重新登陆了一次，这时用ls报错31064，cd报错31301，除了不关涉百度网盘的命令，其他的全没用了......

`获取目录下的文件列表: 遇到错误, 远端服务器返回错误, 代码: 31064, 消息: file is not authorized`
`获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31301, 消息: not stream file`

**Comment by ZH-XiJun** [comment]
忘搞图片了
![Screenshot 2020_2_7 10_17_18](https://user-images.githubusercontent.com/59949135/73996189-e50cd680-4995-11ea-8ce1-26a8d1d1741a.png)

**Comment by iikira** [comment]
将appid改回266719
`config set -appid 266719`
