### ISSUE TITLE
tmux 遍历错误: lstat

### ISSUE THREAD

**Issue by gMan1990** [iikira/BaiduPCS-Go#871]
BaiduPCS-Go v3.6.1, tmux下不支持`~*`路径展开
```plain
> tmux new -s b ~/BaiduPCS-Go
BaiduPCS-Go:/ name$ u ~/_install.sh /
警告: 遍历错误: lstat ~/_install.sh: no such file or directory
BaiduPCS-Go:/ name$ u /home/name/_instal*.sh /
警告: 遍历错误: lstat /home/name/_instal*.sh: no such file or directory
BaiduPCS-Go:/ name$ u /home/name/_install.sh /
加入上传队列
```

**Comment by masx200** [comment]
> BaiduPCS-Go v3.6.1, tmux下不支持`~*`路径展开
> 
> ```
> > tmux new -s b ~/BaiduPCS-Go
> BaiduPCS-Go:/ name$ u ~/_install.sh /
> 警告: 遍历错误: lstat ~/_install.sh: no such file or directory
> BaiduPCS-Go:/ name$ u /home/name/_instal*.sh /
> 警告: 遍历错误: lstat /home/name/_instal*.sh: no such file or directory
> BaiduPCS-Go:/ name$ u /home/name/_install.sh /
> 加入上传队列
> ```

我还遇到另一个问题

上传文件时遇到软链接的文件也会报错

警告: 遍历错误: lstat

**Comment by iikira** [comment]
BaiduPCS-Go的命令模式，暂不支持解析`~`，上传的本地文件，不支持通配符匹配
