### ISSUE TITLE
批量上传文件时遇到的几种应该自动重试的网络错误和成功的判断条件

### ISSUE THREAD

**Issue by masx200** [iikira/BaiduPCS-Go#872]
批量上传文件时遇到的几种应该自动重试的网络错误

`上传文件失败, 分片上传—合并分片文件: 网络错误, Post`

`net/http: timeout awaiting response headers`

`上传文件失败, 分片上传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31352, 消息: commit superfile2 failed`

`上传文件错误: 上传状态过期, 请重新上传`

`获取文件列表错误, 获取目录下的文件列表: 网络错误, Get `

`net/http: timeout awaiting response headers`

`获取文件列表错误, 获取目录下的文件列表: 网络错误, Get `

 `read tcp `     `wsarecv: An existing connection was forcibly closed by the remote host.`

`上传文件失败, 分片上传—文件分片及上传: 网络错误, http 响应错误, 400 Bad Request`

`获取文件列表错误, 获取目录下的文件列表: json 数据解析失败, baidupcs.fdDataJSONExport.List: []*baidupcs.fdJSON: baidupcs.fdJSON.MD5: net/http: request canceled (Client.Timeout exceeded while reading body)`

`全部上传完毕, 总大小: 0B`

批量上传文件成功的判断条件

`上传文件成功, 保存到网盘路径:`

`秒传成功, 保存到网盘路径:`

**Comment by iikira** [comment]
已增加重试判断的条件: https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7
