### ISSUE TITLE
下载文件错误，代码31626

### ISSUE THREAD

**Issue by miRemid** [iikira/BaiduPCS-Go#873]
电脑下着好好的突然重启，重新下载后提示31626代码错误，user is not authorized，hitcode:122.
重新登陆后无效，请问要怎么解决？

**Comment by f0ghua** [comment]
我昨天也遇到了，今天又好了

**Comment by miRemid** [comment]
我也是，过一天就好了。然后我发现只要是下载文件突然中断，重新断点断续下载就会出现这个错误

**Comment by zavi7** [comment]
下载文件错误, 下载单个文件: 遇到错误, 远端服务器返回错误, 代码: 31626, 消息: user is not authorized, hitcode:122, 请问要怎么解决？

**Comment by MengWang23** [comment]
我也是这个问题

**Comment by ddclaus** [comment]
我每次遇到下载速度几K几十K时，中途退出程序，再开不管下什么必定31626。一般第二天会自动好。百度疯了，SVIP都不让好好用，自己客户端不好用，设置下载限速无效，需要快时不让快，需要慢时不让慢，客服反映也无人理会，用三方程序还TEME封杀，会员到期时还这样我必定不续费了。

**Comment by iikira** [comment]
此问题已记录, #802, 先关闭了
