### ISSUE TITLE
go mod vendor 报错

### ISSUE THREAD

**Issue by chenyongze** [iikira/BaiduPCS-Go#874]
➜  BaiduPCS-Go git:(master) go mod vendor
github.com/iikira/BaiduPCS-Go/pcsutil/cachepool tested by
	github.com/iikira/BaiduPCS-Go/pcsutil/cachepool.test imports
	github.com/iikira/BaiduPCS-Go/requester/downloader/cachepool: cannot find module providing package github.com/iikira/BaiduPCS-Go/requester/downloader/cachepool

**Comment by iikira** [comment]
这个问题应该修复了, https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7

再试试呢
