### ISSUE TITLE
下载批量文件时，速度非常不稳定

### ISSUE THREAD

**Issue by caizijiao** [iikira/BaiduPCS-Go#88]
下载批量文件时，速度非常不稳定，我是特例还是普遍这样？

**Comment by iikira** [comment]
麻烦列出你的配置，例如下载缓存和最大并发量

**Comment by caizijiao** [comment]
好的亲，我回去发你，我怀疑两个因素，第一是我下载目录地址过长，第二是我可能用了beta4版本






在 2018-03-16 10:17:21，"iikira" <notifications@github.com> 写道：


麻烦列出你的配置，例如下载缓存和最大并发量

**Comment by iikira** [comment]
地址过长应该不会有影响的。下载的配置影响会比较大

**Comment by iikira** [comment]
尝试修复此bug, 160af1573fd373ef6bf44274ca04852e7dac6bd5, 编译运行程序可看到效果, 
原因可能在于, 下载最大并发量没有调整好, 感谢反馈啊...

**Comment by iikira** [comment]
下载新版本试试效果，如果还用问题请新开issue...

**Comment by caizijiao** [comment]
哦哦哦，好的，最近太忙，都没功夫开PC。
谢谢！





--


Best Regards.


Cai Zi Jiao
Shu Lun Pan CPA CO.,LTD
NO.61,East NanJing Road
Huangpu District
Shanghai 200002
P.R.China
Phone:0086-021-23280260

Fax:0086-021-63214325
Mobile:0086-13818303746
E-mail:caizijiaoqd@163.com





在 2018-03-25 18:44:40，"iikira" <notifications@github.com> 写道：


Closed #88.
