### ISSUE TITLE
undefined: GetHTTPScheme

### ISSUE THREAD

**Issue by robinfoxnan** [iikira/BaiduPCS-Go#880]
编译报错baidupcs.go:270:11: undefined: GetHTTPScheme

是版本不对么？

**Comment by iikira** [comment]
GetHTTPScheme方法在这里
https://github.com/iikira/BaiduPCS-Go/blob/52394a677126a284baea7199271838037a79342f/baidupcs/util.go#L68

看看是不是少了什么文件或者改动了代码
