### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by zzjyg** [iikira/BaiduPCS-Go#890]
share方式下载报了这个
[2] 下载文件错误, 注册分享信息: 网络错误, Get https://dlink.iikira.com/api/v1.1/pan/share/reg?pwd=&share_link=xxx: x509: certificate has expired or is not yet valid, 重试 1/3

**Comment by cheshuai123** [comment]
> share方式下载报了这个
> [2] 下载文件错误, 注册分享信息: 网络错误, Get https://dlink.iikira.com/api/v1.1/pan/share/reg?pwd=&share_link=xxx: x509: certificate has expired or is not yet valid, 重试 1/3

同。好像是大佬的直链接口网站SSL证书出问题了

**Comment by cheshuai123** [comment]
> > share方式下载报了这个
> > [2] 下载文件错误, 注册分享信息: 网络错误, Get https://dlink.iikira.com/api/v1.1/pan/share/reg?pwd=&share_link=xxx: x509: certificate has expired or is not yet valid, 重试 1/3
> 
> 同。好像是大佬的直链接口网站SSL证书出问题了

证书过期了，将时间改到3月19号之前能够使用了。等待大佬证书续签吧

**Comment by machsix** [comment]
运行一下`update-ca-certificates --fresh`试试，可能是系统的证书没有正确的symbolic link， 参见https://serverfault.com/questions/891734/debian-wheezy-outdated-root-certificates

**Comment by zzjyg** [comment]
> 运行一下`update-ca-certificates --fresh`试试，可能是系统的证书没有正确的symbolic link， 参见https://serverfault.com/questions/891734/debian-wheezy-outdated-root-certificates

这两天已经可以下载了，没动别的

**Comment by iikira** [comment]
已更新证书，可以用了
