### ISSUE TITLE
我下载不了BaiduPCS-Go的源代码

### ISSUE THREAD

**Issue by tangmaomao16** [iikira/BaiduPCS-Go#893]
我已经安装好了go环境，以及git。但是运行下面一句下载语句，却失败。
`go get -u -v github.com/iikira/BaiduPCS-Go`

```
$ go get -u -v github.com/iikira/BaiduPCS-Go
github.com/iikira/BaiduPCS-Go (download)
# cd .; git clone -- https://github.com/iikira/BaiduPCS-Go /home/tang/go/src/github.com/iikira/BaiduPCS-Go
正克隆到 '/home/tang/go/src/github.com/iikira/BaiduPCS-Go'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
package github.com/iikira/BaiduPCS-Go: exit status 128
```
是连国外的网站有问题吗？如何能解决连网下载的问题。

还有就是我想下载编译安装，能解决md5校验报错问题的源代码。还有哪个中国国内的站点有这些源代码吗？

**Comment by 123485k** [comment]
您可以使用ssh协议来规避gwf对github的封锁
使用`ssh-keygen`命令生成密匙(一路回车即可)
[将密匙添加进github](https://help.github.com/cn/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account)
将以下内容添加进'~/.ssh/config'
'Host github.com
 HostName github.com
 User git
 IdentityFile ~/.ssh/id_rsa'
使用 'git clone github.com:iikira/BaiduPCS-Go'克隆仓库

**Comment by tangmaomao16** [comment]
多谢啊大佬。后来我用了付费的VPN加速器，可以成功连接国外网站之后，就可以对github 快速下载了。------------------ 原始邮件 ------------------
发件人: "123485k"<notifications@github.com>
发送时间: 2020年3月24日(星期二) 上午10:24
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com>;
抄送: "tangmaomao16"<419242057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iikira/BaiduPCS-Go] 我下载不了BaiduPCS-Go的源代码 (#893)




 
您可以使用ssh协议来规避gwf对github的封锁
 使用ssh-keygen命令生成密匙(一路回车即可)
 将密匙添加进github
 将以下内容添加进'~/.ssh/config'
 'Host github.com
 HostName github.com
 User git
 IdentityFile ~/.ssh/id_rsa'
 使用 'git clone github.com:iikira/BaiduPCS-Go'克隆仓库
 
&mdash;

**Comment by 123485k** [comment]
这个方法不用梯子--可以节约vpn流量

**Comment by tangmaomao16** [comment]
大佬，还有个百度网盘分享链接的问题。我看你的github中的文档，不是很明白。
如果我有别人的百度网盘分享链接以及提取码，我能在Linux命令行，写脚本去下载网盘中的文件吗？
另一方面，我能在Linux命令行，写脚本创建网盘中的文件的分享链接，保存连接和提取码吗？


主要是提取码我没看到相关说明。



---原始邮件---
发件人: "123485k"<notifications@github.com&gt;
发送时间: 2020年3月24日(周二) 中午11:18
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tangmaomao16"<419242057@qq.com&gt;;
主题: Re: [iikira/BaiduPCS-Go] 我下载不了BaiduPCS-Go的源代码 (#893)




 
这个方法不用梯子--可以节约vpn流量

**Comment by iikira** [comment]
目前不支持创建包含提取码的分享链接

**Comment by tangmaomao16** [comment]
@iikira 大佬，我现在的需求是：我从别人那拿到了百度网盘链接URL及其提取码，我想写在Linux 脚本中去下载该文件，该文件是在别人的百度网盘账户里的，我怎么才能下载呢？
我看了你的文档说明中有写

> 以分享文件的方式获取下载链接来下载
> `BaiduPCS-Go download -share ...`

我试了一下，后面接URL会报错，如果接自己网盘账户中的文件路径，是可以下载的，但是没有输出分享链接URL。
我不懂这个 download -share 是什么用途啊？
