### ISSUE TITLE
上传报错 31066

### ISSUE THREAD

**Issue by Firesuiry** [iikira/BaiduPCS-Go#896]
![image](https://user-images.githubusercontent.com/30189673/77515288-383dd880-6eb3-11ea-9f7c-71aa3ba69a87.png)
请问这个是怎么回事。。

**Comment by steveyang687** [comment]
同

**Comment by railannad** [comment]
我也有这个问题

**Comment by steveyang687** [comment]
之前一直没问题，是不是分片被baidu禁了

**Comment by Firesuiry** [comment]
关键设置nosplit也上传不了呀。。



---原始邮件---
发件人: "Steve Yang"<notifications@github.com&gt;
发送时间: 2020年3月26日(周四) 中午11:32
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com&gt;;
抄送: "Firesuiry"<4690734@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [iikira/BaiduPCS-Go] 上传报错 31066 (#896)




 
之前一直没问题，是不是分片被baidu禁了

**Comment by steveyang687** [comment]
> nosplit

刚刚试了一下nosplit也失败了。。

**Comment by steveyang687** [comment]
--nosplit到底有没有用啊，禁用分片是这样写吗

**Comment by iikira** [comment]
和#897 一样，先关闭了
