### ISSUE TITLE
求助：上传文件失败, 分片上传—合并分片文件: 遇到错误

### ISSUE THREAD

**Issue by tempResources** [iikira/BaiduPCS-Go#897]
上传文件失败, 分片上传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

昨天可以正常上传
今天上传就提示这个，删掉pcs_uploading.json重新上传也不行 有大佬知道是啥情况吗

**Comment by Firesuiry** [comment]
好巧我也是。。是不是百度升级了。。

**Comment by zzjyg** [comment]
mark 坐等大佬修复

**Comment by freedomlang** [comment]
我也是，不管什么文件都上传报错了

**Comment by tempResources** [comment]
今天睡醒又可以上传了 emmmmmm 估计是百度云抽风了。

**Comment by Firesuiry** [comment]
> 我也是，不管什么文件只要分片上传的话都报31066 的错了。
> 
> 禁用分片上传的话能上传成功...

你好 能让我看一下您上传的完整指令吗？
我禁用分片上传还是报错呢。。。
我用的命令是
upload D:\zip\M2Q3YTg1MTIyNmIyZjQ4YmM0NDllODE2Y2UzZWZmYjM=.7z / -nosplit

**Comment by freedomlang** [comment]
@Firesuiry -nosplit 接着upload就好，我用的是小文件测试的。
```
BaiduPCS-Go upload -nosplit <file> <remote-path>
```

**Comment by tempResources** [comment]
@Firesuiry u 文件 /  我用的是这个 早上突然就好用了

**Comment by Firesuiry** [comment]
好的我试一下。



---原始邮件---
发件人: "blackie"<notifications@github.com&gt;
发送时间: 2020年3月26日(周四) 上午9:29
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Firesuiry"<4690734@qq.com&gt;;
主题: Re: [iikira/BaiduPCS-Go] 求助：上传文件失败, 分片上传—合并分片文件: 遇到错误 (#897)




 
@Firesuiry -nosplit 接着upload就好，我用的是小文件测试的。
 BaiduPCS-Go upload -nosplit <file&gt; <remote-path&gt;

**Comment by tempResources** [comment]
@Firesuiry 好像。。有的可以上传成功  有的不可以    成功的估计百度云里就有过这个文件？

**Comment by freedomlang** [comment]
@tempResources 你成功的是秒传成功？

**Comment by Firesuiry** [comment]
![image](https://user-images.githubusercontent.com/30189673/77602983-db413180-6f49-11ea-9e11-3e9d6b1c0cfc.png)
还是不行。。。



> @Firesuiry -nosplit 接着upload就好，我用的是小文件测试的。
> 
> ```
> BaiduPCS-Go upload -nosplit <file> <remote-path>
> ```

**Comment by freedomlang** [comment]
@Firesuiry 把pcs_uploading.json 删掉，不要进入交互模式上传。直接命令上传

**Comment by Firesuiry** [comment]
> @Firesuiry 你截图的还是分片上传。把pcs_uploading.json 删掉，不要进入交互模式上传。直接命令上传

请问这个文件在哪里呢？
还有直接命令上传是如何操作呢。。
抱歉  不是很明白 希望您能指点下。

**Comment by freedomlang** [comment]
@Firesuiry 删除pcs_uploading.json 参考https://github.com/iikira/BaiduPCS-Go/issues/436#issuecomment-435071465，删除后试试；是否交互模式应该不影响

**Comment by Firesuiry** [comment]
> @Firesuiry 删除pcs_uploading.json 参考[#436 (comment)](https://github.com/iikira/BaiduPCS-Go/issues/436#issuecomment-435071465)
> 删除后试试；是否交互模式应该不影响

删除后还是不行。。。请问能截个图看下你那边的流程吗。。 您那边是正常上传还是秒传呢？

**Comment by Firesuiry** [comment]
> @Firesuiry 删除pcs_uploading.json 参考[#436 (comment)](https://github.com/iikira/BaiduPCS-Go/issues/436#issuecomment-435071465)
> 删除后试试；是否交互模式应该不影响

就是您输入上传命令以后返回的提示，我看看那里不一样。。。

**Comment by tempResources** [comment]
@freedomlang 恩 能上传成功的文件 用秒传也能成功 估计是百度云更新了吧

**Comment by Firesuiry** [comment]
> @freedomlang 恩 能上传成功的文件 用秒传也能成功 估计是百度云更新了吧

好的 = =  那就不试了，，诶诶

**Comment by steveyang687** [comment]
估计更新了，我也是小文件都没问题，大文件一分片就报错

**Comment by Firesuiry** [comment]
我小文件也报错。。。



---原始邮件---
发件人: "Steve Yang"<notifications@github.com&gt;
发送时间: 2020年3月26日(周四) 中午11:23
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Firesuiry"<4690734@qq.com&gt;;
主题: Re: [iikira/BaiduPCS-Go] 求助：上传文件失败, 分片上传—合并分片文件: 遇到错误 (#897)




 
估计更新了，我也是小文件都没问题，大文件一分片就报错

**Comment by tangmaomao16** [comment]
我是上传单个17MB 的rar文件，没问题。但是如果上传文件夹，就报错了。

**Comment by Firesuiry** [comment]
> 我是上传单个17MB 的rar文件，没问题。但是如果上传文件夹，就报错了。

请问这个RAR是秒传成功还是上传成功呢？有没有测试其他文件呢

**Comment by lin511622** [comment]
不分片上传是可以的。分片上传合并文件的时候会报错。 要改是百度网盘服务端的问题。 没用过百度网盘自己的客户端，不知道上传大的文件有没有问题。

**Comment by Firesuiry** [comment]
> 不分片上传是正常的，秒传文件的功能也是正常的。比较大的文件分片上传合并文件的时候会报错。 应该是百度网盘服务端的问题。 没用过百度网盘自己的客户端，不知道上传大的文件有没有问题。

请问怎么才能不分片上传呢？nosplit命令加上去没作用呢。。

**Comment by lin511622** [comment]
> > 不分片上传是正常的，秒传文件的功能也是正常的。比较大的文件分片上传合并文件的时候会报错。 应该是百度网盘服务端的问题。 没用过百度网盘自己的客户端，不知道上传大的文件有没有问题。
> 
> 请问怎么才能不分片上传呢？nosplit命令加上去没作用呢。。

加nosplit这个参数没错。如果最新版本加这个参数不生效，你可以checkout历史版本编译了试一试。我自己用的是基于一个历史版本魔改的。具体版本记不清楚了。

**Comment by Cyame** [comment]
> > > 不分片上传是正常的，秒传文件的功能也是正常的。比较大的文件分片上传合并文件的时候会报错。 应该是百度网盘服务端的问题。 没用过百度网盘自己的客户端，不知道上传大的文件有没有问题。
> > 
> > 
> > 请问怎么才能不分片上传呢？nosplit命令加上去没作用呢。。
> 
> 加nosplit这个参数没错。如果最新版本加这个参数不生效，你可以checkout历史版本编译了试一试。我自己用的是基于一个历史版本魔改的。具体版本记不清楚了。

是的，我是从liverecorder那边脚本自动装的，`--nosplit`就没用，还是显示分片错误。（我这边都是没有秒传的， 可能tempResourses的文件触发秒传了吧。
应该是百度方面的修改，因为bypy的上传同样返回了31066

**Comment by tangmaomao16** [comment]
我就是用最基本的upload 命令，没有显式指定秒传选项------------------ 原始邮件 ------------------
发件人: "Firesuiry"<notifications@github.com>
发送时间: 2020年3月26日(星期四) 下午3:10
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com>;
抄送: "tangmaomao16"<419242057@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iikira/BaiduPCS-Go] 求助：上传文件失败, 分片上传—合并分片文件: 遇到错误 (#897)




  
我是上传单个17MB 的rar文&#x4EF6;，没问题。但是如果上传文&#x4EF6;夹，就报错了。
  
请问这个RAR是秒传成功还是上传成功呢？有没有测试其他文&#x4EF6;呢
 
&mdash;

**Comment by Firesuiry** [comment]
> 我就是用最基本的upload 命令，没有显式指定秒传选项------------------ 原始邮件 ------------------ 发件人: "Firesuiry"<notifications@github.com> 发送时间: 2020年3月26日(星期四) 下午3:10 收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com>; 抄送: "tangmaomao16"<419242057@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [iikira/BaiduPCS-Go] 求助：上传文件失败, 分片上传—合并分片文件: 遇到错误 (#897) 我是上传单个17MB 的rar文&#x4EF6;，没问题。但是如果上传文&#x4EF6;夹，就报错了。 请问这个RAR是秒传成功还是上传成功呢？有没有测试其他文&#x4EF6;呢 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

那就有可能是秒传了，，

**Comment by iikira** [comment]
尝试修复了：https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7
这里可以下载测试版：https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by Firesuiry** [comment]
> 尝试修复了：[662feec](https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7)
> 这里可以下载测试版：https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

测试上传成功

**Comment by Firesuiry** [comment]
![image](https://user-images.githubusercontent.com/30189673/77653643-f6905900-6faa-11ea-8142-59a233738b33.png)

**Comment by zzjyg** [comment]
大佬强无敌
![image](https://user-images.githubusercontent.com/51195245/77654950-b336ea00-6fac-11ea-9d8c-4e4c3ef2e880.png)

**Comment by tempResources** [comment]
大佬强无敌

**Comment by ZTMC** [comment]
这个问题似乎又再次出现了

**Comment by tangmaomao16** [comment]
我现在不用命令行了，用Ubuntu1804桌面系统的客户端软件------------------ 原始邮件 ------------------
发件人: "Z - The Magical Color"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 上午9:59
收件人: "iikira/BaiduPCS-Go"<BaiduPCS-Go@noreply.github.com>;
抄送: "tangmaomao16"<419242057@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iikira/BaiduPCS-Go] 求助：上传文件失败, 分片上传—合并分片文件: 遇到错误 (#897)




 
这个问题似乎又再次出现了
 
&mdash;

**Comment by freedomlang** [comment]
@ZTMC 实测没问题啊（大文件，分片上传）
