### ISSUE TITLE
秒传报错，百度关掉baidupcs-go的秒传功能了吗？

### ISSUE THREAD

**Issue by ChenChunxiaoit** [iikira/BaiduPCS-Go#899]
用rapidload命令秒传文件时总是报31079错误，内容如下：
上传单个文件, 遇到错误, 远端服务器返回错误, 代码: 31079, 消息: file md5 not found, you should use upload api to upload the whole file.

可文件length、md5我都是从BaiduYunCacheFileV0文件中取的，与直接在baidupcs-go下用ep获得的length、md5一致，应该不会有错吧，请大神得空指点一下，万分感谢！

**Comment by iikira** [comment]
百度在此之前更新了秒传文件接口, #537
除了length、md5，还需要一个slice-md5，请使用最新版本的BaiduPCS-Go的export和秒传等功能

**Comment by iikira** [comment]
秒传功能测试正常
