### ISSUE TITLE
403 问题

### ISSUE THREAD

**Issue by Dothion** [iikira/BaiduPCS-Go#9]
下载时提示 不知道的错误 0 403 403 Forbidden

**Comment by iikira** [comment]
我也不知道……重试也不行吗……还是下载文件都是这样……

**Comment by Dothion** [comment]
是这样的，都是这样，我试试换个号（可能是号被封了

**Comment by iikira** [comment]
结果怎么样呢……

**Comment by Dothion** [comment]
确实是我账号的问题，换一个就好了

**Comment by iikira** [comment]
你的号是被百度网盘封了吗……是的话我加一下错误处理。
