### ISSUE TITLE
完全不会显示下载速度和进度

### ISSUE THREAD

**Issue by aapaulng** [iikira/BaiduPCS-Go#90]
完全不会显示下载速度和进度而且我下载着的文件永远都是0 byte。可是打开task manager network 里却有下载着东西。还有请问cache file 都收在哪里？

windows 64bit

**Comment by iikira** [comment]
缓存文件在download目录里面, 就是目标文件了. 如果目标文件大小是0的话, 应该还没有开始下载才对的啊...

**Comment by aapaulng** [comment]
我测试结果 
文件大小
10kb -> 可以下
1mb -> 下载速度多数停留在0， 偶尔会秒有10kb/s然后归零。下了10分钟还是下不完
可是在task manager 却保持着2Mbps

**Comment by iikira** [comment]
那就奇怪了, 我这边测试没问题啊, 麻烦你提供更多的信息如截图, 程序版本和配置等等....

**Comment by aapaulng** [comment]
我又试了试，使用别的网络可以正常下载。 我推理可能是被防火墙封闭。请问baidu pcs go 使用的是什么port ?

**Comment by iikira** [comment]
程序没有port这个设置的……我打算加上下载的调试吧，遇到错误可以打印出来……

**Comment by aapaulng** [comment]
那我想得到的理由可能是dns的问题，不是pcs go 的问题了
