### ISSUE TITLE
Windows版无法登陆

### ISSUE THREAD

**Issue by SekiBetu** [iikira/BaiduPCS-Go#901]
BaiduPCS-Go login -bduss=我的cookies

回车后提示

invalid character '<' looking for beginning of value

又试了一下用普通的login登陆，也是输完验证码回车后同一个提示

**Comment by zhz1237ok** [comment]
![image](https://user-images.githubusercontent.com/38283893/77630244-a94dc080-6f85-11ea-85a8-93c219912720.png)

补图

**Comment by fantonms** [comment]
我也是这样。

**Comment by lsx0519** [comment]
me too

**Comment by zhixiangyuan** [comment]
mac 端同出现这个问题

**Comment by AhFook** [comment]
Unable to login until today......  glad it works now

**Comment by yongqingxie** [comment]
我这边也是一样 无法登陆

**Comment by SekiBetu** [comment]
it works now
