### ISSUE TITLE
上传失败报错代码31066

### ISSUE THREAD

**Issue by JuMPBELL** [iikira/BaiduPCS-Go#902]
把下载完成的pdf上传，上传的目录无论使用什么路径都是出现31066错误信息，本地的pdf是完好可以打开的，请问下这是什么问题呢？
![1585314445(1)](https://user-images.githubusercontent.com/51331490/77759218-53554780-706f-11ea-9484-1a892db999af.png)

**Comment by JuMPBELL** [comment]
![image](https://user-images.githubusercontent.com/51331490/77759368-94e5f280-706f-11ea-925d-ace0b5b53a47.png)

**Comment by iikira** [comment]
参见 #897

已尝试修复了此问题：https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7
这里可以下载测试版：https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by JuMPBELL** [comment]
感谢
