### ISSUE TITLE
上传文件失败, 分片上传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

### ISSUE THREAD

**Issue by xuwenfei1997** [iikira/BaiduPCS-Go#903]
我仔细检查了路径，感觉没问题啊但是不知道为什么就是失败了。。。
~$ ./BaiduPCS-Go-v3.6.1-linux-amd64/BaiduPCS-Go u /home/dc2-user/baiduyundisk/bilibili_21627536_20200326_235923.flv /apps/bypy
[1] 加入上传队列: /home/dc2-user/baiduyundisk/bilibili_21627536_20200326_235923.flv
[1] 准备上传: /home/dc2-user/baiduyundisk/bilibili_21627536_20200326_235923.flv
[1] 上传文件失败, 分片上传—合并分片文件: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

全部上传完毕, 总大小: 0B

文件路径和云盘的路径都没错，但是就不知道为什么。。。明明前些日子是可用的
提前感谢大佬们的帮助！

**Comment by xuwenfei1997** [comment]
然后我测试了一下上传到别的地方，改变上传至的文件夹名变为111（空文件夹）
即：$ ./BaiduPCS-Go-v3.6.1-linux-amd64/BaiduPCS-Go u /home/dc2-user/baiduyundisk/bilibili_21627536_20200326_235923.flv /111
并没有什么区别。。我也改变过上传的文件，同样是不行的

**Comment by iikira** [comment]
参见 #897

已尝试修复了此问题：https://github.com/iikira/BaiduPCS-Go/commit/662feec06d46cfab9111839062955304775330a7
这里可以下载测试版：https://ci.appveyor.com/project/iikira/baidupcs-go/build/artifacts

**Comment by xuwenfei1997** [comment]
感谢大佬
