### ISSUE TITLE
百度会员不生效

### ISSUE THREAD

**Issue by zhaibin18** [iikira/BaiduPCS-Go#91]
已经购买百度会员，windows客户端下载可以满速，但是BaiduPCS-Go只有4-5M的速度并且不稳定。

**Comment by iikira** [comment]
下载接口的限制...没办法的.

**Comment by zhaibin18** [comment]
呃，有没有能在linux下的命令行的工具，会员也有效？
神速回复超赞！

**Comment by iikira** [comment]
试试另一个: https://github.com/GangZhuo/BaiduPCS
如果不行, 还是用官方的客户端吧...

**Comment by zhaibin18** [comment]
这个貌似效果也一样，我尝试一下，多谢！
官方没有linux下的客户端，win用起来不方便。
