### ISSUE TITLE
英文版系统显示乱码

### ISSUE THREAD

**Issue by linhongye** [iikira/BaiduPCS-Go#920]
英文版系统显示乱码.

**Comment by linhongye** [comment]
cmd 输入 chcp 936

**Comment by JIAZM** [comment]
把终端编码改一下应该就好了


| |
北风
|
|
18846936491@163.com
|
签名由网易邮箱大师定制
在2020年4月11日 11:00，linhongye<notifications@github.com> 写道：

英文版系统显示乱码.
