### ISSUE TITLE
配置无法保存

### ISSUE THREAD

**Issue by zxh95320** [iikira/BaiduPCS-Go#93]
max_parallel 和cache_size修改之后下次打开就又恢复成默认值了。
版本：BaiduPCS-Go-v3.3.1-windows-x64

**Comment by iikira** [comment]
测试正常, 保存失败会输出错误信息的...麻烦你提供更多的信息如截图,等...

**Comment by zxh95320** [comment]
我刚才看了一下又好了。emmmm 不好意思哈。
