### ISSUE TITLE
(已解决)获取下载路径信息错误, 获取文件/目录的元信息: 遇到错误, 远端服务器返回错误, 代码: 31066, 消息: 文件或目录不存在

### ISSUE THREAD

**Issue by iMaxTomas** [iikira/BaiduPCS-Go#930]
#897
下载了测试版本还是无法下载
![304182bf58b3fd2246aaf3282a0e4c5](https://user-images.githubusercontent.com/47150902/79413768-69ee1f00-7fdb-11ea-8426-83472d56d94a.png)

**Comment by iikira** [comment]
看看是不是路径没有输入正确

**Comment by iMaxTomas** [comment]
![微信截图_20200416141042](https://user-images.githubusercontent.com/47150902/79421103-b2620880-7fec-11ea-9620-e5d2ce6b8d00.png)
![微信截图_20200416141116](https://user-images.githubusercontent.com/47150902/79421106-b42bcc00-7fec-11ea-97c0-b72320bd9903.png)
![微信截图_20200416141130](https://user-images.githubusercontent.com/47150902/79421108-b4c46280-7fec-11ea-9dbc-1ed9fbaf0abc.png)
 确实是的，需要名字输入正确 我用了它 #的数字 十分感谢

**Comment by 185264646** [comment]
> 确实是的，需要名字输入正确 我用了它 #的数字 十分感谢

可以使用Tab键自动补全，如果是手机的话可以用音量下键+t
