### ISSUE TITLE
请问直链在浏览器里面不能打开是怎么回事呢？

### ISSUE THREAD

**Issue by SadTomlzr** [iikira/BaiduPCS-Go#931]
![image](https://user-images.githubusercontent.com/43662748/79439744-c7986080-8007-11ea-85f5-c00d9422b41f.png)
我将您的代码运行了起来。获取到相应文件的直链后但是在浏览器里面也不能打开是怎么回事呢？
我看了您的一些issue，说是要和cookie一起带上，于是我将我的云盘登陆了起来，但是也不能打开这个链接。我使用了很久。都没有办法。
我想使用从软件里的直链实现用aria2来下载，但是直链在浏览器里面不能打开，也不能在aria2里打开下载。请问是我的操作有什么问题吗？浏览器里打开后说是sign错误。。。

**Comment by toke3** [comment]
请检测链接空格或请求头是否与客户端一致

**Comment by SadTomlzr** [comment]
那请问有什么较好的获取其他链接的方法吗？我自己从网上爬，也是获取的这样的链接。

**Comment by Curtain2112** [comment]
> 那请问有什么较好的获取其他链接的方法吗？我自己从网上爬，也是获取的这样的链接。

你这样是打不开的用CURL或者postman 不需要带cookie 将User-Agent改成netdisk;2.2.51.6;netdisk;10.0.63;PC;android-android 这个就可以了 如果报104错误 请指定Range 范围要在55M字节以内

**Comment by SadTomlzr** [comment]
牛逼！但是我对比了一下。pandownload和pcs-go获取的直链。有区别欸。。有大佬知道咋回事儿吗？🧐
