### ISSUE TITLE
小小建议：加入 brew 仓库

### ISSUE THREAD

**Issue by bemike** [iikira/BaiduPCS-Go#94]
BaiduPCS-Go 目前更新比较频繁，每次来 Github 页面下载稍微有点麻烦，另外也无法第一时间更新到最新版本。如果能用 brew 管理下载和更新，会节省不少时间。

我是小白，不知道具体怎么做，也不知道是否可行，只能提供一个建议。

**Comment by iikira** [comment]
好吧...

**Comment by CyshallChan** [comment]
可以先弄一个TG订阅频道阿，有更新发个通知。

**Comment by iikira** [comment]
我不要……

**Comment by kzw200015** [comment]
加入Debian仓库吧

**Comment by iikira** [comment]
已增加brew, https://github.com/iikira/homebrew-baidupcs

**Comment by niyoh120** [comment]
已提交至brew仓库
Homebrew/homebrew-core#48189
