### ISSUE TITLE
无论执行任何命令都显示错误4

### ISSUE THREAD

**Issue by jnabnsn** [iikira/BaiduPCS-Go#940]
遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

**Comment by 42SL** [comment]
同样的问题

**Comment by 42SL** [comment]
> 遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation

找到了，把appid调成266719可用

**Comment by jnabnsn** [comment]
谢谢。我试试。



2269099035@qq.com
 
发件人： 42SL
发送时间： 2020-04-22 10:28
收件人： iikira/BaiduPCS-Go
抄送： jnabnsn; Author
主题： Re: [iikira/BaiduPCS-Go] 无论执行任何命令都显示错误4 (#940)
遇到错误, 远端服务器返回错误, 代码: 4, 消息: No permission to do this operation
找到了，把appid调成266719可用
