### ISSUE TITLE
请问 PCS 是什么的缩写?

### ISSUE THREAD

**Issue by Denis-Oakley** [iikira/BaiduPCS-Go#950]
请问 PCS 是什么的缩写?

**Comment by qazwsdc** [comment]
跑厕所（PaoCeSuo----PCS）

**Comment by larryli** [comment]
个人云存储（Personal Cloud Storage，以下简称PCS，是百度推出的针对个人用户的云存储服务。）
http://openapi.baidu.com/wiki/index.php?title=docs/pcs/overview

**Comment by Denis-Oakley** [comment]
谢谢
