### ISSUE TITLE
目录不能带有空格

### ISSUE THREAD

**Issue by shilucus** [iikira/BaiduPCS-Go#96]
rt

![tim 20180323092348](https://user-images.githubusercontent.com/14304571/37806618-f1f13094-2e7b-11e8-9655-aab73f44c9f2.png)

**Comment by JodenHe** [comment]
如果按照Linux习惯，此处应该转义，而且一般文件夹是不建议使用空格的，养成好的命名习惯吧😄

**Comment by iikira** [comment]
参见 #68, #35, #12, [常见问题](https://github.com/iikira/BaiduPCS-Go/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
