### ISSUE TITLE
下载到一半速度变成 0B/s 了

### ISSUE THREAD

**Issue by zhanglianbo35** [iikira/BaiduPCS-Go#97]
如题， 系统是 Ubuntu 16.04 ， 主机是 AWS 
936.64MB/1.64GB 0B/s in 1h11m49.861s ...........

**Comment by zhanglianbo35** [comment]
感觉有可能是baidu网盘自身的问题 ，下载其他的东西就 又没问题了
![image](https://user-images.githubusercontent.com/19187724/37877042-a211bd88-3087-11e8-81f2-55f785ae5c45.png)

**Comment by iikira** [comment]
这样吧，设置环境变量 
```
export BAIDUPCS_GO_VERBOSE=1
```
这样下载的时候会输出下载的调试信息……

**Comment by zhanglianbo35** [comment]
close 掉吧。 我觉得是baidu 网盘自身的问题
