### ISSUE TITLE
BaiduPCS-Go ls 的时候 报错了 

### ISSUE THREAD

**Issue by zhanglianbo35** [iikira/BaiduPCS-Go#98]
刚开始用着挺好的)，下载了几个文件后 就出现这个了

**获取目录下的文件列表, 网络错误,** Get http://pcs.baidu.com/rest/2.0/pcs/file?app_id=260149&by=name&limit=0-2147483647&method=list&order=asc&path=%2FWhite.Deer.Plain.2017.EP01-77.HD1080P.X264.AAC.Mandarin.CHS.Mp4Ba: read tcp 172.31.39.211:51900->58.217.200.64:80: read: connection reset by peer

**Comment by iikira** [comment]
这是你的网络问题……

**Comment by zhanglianbo35** [comment]
但是，很奇怪，我是用的亚马逊的vps。如果换个方式，进入BaiduPCs 控制台，然后再ls，就又正常了

发自我的 iPhone 

**Comment by iikira** [comment]
这个方式……应该没有关联才对啊

**Comment by iikira** [comment]
这是网络的问题, 尝试设置一下代理.
设置代理示例: 
```
export HTTP_PROXY=socks5://localhost:1086
export HTTP_PROXY=http://localhost:1087
```

**Comment by iikira** [comment]
#99 应用同样的解决方法试试.

**Comment by zhanglianbo35** [comment]
代理设置过的,没用. 应该不是设置的问题, 因为我有一次ls 出来结果的, 就一次.

**Comment by iikira** [comment]
就还是报标题正文的错误吗？

**Comment by iikira** [comment]
58.217.200.64:80 这个是你设置的代理吧，可能是代理在vps中不可用，尝试更换代理

**Comment by zhanglianbo35** [comment]
嗯，代理一直是设置好的，像wget curl 都能正常使用

发自我的 iPhone 

**Comment by zhanglianbo35** [comment]
关掉这个issue吧，应该是百度网盘的问题
