### ISSUE TITLE
登录的时候验证出错（信息没有输错，网络没问题）

### ISSUE THREAD

**Issue by zhanglianbo35** [iikira/BaiduPCS-Go#99]
![image](https://user-images.githubusercontent.com/19187724/37884391-551741c8-30e2-11e8-9da4-22d1d04108c4.png)

**Comment by iikira** [comment]
json数据解析失败，一般来说是不会失败的，我测试一下

**Comment by zhanglianbo35** [comment]
我弄了好几次 都这样 （我机子有代理，但是都已经在user的环境变量里设置好了）

**Comment by iikira** [comment]
可能是代理的问题？

**Comment by zhanglianbo35** [comment]
感觉不像（BaiduPCS Go里面有proxy 环境变量的设置吗？ 还是直接调用的 操作系统下面的 proxy 环境变量 ？ ），系统是 红帽子64位

**Comment by zhanglianbo35** [comment]
我用这样的方式也不行  ， 一样的错误提示
BaiduPCS-Go login --bduss=TdKcWFhW4567890987654567890n5ZRjB7890xcHhzamlmZXU2blRXTS1

**Comment by iikira** [comment]
代理配置是从终端中获取的，貌似只能支持http好https的代理……你可以在本地试试看能不能登录?

**Comment by zhanglianbo35** [comment]
我又尝试了一下 ，发现登录成功了，但是 登录后 ls download之类的会报错 （我感觉还是有可能是百度云本身的问题）。

![image](https://user-images.githubusercontent.com/19187724/37894378-aac91dfc-3110-11e8-9c2b-6dbfd68061d7.png)

### _忽略我自定义的命令 ln -s_

**Comment by zhanglianbo35** [comment]
可能是代理问题，如果你程序里面有 time_out 重复尝试连接的逻辑 或许可以解决问题，因为我wget curl 之类的都是可以使用的

**Comment by iikira** [comment]
百度云应该不会有问题……你这网络有毒……

**Comment by iikira** [comment]
有时间的话，我测试一下代理……

**Comment by zhanglianbo35** [comment]
那就拜托你啦

**Comment by zhanglianbo35** [comment]
和#98不是一个原因和症状！你再测试一下试试呢

**Comment by iikira** [comment]
问一下, 在本地使用功能是否正常?

**Comment by zhanglianbo35** [comment]
结果是一样的 。设置好了代理 就如下面截图 所示

![image](https://user-images.githubusercontent.com/19187724/38541965-3c117f48-3cd3-11e8-9504-4d2160b6410a.png)

**Comment by iikira** [comment]
网络确实没有问题。也许你得更换帐号试一试?

**Comment by zhanglianbo35** [comment]
我账号绝对没问题啊。如果不用代理 是可以正常使用的

发自我的 iPhone 

**Comment by iikira** [comment]
意思是使用本程序，不用代理是可以正常使用的，但是用了代理就不能用了，是吗?
百度的接口一般不会出错，否则就会有很多人过来反馈这个问题。看你的错误信息，已收到服务器的消息，可能ip被拉黑了，或者是百度服务器拒绝为你服务……
我还是建议你更换帐号试一试。

**Comment by zhanglianbo35** [comment]
是的。

发自我的 iPhone 

**Comment by zhanglianbo35** [comment]
你好。我重新测试了一下， 我首先unset 掉了 proxy 的 环境变量，这样就是等于我的服务器是无法联网了，因为代理没设置好。结果再次运行你的程序，发现报错的内容和之前设置好代理的是一样的。也就是说明程序没有正确的读取到 系统环境变量的设置 。 
note：  我是在 .bashrc 中设置的代理
http_proxy=ip:port
https_proxy=ip:port

麻烦您再帮我看看呢。  谢谢

**Comment by iikira** [comment]
```go
package main

import (
	"fmt"
	"github.com/iikira/BaiduPCS-Go/requester"
)

func main() {
	body, err := requester.Fetch("GET", "http://ip.chinaz.com/getip.aspx", nil, nil)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s\n", body)
}
```

你尝试设置一下环境变量, http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY, 都试试, 看看能不能正确输出代理的ip

**Comment by iikira** [comment]
987b517f0be07666d5d7b997452ef0aa4e89a829, 也可以编译程序，运行BaiduPCS-Go tool getip, 看看代理有没有生效……

**Comment by iikira** [comment]
export BAIDUPCS_GO_VERBOSE=1

会输出错误信息

你的网络这么奇怪的吗？

**Comment by zhanglianbo35** [comment]
![image](https://user-images.githubusercontent.com/19187724/39562563-f076c886-4ede-11e8-8a75-d69dca2c2e62.png)

**Comment by iikira** [comment]
这是收到了非预期的网页内容啊，猜测是400 bad request，可能请求被篡改，服务器无法解析请求，

建议你开启https试试吧
config set -enable_https

**Comment by zhanglianbo35** [comment]
any idea?

**Comment by iikira** [comment]
暂无解决办法

**Comment by iikira** [comment]
已增加代理设置, 0007020252c3d84f2227cad0f65a88e98c4b7e3a
再不行，就没办法了
